### ISSUE TITLE
Ejercicio en Archi

### ISSUE THREAD

**Issue by mafeave** [udistrital/arka_cliente#1]
Se debe revisar la instalación de la herramienta y crear un ejercicio de ejemplo en archi, se propone realizar el modelo conceptual concertado para ARKA II.

**Comment by Miavega** [comment]
Se anexa el ejercicio de ejemplo en archimate basado en el modelo conceptual para ARKA II. Se puede visualizar en el [enlace](https://drive.google.com/drive/folders/1ev_9O6GGV1jjursp0k1QTEwNCLjjk_RR)

**Comment by mafeave** [comment]
Se revisa enlace adjunto, se verifica imagen del modelo y archivo fuente del modelo.
