### ISSUE TITLE
Mockups de verificación del acta de recibido

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#10]
Crear el mockup correspondiente a la verificación del acta de recibido. Permitirá aprobar los elementos cargados previamente en el acta de recibido.

**Comment by Miavega** [comment]
En el siguiente [enlace](https://drive.google.com/drive/folders/1ZeB27S9iWT7_GwdlqTjnIuM0P4dHWg96) se anexa la imagen PNG con el correspondiente mockup para la verificación de los elementos del acta de recibido.

**Comment by mafeave** [comment]
Verificado el mockup, se da por finalizada la tarea.
