### ISSUE TITLE
Guardar Borrador Acta Recibido

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#100]
Guardar Acta de Recibido como borrador en caso de alguna eventualidad con los registros:

- [x] Registro

- [x] Edicion

**Comment by mafeave** [comment]
Se verifica que en caso de recargar la página y no haber registrado los elementos del acta de recibido, el sistema carga el siguiente mensaje:
![image](https://user-images.githubusercontent.com/14035745/65817211-20b6b900-e1ca-11e9-9748-756010714b2e.png)
Permitiendo acceder al registro con los elementos que se tenían o para iniciar desde cero el registro

**Comment by mafeave** [comment]
Ajustes para la edición: https://github.com/udistrital/arka_cliente/commit/2cbe3c5bfd75a17e183c51590c100f74f123507d

Se da por finalizada la tarea.
