### ISSUE TITLE
Revisión Archivo de carga de datos

### ISSUE THREAD

**Issue by milo19980525** [udistrital/arka_cliente#1009]
Revisar si la estructura y tipología de los archivos corresponden con la plantilla diseñada.

**Comment by ludwinggsanchez** [comment]
Se entiende que el archivo expresa la preocupación por establecer una referencia a los valores generados por el sistema una vez se haga cada cierre. Sin embargo, quedan pendientes columnas de cantidad, clase, proveedor, factura, tipo de entrada, funcionario y valor residual.
