### ISSUE TITLE
Corrección de visualización actas

### ISSUE THREAD

**Issue by milo19980525** [udistrital/arka_cliente#1018]
- [x] Verificación de la carga de actas en el navegador.
- [x] Paginación tabla de actas.

**Comment by diagutierrezro** [comment]
Se realiza la carga de las actas con el id correspondiente en el navegador y se crea la paginación de la tabla de actas, en el [commit](https://github.com/udistrital/arka_cliente/commit/0a3aec65db3ca671b6c1d6761cd710a09a5ec212) se pueden evidenciar los cambios.
![image](https://user-images.githubusercontent.com/38676533/199339896-1362295d-585c-41e1-b42c-24f4509289a8.png)

![image](https://user-images.githubusercontent.com/38676533/199339846-290889f7-2874-4831-aca1-e4ac091e6143.png)
