### ISSUE TITLE
Revisión Archivo de carga de datos v2

### ISSUE THREAD

**Issue by milo19980525** [udistrital/arka_cliente#1028]
- [x] Revisar si la estructura y tipología de los archivos corresponden con la plantilla diseñada.

**Comment by ludwinggsanchez** [comment]
- Las cuentas contables no están en el formato requerido por el sistema. Se recomienda que hagan la respectiva confirmación en el módulo de asignación de cuentas
- Las clases no corresponden al formato deseado: Deben tener 6 dígitos. Se recomienda que confirmen la existencia de las clases en el módulo de construcción de catálogo.
