### ISSUE TITLE
Revisar internacionalización de entradas

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#106]
Se debe configurar la internacionalización de las entradas en el sistema ARKA II. La tarea cuenta con una estimación de 4 horas para su culminación.

**Comment by Miavega** [comment]
Se realiza el ajuste de la internacionalización en los diferentes tipos de entradas:

![imagen](https://user-images.githubusercontent.com/23342808/65543639-2a44d600-ded7-11e9-99a3-67ede7fc4c66.png)
![imagen](https://user-images.githubusercontent.com/23342808/65543652-303ab700-ded7-11e9-9c31-2ba858781d55.png)


- No se realiza para Reposición y Elaboración Propia porque aún falta por definir algunos temas descritos en el [issue 81](https://github.com/udistrital/arka_cliente/issues/81)

**Comment by mafeave** [comment]
Se verifican ajustes para internacionalización. Se da por finalizada la tarea.
