### ISSUE TITLE
Entrega con funcionamiento

### ISSUE THREAD

**Issue by milo19980525** [udistrital/arka_cliente#1062]
- [x] Preparar documento (para presentar a Eduar)
- [x] Definir flujos de manera clara sobre cada una de las acciones que puede realizar cada rol.

**Comment by mcrubianot** [comment]
Se da inicio a las tareas asignadas, retomando un flujo que se trabajados desde que inició el proyecto y ajustándolo a una [nueva versión] (https://app.diagrams.net/?state=%7B%22folderId%22:%220AOBNiTbtzIfeUk9PVA%22,%22action%22:%22create%22,%22userId%22:%22115577396714392713055%22%7D#G1wzyUljU_E_pENTgJ0ssTk6b1xcoubeu9) 
Y se construye el documento [Definir flujos de manera clara sobre cada una de las acciones que puede realizar cada rol.](https://docs.google.com/spreadsheets/d/1PHKLrjMOSWAdB6eDNjxNvW4lMrQTTgecC7hlnZOLUV8/edit#gid=0) de acuerdo a las acciones que ya están definidas en el sistema, para cada funcionalidad y cada rol

**Comment by mcrubianot** [comment]
Se elabora el siguiente documento donde se grafican los flujos
https://drive.google.com/file/d/1-T-n4-qlDk2cKE0hURNdu5oTuHvaYzHG/view?usp=share_link

**Comment by mcrubianot** [comment]
Se da inicio a la construcción del siguiente documento
Posibles inconsistencias que se puedan presentar en Arka II[https://docs.google.com/document/d/1qJSnYo7Aq8d7AdmfnxVFxGi0TPysTEuRnpMJZ3bwK3w/edit](url)

**Comment by mcrubianot** [comment]
Se actualiza el documento Posibles inconsistencias que se puedan presentar en Arka II
