### ISSUE TITLE
Carga de datos

### ISSUE THREAD

**Issue by milo19980525** [udistrital/arka_cliente#1063]
Se requiere llevar a cabo la carga de datos de migración en el ambiente de producción.

**Especificaciones técnicas**

- El aplicativo en su versión estable y actualizada se encuentra en la rama develop y release.
- El archivo de migración se encuentra en: https://udistritaleduco-my.sharepoint.com/:x:/g/personal/cerochac_udistrital_edu_co/ESaojD3HhQZDvDlC2u6l8DYB-0_BCco0D3rYZTHIB1ocCQ?e=3EhHIG

**Sub Tareas**

- [x] Establecer proceso de carga de los elementos a Arka II en entorno de producción.
- [x] Seguir el proceso definido para el cargue.
- [ ] Verificar los datos cargados.

**Criterios de aceptación**

- [ ] Los elementos encontrados en el archivo de migración se encuentran cargados en el aplicativo en ambiente de producción.
- [ ] Se evidencia que las respectivas depreciaciones están correctas.
- [ ] Se comenta el issue con el proceso y pruebas realizadas.

**Requerimientos**

- [x] Las funcionalidades se encuentran en release
- [x] Se cuenta con el archivo de migración

**Dependencias**

- terceros_crud
- Agora
- Argo

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [ ] Criterios de aceptación cumplidos.
- [ ] Documentación de issue realizada.
- [ ] Aprobada por SM/Líder técnico.

**Comment by ludwinggsanchez** [comment]
Pendiente: verificar unidad ejecutora de los elementos que se van a migrar

**Comment by ludwinggsanchez** [comment]
Proveedores pendientes por ser cargados: 

- 800120677
- 815001055
- 830026456
- 830040420
- 860530386
- 900272720
- 900374225
- 900478383
- 900490592
- 900580006
- 900580841
- 900636593
- 900865457
- 901101222
- 901513705
- 8300717011

**Comment by ludwinggsanchez** [comment]
Se recomienda revisar los elementos asignados al funcionario con documento 900490592

**Comment by ludwinggsanchez** [comment]
Confirmar a qué tipo de entrada equivalen los siguientes tipos de entrada registrados en el archivo:

- Avances
- Recuperación

**Comment by ludwinggsanchez** [comment]
Revisar la clase, proveedor, factura, tipo de entrada y valor residual datos de la hoja HERRAMIENTAS_TOTAL

**Comment by ludwinggsanchez** [comment]
Primer versión script para carga de elementos según plantilla definida 
[migracion.txt](https://github.com/udistrital/arka_cliente/files/12046290/migracion.txt)

**Comment by milo19980525** [comment]
La sección de Almacén respondió las observaciones de la siguiente manera:

- Verificar unidad ejecutora de los elementos que se van a migrar (Mencionar cuales elementos son cargados al IDEXUD o a la Universidad) en una nueva columna con los valores (IDEXUD/UD).

respuesta: Todos los elementos se cargan a la universidad.

- Se recomienda revisar los elementos asignados al funcionario con documento 900490592 (FISICOQUÍMICA INTEGRAL S.A.S.), dado que este funcionario también aparece en la lista de proveedores y pareciera ser una empresa.

Respuesta: Corregido 

- Confirmar a qué tipo de entrada equivalen los siguientes tipos de entrada registrados en el archivo:

Avances
Recuperación

Respuesta: 
Avances se homologa a entrada por adquisición en el archivo por efectos de la migración sea coherente con los parámetros establecidos en este momento. Sin embargo se hace la salvedad que en su omento fue registrado con ese tipo de entrada.

Recuperación se homologa a reposición en el archivo a reposición por efectos de la migración sea coherente con los parámetros establecidos en este momento. Sin embargo se hace la salvedad que en su omento fue registrado con ese tipo de entrada.
 
- Revisar los siguientes elementos

Hoja COMPUTO: 1194; 1356; 1364:1373
Hoja SOFTWARE: 256:264
Hoja MUEBLES Y ENSERES: 706; 740
Hoja HERRAMIENTAS_TOTAL

Respuesta:

Hoja COMPUTO: 
1194  Esta entrada es reposición y el sistema no genera ninguna información adicional de proveedor, no es posible conseguir información adicional sobre proveedor y factura 
1356: los datos de depreciación ajustado 
         - 1364:1373 (1358-1370): se ajusta.

Hoja SOFTWARE: 256:264: ajustado columnas de amortización

Hoja MUEBLES Y ENSERES: 706; 740

706 y 740 se complementa la información de acuerdo a lo registrado en arka 1

Hoja HERRAMIENTAS_TOTAL: se incluyó el tipo de entrada, clase y depreciación la otra información no fue posible teniendo en cuenta que Arka 1 no tiene la trazabilidad

Se proporcionó un nuevo archivo de migración el cual es: https://udistritaleduco-my.sharepoint.com/:x:/g/personal/cerochac_udistrital_edu_co/EabXUq8MkqFBsr23kIQrK-IBTGLaiyaq1W8Pyq-rdEv5vg?e=DesaGL

**Comment by ludwinggsanchez** [comment]
Para los elementos que no tienen consecutivo de entradas o salidas, se asignará uno manualmente para que se pueda completar la carga

**Comment by ludwinggsanchez** [comment]
Documento pruebas en producción https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/ETqHrArDfK9Vo50_xgqHSKwByxWtQjzv6n-4ECQsL1gYsw?e=3XTuTC

**Comment by milo19980525** [comment]
El consolidado de archivo de migración se encuentra en: https://udistritaleduco-my.sharepoint.com/:x:/r/personal/cerochac_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7BC3A3A0C8-F2CB-4364-9FF3-9D533A755554%7D&file=UDI_Movimientos%20Migracion%20elementos.xlsx&action=default&mobileredirect=true

**Comment by ludwinggsanchez** [comment]
Se vuelven a verificar funcionarios y quedan pendientes los siguientes:
- 12550145
- 900490592
- 79417666
- 899999230

**Comment by ludwinggsanchez** [comment]
Se vuelven a verificar proveedores y quedan pendientes los siguientes:
-  830071611
-  900085429
-  805027390
-  900487000
-  899999115
-  830109029
-  830035246
-  900425254
-  860001911
-  860512149
-  830065750
-  830007414
-  800036678
-  900042771
-  900047667
-  900080875
-  900348597
-  830014721
-  830004521
-  860000580
-  860351432
-  19392552
-  890941592
-  800078000
-  900245364
-  900130648
-  800179308
-  800061585
-  830145851
-  444444177
-  830051298
-  19208669
-  860047726
-  900085100
-  805000004
-  800158485
-  900011339
-  830094320
-  900337973
-  900572713
-  802004648
-  860502528
-  800240039
-  830036940
-  830046323
-  830029829
-  890935513
-  860001710
-  860034714
-  830086777
-  830053900
-  830023974
-  830033124
-  830136779
-  830025968
-  79754835
-  900177651
-  900177854
-  800053310
-  830137099
-  900215049
-  79399917
-  49738311
-  860067604
-  900579992
-  900372566
-  900409368
-  860516314
-  900549772
-  830073166
-  830007351
-  860090404
-  830072297
-  860511107
-  860086404
-  900428481
-  900274748
-  860071674
-  800198583
-  830017043
-  444444197
-  800252589
-  900682449
-  800066243
-  800052954
-  830145062
-  800032755
-  900410611
-  800007477
-  830081447
-  900462594
-  890914336
-  52209720
-  900167978
-  52901304
-  900134527
-  900301897
-  860515402
-  830107624
-  860000648
-  52501855
-  800134773
-  444444220
-  900802158
-  830107699
-  900137828
-  900804744
-  900800677
-  830067042
-  79513661
-  830122230
-  890943055
-  800098622
-  805014913
-  800002030
-  8001425636
-  9005664662
-  900047839
-  900427477
-  900168246
-  830040329
-  860054854
-  900355024
-  830011990
-  900521573
-  830051965
-  800218933
-  900799002
-  830126969
-  900407304
-  900393949
-  900031824
-  900920547
-  800028446
-  830014795
-  800154275
-  860015971
-  900695672
-  900401996
-  900634967
-  900921326
-  444444243
-  17772
-  860510142
-  830016004
-  800252103
-  860536024
-  890908777
-  900361164
-  900048578
-  830092541
-  830141526
-  900026709
-  901035991
-  901034562
-  900082649
-  900013343
-  444444255
-  890101977
-  860049903
-  900739480
-  830088172
-  800035478
-  8999991158
-  830001637
-  899999061
-  900243378
-  900496600
-  901086691
-  830089928
-  800147578
-  900656879
-  820003227
-  900079139
-  900377789
-  830144572
-  900412503
-  830122576
-  830505910
-  900237306
-  900098586
-  899999230
-  830016713
-  860002184
-  901131181
-  901137501
-  900940278
-  444444270
-  444444269
-  900475408
-  901065217
-  860516281
-  901134931
-  830512338
-  800215239
-  830146283
-  830110570
-  900953964
-  900461036
-  900322842
-  800153832
-  830118571
-  860353110
-  901141547
-  900489070
-  805017133
-  901060192
-  900197753
-  900273006
-  860001307
-  830062489
-  900659438
-  900255743
-  830141369
-  800233837
-  900344751
-  900418656
-  7933886
-  830135205
-  900421798
-  860000810
-  830071391
-  860352010
-  900197258
-  800018856
-  901246019
-  901246050
-  900497003
-  900741497
-  900129370
-  444444286
-  901339668
-  800142563
-  901224882
-  900915742
-  830001338
-  830154851
-  900751438
-  901006295
-  900406263
-  830032614
-  900488849
-  860003168
-  830100385
-  901113330
-  900458002
-  901348252
-  900596780
-  900415344
-  800122811
-  900882944
-  901349534
-  901156910
-  800128897
-  901362177
-  800002942
-  860053274
-  890900943
-  900034424
-  900280219
-  901544600
-  79364185
-  830014277
-  900032888
-  8300717011
-  901101222
-  900374225
-  900025724
-  900279841
-  830040420
-  800120677
-  900701630
-  830026456
-  815001055
-  900580006
-  830034233
-  890900608
-  900580841
-  860530386
-  811021363
-  900636593
-  901216784
-  8600700783

**Comment by ludwinggsanchez** [comment]
Para los elementos HERRAMIENTAS_TOTAL se crea la clase **271100 - Herramientas de mano**

**Comment by ludwinggsanchez** [comment]
Se carga toda la parametrización contable en el sistema

**Comment by ludwinggsanchez** [comment]
Proveedores faltantes actualizados:

-  830071611
-  900085429
-  805027390
-  900487000
-  830035246
-  900425254
-  900047667
-  900348597
-  860000580
-  19392552
-  890941592
-  444444177
-  19208669
-  830094320
-  900572713
-  830046323
-  860001710
-  830033124
-  79754835
-  900177651
-  900177854
-  900215049
-  79399917
-  49738311
-  860067604
-  900579992
-  900372566
-  900409368
-  860516314
-  830073166
-  830007351
-  860511107
-  860086404
-  900428481
-  800198583
-  444444197
-  900682449
-  800032755
-  800007477
-  830081447
-  900462594
-  52209720
-  900167978
-  52901304
-  900134527
-  900301897
-  52501855
-  800134773
-  444444220
-  900802158
-  830107699
-  900804744
-  900800677
-  79513661
-  830122230
-  800098622
-  805014913
-  8001425636
-  9005664662
-  900047839
-  900521573
-  900799002
-  900407304
-  900031824
-  900920547
-  800028446
-  900401996
-  900921326
-  444444243
-  17772
-  900048578
-  901035991
-  901034562
-  900082649
-  444444255
-  800035478
-  8999991158
-  800147578
-  900656879
-  860002184
-  444444270
-  444444269
-  901065217
-  860001307
-  7933886
-  830071391
-  444444286
-  901339668
-  830154851
-  901349534
-  890900943
-  901544600
-  79364185
-  8300717011
-  815001055
-  8600700783

**Comment by ludwinggsanchez** [comment]
Información de proveedores faltantes según ARKA I compartida vie e-mail

**Comment by milo19980525** [comment]
Con base en la reunión de entrega con el usuario, los proveedores que no se encuentran deben asociarse a un proveedor ficticio que los agrupe mientras se depura la información dado que muchos de estos ya no se encuentran registrados en camara y comercio.

**Comment by ludwinggsanchez** [comment]
- Se cargan los elementos correspondientes a entradas por sobrante. Pendiente generar contabilidad para entrada P8-00090-2019 y sus respectivas salidas
- Pendiente crear tabla centro costos en producción

**Comment by ludwinggsanchez** [comment]
Pendiente revisar script reporte de entradas. Basarse en entrada migrada P8-00090-2019

**Comment by ludwinggsanchez** [comment]
Revisar contabilidad
- P8-00028-2014
- P8-00109-2013
- P8-00179-2013
- P8-00181-2014
- P8-00350-2014
- P8-00421-2015
- P8-00270-2016
- P8-00321-2016
- P8-00371-2018

**Comment by milo19980525** [comment]
Se migraron los proveedores extranjeros, por favor revisar.

**Comment by ludwinggsanchez** [comment]
Migrar manualmente filas 5269, 5270.

**Comment by ludwinggsanchez** [comment]
Se revisa el archivo remitido por almacén, sin embargo, no se puede determinar qué elementos de este se deben migrar.

Como Información adicional se indica que la última entrada migrada fue la 164 y en la que se incluyeron 8 elementos.

**Comment by milo19980525** [comment]
@ludwinggsanchez Tal como se preveía se deben cargar todos los elementos del archivo de miración: https://udistritaleduco-my.sharepoint.com/:x:/g/personal/cerochac_udistrital_edu_co/EfilD3jq53ZMpl4o42OgHasB12qSXNkXrjd-bgWTt1y7UA?e=wylTnR

**Comment by ludwinggsanchez** [comment]
- Eliminar elemento mov: 8637
- Eliminar elemento acta: 8630

**Comment by ludwinggsanchez** [comment]
Migrado software y elementos devolutivos

**Comment by milo19980525** [comment]
Se solicita la información faltante a la Sección de Almacén.

**Comment by milo19980525** [comment]
La sección de Almacén y contabilidad remitieron el siguiente archivo con la información faltante solicitada: https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EQyGGy4JJYVHijivz39r2QMBNkJ6eIceivQvSES4UxdlYw?e=uCwTEn

@ludwinggsanchez por favor realizar el ajuste pertinente para los elementos necesarios en producción.

**Comment by ludwinggsanchez** [comment]
Consultar con la sección de contabilidad si las cuentas contables varían para las entradas por sobrante, reposición y donaciones

**Comment by milo19980525** [comment]
Se recibe documento con las clases pero no en el formato requerido.

**Comment by milo19980525** [comment]
Se da por cerrado el issue según la comunicación recibida por parte de la sección de contabilidad, dónde mencionan que no harán algún esfuerzo por la información requerida por ARKA II, antes de entregar los datos necesarios para el ERP.
