### ISSUE TITLE
Entradas por adiciones y mejoras, y por aprovechamientos

### ISSUE THREAD

**Issue by milo19980525** [udistrital/arka_cliente#1069]
**Entradas por adiciones y mejoras**

- [x] No tienen acta
- [x] Las entradas por adiciones y mejoras, y aprovechamientos no deberían tener una placa nueva.
- [x] Se altera el valor del bien el cual es mejorado, en que momento se ingresa ese valor y la vida útil (nuevas columnas en el listado de elementos de entrada)

**Entradas por aprovechamientos**

- [x] No tienen acta
- [x] Para aprovechar partes de un elemento, este tiene que estar dado de baja con anterioridad.
- [x] Revisar cambio de valores en la nueva tabla que relaciona el elemento a ser mejorado con la parte de aprovechamientos
- [x] No deben tener una placa nueva
- [x] Por aprovechamientos se puede realizar varias veces

**Comment by ludwinggsanchez** [comment]
Se identifican las siguientes tareas: 

- Seleccionar el tipo de entrada antes que el acta.

Entrada por adiciones y mejoras
- Agregar columnas para indicar la nueva vida útil, valor en libros y valor residual.
- En la aprobación de estas entradas, incluir la generación de la novedad mediante la que se registra el nuevo valor del elemento.
- Confirmar si el elemento a mejorar debe haber sido de baja o no.

Entrada por aprovechamientos

- Agregar tabla para indicar los elementos que se están mejorando
- Confirmar que tanto el elemento aprovechado como el que se va a mejorar deben estar dados de baja
- Confirmar que al elemento mejorado se le debe actualizar el valor en libros y vida útil
- Crear la novedad en caso que sea necesario

Cierres

- Actualizar el algoritmo de novedades para incluir las novedades generadas

**Comment by mcrubianot** [comment]
- Entrada por adiciones y mejoras
Confirmar si el elemento a mejorar debe haber sido de baja o no.
"No es que se tenga un elemento de baja y se le quita el disco duro y se le va a incorporar a otro, eso no pasa; la mayoría de las partes que se le incorporan a aquellos elementos que ya tienen una vida útil de cero, son nuevos, esto es una mejora". 

Según acta de No.090 del 2022, se estableció que:

- Entrada por aprovechamientos
Confirmar que tanto el elemento aprovechado como el que se va a mejorar deben estar dados de baja
"... Aclara el ingeniero Ludwing que, de acuerdo a la norma, un elemento se dañó y se va a aprovechar una parte que puede servir y que va a ser asociada a un nuevo elemento. La jefe comenta que hay equipos que son ya viejos y no se encuentran las partes en el mercado, pero en una dependencia tiene otro similar y el disco duro se le daño, entonces se reemplaza. En ese caso esa parte que ya no se encuentra en el mercado, el costo sería 0 y no afecta la vida útil, se adiciona la parte y se lleva en control. Y el elemento al cual se le quitó la parte, ya tendría que estar dado de baja."

Confirmar que al elemento mejorado se le debe actualizar el valor en libros y vida útil
De acuerdo a lo que se hablo ese día, se quedo en que "...El ingeniero Ludwing mencionará que queda muy similar a la salida, para que se establezca la vida útil y el valor residual"

Preferí relacionar lo que se habló en esa reunión para no tener dudas.

**Comment by ludwinggsanchez** [comment]
Mejorados
- Se puede mejorar varias veces
- Si se dió de baja, no se puede mejorar
- Puede valer más de cero

Aprovechado
- Se puede aprovechar varias veces
- Si no se dió de baja, no se puede aprovechar

**Comment by ludwinggsanchez** [comment]
Pendiente tener en cuentas las novedades para el cierre
