### ISSUE TITLE
Ajustes desarrollo entradas, de acuerdo a observaciones de la analista

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#109]
Se debe realizar los ajustes necesarios en el módulo de entradas para que quede totalmente finalizado. Incluyendo API MID y Cliente. La tarea cuenta con una estimación de 4 horas para culminarla

Observaciones del módulo de entradas:

**CONSULTA DE ENTRADAS**
- Cuando no hay entradas registradas, se está cargando una fila en la tabla

**REGISTRO DE ENTRADAS**
- Agregar mensaje en select de tipo entrada, ej: Seleccione el tipo de entrada
- Al tratar de enviar la entrada sin elementos: Ajustar GLOBAL.error en el alert, y el mensaje del botón, en vez de 'Confirm', dejarlo como 'OK' o 'Aceptar'
- Se hace una entrada de prueba, la cual tiene solo 1 elemento, pero en el formulario de creación de la entrada está listando 3 elementos (el elemento relacionado pero con 3 Subtotales diferentes)
- No está cargando el porcentaje del IVA (Muestra 3, no el %)
- Ajustar los valores a la derecha con decimales

**Comment by Miavega** [comment]
A continuación se muestran algunas de las correciones realizadas: 

Mensaje al seleccionar tipo de entrada
![imagen](https://user-images.githubusercontent.com/23342808/65656216-a9740000-dfe4-11e9-8566-2440f28a1be9.png)

Mensaje de error
![imagen](https://user-images.githubusercontent.com/23342808/65656235-bc86d000-dfe4-11e9-96b6-cab4efc47ebf.png)

Campos de la tabla todos con Uppercase (Letra en mayúscula), lectura del IVA, Unidad de Medida y campos de moneda
![imagen](https://user-images.githubusercontent.com/23342808/65656270-e6d88d80-dfe4-11e9-9102-58eb49b37b3e.png)

**Comment by mafeave** [comment]
Se prueban los ajustes realizados, pero no se evidencia el cambio de los valores de tipo moneda con formato y alineados a la derecha, @Miavega revisar

**Comment by Miavega** [comment]
Se ajusta el servicio en el MID para traer el acta con su respectiva ubicación:

![imagen](https://user-images.githubusercontent.com/23342808/65935723-be370600-e3df-11e9-8baa-c63aab6b26ba.png)

**Comment by mafeave** [comment]
Se hace merge de los ajustes a las ramas dev del mid y cliente, se hacen los despliegues en el entorno de pruebas en la nube, para que la analista valide el desarrollo del módulo de entradas.
