### ISSUE TITLE
Paso a producción

### ISSUE THREAD

**Issue by milo19980525** [udistrital/arka_cliente#1094]
De acuerdo con los ajustes funcionales realizados generar un checklist para salida a producción de cada una de las apis que se despliegan a producción siguiendo los siguientes formatos:

- [Resoluciones Cliente v2](https://docs.google.com/document/d/1mxJdDG8H_NfkZVEzcHeytSy016L0U7MZ/edit?usp=share_link&ouid=115705338596905688240&rtpof=true&sd=true) 
- [Resoluciones MID v2](https://docs.google.com/document/d/11n0Fir-waAwUaBG2PIWzSjhuviiJu1ZD/edit?usp=share_link&ouid=115705338596905688240&rtpof=true&sd=true)
- [Resoluciones CRUD v2](https://docs.google.com/document/d/16yp9mNJs5mnprr8nNx8ySqISjO5WyfyJ/edit?usp=sharing&ouid=115705338596905688240&rtpof=true&sd=true)

***Criterios de aceptación***

- [x] Checklist de despliegue a producción por cada api
- [x] PR a producción
- [x] Estabilización del sistema

**Comment by ludwinggsanchez** [comment]
Se elaboran los respectivos documentos

- [arka_mid](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/luasanchezl_udistrital_edu_co/EQIluf58hr5Lh--Kzgyl3HEB9COFMeZ4PA6NbAaWCM4pUQ?e=cPIOYj)
- [catalogo_elementos_crud](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/luasanchezl_udistrital_edu_co/EbYlEfiRGMhBvojk8mecGCQBUCa-9rkPZB4VWluHLWRmzw?e=XNe2eB)
- [acta_recibido_crud](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/luasanchezl_udistrital_edu_co/EWhEHEV5gYBFkyC0ctQh6nMBR9j-F5EuzMCTyOSb5amLqg?e=e96YmE)
