### ISSUE TITLE
Ajuste desarrollo de Acta de recibido segun analista 

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#110]
se requiere arreglar ciertas caracteristicas para el acta de recibido

- [x] Valores Alfanumericos de los elementos

- [ ] cambiar la barra de scroll

- [x] errores en el registro del acta de recibido

- [x] errores de traduccion

- [x] Habilitacion del envio a verificacion (No funciona)

- [x] error con actas no registradas en el modulo de consulta

- [ ] labells para los filtros de datos iniciales

**Comment by mafeave** [comment]
Se hace merge de la rama verificacion/acta/2 a dev y se verifican los siguientes ajustes:
Valores Alfanumericos de los elementos
![image](https://user-images.githubusercontent.com/14035745/65817029-2f9c6c00-e1c8-11e9-9661-44a1cf612fc2.png)
Valores negativos: ya no se generan valores negativos en los cálculos de los elementos

Ajustes internacionalización
![image](https://user-images.githubusercontent.com/14035745/65817054-6ecabd00-e1c8-11e9-96f6-80392b0bc256.png)

Se verifica habilitación para envío del acta a verificación

**Comment by mafeave** [comment]
Falta ajustar los valores a la derecha de los datos del Gran Consolidado.

**Comment by mafeave** [comment]
Valores ajustado a la derecha. Se da por finalizada la tarea.
