### ISSUE TITLE
Análisis avaluos

### ISSUE THREAD

**Issue by milo19980525** [udistrital/arka_cliente#1102]
Analizar los requisitos relacionados con el módulo de avalúos.

**Criterios de aceptación**

- [x] Identificar actividades a ser realizadas
- [x] Detectar si se deben alterar los esquemas y estructuras de datos actuales

**Comment by ludwinggsanchez** [comment]
El registro del avalúo consistirá de dos partes:

1. Detalles generales del avalúo: fecha de corte del avalúo, avaluador.
NOTA: Pendiente determinar datos adicionales
2. Lista de inmuebles a los que se registrará el avalúo: a cada uno se le registrará la nueva vida útil, valor en libros y valor residual, así como los valores del área construida.
NOTA: La edad del inmueble no se podrá editar: Ya fue registrada en el módulo de inmuebles
 Pendiente determinar los diferentes "valores" a registrar y cuál corresponde al valor en libros.
