### ISSUE TITLE
Curva de aprendizaje frente al generador (ngxGenerator)

### ISSUE THREAD

**Issue by mafeave** [udistrital/arka_cliente#111]
Hacer un ejercicio de prueba para conocer el funcionamiento de ngxGenerator y aplicarlo para crear  un componente de ejemplo.

Seguir la explicación del siguiente documento: https://docs.google.com/document/d/1mfsdoQ5RRM_odY7QrKaAKiEjys4TS_baHiJ5NLMzTu4/edit

**Comment by ManuelMurillo** [comment]
revisa el repositorio del generador para poder generar los registros del catalogo teniendo en cuenta la siguiente entidad


```shell 
project name catalogo

entity catalogo  {
	Id                	:integer
	Nombre            	:string
	Descripcion       	:string
	Fecha_Inicio 		    :time
	Fecha_Fin	      	  :time
	Activo        	    :bool
}

entity grupo  {
	Id                	:integer
	Nombre            	:string
	Descripcion       	:string
	Activo        	    :bool
}

entity subgrupo_1 {
	Id                	:integer
	Nombre            	:string
	Descripcion       	:string
	Activo        	    :bool
}
entity subgrupo_2 {
	Id                	:integer
	Nombre            	:string
	Descripcion       	:string
	Activo        	    :bool
}
```

**Comment by mafeave** [comment]
Se verifica revisión del generador para las tareas de generación de catálgo, grupos y subgrupos, ver https://github.com/udistrital/arka_cliente/issues/117, https://github.com/udistrital/arka_cliente/issues/114 y https://github.com/udistrital/arka_cliente/issues/115
