### ISSUE TITLE
Documento Informe Final Contratación

### ISSUE THREAD

**Issue by milo19980525** [udistrital/arka_cliente#1115]
Diligenciar a modo de informe todas las actividades realizadas, frente a cada una de las "actividades contractuales" 
especificadas en su contrato, en dado caso de no haber cumplido con alguna, por favor escribir la observación correspondiente del por qué no se realizó.

_Nota: Tomar como formato ejemplo: https://udistritaleduco-my.sharepoint.com/:x:/r/personal/cerochac_udistrital_edu_co/Documents/Trabajo%20OAS/Arka/[informe_terminacion.xlsx](https://udistritaleduco-my.sharepoint.com/:x:/r/personal/cerochac_udistrital_edu_co/Documents/Trabajo%20OAS/Arka/informe_terminacion.xlsx?d=w9727ccceffb64e09aa95d447d1158c42&csf=1&web=1&e=PhslBy)?d=w9727ccceffb64e09aa95d447d1158c42&csf=1&web=1&e=PhslBy_

**Comment by ludwinggsanchez** [comment]
[informe_terminacion.xlsx](https://github.com/udistrital/arka_cliente/files/10788716/informe_terminacion.xlsx)
