### ISSUE TITLE
Desarrollo Modulo Registro Catalogo

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#113]
desarrollar el modulo de registro de catalogo

**Comment by mafeave** [comment]
Se verifica desarrollo del crud para gestión de catalogo: 
![image](https://user-images.githubusercontent.com/14035745/67013507-d635a780-f0b8-11e9-89a2-80f5ecd21e35.png)

Se da por finalizada la tarea.
