### ISSUE TITLE
Desarrollo modulo Registro Grupo

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#114]
Desarrollar el modulo de registro del grupo para el catalogo

**Comment by mafeave** [comment]
Se verifica desarrollo del crud para gestión de grupo: 
![image](https://user-images.githubusercontent.com/14035745/67013507-d635a780-f0b8-11e9-89a2-80f5ecd21e35.png)

Se da por finalizada la tarea.
