### ISSUE TITLE
Desarrollo modulo registro Subgrupos Catalogo

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#115]
Desarrollar el modulo de registro para los subgrupos de catalogo

**Comment by mafeave** [comment]
Se verifica CRUD para la gestión de subgrupos del catálogo de elementos:
![image](https://user-images.githubusercontent.com/14035745/67013781-480df100-f0b9-11e9-98b2-6d5ff8edb8e0.png)
Se da por finalizada la tarea.
