### ISSUE TITLE
Generación de reporte de la hoja de vida del bien 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#1150]
Se debe realizar la Generación de reporte de la hoja de vida del bien, la issue debe cumplir con los siguientes requerimientos: 

- [x] El reporte debe cumplir con la definición de la [historia de usuario ](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/computo_udistrital_edu_co/EVoflrCQxiBTK1zjxJ2fOygBs-iUOT3a8U9u3v-pvf9ftw?e=LAXnSE)
- [x] Desarrollar el reporte mediante la herramienta Knowage

**Comment by ludwinggsanchez** [comment]
Se genera el reporte y se sube exitosamente a knowake.
[historial_0.0.1.zip](https://github.com/udistrital/arka_cliente/files/11205415/historial_0.0.1.zip)
