### ISSUE TITLE
Corrección despliegues crud Arka II

### ISSUE THREAD

**Issue by milo19980525** [udistrital/arka_cliente#1152]
Se requiere corregir el despliegue de catalogo_crud, movimientos_contables_arka_crud, acta_recibido_crud en el entorno de producción.

**Especificaciones técnicas**

- El desarrollo de las api_crud se encuentra en master pero no ha podido desplegarse.

**Sub Tareas**

- [x] Revisar logs en Cloudwatch para revisar si se desplegaron las nuevas funcionalidades.
- [x] Elevar caso a infraestructura.
- [x] Probar despliegue correcto.

**Criterios de aceptación**

- [x] Los despliegues se encuentran corregidos y las funcionalidades se pueden apreciar en entorno de producción.

**Requerimientos**

- [x] Las funcionalidades se encuentran en master

**Dependencias**

- arka_mid
- movimientos_arka_crud
- acta_recibido_crud
- catalogo_elementos_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] PR a Master.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ludwinggsanchez** [comment]
Despliegue correcto de 
- arka_mid
- movimientos_arka_crud
- acta_recibido_crud

Persiste error en consulta de tipos de bien en api:
- catalogo_elementos_crud

**Comment by ludwinggsanchez** [comment]
Se confirma despliegue correcto en producción de api catalogo_elementos_crud.
