### ISSUE TITLE
Correcciones 8-06-2023

### ISSUE THREAD

**Issue by milo19980525** [udistrital/arka_cliente#1155]
Realizar los ajustes necesarios para que el sistema quede funcional y listo para desplegar en ambientes de prueba y producción.

**Especificaciones técnicas**

- El último desarrollo probado con la sección de Almacén e inventarios se encuentra en la rama "Release", sobre la cual se presenta la inconsistencia.

**Sub Tareas**

- [x] En bodega de consmo no permite reponder solicitudes, el sistema se queda procesando y se evidencia error en la consola.
- [x] Se requiere que salga un seleccionable con las dependencias que se encuentren en una sede para que no quede a la deriva encontrar una ubicación específica.
- [x] No permite realizar un cierre debido a que se presentan conflictos en las clases de los elementos del cierre, por lo que se debe puntualizar o especificar en que elementos se presenta la inconsistencia.
- [x] Modificar aviso de error cuando se carga la plantilla de elementos en un acta de recibido para que en dado caso de no subir la clase (No se encuentra en la plantilla) no lo tome como error leve si no como un aviso que indique "Estimado usuario por favor seleccionar la clase y tipo de bien para cada uno de los elementos a continuación".
- [x] Revisar reporte de bajas que no está funcionando.

**Criterios de aceptación**

- [x] Comentario del issue con evidencia de los errores corregidos.
- [x] Revisión y aprobación de solicitudes de bodega de consumo.
- [x] Evidencia de mensaje de orientación más no de alerta cuando se carga una plantilla con elementos sin clase.
- [x] Evidencia funcional del reporte de bajas.
- [x] Filtrar las dependencias por sede.
- [x] Evidenciar un aviso con las fallas específicas que impidan cierre contable.

**Requerimientos**

- [x] Ninguna

**Dependencias**

- Movimientos_arka_crud
- catalogo_elementos_bien_crud
- Arka_mid
- acta_recibido_crud

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ludwinggsanchez** [comment]
Reporte de bajas: [reporteBajas.pdf](https://github.com/udistrital/arka_cliente/files/11777573/reporteBajas.pdf)
