### ISSUE TITLE
Correcciones 22-06-23

### ISSUE THREAD

**Issue by milo19980525** [udistrital/arka_cliente#1157]
Se requiere corregir los hallazgos relacionados en el [documento](https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7B0AAC873A-7CC3-55AF-A39D-3FC60A8748AC%7D&file=Aplicaci%C3%B3n%20pruebas%20Funcionales%20y%20de%20Usabilidad%20%20-%20Arka%20II%20-%202022.xlsx&action=default&mobileredirect=true&CID=c25e2277-bdaa-f542-0c56-4acec03413fc)

**Especificaciones técnicas**

- El último desarrollo probado se encuentra en la rama release de cada una de las apis involucradas en el aplicativo.

**Sub Tareas**

- [x] Revisar porque en el reporte de bajas no muestra el mismo elemento encontrado en la fase de revisión comité de Arka.
- [x] Ejecución etl para poblar tabla asignacion_espacio_fisico_dependencia de Oikos.
- [x] La consulta de traslados está fallando al buscar ubicaciones no encontradas.
- [x] Consulta de solicitud de bodega de consumo.
- [x] Consulta consulta de baja
- [x] Verificar generación de ajuste automático.
- [x] Verificar si es necesario comprobante contable en bienes inmuebles.

**Criterios de aceptación**

- [x] Los hallazgos son validados y en dado caso de ser requerido corregidos.

**Requerimientos**

- [x] Las funcionalidades se encuentran en release

**Dependencias**

- arka_mid
- cuentas_contables_crud
- Knowage
- oikos

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] PR a Release.
- [x] PR a Master.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ludwinggsanchez** [comment]
- Falla consulta de solicitud de bodega de consumo:
![image](https://github.com/udistrital/arka_cliente/assets/35748918/ef77f2b4-b8bb-489f-9cbb-211f477ba0f2)
- Falla consulta de lista de traslados: 
![image](https://github.com/udistrital/arka_cliente/assets/35748918/aa9ec6b5-3b61-435f-a5c2-6afa039ceb7b)
- Falla consulta de baja:
![image](https://github.com/udistrital/arka_cliente/assets/35748918/34c32f98-042c-4992-ace0-4a3c5ad70771)

**Comment by ludwinggsanchez** [comment]
Se reitera que el reporte de elementos en comité de bajas incluye **únicamente** los elementos asociados en las bajas que se encuentren en estado **BAJA EN COMITÉ**

![image](https://github.com/udistrital/arka_cliente/assets/35748918/4c7e0d05-6d31-4192-96b5-80014e8354d9)
