### ISSUE TITLE
Revisión espacios físicos

### ISSUE THREAD

**Issue by milo19980525** [udistrital/arka_cliente#1158]
Se requiere revisar cada uno de los espacios físicos asociados a los elementos remitidos por la sección de Almacén e inventario.

**Especificaciones técnicas**

- El último despliegue se encuentra en la rama release
- El archivo de migración se encuentra en: [https://udistritaleduco-my.sharepoint.com/❌/g/personal/cerochac_udistrital_edu_co/ESaojD3HhQZDvDlC2u6l8DYB-0_BCco0D3rYZTHIB1ocCQ?e=3EhHIG](https://udistritaleduco-my.sharepoint.com/:x:/g/personal/cerochac_udistrital_edu_co/ESaojD3HhQZDvDlC2u6l8DYB-0_BCco0D3rYZTHIB1ocCQ?e=3EhHIG)

**Sub Tareas**

- [x] Revisar los scripts encontrados en: https://udistritaleduco-my.sharepoint.com/:f:/g/personal/cerochac_udistrital_edu_co/EnEPqbAJ1oRDv6_sCeUlaVoB2CefeuQzCPetf25LsExtVg?e=T9DcyZ
- [x] Ejecutar los scripts de manera secuencial en cada uno de los pasos encontrados en estos.
- [x] Definir que espacios físicos no se encuentran en OIKOS.

**Criterios de aceptación**

- [x] Comentario en el issue con la relación de espacios, dependencias y sedes no encontradas.

**Requerimientos**

- [x] Ninguna

**Dependencias**

- [x] Ejecución de ETL en Oikos.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ludwinggsanchez** [comment]
- Pendiente sincronizar espacios físicos de producción y test
- Pendiente sincronizar asignaciones de producción y test

**Comment by ludwinggsanchez** [comment]
- Se requiere sincronizar las sedes en test y producción

**Comment by milo19980525** [comment]
@ludwinggsanchez entiendo la necesidad de sincronización para el cargue de datos en producción, sin embargo la comparativa de espacios físicos se puede realizar en pruebas, por favor especificar que tablas se deben sincronizar.

**Comment by milo19980525** [comment]
@ludwinggsanchez El arquitecto quedó en realizar la ejecución del ETL hacía prod hoy en la noche.

**Comment by ludwinggsanchez** [comment]
- Espacios físicos en test: [espacios_fisicos_test.csv](https://github.com/udistrital/arka_cliente/files/11963601/espacios_fisicos_test.csv)
- Ubicaciones-Sede para migrar (464): 
[ubicaciones_arka.csv](https://github.com/udistrital/arka_cliente/files/11963605/ubicaciones_arka.csv)
- Haciendo el respectivo cruce, se definen las (142) ubicaciones faltantes: 
[ubicacionesFaltantes.csv](https://github.com/udistrital/arka_cliente/files/11963629/ubicacionesFaltantes.csv)

**Comment by ludwinggsanchez** [comment]
- Sede PORVENIR BOSA -> PORVENIR
- ENFERMERÃA -> ENFERMERIA
- COORDINACIÃ“N BIENESTAR INSTITUCIONAL -> COORDINACION BIENESTAR INSTITUCIONAL
- CUARTO DE SERVIDORES -> SERVIDORES
- AULA SISTEMAS 538 -> SALA DE SISTEMAS PRACTICAS LIBRES 538
- AULA SISTEMAS 539 -> SALA DE SISTEMAS PRACTICAS LIBRES 539

**Comment by ludwinggsanchez** [comment]
Pendiente resolver confusión con sedes POSGRADO Y CENTRO

**Comment by ludwinggsanchez** [comment]
Tras la correcciones mencionadas se establecen las siguientes 66 ubicaciones faltantes: [ubicacionesFaltantes.csv](https://github.com/udistrital/arka_cliente/files/11964670/ubicacionesFaltantes.csv)

**Comment by ludwinggsanchez** [comment]
### Ajustes a dependencias

- ARTES PLASTICAS -> ARTES PLASTICAS Y VISUALES
- COORDINACIÓN DE AUTOEVALUACIÓN Y ACREDITACIÓN -> COORDINACION GENERAL DE AUTOEVALUACION Y ACREDITACION
- RED UDNET -> RED DE DATOS UDNET
- BIENESTAR UNIVERSITARIO -> CENTRO DE BIENESTAR INSTITUCIONAL
- OFICINA ASESORA DE JURIDICA -> OFICINA ASESORA JURIDICA

**Comment by ludwinggsanchez** [comment]
Tras la correcciones mencionadas a las dependencias, se establecen las siguientes 2 dependencias faltantes: [dependenciasFaltantes.csv](https://github.com/udistrital/arka_cliente/files/11965592/dependenciasFaltantes.csv)

**Comment by ludwinggsanchez** [comment]
### Correcciones finales dependencias


- ADMINISTRACION DE INSTITUTO DE INVESTIGACIONES -> CENTRO DE INVESTIGACIONES Y DESARROLLO CIENTIFICO
- COORDINACIÓN LABORATORIOS FACULTAD DE INGENIERÍA -> LABORATORIO INGENIERIAS

**Comment by ludwinggsanchez** [comment]
Se recomienda revisar el árbol de dependencias para LABORATORIO INGENIERIAS

**Comment by ludwinggsanchez** [comment]
- SALA SISTEMAS 603 -> SALA 603
- SALA SISTEMAS 202 -> AULA DE INFORMATICA POSTGRADOS 202
- LABORATORIO ELECTRONICA B -> LABORATORIO DE ELECTRONICA B
- SALA DE INVESTIGACIÓN -> SALA DE JUNTAS CENTRO DE INVESTIGACION Y DESARROLLO CIENTIFICO
- COORDINACIÓN TECNOLOGIA E INGEELÉCTRICA POR CICLOS PROP -> COORDINACIÓN TECNOLOGIA E INGENIERÍA ELÉCTRICA POR CICLOS PROP.
- SALA DE SOFTEWARE -> SALA SOFTWARE ESPECIALIZADO
- SALA DE SOFTWARE -> SALA SOFTWARE ESPECIALIZADO
- LABORATORIO GESTION DE OPERACIONES -> LABORATORIO ESPECIALIZADO EN GESTIÓN DE OPERACIÓN LE-IN-02
- LABORATORIO DE MICROBIOLOGÍA -> LABORATORIO DE MICROBIOLOGIA Y BIOPROSPECCION MEDIOAMBIENTAL
- LABORATORIO DE CALIDAD DE AGUAS Y SERVICIOS PÚBLICOS -> ADMINISTRACIÓN LABORATORIO DE CALIDAD DE AGUAS Y SERVICIOS PÚBLICOS
- OFICINA COORDINACIÓN DE LAB. MADERAS -> OFICINA DE PROFESORES LAB. MADERAS

**Comment by ludwinggsanchez** [comment]
Finalmente, se tiene que los siguientes 40 espacios físicos no pudieron ser establecidos: [ubicacionesFaltantes.csv](https://github.com/udistrital/arka_cliente/files/11972188/ubicacionesFaltantes.csv)

**Comment by ludwinggsanchez** [comment]
Se tiene el siguiente consolidado para compartir con planeación: [consolidadov0.csv](https://github.com/udistrital/arka_cliente/files/11974678/consolidadov0.csv)

**Comment by ludwinggsanchez** [comment]
Solicitar a almacén indicar las ubicaciones de las filas 1847:1852 de la hoja de elementos de **COMUNICACIÓN**

**Comment by ludwinggsanchez** [comment]
Se establece el siguiente consolidado de acuerdo a la información solicitada por planeación [consolidadov0.csv](https://github.com/udistrital/arka_cliente/files/11988651/consolidadov0.csv)
