### ISSUE TITLE
Ajuste de HU y desarrollo entradas

### ISSUE THREAD

**Issue by milo19980525** [udistrital/arka_cliente#1159]
Se requieren realizar ajustes en las entradas por aprovechamientos y por adiciones y mejoras.

**Especificaciones técnicas**

- El último desarrollo se encuentra en la rama release.
- Las HU asociadas se encuentran en: [HU10 y HU11](https://udistritaleduco-my.sharepoint.com/:x:/r/personal/cerochac_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7BF18511B9-93D8-496D-A09B-0081EFADF05C%7D&file=HU%20-%2005%20A%2015-4%20Entradas%20-%20Diferentes%20conceptos_V4..xlsx&action=default&mobileredirect=true).

**Sub Tareas**

1. Entradas por aprovechamientos y por adiciones y mejoras.

- [x] Cambiar los nombres de las columnas de la siguiente manera:
- Valor libros -> Valor mejorado
- Valor actual -> Valor libros
- Valor inicial -> Valor Entrada  

- [x] Ordenar las columnas así: inicial, libros, mejorado
- [x] Adicionar campo "Vida útil remanente"
  

**Criterios de aceptación**

- [x] Se evidencian los campos requeridos por la sección de Almacén con su respectivo nombre.
- [x] Se evidencia la organización de campos requerida.

**Requerimientos**

- [HU10 y HU11](https://udistritaleduco-my.sharepoint.com/:x:/r/personal/cerochac_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7BF18511B9-93D8-496D-A09B-0081EFADF05C%7D&file=HU%20-%2005%20A%2015-4%20Entradas%20-%20Diferentes%20conceptos_V4..xlsx&action=default&mobileredirect=true).

**Dependencias**

- ninguna

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Desarrollo en local.
- [x] Push en Feature.
- [x] Pruebas locales (funcionales).
- [x] PR a Develop.
- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ludwinggsanchez** [comment]
Columnas ajustadas:

![image](https://github.com/udistrital/arka_cliente/assets/35748918/3867a9f2-be6e-4752-8a13-86f56f0882bf)
