### ISSUE TITLE
Desarrollo cliente de consulta específica de catalogo de elementos

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#116]
Mostrar el árbol del catálogo específico seleccionado en el cliente de Angular 7 de ARKA II. La tarea cuenta con una estimación de 12 horas para su culminación.

**Comment by mafeave** [comment]
Se verifica desarrollo de la cosulta general del catálogo y carga de select de catálogos en la consulta del arbol:

![Captura de pantalla de 2019-10-14 22-01-39](https://user-images.githubusercontent.com/14035745/67013012-03ce2100-f0b8-11e9-8d82-d45a88d65d54.png)

Se da por finalizada la tarea.
