### ISSUE TITLE
Despliegue a producción Arka II

### ISSUE THREAD

**Issue by milo19980525** [udistrital/arka_cliente#1160]
Se requiere realizar la salida a producción de todas las funcionalidades desarrolladas en Arka II a la fecha, relacionadas con el MVP, teniendo en cuenta los siguientes requerimientos:

**Definition of Done - DoD - Despliegues**

- [x] Aprobación Gerente de Proyectos: no obligatorio Hotfix, Bugfix
- [x] Aprobación Funcionamiento
- [x] Actualización de Swagger en WSO2 
- [x] Revisión y actualización de variables de entorno - L
- [x] Pruebas funcionales (grupo de soporte) - MC, Almacén, Ludwing
- [x] Pruebas de carga, estrés y seguridad (líder de seguridad)
- [x] Pruebas de usuario (Preguntar Revisión SIGUD) - Almacen
- [x] Pruebas unitarias (equipo de desarrollo)
- [x] Reportes apuntando a data de producción.
- [x] Revisión de sincronización de bases de datos en ambientes (pruebas y producción) - L
- [x] Revisión de configuración de roles en Api de configuración (pruebas y producción) - L
- [x] Revisión de estado de bases de datos (ETL) - L
- [x] Revisión de actualización de APIs consumidas (terceros, transversales) - L
- [x] Definición y/o actualización de manual de usuario/videotutoriales - MC
- [x] Documento técnico - L

**Comment by ludwinggsanchez** [comment]
Avance [Documento técnico](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/luasanchezl_udistrital_edu_co/EVZ7_y6bPy1EuDk02CvA-qABFPcxTtFEfQaEB7Mmmc-lAA?e=MRMePm)

**Comment by milo19980525** [comment]
Ludwing tomar como ejemplo: https://udistritaleduco-my.sharepoint.com/:w:/g/personal/yaortizv_udistrital_edu_co/EUHfVe8MzjVNja7m39gFSz0BxpNNYz1eADjqBWjhjhr8hg?e=UvuF41

**Comment by ludwinggsanchez** [comment]
Revisar variable ADMINISTRATIVA_SERVICE en arka_mid

**Comment by ludwinggsanchez** [comment]
Se ejecuta migración faltante en ambiente de producción en [kanban](https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=54736)

**Comment by milo19980525** [comment]
@ludwinggsanchez el valor de la variable ADMINISTRATIVA_SERVICE es: api.intranetoas.udistrital.edu.co:8104/v1/

**Comment by milo19980525** [comment]
Agregar al documento técnico:

**Apis y clientes que dependen de novedades
Limitaciones (funcionalidades no contempladas en el MVP) 
Autenticación**
Para iniciar sesión se utilizará únicamente el usuario de Outlook (correo institucional), la autenticación con WSO2 está solamente en pruebas.

**Comment by milo19980525** [comment]
Hablar con Jhon para que habilite la autenticación por outlook

**Comment by milo19980525** [comment]
- [ ] Preparar script de borrado de datos en producción (bases de datos, esquemas y tablas afectadas por las pruebas a realizar)

**Comment by milo19980525** [comment]
Se debe actualizar la variable `ACTA_RECIBIDO_CRUD` a: api2.intranetoas.udistrital.edu.co:8206/v1/

**Comment by milo19980525** [comment]
Los videotutoriales están aprobados por el usuario y están en: https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EvcbwYlaBbtHoqAn0dSIAkoB-wWs6MWbE9Y8IPEESFSX9w?e=flXfr7

**Comment by ludwinggsanchez** [comment]
Confirmar valor de CUENTAS_CONTABLES_SERVICE en arka_mid: debe ser http://api2.intranetoas.udistrital.edu.co:8209/v1/

**Comment by milo19980525** [comment]
La variable de entorno "CUENTAS_CONTABLES_SERVICE" tiene el valor de: api2.intranetoas.udistrital.edu.co:8209/v1/

**Comment by ludwinggsanchez** [comment]
Urgente: establecer el filtro para funcionarios y poder determinar la lista de terceros que aparecen disponibles para seleccionar en el módulo de salidas.

**Comment by ludwinggsanchez** [comment]
Resolver el siguiente error de permisos `pq: permission denied for table novedad_elemento`

**Comment by milo19980525** [comment]
Se solicita la actualización de permisos sobre la tabla novedad elemento: https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=54806&group_id=177

**Comment by milo19980525** [comment]
Se definen como documentos finales necesarios para salir a producción:

1. [Videotutoriales](https://udistritaleduco-my.sharepoint.com/:f:/g/personal/computo_udistrital_edu_co/EvcbwYlaBbtHoqAn0dSIAkoB-wWs6MWbE9Y8IPEESFSX9w?e=flXfr7)
2. [Diagrama de flujo](https://drive.google.com/file/d/15njiBPnkRf49MOOfwWyriD8aTPhJcsGn/view?usp=sharing)
3. [Diagrama modular](https://drive.google.com/file/d/1Jl8pj2sToIWRRXjb_GNW4MCRPdkRxZFR/view?usp=sharing)
4. [Socialización de diagramas](https://udistritaleduco-my.sharepoint.com/personal/computo_udistrital_edu_co/_layouts/15/stream.aspx?id=%2Fpersonal%2Fcomputo%5Fudistrital%5Fedu%5Fco%2FDocuments%2FINVERSI%C3%93N%2FPROYECTOS%20DE%20INVERSI%C3%93N%2FGERENCIA%20DE%20PROYECTOS%2FPROYECTOS%20OAS%2FPROYECTO%20ARKA%20II%2FEJECUCI%C3%93N%2FActas%20de%20reuni%C3%B3n%2FLevantamiento%20de%20requerimientos%2FArka%20II%20%2D%202022%2FActa%20No%2E093%20%2D%202022%20%2D%20Arka%20II%20%2D%20Revisi%C3%B3n%20Flujo%2FRevisi%C3%B3n%20Flujo%20de%20Arka%20II%2Emp4&ct=1690822224077&or=OWA-NT&cid=9ce0589c-0aee-94e4-c323-1d16ddd24e86&ga=1)
5. [Documento técnico](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/luasanchezl_udistrital_edu_co/EVZ7_y6bPy1EuDk02CvA-qABFPcxTtFEfQaEB7Mmmc-lAA?e=MRMePm)
6. [Formato entregable de Arka II](https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EZRZxjfYZ1NWWU41fc3FyMMBAViOH7YH8KIsRuETET1X9Q?e=MQkiCY)

**Comment by norbeydanilo** [comment]
OK documentación y acta.

Pendiente día y hora de reunión entre dependencias.

03 de agosto 2023 revisado y enviada solicitud para entrega

**Comment by milo19980525** [comment]
[DepuraciónEspaciosFísicos (1).xlsx](https://github.com/udistrital/arka_cliente/files/12252483/DepuracionEspaciosFisicos.1.xlsx)

En lo referente al avance de depuración de espacios físicos, se responden los siguientes comentarios:

- Aquellos espacios físicos que se tenga conocimiento existen pero no están registrados se deben registrar en SGA y deben asociarse en una nueva columna el código del espacio físico añadido.
- Los espacios físicos que están en duda y consulta en las respectivas dependencias una vez sean resueltas se podrán evaluar los diferentes casos para tomar las acciones requeridas.
- Aquellos espacios que fueron trasladados, amablemente solicitamos se registre en una nueva columna cual es su código para poder realizar las asignaciones pertinentes.

**Comment by ludwinggsanchez** [comment]
Para migrar los elementos asociando el centro de costos (relación sede-dependencia) se requiere hacer los siguientes cambios:

- Crear la siguiente tabla en esquema oikos:

![image](https://github.com/udistrital/arka_cliente/assets/35748918/4f802d67-52a9-4772-8fec-ca0e7b64592a)

- Ajustar servicios para consultar salidas y bajas (que la consulta no se haga por ubicación sino por centro de costos).
- Ajustar interfaz para mostrar detalle de salidas y bajas (que no se muestre sede-dependencia-ubicación sino sede-dependencia).
- En las nuevas salidas y traslados no se manejará centro de costos, eso sólo se hará para los elementos migrados.

- Establecer el mapeo sede-dependencia -> centro de costos para los elementos que así lo requieran

Finalmente, se sugiere establecer una solución para actualizar dicha información en las salidas migradas. **Lo anterior, debido a que el módulo de levantamiento de inventarios no está implementado.**

**Comment by milo19980525** [comment]
Se ejecutan las migraciones asociadas al centro de costos en ambiente de producción.
https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=55922

**Comment by milo19980525** [comment]
Queda pendiente cargue de cuentas contables por falta de datos proporcionados por la Sección de contabilidad.
