### ISSUE TITLE
Creación de centro de costos

### ISSUE THREAD

**Issue by milo19980525** [udistrital/arka_cliente#1166]
Se requiere ajustar el esquema de base de datos de OIKOS, crear controladores para "Centro de costos" y ajustar las consultas que se hacen en arka hacía todos los elementos, de igual manera en los reportes.

**Especificaciones técnicas**

- El aplicativo en su versión estable y actualizada se encuentra en la rama master.
- El archivo con los centros de costos se encuentra en: https://sgral.udistrital.edu.co/xdata/rec/res_2023-140.pdf.

**Sub Tareas**

- [x] Crear la siguiente tabla en esquema oikos:
![image](https://github.com/udistrital/arka_cliente/assets/106636533/845222ee-9d39-410b-b406-7990c4e6a192)
- [x] Ajustar servicios para consultar salidas y bajas (que la consulta no se haga por ubicación sino por centro de costos).
- [x] Ajustar interfaz para mostrar detalle de salidas y bajas (que no se muestre sede-dependencia-ubicación sino sede-dependencia).
- [x] En las nuevas salidas y traslados no se manejará centro de costos, eso sólo se hará para los elementos migrados.
- [x] Establecer el mapeo sede-dependencia -> centro de costos para los elementos que así lo requieran.
- [x] Ajustar reportes de knowage para elementos antiguos con código de centro de costos.

**Criterios de aceptación**

- [x] Se evidencia cambio en estructura de datos del esquema Oikos.
- [x] Se pueden consultar centros de costo por el SMBD y por consultas al api de oikos.
- [x] Se resuelve incidente de consulta de movimientos, actas y reportes de elementos cargados de la migración.

**Requerimientos**

- [x] Las funcionalidades se encuentran en master.
- [x] Se cuenta con el archivo de centro de costos.

**Dependencias**

- oikos_api

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico

**Comment by ludwinggsanchez** [comment]
Resolución depurada 
[res_2023-140-pages-5-13.xlsx](https://github.com/udistrital/arka_cliente/files/12375688/res_2023-140-pages-5-13.xlsx)

**Comment by ludwinggsanchez** [comment]
Pendiente establecer la dependencia a los siguientes centros de costos:

[dependenciasPendientes.csv](https://github.com/udistrital/arka_cliente/files/12416387/dependenciasPendientes.csv)

**Comment by ludwinggsanchez** [comment]
Archivo final centro costos - sede - dependencia
[centros_costos.csv](https://github.com/udistrital/arka_cliente/files/12426372/centros_costos.csv)

**Comment by milo19980525** [comment]
Se opta por crear la tabla centro_de_costos en el esquema de movimientos_arka debido a que no se aprobó su adición en el esquema de oikos.
