### ISSUE TITLE
Ajustes finales ARKA II

### ISSUE THREAD

**Issue by milo19980525** [udistrital/arka_cliente#1168]
Se requiere crear un reporte de inventario por funcionario, revision de reporte de entradas y paginar salidas.

**Especificaciones técnicas**

- El aplicativo en su versión estable y actualizada se encuentra en la rama master.

**Sub Tareas**

- [x] Realizar reporte de inventario por funcionario con base en la estructura definida en: https://udistritaleduco-my.sharepoint.com/:x:/r/personal/computo_udistrital_edu_co/_layouts/15/Doc.aspx?sourcedoc=%7B548EC01C-2AC8-43A0-A467-D2B2B59DF09E%7D&file=HU%20-%20Reportes%20Arka%20II.xlsx&action=default&mobileredirect=true. Tener en cuenta el parámetro de identificación del funcionario.
- [x] Paginar salidas, tomando como base el de actas de recibido.
- [x] Revisar reporte de entrada dado que no salen todos los elementos.

**Criterios de aceptación**

- [x] El reporte de entradas muestra todos los elemntos asociados a una entrada
- [x] El reporte de inventario por funcionario, retorna todos los elementos asignados a un funcionario filtrando por la cédula.
- [x] Se paginan los movimientos de salidas al consultarlos.

**Requerimientos**

- [x] Las funcionalidades se encuentran en master.
- [x] la tabla centro de costos se encuentra creado en ambiente de producción.

**Dependencias**

- ninguna.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM

**Comment by milo19980525** [comment]
@ludwinggsanchez Por favor comentar el issue con los cambios realizados:

- Mostrar pantallazos de reportes
- Evidenciar Paginación de salidas

**Comment by ludwinggsanchez** [comment]
Se agregan en el sistema de configuración las rutas correspondientes a la paginación de salidas:

![image](https://github.com/udistrital/arka_cliente/assets/35748918/b0f9cd69-9309-4514-b2ac-ae70a4702ee7)

**Comment by ludwinggsanchez** [comment]
El filtro en la tabla de consulta de salidas se refleja en la url:

![image](https://github.com/udistrital/arka_cliente/assets/35748918/a20d0380-e6c1-484a-87ad-211a9a93856f)
