### ISSUE TITLE
Desarrollo cliente de consulta general de catalogo de elementos

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#117]
Desarrollar la consulta que muestre todos los catálogos de biens existentes en el sistema de ARKA II. La tarea cuenta con una estimación de 8 horas para su culminación.

**Comment by mafeave** [comment]
Se verifica consulta de los catálogos:
![Captura de pantalla de 2019-10-14 22-03-10](https://user-images.githubusercontent.com/14035745/67014322-442e9e80-f0ba-11e9-9700-bb034c5bb56d.png)
