### ISSUE TITLE
Documento Diagnósito Final

### ISSUE THREAD

**Issue by milo19980525** [udistrital/arka_cliente#1173]
Se requiere realizar el documento final "Diagnóstico" para todos las funcionalidades desarrolladas y por desarrollar en Arka v2.

**Especificaciones técnicas**

- El formato del informe diagnóstico se encuentra en: https://udistritaleduco-my.sharepoint.com/:w:/g/personal/computo_udistrital_edu_co/EcEzaU-TYfNMpdLTB7j9u5IB-pa9uKfFzPSdI-ANpHqThA?e=1l6H4s.

**Sub Tareas**

- [x] Con base en el formatos propuesto desarrollar el informe.

**Criterios de aceptación**

- [x] Se genera un diagnóstico final sobre los proyectos llevados a cabo en Arka v2..

**Requerimientos**

- [X] Formato para desarrollar.

**Dependencias**

- No presenta.

**Definition of Ready - DoR**

- [x] Está refinada y estimada en puntos de historia por el equipo.
- [x] Incluye la descripción y criterios de aceptación, con el detalle funcional y especificaciones técnicas, de forma entendible por cualquier miembro del equipo.
- [x] No tiene bloqueos que impidan su ejecución.
- [x] Las dependencias entán identificadas y resueltas.
- [x] Puede ser probada dentro del Sprint. 

**Definition of Done - DoD - Desarrollo**

- [x] Criterios de aceptación cumplidos.
- [x] Documentación de issue realizada.
- [x] Aprobada por SM/Líder técnico.

**Comment by ludwinggsanchez** [comment]
Avance documento diagnóstico: https://udistritaleduco-my.sharepoint.com/:w:/g/personal/luasanchezl_udistrital_edu_co/EZFlQUgSNq1JsUHfP6DpKKwBO1C7QOMnzZqOT65fT4Q5Iw?e=w01SZY

**Comment by milo19980525** [comment]
@ludwinggsanchez por favor añadir los videotutoriales, en las limitaciones mencionar como se pueden subsanar o que proceso se deben realizar.

Además, revisar en plan de mejoramiento la toma por qr del inventario y relacionamiento con Idexud (SIDEXUD).

**Comment by ludwinggsanchez** [comment]
Documento actualizado

**Comment by milo19980525** [comment]
@ludwinggsanchez Quedan pendiente los videotutoriales

**Comment by ludwinggsanchez** [comment]
Videotutoriales incluidos en el documento.

**Comment by milo19980525** [comment]
@ludwinggsanchez perfecto, buen trabajo, gracias
