### ISSUE TITLE
Optimizar Servicio Proveedor

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#121]
se debe optimizar el procesamiento de datos asociados a los proveedoresdebido a una larga espera en la carga de los formularios:

- [x] Registro

- [x] Edicion

- [x] Verificacion

- [x] Detalle

**Comment by mafeave** [comment]
Se hace despliegue de los commits y se verifica mejoramiento en el tiempo de la carga de los proveedores en el select de registro del acta y de consulta del acta,
![image](https://user-images.githubusercontent.com/14035745/66792570-fa2d9900-eebe-11e9-9faf-128b755445dc.png)

-
