### ISSUE TITLE
Desarrollo creación de subgrupo desde el cliente de ARKA II

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#124]
Se debe registrar los subgrupos asociados a un grupo y un catálogo de bienes de ARKA II. La tarea fue una tarea no planeada que reemplazó la tarea de _**Desarrollo edición del catalogo de elementos - 16 horas**_ ya que no era necesaria puesto que ya existían procedimientos que realizan esto desde el CRUD.

**Comment by Miavega** [comment]
Se realiza el desarrollo desde el cliente para registrar los subgrupos, se anexan imágenes del desarrollo:

Registro: 
![imagen](https://user-images.githubusercontent.com/23342808/66344879-7569da80-e914-11e9-94cf-43a1e0808598.png)

Verificación:
![imagen](https://user-images.githubusercontent.com/23342808/66344977-a4804c00-e914-11e9-983c-aa78dc77e7eb.png)

Consulta de nuevo registro:
![imagen](https://user-images.githubusercontent.com/23342808/66345008-b82bb280-e914-11e9-82de-91e1e7284884.png)

Datos Erroneos:
![imagen](https://user-images.githubusercontent.com/23342808/66345031-c8dc2880-e914-11e9-9a5c-e2ee3125ecaf.png)

**Comment by mafeave** [comment]
Se verifica el desarrollo realizado, se unifica con el registro del grupo, ver https://github.com/udistrital/arka_cliente/issues/127
