### ISSUE TITLE
TAREA NO PLANEADA: Ajustar consulta de reporte de entradas en Spagobi

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#125]
Se debe ajustar el reporte de entradas en SpagoBI con al entorno local de la OAS. La tarea no fue planeada y fue necesario 4 horas para cumplirla.

**Comment by Miavega** [comment]
Se corrige el reporte ajustando los parámetros al entorno local de la OAS:
 
![imagen](https://user-images.githubusercontent.com/23342808/66346431-c7602f80-e917-11e9-8155-6e517d863f07.png)

El reporte actualizado es la **_versión 11_**  alojada en **_pruebas_arka, SpagoBI_**

**Comment by mafeave** [comment]
Se verifica ajuste de la consulta y correcta generación de los reportes de entradas.
