### ISSUE TITLE
Desarrollo creacion grupo desde componente arbol 

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#127]
Creacion del registro del componente grupo del arbol de catalogo

**Comment by mafeave** [comment]
Se verifica registro de los grupos y la unificación con el registro de los subgrupos:
![Captura de pantalla de 2019-10-14 22-04-55](https://user-images.githubusercontent.com/14035745/66958817-ad68d000-f02e-11e9-96ef-4f7695501804.png)

**Comment by mafeave** [comment]
Se da por finalizada la tarea.
