### ISSUE TITLE
TAREA NO PLANEADA Revisión servicio para cargar datos con carga masiva

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#128]
se debe revisar servicio desplegado de carga de archivo de elementos masivos para acta de recibido debido a un error de sintaxis erronea

**Comment by ManuelMurillo** [comment]
se relacionan los cambios realizados en el issue #131

**Comment by mafeave** [comment]
Se verifica funcionamiento del servicio de carga masiva de elementos, se da por finalizada la tarea.
