### ISSUE TITLE
Consultar el arbol de catalogo con las cuentas contables asociadas

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#129]
Se debe generar el árbol de catálogo con las cuentas contables asociadas a cada subgrupo. La tarea cuenta con una disponibilidad de 10 horas para su culminación.

**Comment by Miavega** [comment]
Se decidio no añadir las cuentas contables al arbol por simplicidad del mismo, se propuso ahora un _**detalle**_, en el que apenas el usuario seleccione un subgrupo y seleccione el botón, se despliegue la información del mismo con sus respectivas cuentas contables. Para esto se hizo una consulta en el MID que permite traer toda esta información. El resultado es el siguiente:

![imagen](https://user-images.githubusercontent.com/23342808/66846982-436dff00-ef38-11e9-82c3-e69bcc9652cf.png)

**Comment by Miavega** [comment]
El API de movimientos aún no está desplegada por lo que falta añadir esa información, actualmente se muestra el ID.

**Comment by mafeave** [comment]
Se verifica funcionalidad, se da por finalizada la tarea.
