### ISSUE TITLE
Ajustar reporte de entradas para consultar información de la base de datos del core y administrativa

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#133]
Se debe ajustar el reporte de entradas para que consuma los servicios de administrativa y el core, y así poder traer los campos de **_tipo_contrato_** y _**unidad_medida**_. La tarea cuenta con una estimación de 12 horas para su culminación.

**Comment by Miavega** [comment]
Se ajusta el reporte consumiendo los servicios de administrativa y del core. 

![imagen](https://user-images.githubusercontent.com/23342808/66724351-a2256280-edea-11e9-96d0-40d75111f3b7.png)

Además se ajustan otros detalles no contemplados en la tarea:
- Fuente en UpperCase
- Moneda con signo de pesos y unidades de miles

**Comment by Miavega** [comment]
Se adjunta proyecto en Kanowage Studio:

[report.rptdesign.zip](https://github.com/udistrital/arka_cliente/files/3722620/report.rptdesign.zip)

**Comment by mafeave** [comment]
Pendiente verificar reporte en SpagoBI, se queda cargando el usuario al iniciar sesión.

**Comment by Miavega** [comment]
Se actualiza reporte en SpagoBI quedan en _**Version 14**_:

![imagen](https://user-images.githubusercontent.com/23342808/66835493-385da380-ef25-11e9-9bcf-8533facef2fd.png)

**Comment by mafeave** [comment]
Se debe:
- Agregar el año del contrato, 
- Revisar correspondencia entre el contrato y tipo de contrat, para el ejemplo, la entrada corresponde al contrato 859/2019 con tipo de contrato 14 "Orden de Servicios" y en el reporte sale con tipo de contrato 6 "Contrato de Prestación de Servicios Profesionales o Apoyo a la Gestión".

**Comment by DianaPatriciaRamirez** [comment]
El ingeniero @Miavega agregará el año del contrato, para poder cerrar esta actividad. Para la segunda actividad se creará un nuevo issue.

**Comment by Miavega** [comment]
Se agrega la vigencia al reporte como lo estipulado en la reunión:

![imagen](https://user-images.githubusercontent.com/23342808/67310103-bd673080-f4c2-11e9-820b-98b444d616f4.png)

Reporte en Knowage Studio:

[report.rptdesign.zip](https://github.com/udistrital/arka_cliente/files/3757254/report.rptdesign.zip)

**Comment by mafeave** [comment]
La revisión de la correspondencia del tipo de contrato se traajará mediante el issue: https://github.com/udistrital/arka_cliente/issues/143
