### ISSUE TITLE
desarrollo asignacion de cuentas contables

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#135]
Requisitos:

- [x] Simular servicio de API Financiera para cuentas contables

- [x] tipos de movimiento

- [x] revision con analista

**Comment by ManuelMurillo** [comment]
Se agrega la direccion del modelo del plan de cuentas del API de financiera con las cuentas de la clase 1 (Activo)

http://10.20.2.143:8089/swagger/

http://10.20.2.143:8089/v1/cuenta_contable

http://10.20.2.143:8089/v1/nivel_clasificacion

**Comment by ManuelMurillo** [comment]
![20190911_150925 (1)](https://user-images.githubusercontent.com/29108085/66731785-aa979080-ee1e-11e9-972a-ba4ffcee32f4.jpg)

en esta imagen se encuentran los posibles movimientos relacionados al catalogo revisados en la reunion de 2019/09/11

**Comment by ManuelMurillo** [comment]
en el siguiente commit  0f5c00e808c5c28f6b8cf8340a46938145675378 se encuenta la agregacion y modificacion de cuentas contables #142

**Comment by mafeave** [comment]
Se verifica funcionalidad para la asignación de cuentas contables a los grupos del catálogo de elementos
![Captura de pantalla de 2019-11-27 17-15-56](https://user-images.githubusercontent.com/14035745/69762945-b70b4a80-1139-11ea-8834-01d8d6944876.png)

Se da por finalizada la tarea.
