### ISSUE TITLE
Ajustar el modelo de datos y API de catálogo de elementos para asociar el tipo del elemento al grupo

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#137]
Ajustar el modelo de datos del API de catálogo de elementos para que se pueda asociar el tipo de bien (Consumo, consumo controlado y devolutivo) a los subgrupos del catálogo. También se debe modificar la relación de los elementos con el catálogo puesto que ahora va asociada al subgrupo. La tarea cuenta con una estimación de 3 horas para su culminación. Sin embargo se deja como observación que puede requerir un poco más de tiempo dado que toca actualizar el modelo de datos en PgModeler, generar migraciones en GO, ajustar las transacciones para añadir grupos y subgrupos y la consulta. **Se estima un tiempo de al menos 8 horas para realizar todo esto.**

**Comment by Miavega** [comment]
Se ajusta el modelo de datos quedando de la siguiente manera: 

![catalogo_elementos](https://user-images.githubusercontent.com/23342808/66942996-e5ace600-f00f-11e9-9327-4e49c8a7b9fe.png)

El modelo en PgModeler y SQL:

[catalogo_elementos.zip](https://github.com/udistrital/arka_cliente/files/3735611/catalogo_elementos.zip)

**Comment by Miavega** [comment]
Se ajusta el API a los cambios realizados en el modelo en los commits [076e164](https://github.com/udistrital/catalogo_elementos_crud/commit/076e1649a20d31dbd8d4a0d3f3822449fb381832) y [4126479](https://github.com/udistrital/catalogo_elementos_crud/commit/4126479616d6da62e6a8549c175d7c8c5c84d456)

**Comment by Miavega** [comment]
Los subgrupos ya traen el tipo de bien asociado:

![imagen](https://user-images.githubusercontent.com/23342808/66957523-03884400-f02c-11e9-818a-426e9c052a42.png)

**Comment by Miavega** [comment]
Se ajusta el MID para la consulta de cuentas en el commit [d4e286b](https://github.com/udistrital/arka_mid/commit/d4e286b631250057a13651268017aa8fe44a4303)

**Comment by mafeave** [comment]
Se verifican ajustes, se da por finalizada la tarea.
