### ISSUE TITLE
Revision de las peticiones de la edicion del acta de recibido

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#139]
Se necesita resolver un problema en las peticiones de la edicion del acta en la cual se esta realizando la peticion solo una vez, al volver a entrar en el componente esta deja de funcionar correctamente:

- [x] Revision del API Cliente desplegada

- [x] Observacion de problemas y correcciones

- [x] Realizar los ajustes pertinentes

**Comment by mafeave** [comment]
Se verifica correcta modificación del acta de recibido en el entorno de pruebas, se da por finalizada la tarea.
