### ISSUE TITLE
Ajustar el cliente de catálogo de elementos para asociar el tipo del elemento al grupo

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#140]
Se debe ajustar el catálogo de elementos para asociar el tipo de elemento al que pertenece el grupo. La tarea cuena con una estimación de 4 horas para su culminación.

**Comment by Miavega** [comment]
Se ajusta el árbol del catálogo de elementos para que indique el tipo de bien al que pertenece:

https://github.com/udistrital/arka_cliente/issues/140
![imagen](https://user-images.githubusercontent.com/23342808/67166729-9d672e00-f357-11e9-8c53-968e767eb045.png)

Se deja como observación que no se ha podido configurar la cabecera de la tabla para que no muestre la columna del JSON sino que salga la que se desea

**Comment by mafeave** [comment]
Se hace despliegue y se verifica asignación de tipo de bien a los grupos del catálogo
![Captura de pantalla de 2019-11-27 17-46-47](https://user-images.githubusercontent.com/14035745/69764317-eb810580-113d-11ea-9d10-bc89c1c2654f.png)

Se da por finalizada la tarea.
