### ISSUE TITLE
Registrar elementos al catálogo en el Cliente

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#141]
Se debe crear el componente que permita registrar elementos al catálogo de elementos en el cliente. La tarea cuenta con una estimación de 10 horas para su culminación.

**Comment by Miavega** [comment]
Se crea formulario para añadir elementos a un subgrupo: 

![imagen](https://user-images.githubusercontent.com/23342808/67168177-4c5f3600-f367-11e9-90f8-807029a85c27.png)

**Comment by Miavega** [comment]
Se valida formulario: 

Campos
![imagen](https://user-images.githubusercontent.com/23342808/67168224-a6f89200-f367-11e9-8d42-ff89c97060f1.png)

Subgrupo seleccionado

![imagen](https://user-images.githubusercontent.com/23342808/67168214-98aa7600-f367-11e9-97fc-6e33e405bb17.png)

**Comment by Miavega** [comment]
Se realiza registro: 

- Cliente

![imagen](https://user-images.githubusercontent.com/23342808/67168236-d3141300-f367-11e9-8e77-cfe8aa42ed57.png)

- Base de datos

![imagen](https://user-images.githubusercontent.com/23342808/67168240-de673e80-f367-11e9-9562-7f91966c27e0.png)

**Comment by mafeave** [comment]
Se hace la prueba del registro de un elemento a un subgrupo del catalogo
![Captura de pantalla de 2019-11-27 17-32-05](https://user-images.githubusercontent.com/14035745/69763700-0e121f00-113c-11ea-9353-4c8c26076907.png)

Tener en cuenta las siguientes observaciones:

- Revisar translate del formulario:
  - GLOBAL.registro_elementos
  - GLOBAL.registrar_elementos

- El registro de elementos no debe solicitar los campos de fecha inicio y fecha fin
- No se están listando los elementos que conforman el catálogo de elementos

**Comment by mafeave** [comment]
Ajustes realizados.
