### ISSUE TITLE
Revisar correspondencia entre el contrato y tipo de contrato.

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#143]
Se debe revisar que el contrato que trae el reporte corresponda al que fue registrado al momento de hacer la entrada. Para el ejemplo, la entrada corresponde al contrato 859/2019 con tipo de contrato 14 "Orden de Servicios" y en el reporte sale con tipo de contrato 6 "Contrato de Prestación de Servicios Profesionales o Apoyo a la Gestión"

**Comment by Miavega** [comment]
Se realiza el ajuste en el reporte para que filtre el contrato no solo por **_numero_contrato_**, sino por **_vigencia_** también. Sin embargo, el resultado para el ejemplo propuesto de contrato 859/2019 no muestra resultados dado que ese contrato no existe para esa vigencia, la información de ese contrato es para una vigencia de 2017, por lo que se debe revisar los contratos existentes en administrativa para saber por qué hay ambiguedad en la información.

![imagen](https://user-images.githubusercontent.com/23342808/67323069-923b0c00-f4d7-11e9-914a-7958df22be7d.png)

Archivo Knowage Studio: 

[report.rptdesign.zip](https://github.com/udistrital/arka_cliente/files/3758009/report.rptdesign.zip)

**Comment by DianaPatriciaRamirez** [comment]
@jairolh sugiere revisar si está el registro en la base de datos o si se está realizando mal la consulta. También se sugiere realizar consulta mediante TuLeap para ver si se está revisando la base de datos correcta y si se tienen los permisos completos para realizar esta consulta @mafeave
