### ISSUE TITLE
Modificacion de formularios de entrada para las diferentes entradas

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#145]
Se debe agregar los formularios para la creacion y modificacion de cada una de los tipos de entrada para el catalogo de elementos

**Comment by ManuelMurillo** [comment]
se tuvo que proceder a realizar unas modificaciones al formulario dinamico lo cual conllevo a que se invirtieran mas horas en el desarrollo de esta tarea. Total horas: 16

**Comment by ManuelMurillo** [comment]
0f5c00e808c5c28f6b8cf8340a46938145675378

**Comment by mafeave** [comment]
Se verifica asignación de cuentas por tipo de entrada
![Captura de pantalla de 2019-11-27 17-56-21](https://user-images.githubusercontent.com/14035745/69764688-41a27880-113f-11ea-84ae-dfc70a41eab2.png)

Se da por finalizada la tarea.
