### ISSUE TITLE
TAREA NO PLANEADA: Generar modelo de datos que se adapte al API de movimientos de Kronos

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#147]
Se debe generar un modelo de datos que permita consumir el API de movimientos de KRONOS y permita registrar todos los tipos de movimientos del sistema ARKA II.

**Comment by Miavega** [comment]
Se genera un modelo de datos propuesto para que se pueda consumir el API de movimientos de Kronos y se manejen los diferentes tipos de movimientos en ARKA. En este modelo no se contempla la bodega de consumo ya que a consideración es mejor realizar otra API para este proceso pero se deja a consideración:

- Modelo de datos:
![movimientos_arka](https://user-images.githubusercontent.com/23342808/67601291-9a928180-f739-11e9-95e1-5cc994d21831.png)

- Archivo PgModeler y SQL:
[movimientos_arka.zip](https://github.com/udistrital/arka_cliente/files/3773644/movimientos_arka.zip)

**Comment by Miavega** [comment]
Se propone el modelo con los ajustes solicitados para su revisión:
![movimientos_arka](https://user-images.githubusercontent.com/23342808/67895078-d5c0f600-fb27-11e9-84c9-97fd6192d512.png)

Archivo PgModeler y SQL:
[movimientos_arka.zip](https://github.com/udistrital/arka_cliente/files/3790949/movimientos_arka.zip)

**Comment by mafeave** [comment]
Revisar:
- Campo clasificacion en la tabla formato_tipo_movimiento

**Comment by jairolh** [comment]
Se verifican ajustes propuestos, ok

**Comment by Miavega** [comment]
Se elimina campo clasificación en la tabla formato_tipo_movimiento:

![movimientos_arka](https://user-images.githubusercontent.com/23342808/68446870-01894f00-01ac-11ea-922d-ec834a7a645c.png)

Archivo PgModeler y SQL:

[movimientos_arka.zip](https://github.com/udistrital/arka_cliente/files/3822842/movimientos_arka.zip)

**Comment by mafeave** [comment]
Aprobado el modelo, se da por finalizada la tarea.
