### ISSUE TITLE
TAREA NO PLANEADA: Ajustar modelo de datos y API de catálogo de elementos de acuerdo a revisión con el usuario 

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#148]
Se debe ajustar el modelo y API de catálogo de elementos de acuerdo a la reunión con el cliente eliminando el tipo_bien ya que iría en el acta_recibido

**Comment by Miavega** [comment]
Se corrige el modelo de datos eliminanto la tabla _**tipo_bien**_:

![catalogo_elementos](https://user-images.githubusercontent.com/23342808/67602365-0249cc00-f73c-11e9-8fbb-c8651da3183a.png)

Archivo PgModeler y SQL:

[catalog_elementos.zip](https://github.com/udistrital/arka_cliente/files/3773695/catalog_elementos.zip)

**Comment by Miavega** [comment]
Se ajusta el API **_catalogo_elementos_crud_** en los siguientes commits:
- [7cf3930](https://github.com/udistrital/catalogo_elementos_crud/commit/7cf393012c12697c5824c4b8ca6cbe249f579647)
- [75109ab](https://github.com/udistrital/catalogo_elementos_crud/commit/75109ab194254ac3ea66034f2623b0895f8be26e)

**Comment by mafeave** [comment]
Se verifica ajuste en el modelo de datos y en el API Crud.
Se ajusta cliente para que no se solicite el tipo de bien al crear un grupo, https://github.com/udistrital/arka_cliente/commit/b92dd10406b85a0555f8df2426baf13ed77fb260
