### ISSUE TITLE
Carga de archivos para acta de recibido y entradas

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#149]
Se debe ajustar el cliente para permitir la carga de soportes en los módulos de **_acta de recibido_** y **_entradas_** consumiendo los servicios de NUXEO. La tarea cuenta con una estimación de 16 horas (2 semanas) para su culminación

**Comment by Miavega** [comment]
Ajuestes al modelo y API de entradas para que acepte soportes en el commit [53a4eb9](https://github.com/udistrital/entradas_crud/commit/53a4eb9c634dbaee7c890aec36d047383767ef4a)

**Comment by Miavega** [comment]
Se ajustan los servicios en el cliente para consumir el servicio de NUXEO, falta configurar el espacio de trabajo en _**documentos_crud**_ para dar por finalizada la tarea.

**Comment by Miavega** [comment]
Se configura el espacio de trabajo y queda funcionando en NUXEO:

![imagen](https://user-images.githubusercontent.com/23342808/68548403-8b0e6c00-03ba-11ea-9034-37a3dd2aacba.png)

**Comment by mafeave** [comment]
Se verifica carga de documento para el registro de entradas, con el tipo de entrada por Sobrante

**Comment by mafeave** [comment]
Se debe revisar la carga de documentos del acta de recibido:
- Se está cargando el documento en Nuxeo, pero no queda el id en el registro del soporte, ej: http://pruebasapi.intranetoas.udistrital.edu.co:8206/v1/soporte_acta?query=ActaRecibidoId:68, donde documentoId queda en 0
