### ISSUE TITLE
Realizar ajustes de Mockups

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#15]
Se deben realizar los ajustes solicitados a los mockups de los procedimientos _**Registro Acta Recibido**_ y _**Baja Bien**_ .

**Comment by mafeave** [comment]
Se verifica commit, con la eliminación de los datos correspondientes a los contratos en los fomulario de acta de recibido y verificación de acta de recibido.

**Comment by Miavega** [comment]
En el siguiente [enlace](https://drive.google.com/drive/folders/1k4BK57ia-kbRApdCsDgIA2HzhPUahWRl) se encuentran los ajustes a los mockups del procedimiento de entradas. Se deja como observación revisar algunas entradas que pueden no tener IVA.

**Comment by mafeave** [comment]
Se verifican los mockups, queda pendiente la validación con el usuario final.
