### ISSUE TITLE
TAREA NO PLANEADA: Transaccion para registro de cuentas contables asociadas al catalogo

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#150]
Se debe crear una transaccion en el API de catalogo definiendo el arreglo de cuentas contables asociados al subgrupo

- [x] Consulta

- [x] Registro

- [x] Edicion

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/catalogo_elementos_crud/issues/1

**Comment by mafeave** [comment]
Se despliega y verifica funcionalidad de la transacción tr_cuentas_subgrupo, se da por finalizada la tarea.
