### ISSUE TITLE
Ajuste del Tema para el cliente

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#151]
Se debe ajustar el tema en el cliente para que corresponda a los lineamientos presentados:

- [x] Paleta de Colores

- [x] Header

- [x] Footer

- [x] Ajustes de Sidebar

- [x] Ajuste de Componentes

**Comment by ManuelMurillo** [comment]
en la rama Catalogo/movimientos/cuentas se encuentran los cambios del estilo y la paleta de colores del cliente

**Comment by ManuelMurillo** [comment]
Inicio o Dashboard:
![inicio](https://user-images.githubusercontent.com/29108085/68052799-77774d00-fcb8-11e9-90ea-45541fa55d5e.png)

Componentes:
![inicio_componentes](https://user-images.githubusercontent.com/29108085/68052821-8231e200-fcb8-11e9-8b1d-d5cd0e8ad7ec.png)

Responsive:
![inicio_responsive](https://user-images.githubusercontent.com/29108085/68052831-88c05980-fcb8-11e9-931a-ed6fae4416c2.png)

**Comment by mafeave** [comment]
Se verifican los commits realizados, se hace merge a las ramas dev y test.
Se puede revisar el resultado final desde [https://pruebasarka.portaloas.udistrital.edu.co/](https://pruebasarka.portaloas.udistrital.edu.co/)
