### ISSUE TITLE
Pruebas unitarias (API MID) Arka II - 20 horas - 2 semanas

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#158]
Se debe generar las pruebas unitarias a todas las funciones establecidas en los Helpers del API MID de ARKA II. La tarea cuenta con una estimación de 20 horas (2 semanas) para su culminación.

**Comment by Miavega** [comment]
Se generan los archivos que contienen las pruebas unitarias de todas las funcionalidades. Falta verificar las variables de entorno las cuales no están siendo tomadas por el API lo cual no permite tener un test exitoso al correr las pruebas. 

Se pueden verificar las pruebas en el commit [e36dd95](https://github.com/udistrital/arka_mid/commit/e36dd95e5a438430a3d271edb8dab40e83279b9d)

**Comment by Miavega** [comment]
Se ajustan las pruebas para que capturen las variables de entorno en el commit [227f7d7](https://github.com/udistrital/arka_mid/commit/227f7d78425b139dcd844bf99e868e9fd8c15d4a)

**Comment by Miavega** [comment]
Para correr las pruebas se debe ejecutar el comando: 
- `ACTA_RECIBIDO_CRUD=pruebasapi.intranetoas.udistrital.edu.co:8206/v1/ OIKOS_CRUD=pruebasapi.intranetoas.udistrital.edu.co:8087/v1/ ENTRADAS_CRUD=pruebasapi.intranetoas.udistrital.edu.co:8207/v1/ PARAMETROS_GOBIERNO_CRUD=pruebasapi.intranetoas.udistrital.edu.co:8205/v1/ OIKOS_CRUD=pruebasapi.intranetoas.udistrital.edu.co:8087/v1/ ADMINISTRATIVA_SERVICE=pruebasapi.intranetoas.udistrital.edu.co:8104/v1/ CUENTAS_CONTABLES_SERVICE=10.20.2.143:8089/v1/ go test ./... -v`

**Comment by Miavega** [comment]
Resultado de las pruebas:

![imagen](https://user-images.githubusercontent.com/23342808/69001506-c672d400-08ad-11ea-84b7-69ac4afe5b26.png)

**Comment by mafeave** [comment]
Se verifica funcionamiento de las pruebas realizadas, se da por finalizada la tarea.
