### ISSUE TITLE
Ajustes solicitados por el analista del Acta de Recibido

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#159]
- [x] registro masivo FALTA IMAGEN DE REGISTRO YA QUE NO ESTÁ TRAYENDO EL RESULTADO DE LOS DATOS

- [x] editar falta ALERTAR QUE SE DEBE SELECCIONAR EL SOPORTE A RELACIONAR

**Comment by mafeave** [comment]
Revisar las siguientes observaciones:
- una vez se realiza el registro del acta de recibido, se está redireccionando al formulario que lista las actas antes de que aparezca el modal del registro exitoso, con lo cual, cuando se va a buscar el acta... no sale el id que se acaba de registrar
- Tener en cuenta que no está pidiendo como obligatorio el documento en el formulario de registro del acta de recibido.
