### ISSUE TITLE
Modelo de datos del procedimiento: Ingreso de Entradas

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/arka_cliente#16]
La plataforma requiere poder adminitrar el registro de entradas, basados en el flujograma en el SIGUP y la historia de usuario. Reconocer y categorizar los campos requeridos.

- [x] Abstraer los campos del procedimiento para el modelo de datos.

- [x] Categorizar los distintos datos requeridos y organizarlos en tablas

- [x] Generar Modelo de Datos apartir de las notas

**Calidad**

- [ ] El modelo de datos contiene todos los campos requeridos

- [ ] El modelo en base de datos es óptimo

- [ ] El modelo de datos queda documentando en este issue y en el repo

**Comment by Soulfilip-UD** [comment]
![Modelo de Datos de Registro de Entrada](https://user-images.githubusercontent.com/50924615/59135346-8ed83580-89b9-11e9-8e8f-a0fa38abb545.png)

**Comment by Soulfilip-UD** [comment]
[Modelo e Imagen SVG](https://github.com/udistrital/arka_cliente/files/3267721/ArkaII.zip)

**Comment by Soulfilip-UD** [comment]
Queda por socializar el modelo

**Comment by mafeave** [comment]
Socializado el modelo, se verifica archivo en pgmodeler e imagen, se da por finalizada la tarea
