### ISSUE TITLE
1ra revisión funcional hito 1 - Arka II - 6/Nov/2019

### ISSUE THREAD

**Issue by DianaPatriciaRamirez** [udistrital/arka_cliente#164]
De acuerdo a revisión realizada por la Oficina Asesora de Sistemas, surgen las siguientes observaciones:

ACTA DE RECIBIDO
- [x] Se recomienda ajustar la dirección de las flechas del menú.
- [x] Revisar límite de carga de los documentos.
- [x] Alerta que indique que la estructura del archivo no es compatible, para la carga masiva de elementos.
- [x] Cambiar el nombre del botón "Limpiar espacio" por "Descartar archivo".
- [x] Validar en la carga masiva, que pasó con el subgrupo ya que el archivo .xls si contiene dicha información.
- [x] Cuando cargue los elementos desde el archivo .xls se debe eliminar el archivo.
- [x] Deshabilitar el botón de cargue masivo, cuando ya se haya cargado uno.
- [x] Cuando se agreguen nuevos elementos, lo muestre de primero.
- [x] Cambiar mensaje de alerta "¿Esta seguro de la información registrada?".
- [x] Al registrar el acta de recibido, deshabilitar botones.
- [x] Validar los campos obligatorios al momento de cargar los elementos.

CONSULTA ACTA
- [x] No debe aparecer el botón de "Seleccionar archivo".
- [ ] Eliminar columna de Acciones. No se va a modificar hasta que exista un usuario final que valide si es necesario este paso.

EDITAR ACTA
- [x] No debe estar el botón de Verificar.
- [x] Al rechazar debe aparecer campo de diligenciamiento obligatorio, para que el usuario describa la razón del rechazo.
- [ ] Sólo dando clic sobre el acta de recibido, el sistema debe permitir consultarlo y en la misma vista debe permitir editar. No se va a modificar hasta que exista un usuario final que valide si es necesario este paso.
- [ ] En un solo formulario se puedan realizar todas las acciones (editar o modificar, verificar, aprobar o rechazar). Cuando se tenga un usuario final confirmado y que verifique todos los módulos, se realizará este ajuste (incluyendo salidas, baja de bien, etc.)

ENTRADAS
- [x] Cambiar icono de seleccionar entrada.
- [x] Al digitar el número del contrato debe verificar y sacar un aviso "El contrato no existe".
- [x] Desahibilitar botón "Registrar entrada", solo debe aparecer al final.

OTROS
- [ ] Validar con el equipo CORE el tema de autenticacion única debido a que nos saco del sistema, la sesión debería cerrarse por inactivación en el sistema, no por tiempo.

**Comment by Miavega** [comment]
Se cambia el ícono de entrada:
- Ícono anterior:
![imagen](https://user-images.githubusercontent.com/23342808/69001637-57e34580-08b0-11ea-8281-47c250023556.png)

-Ícono nuevo:
![imagen](https://user-images.githubusercontent.com/23342808/69001651-84975d00-08b0-11ea-9ded-01f52b83e712.png)

**Comment by Miavega** [comment]
Se verifica que el contrato no existe: 
![imagen](https://user-images.githubusercontent.com/23342808/69002023-5caaf800-08b6-11ea-9787-2d890f50eb5b.png)

**Comment by Miavega** [comment]
Se deshabilita boton de registro hasta que complete el formulario: 
![imagen](https://user-images.githubusercontent.com/23342808/69002287-5cacf700-08ba-11ea-90fc-f189af4e026c.png)
![imagen](https://user-images.githubusercontent.com/23342808/69002290-6a627c80-08ba-11ea-8ebc-3f83e01724b1.png)

**Comment by DianaPatriciaRamirez** [comment]
De acta de recibido quedaron pendientes las siguientes tareas, sin embargo, se retomaran cuando se tenga un usuario del proceso de Almacén e Inventarios que pueda validar estos procedimientos y con el fin de no hacer re-procesos en el desarrollo:

- [ ] Eliminar columna de Acciones. 
- [ ] Sólo dando clic sobre el acta de recibido, el sistema debe permitir consultarlo y en la misma vista debe permitir editar. 
- [ ]  En un solo formulario se puedan realizar todas las acciones (editar o modificar, verificar, aprobar o rechazar). 

Por otra parte, la siguiente tarea no depende del equipo de trabajo del proyecto Arka II por lo tanto no la debemos ajustar, sin embargo, se transfirió esta eventualidad al equipo CORE quienes indican que ese tema lo debe revisar el ingeniero Jhon Castellanos @corio27 ya que es un tema del WSO2:

* Validar con el equipo CORE el tema de autenticacion única debido a que nos saco del sistema, la sesión debería cerrarse por inactivación en el sistema, no por tiempo.
