### ISSUE TITLE
Generar API refactor de movimientos 

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#165]
Se debe generar el API en GO para gestionar el CRUD de movimientos_arka.

**Comment by Miavega** [comment]
Se crea el API CRUD [movimiento_arka_crud](https://github.com/udistrital/movimientos_arka_crud) con su entorno de desarrollo local

**Comment by mafeave** [comment]
De la revisión realizada al API, tener en cuenta lo siguiente:
- Ajustar readme de acuerdo a los lineamientos

**Comment by mafeave** [comment]
El ajuste se realizará en un issue nuevo, teniendo en cuenta los nuevos lineamientos para la definición del Readme.
