### ISSUE TITLE
(Tarea no planeada) Ajustar modelo y API de catálogo para asociar características

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#166]
Ajustar el modelo de datos y el API CRUD de catalogo_elementos_crud de acuerdo a las observaciones realizadas en el [Acta No. 15](https://docs.google.com/document/d/1BZZyzHc_K1C3jK4jPkYefUUfxmOGz8fML5yAKudA10Q/edit) (requiere valorización, depreciación, etc) a los grupos

**Comment by Miavega** [comment]
Se ajusta el modelo de datos:

![catalogo_elementos](https://user-images.githubusercontent.com/23342808/68551355-22cf8280-03da-11ea-8c25-4cb053a1513b.png)

Archivo PgModeler y SQL:

[catalogo_elementos.zip](https://github.com/udistrital/arka_cliente/files/3829086/catalogo_elementos.zip)

**Comment by Miavega** [comment]
Se ajusta el [API](https://github.com/udistrital/catalogo_elementos_crud/tree/dev) en los commits:
- [086f860](https://github.com/udistrital/catalogo_elementos_crud/commit/086f8606f8da548388715e5325abc2125896a630)
- [ffeac30](https://github.com/udistrital/catalogo_elementos_crud/commit/ffeac305f8ff2be4b2aceb54251cf0877a35937c)
- [3f721b8](https://github.com/udistrital/catalogo_elementos_crud/commit/3f721b8f4895f6df40434a23867bcc8a2a85997b)

**Comment by Miavega** [comment]
Se ajusta la transacción **_tr_grupo_** añadiendo el detalle_subgrupo:

![imagen](https://user-images.githubusercontent.com/23342808/68552278-3c28fc80-03e3-11ea-8587-939216aff39d.png)

Se ajusta en el commit:
- [3aac0ae](https://github.com/udistrital/catalogo_elementos_crud/commit/3aac0aeda8eff219bb759c6442f24b1eddddef11)

**Comment by mafeave** [comment]
Se verifica el ajuste sobre la transacción tr_grupo, para registrar las características que aplicarían a cada grupo del catálogo. 
Se da por finalizada la tarea.
