### ISSUE TITLE
Agregar opcion para consultar los soportes para entradas 

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#167]
Se debe permitir consultar los soportes registrados en NUXEO en la consulta de entradas.

**Comment by mafeave** [comment]
Se verifica la carga de archivos subidos al momento de registrar una entrada
![Captura de pantalla de 2019-11-27 18-32-51](https://user-images.githubusercontent.com/14035745/69766063-6b11d300-1144-11ea-8205-a70b9984c56d.png)

Se da por finalizada la tarea
