### ISSUE TITLE
Inactivar grupos y subgrupos de catalogo a nivel de Cliente

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#168]
Se debe permitir inactivar los grupos y subgrupos registrados en el catálogo de bienes de ARKA II.

**Comment by Miavega** [comment]
Se ajusta el API [catalogo_elementos_crud](https://github.com/udistrital/catalogo_elementos_crud/tree/dev) para que permita desactivar grupos y subgrupos. Los cambios se pueden observar en el commit: 
- [3fbeffe](https://github.com/udistrital/catalogo_elementos_crud/commit/3fbeffe454ca6557769b4a2b63326d1b428573d9)

**Comment by Miavega** [comment]
Se crea formulario que permite inactivar grupos:

![imagen](https://user-images.githubusercontent.com/23342808/68627143-0cddc280-04ab-11ea-90bf-ed81e3fe797c.png)

**Comment by Miavega** [comment]
Se crea funcionalidad para inactivar grupos:

![imagen](https://user-images.githubusercontent.com/23342808/68627173-2121bf80-04ab-11ea-95bf-e2e491125c03.png)

Confirmación de acción:
![imagen](https://user-images.githubusercontent.com/23342808/68627194-2f6fdb80-04ab-11ea-80e6-0d9ddd60ea97.png)

**Comment by Miavega** [comment]
Se agrega internacionalización:
![imagen](https://user-images.githubusercontent.com/23342808/68627258-59290280-04ab-11ea-982d-bfe721766807.png)

**Comment by mafeave** [comment]
Ajustar nombre de botón 'Inactivatar' 
![Captura de pantalla de 2019-11-27 18-27-15](https://user-images.githubusercontent.com/14035745/69765858-9811b600-1143-11ea-840c-28f585ee7c2d.png)

**Comment by mafeave** [comment]
Ajuste realizado y desplegado en ambiente de pruebas.
