### ISSUE TITLE
agregar caracteristicas catalogo de elementos

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#169]
- [x] Agregar Depreciacion

- [x] agregar valorizacion

- [x] agregar Tipo de Bien

- [x] asociar las cuentas contables y las caracteristicas a los grupos

**Comment by ManuelMurillo** [comment]
e922d837b758843c62e075d1e43763e42677de45

**Comment by mafeave** [comment]
Ajustar internacionalización de las características
![Captura de pantalla de 2019-11-27 18-45-47](https://user-images.githubusercontent.com/14035745/69766492-3ef75180-1146-11ea-994d-ac47230ee918.png)

Ajustar el formulario para que se cargue el tipo de bien en el componente de modificación del grupo.
