### ISSUE TITLE
Mockup: Vista General Registrar Entrada

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/arka_cliente#17]
La plataforma requiere poder adminitrar el registro de entradas, basados en la historia de usuario y el modelo de datos proponer uno mockups que cumplan con:

- [ ] Organizar y contener todos los campos del modelo de Datos

- [ ] Categorizar los campos por relación entre modulos dentro de la misma vista

- [ ] Que se pueda describir la historia de usuario en el mockup

Calidad

- [ ] Los mockups son referentes al requerimiento y a la historia de usuario

- [ ] Los mockups contienen y organizan todos los camos del modelo de datos

- [ ] Los mockups quedan documentandos en este issue y en el repo

**Comment by Soulfilip-UD** [comment]
Los siguientes Mockups capturan la disposición del menu y el formulario inicial para empezar a registrar una entrada.
![Screenshot from 2019-06-11 00-58-22](https://user-images.githubusercontent.com/50924615/59208478-1dc89600-8be4-11e9-90f2-66d34c6da25c.png)

**Comment by mafeave** [comment]
Revisado el mockup, se da por finalizada la tarea
