### ISSUE TITLE
Integrar modelo de datos de movimientos de Arka II y Kronos, en catálogo

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#173]
Se debe integrar el modulo de movimientos de kronos para la asignacion de cuentas contables

- [x] Agregar registros a tipos de movimiento en kronos

- [x] Consultar registros de movimientos asociados para arka en kronos

**Comment by ManuelMurillo** [comment]
para poder realizar la asignacion de cuentas se tuvo que revisar el procedimiento de forma global, registro de catalogo, grupos, subgrupos, consulta de los mismos y asignacion de cuentas, debido a un merge de las ramas creadas por @Miavega y @ManuelMurillo, lo cual alargo la tarea de 4 a 16 horas

**Comment by mafeave** [comment]
Se verifica la carga de los tipos de movimientos registrados en el API de movimientos_crud de Kronos en el formulario de asignación de cuentas.
Se da por finalizada la tarea.
