### ISSUE TITLE
Carga de información de las entradas con Json de movimientos - 8 horas

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#174]
Se debe ajustar el API MID y el cliente de Angular 7 para permitir consultar las entradas con su respectivo detalle.

**Comment by Miavega** [comment]
Se ajusta la consulta de adquisición: 
![imagen](https://user-images.githubusercontent.com/23342808/69485690-ec99f600-0e10-11ea-9c3c-e6b7be9d281a.png)

**Comment by Miavega** [comment]
Se ajusta la consulta de elaboración propia:
![imagen](https://user-images.githubusercontent.com/23342808/69485700-0afff180-0e11-11ea-9d30-b0bbb1a4ac0e.png)

**Comment by Miavega** [comment]
Se ajusta la consulta de donación:
![imagen](https://user-images.githubusercontent.com/23342808/69485706-1d7a2b00-0e11-11ea-8886-4cb04280cc40.png)

**Comment by Miavega** [comment]
Se ajusta la consulta de sobrante de inventario:
![imagen](https://user-images.githubusercontent.com/23342808/69485712-308cfb00-0e11-11ea-8e2e-2d51352fc482.png)

**Comment by Miavega** [comment]
Se ajusta la consulta de terceros:
![imagen](https://user-images.githubusercontent.com/23342808/69485722-574b3180-0e11-11ea-8504-c66c5cd885b4.png)

**Comment by mafeave** [comment]
Se agrega migrations de los estados de los movimientos y los formatos de registro por tipo de movimiento, ver: commit [889ae1be37430932bc786db610230799e3c85690](https://github.com/udistrital/movimientos_arka_crud/commit/889ae1be37430932bc786db610230799e3c85690), commit [fcfd0051e0c9221d4b602dcd9d2f81221e4db225](https://github.com/udistrital/movimientos_arka_crud/commit/fcfd0051e0c9221d4b602dcd9d2f81221e4db225)

Se hace despliegue del API de movimientos en el entorno de pruebas, ver kanban N° [33911](https://tuleap.udistrital.edu.co/plugins/tracker/?aid=33911)

Se verifica registro de una entrada por Adquisición, queda pendiente la verificación de los otros tipos de entrada, debido a que los servicios de JBPM no están cargando.
