### ISSUE TITLE
Crear transacción de salidas

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#181]
Se debe crear la transacción que permita registrar las salidas del sistema ARKA II.

**Comment by Miavega** [comment]
Se crea transacción en el API CRUD [movimientos_arka_crud](https://github.com/udistrital/movimientos_arka_crud/tree/dev) en el commit [6c1fe60](https://github.com/udistrital/movimientos_arka_crud/commit/6c1fe606f8fc20fc7b8af0dbbc96212a732b6af4)

**Comment by Miavega** [comment]
Se crea transacción en el MID API [arka_mid](https://github.com/udistrital/arka_mid/tree/dev) en el commit [933c20e](https://github.com/udistrital/arka_mid/commit/933c20e154d250c375254a4a09014c649c6cf44c)

**Comment by Miavega** [comment]
Para realizar el post se debe enviar un JSON de la siguiente manera:
![imagen](https://user-images.githubusercontent.com/23342808/69489903-7c5d9580-0e4d-11ea-81a4-b60beff76e0b.png)

**Comment by Miavega** [comment]
Se dejan las siguientes observaciones:
- Los estados tanto en entradas como en salidas están quemados en la transacción ya que no se han definido aún
- No se asocian soportes a la salida porque no se tiene claridad existen para este movimiento

**Comment by DianaPatriciaRamirez** [comment]
Tener en cuenta que las salidas deben estar aprobadas por el jefe de Almacén e Inventarios. Además, se aclara que no se tienen documentos físicos asociados a las salidas.
