### ISSUE TITLE
Registro de Salidas mostrar entradas aprobadas y elementos de salidas asociadas

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#185]
- [x] Elementos Asociados

- [x] Tabla de entradas aprobadas

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/arka_cliente/commit/f08d9f814e5c5669390ff330dc172c2794c8ad46

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial de este Issue
