### ISSUE TITLE
Asociar funcionario y ubicacion al registro unitario de salidas 

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#186]
- [x] Sede

- [x] Dependencia

- [x] Ubicacion

- [x] Funcionario Asociado/Tercero

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/arka_cliente/commit/f08d9f814e5c5669390ff330dc172c2794c8ad46

**Comment by DianaPatriciaRamirez** [comment]
La asignación debe realizarse a los funcionarios de planta, únicamente.

**Comment by AlexFBP** [comment]
Posiblemente lo mencionado arriba ya esté implementado, por lo que se abre #633 para validarlo, y con propósito de cerrar este Issue, de acuerdo al historial
