### ISSUE TITLE
Asociar funcionario y ubicacion al registro de varias salidas

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#187]
- [x] Tabla de Elementos

- [ ] Asociacion a funcionarios

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/arka_cliente/commit/7710aa9c75fb9922a4cafa165fb2abd434784e6e

**Comment by AlexFBP** [comment]
Commit mencionado ya fusionado en Develop.
Con lo anterior y, por otro lado, se procede a cerrar el Issue dado que no es muy claro el contexto o procedimiento para finalizar el segundo ítem
