### ISSUE TITLE
(TAREA NO PLANEADA)Ajuste general de componentes de catalogo por revision de lider tecnica 

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#188]
Debido a la revision efectuada por @mafeave en el módulo de catalogo, se generaron varias correcciones para verificar la funcionalidad completa del modulo.

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/arka_cliente/commit/f08d9f814e5c5669390ff330dc172c2794c8ad46

**Comment by AlexFBP** [comment]
Commit mencionado ya fusionado en develop. Se procede a cerrar el Issue
