### ISSUE TITLE
Mockup's del procedimiento de entrada 

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#19]
Crear el Mockup correspondiente al proceso de entrada (incluye los criterios de cada uno de los procedimientos de entradas: Ingreso bien tangible, Ingreso por reposición, Ingreso por elaboración propia y/o donación, Ingreso por sobrante de inventario e Ingresar el bien)

**Comment by Miavega** [comment]
En el siguiente [enlace](https://drive.google.com/drive/folders/125n8yG5JpnfySz5yN0PwLkvygEstjXn3) se encuentran las imagenes PNG de los mockups: 

- Adquisición
- Reposición
- Elaboración Propia
- Donación
- Sobrante

**Comment by mafeave** [comment]
Se da por finalizada la tarea.
