### ISSUE TITLE
 Alimentar API_financiera con las cuentas de catalogo de bienes

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#194]
Alimentar API_financiera con las cuentas de catalogo de bienes, ejemplos para el usuario 
(19-10-01-17, 16-35-04-21, 24-01-01-90 y 51-11-14-01) 

- [x] Sentencias SQL

- [x] Ajuste de datos para base desplegada

- [x] Ajuste del cliente y el mid para alimentar la aplicacion con los nuevos elementos

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/arka_cliente/commit/d7dc7356ca76cd973c5f4324db4fe7653a55b118

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
