### ISSUE TITLE
Ajustar consulta de la ubicación, sede y dependencia

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#195]
Ajustar consulta de la ubicación, sede y dependencia

- [x] Creacion de funcion en el MID para la consulta compuesta

- [x] Ajuste del cliente para consumir datos y realizar la consulta

- [x] Pruebas de funcionalidad del cambio del codigo

- [x] Carga de Informacion en OIKOS de espacio fisico vs dependencia

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/arka_cliente/commit/7710aa9c75fb9922a4cafa165fb2abd434784e6e

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
