### ISSUE TITLE
Iternacionalizacion de catalogo y revision de Idioma por defecto

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#196]
- [x] Lista de Catalogo

- [x] Construccion de catalogo

- [x] Registro de elementos

- [x] Inactivar Grupos y subgrupos

- [x] Asignacion de Cuentas

- [x] Revision de idioma por defeco

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial.

Teniendo en cuenta la [Diferencia entre Internacionalización (i18n) y Localización (L10n)](https://es.wikipedia.org/wiki/Internacionalizaci%C3%B3n_y_localizaci%C3%B3n), a futuro se requerirá en los PR que los desarrolladores dejen lista al menos la i18n y, de ser posible, se preferirá que ajusten la L10n a inglés, para evitar abrir PR(s) dedicado(s) a i18n/L10n
