### ISSUE TITLE
VALIDAR: Asignar funcionarios de planta al registro unitario de salidas

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#197]
Asignar funcionarios de planta (administrativos y docentes) al registro unitario de salidas

- [ ] Ajuste de las consultas para traer los datos de funcionarios de planta

**Edit:** Posiblemente esto ya esté implementado. Verificar primero si ya está implementado

**Comment by ManuelMurillo** [comment]
Al realizar la consulta pertinente, @mafeave indica que la unica base de datos que contiene la informacion de docentes de planta es SiCapital de la cual no se puede consultar informacion de forma directa, se debe pedir un endpoint para obtener la informacion pertinente.
De momento, se usaran los servicios de proveedores.

**Comment by DianaPatriciaRamirez** [comment]
El Sistema Arka II debe estar integrado con Agora (terceros). Mientras se logra esa integración, se sugiere generar un listado de los docentes de plantas y de los administrativos, solicitando información al sistema Nomina OAS, mediante correo al Centro de Servicios.
