### ISSUE TITLE
Definir modelo de datos para el registro del acta de recibido

### ISSUE THREAD

**Issue by mafeave** [udistrital/arka_cliente#2]
Se debe revisar el modelo de datos propuesto para el registro de la información correspondiente al acta de recibido, tener en cuenta el diseño que se encuentra en: https://tuleap.udistrital.edu.co/plugins/tracker/?aid=15213

**Comment by Miavega** [comment]
En el siguiente [Enlace](https://drive.google.com/drive/folders/11hi02uomnx8ELaiFiJCTXxgm_j9q2laI) se encuentra la imagen PNG y el fuente para el modelo de datos del acta de recibido, se dejan algunas consideraciones a tener en cuenta:

> Existen dos fechas, una de recibido y una de registro, se plantea dejar solo una que sería la fecha de registro que se obtendría automáticamente al momento de realizar el acta de recibido.

> El campo revisor puede que no sea necesario.

> En el formulario de registro de acta se solicita la _**sede, dependencia y ubicación**_, sin embargo en el modelo de datos solo se estipula un campo **_sede_** puesto que esta información se consume de Oikos. Se debe verificar que efectivamente esto se puede obtener con solo un campo, o se deben dejar los tres campos separados en el modelo de datos.

> Se añade un campo **_elemento_contrato_** con el fin de obtener los datos del ordenador de gasto, verificar si esto es posible o se debe traer de otro servicio

**Comment by mafeave** [comment]
Se tienen las siguientes observaciones sobre el modelo definido:
1. Cambiar nombre de documento_soporte_acta a soporte_acta
2. Cambiar campo enlace por documento de tipo integer, que referenciaría al microservicio de documentos del CORE
3. Revisar relación ente el acta, contrato (Argo) y contrato_elemento
4. El campo revisor si sería necesario, se referencia el id del ente del revisor

**Comment by mafeave** [comment]
Debido a dudas frente al proceso, se deja por terminada la tarea. En caso de requerirse ajustes al modelo se creará un nuevo issue en el proyecto
