### ISSUE TITLE
Modelo de datos del procedimiento de entrada

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#20]
Realizar el diseño del modelo de datos para el procedimiento de entrada

- [x] Revisar el modelo actual

- [x] Revisar el proceso para el procedimiento de baja de bienes

- [x] Generar un modelo en pg modeler con el nuevo modelo de datos

- [x] Generar imagen png con el nuevo modelo de datos

**Comment by Miavega** [comment]
Se realiza la revisión del modelo en el [issue](https://github.com/udistrital/arka_cliente/issues/18 ) en donde se realizó la unificación de los modelos, el cual puede ser visto en el siguiente [enlace](https://drive.google.com/drive/folders/1aBu01RLI379Hwej1HbVuCUUqlJsw_yH3)

**Comment by mafeave** [comment]
Se da por finalizada la tarea.
