### ISSUE TITLE
Ajustar Registro de elementos con asociacion de catalogo

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#202]
- [x] Agregar funcion en el API de Catalogo para la consulta de subgrupos por tipo

- [x] Aplicar un storage con Reducer para la consulta de los subgrupos por tipo de bien

- [x] Ajustar filtro en la cracion de elementos para la asignacion del subgrupo

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/arka_cliente/commit/7a37db56929c9dcb3ec88ce19b371fecae146efc
https://github.com/udistrital/arka_cliente/commit/df64ef8304d5d71aac4674a04494bc768c1d291c

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
