### ISSUE TITLE
 Ajustes de acuerdo a la revisión funcional del módulo catálogo de elementos, realizado por la analista de requerimientos

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#203]
https://github.com/udistrital/administrativa_cliente/issues/343

**Comment by ManuelMurillo** [comment]
Se actualiza el documento relacionado al issue de administrativa con los ajustes realizados

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/arka_cliente/commit/9ededf75b080ede818632f43cc9ad5cfdc663cc1

**Comment by AlexFBP** [comment]
El commit mencionado fue fusionado a Develop. Se procede a cerrar este Issue
