### ISSUE TITLE
Reporte nueva versión

### ISSUE THREAD

**Issue by anndresfelipe29** [udistrital/arka_cliente#210]
Se adjunta imagen del nuevo formato de reporte

![image](https://user-images.githubusercontent.com/30865375/70858510-41d99c80-1ed1-11ea-8255-cfe4144cf0f0.png)

Cambios principales:
- Se optimiza el espacio de la tabla de elementos.
- Se agrega un número de cuenta por elemento, el correspondiente al de la cuenta débito del subgrupo asociado.
- Para los tipos de entrada que no usan contrato en el formato indicará que no aplica el mismo

Se dejan las siguientes observaciones:
- Falta agregar al responsable de la entrada
- Falta actualizar la información del encabezado de la tabla

**Comment by anndresfelipe29** [comment]
Dudas:
Respecto a las cuentas asociadas, con los datos de prueba se encuentra que en algunos casos el subgrupo no presenta una cuenta asociada por tanto para esos casos no se muestra el elemento ¿En un caso real que debería pasar?

**Comment by anndresfelipe29** [comment]
Se adjunta imagen con el nuevo reporte en la página de pruebas de Arka

![image](https://user-images.githubusercontent.com/30865375/70858608-148dee00-1ed3-11ea-9d91-0f70eddf47fd.png)

**Comment by DianaPatriciaRamirez** [comment]
En revisión del 16 de diciembre, surgen las siguientes observaciones:

- [ ] Se debe relacionar la cuenta crédito y el valor.
- [ ] Dejar la columna de "Cuenta" de primeras.
- [ ] Unir en una misma celda los datos de elemento, marca y serie.
- [ ] Cambiar nombre de columna "Total" por "Valor débito".
- [ ] Mostrar los elementos por subgrupos.

**Comment by anndresfelipe29** [comment]
![image](https://user-images.githubusercontent.com/30865375/71289296-d1040b80-233a-11ea-966a-6a3066d990ca.png)
Se adjunta imagen del nuevo reporte con las observaciones efectuadas

**Comment by DianaPatriciaRamirez** [comment]
Revisar: Total entradas + Total IVA

**Comment by anndresfelipe29** [comment]
Se hacen todos los cambios excepto el nombre del usuario que genero el reporte y se aclara que el error en la suma de los valores subtotal e IVA es debido a incongruencias en los datos :
![image](https://user-images.githubusercontent.com/30865375/71382416-c26d5c80-25a5-11ea-88f1-89fd07f7804d.png)
![image](https://user-images.githubusercontent.com/30865375/71382717-204e7400-25a7-11ea-8492-f8258a6dde11.png)

**Comment by mafeave** [comment]
Se verifica la generación de los reportes de entradas.
![Captura de pantalla de 2020-01-16 12-47-01](https://user-images.githubusercontent.com/14035745/72549270-602f1100-385e-11ea-9c85-7b0291328f7d.png)

Observaciones:
- Se carga el número del contrato relacionado, pero la fecha y los datos del proveedor no corresponden
- Tener en cuenta que si un subgrupo padre no tiene las cuentas contables asociadas para el movimiento, no se genera el reporte de forma correcta, por lo cual, desde el cliente se debe restringir la asociación de subgrupos que no tengan cuentas contables asociadas en el registro del acta de recibido.
