### ISSUE TITLE
Mockup de Salidas

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#211]
Propuesta para mejorar la usabilidad del modulo de salidas

**Comment by ManuelMurillo** [comment]
En la siguiente imagen se muestra la propuesta que reduce el area de trabajo para el usuario y la cantidad de componentes para mejorar la interaccion del usuario con la aplicacion

![image](https://user-images.githubusercontent.com/29108085/70916981-89a01700-1fea-11ea-81ad-fa9a7f0ada0a.png)

**Comment by mafeave** [comment]
Se revisa mockup con el equipo de trabajo y se aprueba su implementación para el desarrollo del módulo de salidas.

Se da por finalizada la tarea.
