### ISSUE TITLE
Realizar ajustes prueba de seguridad hito 1

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#212]
Se deben realizar los ajustes solicitados para el Hito 1

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/arka_cliente/commit/b369562b2fa670ec9e551de04d072b44582f5e0a

https://github.com/udistrital/arka_cliente/commit/3d58d1d6f77c5d78402d45976198fe9f391b7ccd

https://github.com/udistrital/arka_cliente/commit/f55c689b2758aa9512d0bf6bfb23823462bd839f

**Comment by AlexFBP** [comment]
Los commit mencionados ya fueron fusionados a Develop. Se procede a cerrar este Issue
