### ISSUE TITLE
Ajuste entrada por reposición

### ISSUE THREAD

**Issue by anndresfelipe29** [udistrital/arka_cliente#213]
Se agrega una lista con las placas de los elementos a la entrada reposición

**Comment by DianaPatriciaRamirez** [comment]
En revisión del 16 de diciembre falta:

- [ ] Relacionar el encargado de la placa.

- [ ] Probar el registro.

**Comment by anndresfelipe29** [comment]
2d909ba Funcion de consulta de encargado

**Comment by anndresfelipe29** [comment]
https://github.com/udistrital/arka_mid/commit/2d909bac37cea00c439b1d7c0e009838c29e1268 Se crea función en arka_mid para la búsqueda del encargado

**Comment by AlexFBP** [comment]
Se cierra este Issue de acuerdo al histórico
