### ISSUE TITLE
Ajustar Registro de elementos con asociacion de catalogo para registro masivo

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#214]
Se debe ajustar la aplicacion MID para asociar el tipo de bien y los subgrupos de catalogo en el registro masivo de elementos

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/catalogo_elementos_crud/commit/9838f1676674126998f191eca71935aa021ad25b

https://github.com/udistrital/arka_mid/commit/6f9dfe94344ce8474106b33fc4dc7cdf6760e197

**Comment by AlexFBP** [comment]
Se observa que los commit mencionados están ya fusionados en la rama develop de cada repo. Se procede a cerrar este Issue
