### ISSUE TITLE
Ajustar Edicion de elementos con asociacion de catalogo en registro masivo 

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#215]
Se debe asociar el la edicion de elementos el catalogo en el registro masivo de elementos

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/arka_mid/commit/6f9dfe94344ce8474106b33fc4dc7cdf6760e197

https://github.com/udistrital/catalogo_elementos_crud/commit/9838f1676674126998f191eca71935aa021ad25b

**Comment by AlexFBP** [comment]
Se observa que los commit anteriores ya están fusionados en las ramas develop correspondientes. se procede a cerrar este Issue
