### ISSUE TITLE
Realizar Consulta de salidas en el MID

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#222]
Se debe crear la transaccion para la consulta de Salidas en el MID

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/movimientos_arka_crud/commit/ae76fe003e2e76253d5fe847136298f26cd8efbb

https://github.com/udistrital/movimientos_arka_crud/commit/532c1b0975726fd09be2263b46fb36345ac277a5

**Comment by AlexFBP** [comment]
Los commit mencionados hacen parte del histórico de la rama master de movimientos_arka_crud. Se procede a cerrar este Issue
