### ISSUE TITLE
Realizar Salida de elementos desde el Cliente

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#223]
Se debe realizar la salida de elementos desde el cliente Teniendo en cuenta los ajustes de las apis

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/arka_cliente/commit/3796d8185fa4f2405d667a154a092b0cc6e262d5
https://github.com/udistrital/arka_cliente/commit/3d5aa9578a7b6ae90f542d73f7f17f33103e91a3

**Comment by ManuelMurillo** [comment]
debido a un ajuste no previsto para la creacion del objeto necesario para realizar la transaccion, la tarea requiere de 4 horas mas para poder ser terminada

**Comment by mafeave** [comment]
Se verifica asignación de elementos en formulario de registro de salidas
![image](https://user-images.githubusercontent.com/14035745/71884084-a02b2100-3105-11ea-9245-ebb7cae8b22d.png)

Una vez que son asignados todos los elementos de la entrada, se habilita el botón de 'ASIGNAR'
Se verifica que al volver a seleccionar alguno de los elementos ya preasignados, se puede hacer una reasignación del elemento

Se realizan las salidas y se verifican desde el formulario de consulta:
![Captura de pantalla de 2020-01-07 04-31-23](https://user-images.githubusercontent.com/14035745/71884573-9bb33800-3106-11ea-93e1-74a645edd646.png)
