### ISSUE TITLE
Consulta de Salidas Cliente

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#227]
Se debe consultar la salida de elementos desde el cliente

- [x] Tabla de Consulta

- [x] Vista Especifica

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/arka_cliente/commit/969d640218a6c04e2d113b1ac59fb60444b2bd31

**Comment by ManuelMurillo** [comment]
Es necesario ajustar la tabla para mostrar los funcionarios y las ubicaciones

**Comment by mafeave** [comment]
Se verifican los formularios de consulta de las salidas:

- Consulta general
![Captura de pantalla de 2020-01-07 03-45-14](https://user-images.githubusercontent.com/14035745/71881375-27759600-3100-11ea-8562-bf6fb5c06206.png)

- Consulta específica
![Captura de pantalla de 2020-01-07 03-49-31](https://user-images.githubusercontent.com/14035745/71881687-c13d4300-3100-11ea-9008-72d1e12f9c58.png)

Observaciones: 
- cambiar título de Registrar Salida por Consultar Salida
- no está cargando el id de la entrada en la consulta general de salidas
- revisar que cuando se hace click en el botón de 'VOLVER', se está repitiendo varias veces los registros de salidas:
![Captura de pantalla de 2020-01-07 03-51-03](https://user-images.githubusercontent.com/14035745/71881761-f5186880-3100-11ea-8a29-4bfc542d40ba.png)

Pendiente actualización de swagger en WSO2 del API de movimientos_arka, para poder ver el despliegue en el ambiente de pruebas

**Comment by ManuelMurillo** [comment]
ajustes solicitados realizados

**Comment by mafeave** [comment]
Se verifican los ajustes, sin embargo, se encuentra la siguiente observacion:
en la tabla que aparece en el formulario de Registrar Salida, se están repitiendo registros
![Captura de pantalla de 2020-01-12 08-53-32](https://user-images.githubusercontent.com/14035745/72225792-759ef500-3557-11ea-9ae5-e75ff160d02a.png)

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial. Se abre #634 para abordar [lo encontrado](#issuecomment-573458444)
