### ISSUE TITLE
Desarrollo de tabla con asociacion de elementos Bodega de consumo

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#228]
se debe generar una tabla para la la solicitud de elementos de la bodega de consumo, de acuerdo a la historia de usuario HU 17 y HU 18

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/arka_cliente/commit/4a621ce0f5e842909ae9cb0c8d2b65e71cbb98d8
https://github.com/udistrital/arka_cliente/commit/5da32e5b218086b29ca7726332213f6c1dd7cb3b

**Comment by ManuelMurillo** [comment]
Es necesario ajustar la tabla de elementos para que coincidan con los campos propuestos en la historia de usuario

**Comment by mafeave** [comment]
Se verifica tabla que lista los elementos de consumo:
![Captura de pantalla de 2020-01-07 04-52-07](https://user-images.githubusercontent.com/14035745/71886154-b33ff000-3109-11ea-9c6a-54d72ceeaca5.png)

**Comment by AlexFBP** [comment]
Se cierra este Issue de acuerdo al histórico
