### ISSUE TITLE
Mockup's Procedimiento de salida

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#23]
Realizar los mockups para la gestion de salidas donde se debe revisar:

- [x] Realizar la vista del registro

- [x] Posibles componentes o vistas adicionales al registro

- [x] Comparar los campos del formulario con el modelo de datos de la gestion de salidas

**Comment by ManuelMurillo** [comment]
en el siguientes commits se realiza la configuracion del modulo de salidas y la vista del registro

https://github.com/udistrital/arka_cliente/commit/9b8250a4774b5643fbdc6e32284af3ec80a4bdcc

https://github.com/udistrital/arka_cliente/commit/783b95a7a630c7721174818157dd9f562b997f49

**Comment by mafeave** [comment]
Agregar la imagen final del mockup.

Se debe tener en cuenta que para que se pueda dar salida a los elementos, estos debe quedar desagregados desde el registro del acta de recibido.

**Comment by ManuelMurillo** [comment]
![Mockup Salidas](https://user-images.githubusercontent.com/29108085/60111796-3bdddc80-9734-11e9-9b1b-c2a7c2176017.png)

En la primera imagen se muestra la tabla asociada a la entrada con elementos ya desagregados en los cuales se puede asignar individualmente o por grupo los elementos de la lista 

![Mockup Salidas 2](https://user-images.githubusercontent.com/29108085/60111795-3bdddc80-9734-11e9-87e7-70642f8d3d8e.png)

En la segunda imagen se encuentran los modelos en los cuales se observara la asignacion a los elementos seleccionados, ya sea uno solo o varios elementos

**Comment by ManuelMurillo** [comment]
Agregar Modificaciones:

- [ ] Tabla que muestre los elementos ya asignados a funcionarios 

- [ ] Ocultar los elementos seleccionados ya asignados de la tabla inicial

- [ ] Agregar seleccion de todos los elementos

- [ ] Identificacion del funcionario

- [ ] Lista de Consulta

**Comment by ManuelMurillo** [comment]
se relacionan a continuacion los elementos que faltan para el mockup de salidas
Consulta:
![Consulta_Salidas_v2](https://user-images.githubusercontent.com/29108085/61494077-d7045380-a97a-11e9-83f5-a0de9888e723.png)

Registro
![Registro_Salidas_v2](https://user-images.githubusercontent.com/29108085/61494085-dbc90780-a97a-11e9-9345-5a2fdcdb97e2.png)
![Registro_Salidas_2_v2](https://user-images.githubusercontent.com/29108085/61494086-dcfa3480-a97a-11e9-95b7-052966c03062.png)
![Registro_Salidas_3_v2](https://user-images.githubusercontent.com/29108085/61494090-de2b6180-a97a-11e9-9cdb-4d965b17c0a8.png)

**Comment by mafeave** [comment]
Mockups aprobados y verificados junto al usuario final.
