### ISSUE TITLE
Agregar Registro Solicitud Bodega Consumo a API Elementos

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#230]
Se necesita realizar el registro del formato de solicitud de elementos de bodega de consumo

**Comment by ManuelMurillo** [comment]
en el siguiente commit se encuentra la tabla agregada a los migrates con el siguiente formato
```
{ 
    "Elementos": [ 
        { 
            "Funcionario": "number",
            "Ubicacion": "number", 
            "ElementoActa": "number",
            "Cantidad": "number" 
        }
    ] 
}
```
donde se guarda la informacion del funcionario, la ubicacion donde se solicita el bien, el elememto asociado y la cantidad solicitada

https://github.com/udistrital/movimientos_arka_crud/commit/4e09e519ff92fe5595c6f0a5156c86f736749b3b

**Comment by mafeave** [comment]
Se hace despliegue del ajuste y se verifica realización de la migración de los nuevos formatos de movimientos.

Se da por finalizada la tarea.
