### ISSUE TITLE
Desarrollar Formulario Solicitud Elementos Bodega Consumo

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#231]
Se debe desarrollar el formulario de solicitud de elementos de la bodega de consumo teniendo en cuenta la HU 17 y HU 18 del la solicitud de elementos

- [x] Tabla de elementos a Solicitar

- [x] Componente Formulario con Cantidad, Funcionario y Ubicacion

- [x] Tabla que muestra los elementos asignados con la informacion requerida

- [x] Interoperabilidad de los componentes

**Comment by mafeave** [comment]
Se verifica desarrollo de formulario para hacer solicitudes de elementos de la bodega de consumo a Almacen
![image](https://user-images.githubusercontent.com/14035745/71887172-8e4c7c80-310b-11ea-866f-87161cc3280e.png)

**Comment by mafeave** [comment]
Se da por finalizada la tarea.
