### ISSUE TITLE
Registrar Solicitud de Elementos Bodega de Consumo

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#239]
Se debe crear el registro de solicitud de elementos de bodega de consumo

- [x] Modificacion de formato de solicitud en API

- [x] Ajuste registro salidas de consumo en Cliente y API

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/arka_cliente/commit/00cfd3df22b94388f6af225ad554a0cf8689db27

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/arka_cliente/commit/f1bb69822f5f08408cba749d84020eb91cfcd071

**Comment by mafeave** [comment]
Se verifica registro de la solicitud a la Bodega de consumo, registrando un nuevo movimiento y asignando como funcionario solicitante al que se encuentra logueado en el sistema.

Pendiente: recargar la página o redireccionar al listado de solicitudes para que el usuario no tenga la opción de enviar varias veces la solicitud.

**Comment by mafeave** [comment]
Se verifica redirección al listado de solicitudes.
![Captura de pantalla de 2020-01-25 23-41-52](https://user-images.githubusercontent.com/14035745/73130752-529b2900-3fcc-11ea-9320-e227cced6cb1.png)
