### ISSUE TITLE
Ajustar formato de Solicitud para tomar el usuario que esta logueado

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#240]
Se debe registrar en la informacion de solicitud de elementos de bodega de consumo el usuario que este usando el sistema

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/arka_cliente/commit/b1bbf0cd40d750c620003c62333ded0d1f9066b3

**Comment by mafeave** [comment]
Se verifica el registro de la solicitud a la Bodega de consumo, teniendo en cuenta que en el detalle del movimiento queda el id del funcionario solicitante (tercero) que se encuentra logueado en el sistema:
![Captura de pantalla de 2020-01-12 19-08-27](https://user-images.githubusercontent.com/14035745/72227836-003f1e80-356f-11ea-9548-a37331142993.png)

Se da por finalizada la tarea. asignando como
