### ISSUE TITLE
Ajustar Registro de Salida para agregar elementos de consumo

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#241]
Se debe ajustar la salida para registrar la salida de los elementos de consumo de forma automatica

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/arka_cliente/commit/6b3873ec5a6bfe247966cf983d1af903bd173729

**Comment by mafeave** [comment]
Se verifica registro automático de los elementos de consumo, se hace despliegue y ejemplo para probar funcionalidad:
![Captura de pantalla de 2020-01-12 19-12-07](https://user-images.githubusercontent.com/14035745/72227892-79d70c80-356f-11ea-9a5f-25350d5e3ad3.png)

Revisar que cuando se hace la consulta del detalle de la salida, solo se muestra el consecutivo y la fecha

**Comment by mafeave** [comment]
Se verifica ajuste para consultar el detalle de una salida de elementos de consumo.
![Captura de pantalla de 2020-01-19 20-04-36](https://user-images.githubusercontent.com/14035745/72691981-612e9f80-3af7-11ea-9210-2988e3ea5831.png)

Se da por finalizada la tarea.
