### ISSUE TITLE
Funcion MID para consultar elementos de consumo 

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#242]
se debe crear una funcion para consultar los elementos de consumo necesarios para realizar la solicitud a la bodega de consumo

**Comment by ManuelMurillo** [comment]
Debido a los ajustes de los issues #241 y #239 no fue necesario hacer una funcion, solo realizar los siguientes ajustes:

https://github.com/udistrital/movimientos_arka_crud/commit/4e09e519ff92fe5595c6f0a5156c86f736749b3b

https://github.com/udistrital/movimientos_arka_crud/commit/25ea050494e3069733c36c6874ff9131fd14b9d9

https://github.com/udistrital/arka_cliente/commit/586aca5c19965d4dc83ad0c04b99e91371398ffd

**Comment by mafeave** [comment]
Revisados los ajustes, se da por finalizada la tarea.
