### ISSUE TITLE
Lista de las solicitudes de elementos de bodega de consumo

### ISSUE THREAD

**Issue by anndresfelipe29** [udistrital/arka_cliente#243]
Tabla creada para listar solicitudes a bodega de consumo: 
![image](https://user-images.githubusercontent.com/30865375/72228182-80b34e80-3572-11ea-8b11-279dd3aa9f55.png)

Observaciones:
- No se agregan los elementos de la solicitud en esta tabla, porque, en consecuencia la tabla se demoraría mucho en cargar y seria visualmente confusa
- Se sugiere agregar cargo del solicitante y dependencia a la cual pertenece o su ubicación

**Comment by mafeave** [comment]
Se verifica el listado de las solicitudes a la bodega de consumo:
![Captura de pantalla de 2020-01-17 07-56-44](https://user-images.githubusercontent.com/14035745/72613976-0af70c00-38ff-11ea-8e22-d8daef87d9a0.png)

Se da por finalizada la tarea.
