### ISSUE TITLE
Solicitud de elementos de bodega de consumo (Consulta Específica)

### ISSUE THREAD

**Issue by anndresfelipe29** [udistrital/arka_cliente#245]
![image](https://user-images.githubusercontent.com/30865375/72228320-a0974200-3573-11ea-806b-23db8cab83d8.png)

Observaciones:
- Para llenar esta tabla se requiere traer datos de:
1. Movimientos para traer la solicitud especifica (acá se encuentran los Id de los elementos solicitados)
2. Elementos, en el esquema de movimientos, para ver los elementos solicitados.
3. Elementos acta, en el esquema de movimientos para la información general del elemento .

**Comment by anndresfelipe29** [comment]
Se crea rama con la consulta desde mid
https://github.com/udistrital/arka_mid/commit/5ca10b91086db70f92ad37c04125db888f6ccb60

**Comment by mafeave** [comment]
Se despliegan los commits del cliente y del mid y se verifica la funcionalidad:
![Captura de pantalla de 2020-01-17 08-00-19](https://user-images.githubusercontent.com/14035745/72614180-9b355100-38ff-11ea-9521-56748ad0307e.png)

Se da por finalizada la tarea.
