### ISSUE TITLE
Desarrollo Apertura de Kardex

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#255]
Desarrollar la apertura de kardex usando la historia de usuario HU 19 Kardex - Bodega de bienes de consumo V3 https://docs.google.com/spreadsheets/d/1X4BFq2OsDuytWJV-RMLMfYN6z0Z20IIXKpp2jO2DipQ/edit#gid=852078008 - 16 horas

**Comment by ManuelMurillo** [comment]
Se han generado los componentes necesarios para seguir el proceso de apertura de kardex teniendo en cuenta el flujo propuesto:
![image](https://user-images.githubusercontent.com/29108085/72744849-5a963b80-3b7c-11ea-927f-ae9cc7186d98.png)

**Comment by mafeave** [comment]
Se verifica el formulario para realizar la entrada al Kardex
![Captura de pantalla de 2020-01-25 23-27-25](https://user-images.githubusercontent.com/14035745/73130664-d7854300-3fca-11ea-9718-8c1681a0654f.png)

**Comment by mafeave** [comment]
Modificar mensaje que se muestra en la tabla en caso de no haber elementos disponibles para realizar la apertura del Kardex
![Captura de pantalla de 2020-01-25 13-38-36](https://user-images.githubusercontent.com/14035745/73179867-37224200-40e2-11ea-83f5-7c3f85955c0e.png)

**Comment by ManuelMurillo** [comment]
![image](https://user-images.githubusercontent.com/29108085/73193947-61cbc500-40f9-11ea-9d34-d93ddb826f84.png)
 ajuste de flujograma
