### ISSUE TITLE
Ajustar API Movimientos para relacionar Elementos

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#256]
Se debe ajustar API de movimientos para relacionar el elemento general del catálogo al movimiento del Kardex

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/movimientos_arka_crud/commit/98f5f503d8bea89ca8e14e5ee2d8c66891786c7c
https://github.com/udistrital/movimientos_arka_crud/commit/213abcdcaafa73c8d350d84e7f82edb0197074df
https://github.com/udistrital/movimientos_arka_crud/commit/7e94f5a162e51f5ea628b84c8927f814d21fa1d9

**Comment by mafeave** [comment]
Pendiente migración por problemas de acceso a la base de datos: "_**Could not show columns of migrations table: pq: remaining connection slots are reserved for non-replication superuser and rds_superuser connections**_"

**Comment by ManuelMurillo** [comment]
el migrations se ejecuto de forma satisfactoria
