### ISSUE TITLE
Ajuste Componente Kardex

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#259]
Se necesita ajustar el componente de kardex para la visualizacion de datos para:

- [x] Registro Apertura

- [x] Consulta Especifica

- [x] Registro Entrada

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/arka_cliente/commit/bf5852a7d1f99bd35725c6ab3a552e2be702fa0f

**Comment by mafeave** [comment]
Se verifica consulta de Kardex de un elemento
![Captura de pantalla de 2020-01-25 23-37-44](https://user-images.githubusercontent.com/14035745/73182151-836f8100-40e6-11ea-81f3-b09929649137.png)
