### ISSUE TITLE
Consulta Especifica de Kardex de elementos

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#260]
se debe ajustar la consulta especifica de kardex de elementos de consumo con el componente de kardex

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/arka_cliente/commit/7d91a868ce36383c956cae248858ef0156082938

**Comment by mafeave** [comment]
Se verifica consulta de Kardex de un elemento
![Captura de pantalla de 2020-01-25 23-37-44](https://user-images.githubusercontent.com/14035745/73182151-836f8100-40e6-11ea-81f3-b09929649137.png)
