### ISSUE TITLE
Registrar Entrada de Elementos Bodega de Consumo

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#261]
Se debe realizar el registro de elementos al kardex

**Comment by mafeave** [comment]
Se verifica funcionalidad a través del issue: https://github.com/udistrital/arka_cliente/issues/255

**Comment by mafeave** [comment]
Falta ajustar los saldos para que indique el saldo de la entrada

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/arka_cliente/commit/19a256dc13e9b01957be0e9e8b01f7e168487534
Se ajustan los saldos 

![image](https://user-images.githubusercontent.com/29108085/73199558-0bfc1a80-4103-11ea-8847-4f9fc9fa5b8c.png)
