### ISSUE TITLE
Dar respuesta a las solicitudes de Bodega de Consumo

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#265]
Se debe dar respuesta a las solicitudes de elementos a las bodegas de consumo teniendo en cuenta la afectacion al kardex de elementos

- [x] Generar Estados de solicitud

- [x] Creacion de componente

- [x] Registro de movimientos en el kardex

**Comment by ManuelMurillo** [comment]
Movimientos CRUD:
https://github.com/udistrital/movimientos_arka_crud/commit/3ad9cba5fcca2d18b0ac2b5abf0c65a763630cf6
https://github.com/udistrital/movimientos_arka_crud/commit/7c52f1aa2638e1acde3609495820ed54c3a88c4b

Cliente:
https://github.com/udistrital/arka_cliente/commit/fb38463fe570fe84d45535598dc7a791f7ca5544
https://github.com/udistrital/arka_cliente/commit/0043d1e77b172a602c0fcee6c206ccb3605d567a

**Comment by mafeave** [comment]
Dado que el formulario de registro de la baja no está terminado, no se ha verificado el funcionamiento de dar respuesta a una solicitud de baja.
