### ISSUE TITLE
Revisar uso de API Oikos para usar la version 2

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#266]
Se debe revisar y ajustar los escenarios donde se use la aplicacion de oikos para realizar la actualizacion a la version 2:

- [x] Cliente

- [x] MID

**Comment by ManuelMurillo** [comment]
Se reviso el enviroment para ajustar las consultas y los campos de Codigo Abreviacion y TipoEspacioFidicoId que cambian con la version 2 de Oikos

Cliente:
https://github.com/udistrital/arka_cliente/commit/646ddfe3f89798ca61b96c946331a1f1b3b5f67d

**Comment by ManuelMurillo** [comment]
Para el MID fue necesaria una depuracion de los helpers que usaban la version 1 de Oikos de forma similar con el cliente

MID:
https://github.com/udistrital/arka_mid/commit/adc57d1989adfb692910a83c0dd66946dc5b42b4

**Comment by mafeave** [comment]
Se verifica ajuste para consumir el API de OIKOS v2
