### ISSUE TITLE
Ajuste Acta de recibido

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#267]
se deben realizar los siguientes ajustes:

- [x] falta agregar enlace del archivo base - plantilla para carga masiva

- [x] ocultar botón de “DESCARTAR ARCHIVO”

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/arka_cliente/commit/36b9ccf7d3146ca3728dcc003d6719f27ab056a8

**Comment by mafeave** [comment]
Se verifica ajuste para poder descargar la plantilla para cargue masivo en el cliente:

![imagen](https://user-images.githubusercontent.com/14035745/93344344-2e0fed80-f7f7-11ea-82d5-4f97c58da8d7.png)
