### ISSUE TITLE
Filtrar Informacion de subgrupos con cuentas ya asignadas

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#268]
Se debe filtrar información en carga de subgrupos para que busque solo aquellos que tienen cuentas contables relacionadas en el acta de recibido

**Comment by ManuelMurillo** [comment]
Esta tarea se debe realizar en el MID, debido a que de ahi se trae toda la informacion de los subgrupos
MID: 
https://github.com/udistrital/arka_mid/commit/80a4b79aab8c9628f6ddf56f36e76b7813f4ce03

**Comment by mafeave** [comment]
Revisar con el equipo de trabajo:

Se consulta el subgrupo _**Instrumentos de grupo**_ que pertenece al grupo _**Instrumentos Musicales, Juegos, Juguetes, Artes, Artesanías y Equipo educativo, Materiales, Accesorios y Suministros**_, el cual no tiene cuentas contables asociadas.
![imagen](https://user-images.githubusercontent.com/14035745/93901927-a45f9480-fcbc-11ea-9da6-dd4e9078ad15.png)

![imagen](https://user-images.githubusercontent.com/14035745/93901009-b260e580-fcbb-11ea-8fe0-c4d587872fe3.png)

Al hacer el registro de los elementos el subgrupo no debería listarse
![imagen](https://user-images.githubusercontent.com/14035745/93901775-7e39f480-fcbc-11ea-8c9a-bf6177bfc37a.png)

Los ajustes se realizarán en un issue nuevo.
