### ISSUE TITLE
Ajuste Verificacion Acta de Recibido

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#269]
Se debe ajustar la tabla para debido a que hay problemas con el check de verificacion

**Comment by ManuelMurillo** [comment]
Se procede a cambiar el componente de tabla para la verificacion de los elementos

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/arka_cliente/commit/62eb3c5a349f25d1a14a65a5cacd8f93d39d3bad
https://github.com/udistrital/arka_cliente/commit/646ddfe3f89798ca61b96c946331a1f1b3b5f67d

**Comment by mafeave** [comment]
Se valida el check para la verificación de 1 o de todos los elementos de 1 acta de recibido
![imagen](https://user-images.githubusercontent.com/14035745/93899638-1edae500-fcba-11ea-966b-0dde8dbbacdf.png)
