### ISSUE TITLE
Generar Solicitud de Baja de Elementos

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#271]
Se debe generar el componente de solicitud de bajas en el cliente y las funcionalidades en las APIs correspondientes.

- [x] Componente de Solicitud

- [ ] Funciones MID

- [ ] Consultas y registros en API Movimientos

**Comment by mafeave** [comment]
El filtro de terceros lista múltiples veces el nombre del funcionario:
![imagen](https://user-images.githubusercontent.com/14035745/93904092-133ded00-fcbf-11ea-921c-e139f0cc2570.png)

Revisar carga de elementos con la placa.
