### ISSUE TITLE
Consulta General de Solicituedes de Baja

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#272]
se debe generar las consultas de todas las solicitudes de bajas realizadas

**Comment by mafeave** [comment]
Cuando no hay registros de bajas, se está retornando null y no un json vacio, por lo cual el API da una respuesta errónea.
![imagen](https://user-images.githubusercontent.com/14035745/93809118-83426980-fc12-11ea-9a5e-8e1284158cca.png)
