### ISSUE TITLE
Ajustes Mockup's entradas

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#28]
Ajustar los Mockup's de entradas de acuerdo a las observaciones realizadas.

**Comment by Miavega** [comment]
En el siguiente [enlace](https://drive.google.com/drive/folders/1P3-3Kve267-ZPRnV35IH9AUwIrss6c1S) se encuentran las imagenes PNG con los ajustes realizados a los modelos de entradas. A tener en cuenta, cuando se pide un detalle en las consultas de entradas, el formulario que se mostrará es el mismo de la solicitud, solo que con los campos deshabilitados, por ende no se generó un nuevo componente para este, se reutilizará el mismo.

**Comment by mafeave** [comment]
Se verifican los ajustes solicitados en revisión del 12 de julio de 2019 y de las observaciones dadas por el usuario final en el acta Nº 11
