### ISSUE TITLE
Revisión de tareas pendientes en el tablero github del proyecto ARKA

### ISSUE THREAD

**Issue by mafeave** [udistrital/arka_cliente#286]
Se deben revisar los issues que se encuentran abiertos en el tablero github del proyecto ARKA

**Comment by mafeave** [comment]
Se solicita suscripción del cliente de ARKA al API de documentos_crud, tener presente que el API de documentos_crud está apuntando a Planestic.
Se revisan permisos sobre los esquemas movimientos_arka y acta_recibido en la base de datos de udistrital_administrativa con DBAs

**Comment by AlexFBP** [comment]
Pregunta @corio27 : Se pueden cerrar #348 y #349 ?
Pregunta @CristianDavidSanchez : Se puede cerrar el #292 ?

**Comment by AlexFBP** [comment]
Las tareas que parecen abandonadas y/o sin actividad se movieron a #670

**Comment by AlexFBP** [comment]
Quedaron [en el tablero](https://github.com/orgs/udistrital/projects/3) solamente las tarjetas asociadas.
"La labor inversa", siguiente, de limpiar los Issues de los repositorios de Arka (MID, Cliente y CRUDs) se realizará en otro Issue.
Se da por concluído este Issue tal como fue planeado
