### ISSUE TITLE
Ajustes Modelo de datos entradas

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#29]
Ajustar el modelo de datos de entradas de acuerdo a las observaciones realizadas. Añadir archivon PgModeler e imagen PNG.

**Comment by Miavega** [comment]
En el siguiente [enlace](https://drive.google.com/drive/folders/1UDiGt8pSKae0wRrdzG7gJcWtM5uubm8q) se anexa la imagen PNG y el archivo en PgModeler del modelo de datos con los ajustes correspondientes al proceso de entradas.

**Comment by mafeave** [comment]
De acuerdo a la reunión realizada con @jairolh y @fnrojash el día 15 de Julio, se deben realizar los siguientes ajustes:
- Agregar '_id' a los campos con relación foránea: Campo acta_recibido en la tabla entrada
- Cambiar nombre de la tabla entrada por entrada_elemento
- La tabla de documento_entrada se eliminaría ya que se crearía el registro en el Core
- Cambiar nombre del campo placa a un nombre más descriptivo ya que esta aplica para una entrada por Reposición, en la gestión de salidas el campo quedaría como placa_asignada

**Comment by mafeave** [comment]
Tener en cuenta la relación de las entradas con un documento contable (P8), el cual se consumiría de un servicio de KRONOS

**Comment by Miavega** [comment]
Se realizan los ajustes al modelo dadas las observaciones. Pueden verse en el [enlace](https://drive.google.com/drive/folders/1UDiGt8pSKae0wRrdzG7gJcWtM5uubm8q). Se deja como observación que para la relación con el documento contable (P8), no se realiza ningún ajuste sobre el modelo para esto ya no afecta este.
La imagen respectiva para revisión es entradas_v2.png

**Comment by Miavega** [comment]
![entrada](https://user-images.githubusercontent.com/23342808/61565509-db924000-aa3e-11e9-9399-98a9e043f4f9.png)

**Comment by mafeave** [comment]
Se envian los ajustes para aprobación del modelo de datos mediante el [kanban Nº 31308](https://tuleap.udistrital.edu.co/plugins/tracker/?aid=31308)
