### ISSUE TITLE
Revisar y ajustar creación de árbol con nueva norma contable, debe permite crear la relación en la tabla

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#294]
Se debe revisar el funcionamiento actual de la creación de la tabla con relación entre el grupo y los subgrupos, se debe permitir la creación de dos niveles mas para cumplir con los cuatro niveles, la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar el componente para la creación de hasta 4 niveles (Grupos, Segmento, Familia y clase)

- [x] Realizar los ajustes de los label con la nueva jerarquía

- [x] Ajustar componente de agregar nuevo subgrupo

**Comment by AlexFBP** [comment]
Se empieza a abordar el *Issue*

**Comment by AlexFBP** [comment]
De acuerdo al manual, secc. 3.2.1.3.2. (p.41), la jerarquía es la siguiente:

![image](https://user-images.githubusercontent.com/6588872/99422071-1e7f5480-28cd-11eb-8644-ae2c2bc6ea26.png)

**Comment by AlexFBP** [comment]
Referencias
1. [Manual de Bienes (SDH)](https://www.shd.gov.co/shd/node/36684)
1. [Clasificador de bienes y servicios](https://www.colombiacompra.gov.co/clasificador-de-bienes-y-Servicios)
2. [Catálogo general de cuentas](https://www.contaduria.gov.co/catalogo-general-de-cuentas)

**Comment by AlexFBP** [comment]
Se revisaron con Fabian y Cristian Sanchez, el modelo de la base de datos (#35), para aclarar dudas y para tener en cuenta cómo abordar el issue.

Se piensa unificar/generalizar los componentes crud-grupo y crud-subgrupo_1 dentro de [pages/catalogo-bienes](https://github.com/udistrital/arka_cliente/tree/dev/src/app/pages/catalogo-bienes), a algo como crud_nivel, que reciba como argumento el nivel de jerarquía y en función del nivel muestre u oculte campos del formulario

**Comment by AlexFBP** [comment]
De por sí desde "Construcción Catálogo" se pueden crear jerarquías infinitas:

![image](https://user-images.githubusercontent.com/6588872/99560671-20601b00-2994-11eb-945b-708d6e7539ee.png)

Por otro lado, en el módulo "Registro Elementos" se pueden agregar Elementos desde el Segmento. Debería limitarse únicamente a cuando se tenga seleccionada la Clase

Lo que vendría sería limitar que solamente sea hasta Clase, lo que podría ir de la mano con los cambios que implique el #35

**Comment by AlexFBP** [comment]
> *para la creación de **hasta** 4 niveles*

Desde "Catalogo de Elementos > Construcción de Catálogo", una vez seleccionado un catálogo, la-tabla/el-arbol implementado en src/app/pages/catalogo-bienes/registro-catalogo/ ; al hacer click en cada fila se genera un evento con la información de la fila, que es capturado por `receiveMessage(event)`.

El evento, los datos de la fila; ahora deberán incluir el nivel jerárquico, de tal manera que:

- En la nueva variable `modificando_tipo` se rellene con el nivel para actualizar el formulario de subgrupos, de tal manera que coincida con las nuevas frases disponibles L10n (en src/assets/i18n/e*.json)
- La nueva variable `permitir_crear_subgrupo` deberá ponerse a `true` o `false` dependiendo de si el nivel jerárquico actual es clase o no, respectivamente.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
