### ISSUE TITLE
Organizar el menú de enlistar catalogo por crear catalogó, listar catalogo y consultar cataloga, ajustar tamaño de tabla de lista que se ajuste

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#295]
Se debe re organizar el componente de lista de catalogo en tres nuevos submenús, la issue debe cumplir con los siguientes requerimientos:

- [x] El sub componente de lista a un submenú de en listar catálogos 

- [x] El sub componente de formulario a un submenú de crear catalogo, al finalizar la creación del catalogo se debe redireccionar al componente de listar catalogo 

- [x] El sub componente de detalle a un submenú de consultar catalogo

**Comment by juandavidvelezaalvarez** [comment]
- Se modificó el html en el componente ngx-list-catalogo para que no mostrara las tres pestañas si no solamente la lista.
- Se ajustó el tamaño de la tabla en el html del componente ngx-list-catalogo para que la tabla ocupara solo una pantalla horizontal sin necesidad de hacer scroll
- Se cambió el archivo de menú pages-menu para que mostrara las dos nuevas opciones de menú, para crear catalogos y para consultar catalogos.
- Se modificó el componente ngx-crud-catalogo para que al guardar llamara la lista.
- Se modificó el componente ngx-crud-catalogo para que reciba por la ruta el id del catalogo a actualizar y lo cargue así.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
