### ISSUE TITLE
Ajustar botón en lista de borrar, no debe borrar el catalogo si no cambiar el estado de true a false, ajustar en campo tabla activo de true a activo y false a inactivo 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#296]
Se debe corregir el funcionamiento del botón eliminar en el componente de lista catalogo, este no debe borrar el registro de la base de datos, si no cambiar el estado de true a false, ajustar en campo tabla activo de true a activo y false a inactivo, la issue debe cumplir con los siguiente requerimientos:

- [x]  Ajustas función para que no realice un DELETE Si no un PUT al campo ACTIVO

- [x] Ajustar en la tabla no se muestre campo activo  true cambiar por  Activo y false a Inactivo

**Comment by juandavidvelezaalvarez** [comment]
- Se ajustó el componente ngx-list-catalogo para que en el evento click del  botón delete no llamé al metodo delete del api sino que llame al método put para que actualice el estado.
- En los settings de la tabla se puso cambió lo que se muestra para el campo activo, para que no muestre true o false sino activo o inactivo según el caso.
En esta funcionalidad usé ocho horas con pruebas y todo.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
