### ISSUE TITLE
Realizar el funcionamiento para el registro de desde el cliente a API Catalogo_elementos_crud, con los nuevos niveles 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#299]
Se debe realizar el funcionamiento desde el cliente con los ajustes correspondientes para el registro de los grupos al catalogo y de los distintos subgrupos(niveles) al catalogo, la issue debe cumplir con los siguientes requerimientos:

- [x] Reorganizar el JSON que se debe enviar al API_CRUD para que se pueda realizar la transacción correcta

- [x] Realizar la prueba de resgistro de un grupo a un catalogo y los diferentes subgrupos(niveles)

**Comment by AlexFBP** [comment]
Se da inicio al *Issue*

**Comment by AlexFBP** [comment]
Como referencia, los JSON que se envían actualmente al crear un grupo/subgrupo:

- tr_grupo

```json
{
  "Catalogo": {
    "Id": 4
  },
  "Subgrupo": {
    "Codigo": 22,
    "Nombre": "prueba fabian",
    "Descripcion": "pruebas Alex",
    "TipoBienId": {
      "Id": 1,
      "Nombre": "Consumo",
      "Descripcion": "Elemento designado como bien de consumo",
      "CodigoAbreviacion": "Consumo",
      "Orden": 1,
      "Activo": true,
      "FechaCreacion": "2019-11-19 19:34:21.116338 +0000 +0000",
      "FechaModificacion": "2019-11-19 19:34:21.116338 +0000 +0000"
    },
    "Depreciacion": true,
    "Valorizacion": false,
    "Activo": true
  },
  "DetalleSubgrupo": {
    "Depreciacion": true,
    "Valorizacion": false,
    "TipoBienId": {
      "Id": 1,
      "Nombre": "Consumo",
      "Descripcion": "Elemento designado como bien de consumo",
      "CodigoAbreviacion": "Consumo",
      "Orden": 1,
      "Activo": true,
      "FechaCreacion": "2019-11-19 19:34:21.116338 +0000 +0000",
      "FechaModificacion": "2019-11-19 19:34:21.116338 +0000 +0000"
    }
  }
}
```

En crudo: `{"Catalogo":{"Id":4},"Subgrupo":{"Codigo":22,"Nombre":"prueba fabian","Descripcion":"pruebas Alex","TipoBienId":{"Id":1,"Nombre":"Consumo","Descripcion":"Elemento designado como bien de consumo","CodigoAbreviacion":"Consumo","Orden":1,"Activo":true,"FechaCreacion":"2019-11-19 19:34:21.116338 +0000 +0000","FechaModificacion":"2019-11-19 19:34:21.116338 +0000 +0000"},"Depreciacion":true,"Valorizacion":false,"Activo":true},"DetalleSubgrupo":{"Depreciacion":true,"Valorizacion":false,"TipoBienId":{"Id":1,"Nombre":"Consumo","Descripcion":"Elemento designado como bien de consumo","CodigoAbreviacion":"Consumo","Orden":1,"Activo":true,"FechaCreacion":"2019-11-19 19:34:21.116338 +0000 +0000","FechaModificacion":"2019-11-19 19:34:21.116338 +0000 +0000"}}}`

- tr_subgrupo

```json
{
  "SubgrupoPadre": {
    "Id": 23,
    "Nombre": "Prueba_2 15/05/2020 .",
    "Descripcion": "Ejercicio de prueba",
    "FechaCreacion": "2020-05-15 15:16:07.104881 +0000 +0000",
    "FechaModificacion": "2020-05-15 15:16:07.104883 +0000 +0000",
    "Activo": true,
    "Codigo": 3
  },
  "SubgrupoHijo": [
    {
      "Codigo": 2342,
      "Nombre": "khfjksd j hgkj hgsdk",
      "Descripcion": "jkshdfgjksdfhg jdkh gjskdg",
      "Activo": true
    }
  ]
}
```

En crudo: `{"SubgrupoPadre":{"Id":23,"Nombre":"Prueba_2 15/05/2020 .","Descripcion":"Ejercicio de prueba","FechaCreacion":"2020-05-15 15:16:07.104881 +0000 +0000","FechaModificacion":"2020-05-15 15:16:07.104883 +0000 +0000","Activo":true,"Codigo":3},"SubgrupoHijo":[{"Codigo":2342,"Nombre":"khfjksd j hgkj hgsdk","Descripcion":"jkshdfgjksdfhg jdkh gjskdg","Activo":true}]}`

(Este *Issue* va de la mano con udistrital/catalogo_elementos_crud#37)

**Comment by AlexFBP** [comment]
Se movieron en la vista los campos de detalle del crud-grupo...:

![image](https://user-images.githubusercontent.com/6588872/100192335-c4c7ed00-2ebf-11eb-90eb-020ae7f45c3c.png)

... a crud-subgrupo:

![image](https://user-images.githubusercontent.com/6588872/100192421-eaed8d00-2ebf-11eb-881b-f36b8920b2bb.png)

*Nota: no se ha publicado aún commit que incluya estos cambios, y mucho menos se ha verificado la transacción

**Comment by AlexFBP** [comment]
Los [cambios a la API CRUD](udistrital/catalogo_elementos_crud#37) podrían ser mover, de tr_grupo a tr_subgrupo, el `"DetalleSubgrupo": {}` y hacerlo opcional:

- tr_grupo - Si no se especifica `"DetalleSubgrupo": {}` *no* crea el grupo, la API deberá ahora permitir no especificarlo.

```diff
 {
   "Catalogo": {
     "Id": 1
   },
   "Subgrupo": {
     "Activo": true,
     "Codigo": 234,
     "Nombre": "grupo prueba2",
     "Descripcion": "grupo prueba2",
     "TipoNivelId": {
       "Id": 1
-    },
-    "DetalleSubgrupo": {
-      "Depreciacion": true,
-      "Valorizacion": false,
-      "Deterioro": false,
-      "Activo": true,
-      "TipoBienId": {
-        "Id": 1
-      }
     }
   }
 }
```

- tr_subgrupo - De especificarse `"DetalleSubgrupo": {}` deberá ser obligatorio que incluya `"TipoBienId":{}`

```diff
 {
   "SubgrupoPadre": {
     "Id": 1
   },
   "SubgrupoHijo": [{
     "Codigo": 2342,
     "Nombre": "segmento prueba",
     "Descripcion": "segmento prueba",
     "Activo": true,
     "TipoNivelId": {
       "Id": 2
+    },
+    "DetalleSubgrupo": {
+      "Depreciacion": true,
+      "Valorizacion": false,
+      "Deterioro": false,
+      "Activo": true,
+      "TipoBienId": {
+        "Id": 1
+      }
     }
   }]
 }
```

**Comment by AlexFBP** [comment]
Ajustado el cliente para enviar los paquetes:

- tr_grupo

![image](https://user-images.githubusercontent.com/6588872/100308389-47ab7f00-2f76-11eb-849a-986a0b7e1df6.png)

**Comment by AlexFBP** [comment]
Ajustado el cliente para enviar tr_subgrupo:

- tr_subgrupo

![image](https://user-images.githubusercontent.com/6588872/100369352-c930fa80-2fd2-11eb-894f-13cb0bbd9ad4.png)

**Comment by AlexFBP** [comment]
Agregado `TipoNivelId` a...

- tr_grupo

![image](https://user-images.githubusercontent.com/6588872/100389684-065db280-2ffc-11eb-8b84-0a8360fe0ea5.png)

- tr_subgrupo

![image](https://user-images.githubusercontent.com/6588872/100391480-8d615980-3001-11eb-8854-ab11252662bc.png)

También se cambió `Detalle` a `DetalleSubgrupo` en tr_subgrupo, de acuerdo al [mensaje de ayer](#issuecomment-733724499) (aunque podría dejarse simplemente como `Detalle`)

**Comment by AlexFBP** [comment]
Se dejó indicado en los comentarios a crud_grupo/subgrupo.ts; lo que se debe cambiar/agregar/eliminar una vez se actualice la API, por lo que las transacciones quedaron de tal manera que funcionan con respecto a la versión actual de la API

**Comment by AlexFBP** [comment]
Se reajustan los JSON enviados por PUT (actualizacion de datos) de acuerdo al [mensaje de arriba](#issuecomment-733724499):

- PUT a /subgrupo/{id} (no se requiere hacerlo a /tr_grupo)

  ![image](https://user-images.githubusercontent.com/6588872/100534281-1d0e3000-31db-11eb-8b84-018818779eb6.png)

- PUT a /tr_subgrupo/{id}

  ![image](https://user-images.githubusercontent.com/6588872/100534130-bb00fb00-31d9-11eb-844b-ddd179975f64.png)

**Comment by AlexFBP** [comment]
Finalmente, los PUT que se envían, son los siguientes:

- ~~`tr_grupo/{id}`~~ `subgrupo/{id}` Para Grupos (tipo_nivel.id = 1)

```json
{
  "Id": 65,
  "Nombre": "jsdhflkg kjsdlhgl",
  "Descripcion": "kjlsdhfg kjslhdfgkl",
  "FechaCreacion": "2020-11-30 09:06:58.314286 +0000 +0000",
  "FechaModificacion": "2020-11-30 09:06:58.314431 +0000 +0000",
  "Activo": true,
  "Codigo": 897,
  "TipoNivelId": {
    "Id": 2
  }
}
```

- ~~`subgrupo/{id}`~~ `tr_subgrupo/{id}` Para Segmento(2), Familia(3) y Clase(4). `DetalleSubgrupo` se envía únicamente si `SubgrupoHijo.TipoNivelId.Id` es Clase

```json
{
    "SubgrupoHijo": {
        "Id": 62,
        "Nombre": "ekjrht jkerhtkj er",
        "Descripcion": "jkerhtkj eht kjreh",
        "Activo": true,
        "Codigo": 57987,
        "TipoNivelId": {
            "Id": 4
        }
    },
    "DetalleSubgrupo": {
        "Id": 43,
        "Activo": true,
        "Depreciacion": false,
        "Valorizacion": true,
        "TipoBienId": {
            "Id": 2
        },
        "SubgrupoId": {
            "Id": 62
        }
    }
}
```
