### ISSUE TITLE
Crear mockups para el registro del acta de recibido

### ISSUE THREAD

**Issue by mafeave** [udistrital/arka_cliente#3]
Crear el mockup correspondiente al registro del acta de recibido.

**Comment by Miavega** [comment]
En el siguiente [https://drive.google.com/drive/folders/1_JnAencA4BUgeqWjhjP0m2-By0kkL2la](url) se encuentran las capturas de pantalla del mockup para el acta de recibido.

**Comment by mafeave** [comment]
De acuerdo con la [reunión](https://docs.google.com/document/d/1Lsslpenvr_xJyNNFBkw8D2SGZbCyw90nuc1gwFKUwg0/edit) realizada el día 29 de mayo, el acta debe asignarse a un usuario de Almacen, que no sea el Jefe, se debe agregar el campo.

**Comment by Miavega** [comment]
En el siguiente [enlace](https://drive.google.com/drive/folders/1_JnAencA4BUgeqWjhjP0m2-By0kkL2la) se encuentran los Mockups con las respectivas correcciones descritas a continuación:

- Imagen _**004**_ contiene las correcciones a la imagen _**002**_, donde se indicaba que se debía permitir la carga de soportes de certificados de satisfacción y factura. El contrato ya se encuentra ligado al acta por ende no se solicita su carga.

- Imagen _**005**_ en la que se añade un campo para seleccionar el usuario de almacen al cual se le asignará el acta de recibido. Complementa la imagen _**001**_

**Comment by mafeave** [comment]
Se verifican los ajustes solicitados. Se da por finalizada la tarea.
