### ISSUE TITLE
Ajuste Mockups Acta de Recibido

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#30]
Se debe ajustar los mockups del acta de recibido de acuerdo teniendo en cuenta los aspectos observados en acta No 8 teniendo en cuenta los siguientes aspectos

- [x] Número de factura alfanumérico

- [x] Incluir el concepto (devolutivo, consumo, consumo controlado)

- [x] Valores con decimales y miles

- [x] Porcenta iva, valor iva

- [x] Valores totales por concepto

- [x] Valor total para corroborar total de factura

- [x] Incluir Descuentos

- [x] Creacion de mockup de consultas de actas de recibido

- [x] Quitar valores de los elementos en el mockup de verificacion

**Comment by ManuelMurillo** [comment]
En el siguiente commit se encuentra la modificacion de los mockups
https://github.com/udistrital/arka_cliente/commit/4ff1382572195b7f0c5843ce547dc11d5e2d4b79

**Comment by ManuelMurillo** [comment]
Agregar Modificaciones:

- [ ] Agregar estado del Acta de recibido

- [ ] Agregar proveedor, fecha de factura y numero de factura

- [ ] Agregar varias facturas 

- [ ] Ver los datos de la factura y los datos de los elementos

- [ ] Posibilidad de ver a los usuarios que crearon y editaron los elementos en el acta de recibido

**Comment by ManuelMurillo** [comment]
![Mockup consultas acta de recibido](https://user-images.githubusercontent.com/29108085/61178332-a609d480-a5b0-11e9-9564-37550db36085.png)

Mockup Consultas Acta de Recibido

**Comment by ManuelMurillo** [comment]
![Mockup registro acta de recibido 1](https://user-images.githubusercontent.com/29108085/61178338-b5891d80-a5b0-11e9-80de-6be020ed55b7.png)
![Mockup registro acta de recibido 2](https://user-images.githubusercontent.com/29108085/61178339-b91ca480-a5b0-11e9-8cee-b294ed95bc1e.png)
![Mockup Verificacion acta de recibido 3](https://user-images.githubusercontent.com/29108085/61178365-58419c00-a5b1-11e9-98ab-0625fa57d8cb.png)


Mockup Registro Acta de recibido

**Comment by ManuelMurillo** [comment]
![Mockup Verificacion acta de recibido ](https://user-images.githubusercontent.com/29108085/61178381-a6569f80-a5b1-11e9-8d21-9474fc1b9d29.png)
![Mockup Verificacion acta de recibido 2](https://user-images.githubusercontent.com/29108085/61178384-b40c2500-a5b1-11e9-92d8-aa6b3a7bc438.png)
![Mockup Verificacion acta de recibido 3](https://user-images.githubusercontent.com/29108085/61178387-b8384280-a5b1-11e9-9dca-4db9c0032537.png)

Mockup Verificacion Acta de recibido

**Comment by ManuelMurillo** [comment]
Teniendo en cuenta la reunion del 18 de Julio del 2019, se actualizan los mockups del acta de recibido
Consulta
![Consulta_Acta_de_Recibido_v4](https://user-images.githubusercontent.com/29108085/61490822-6e65a880-a973-11e9-8175-3d78a03c63d1.png)
Registro
![Registro_Acta_de_Recibido_v4](https://user-images.githubusercontent.com/29108085/61490858-80474b80-a973-11e9-96b1-1a1d3333db33.png)
![Registro_Acta_de_Recibido_2_v4](https://user-images.githubusercontent.com/29108085/61490862-81787880-a973-11e9-9c96-eec4a1f6a6e1.png)
![Registro_Acta_de_Recibido_3_v4](https://user-images.githubusercontent.com/29108085/61490865-83423c00-a973-11e9-8163-de922bed455e.png)

Verificacion
![Verificacion_Acta_de_Recibido_v4](https://user-images.githubusercontent.com/29108085/61490875-89381d00-a973-11e9-8d88-8eaee9f78e68.png)
![Verificacion_Acta_de_Recibido_2_v4](https://user-images.githubusercontent.com/29108085/61490879-8a694a00-a973-11e9-8b2b-5b054e7529fb.png)
![Verificacion_Acta_de_Recibido_3_v4](https://user-images.githubusercontent.com/29108085/61490881-8b9a7700-a973-11e9-831e-5e478f26ad83.png)

**Comment by mafeave** [comment]
Se verifican los ajustes solicitados en [revisión](https://github.com/udistrital/administrativa_cliente/issues/306) del 12 de julio de 2019 y de las observaciones dadas por el usuario final en el [acta Nº 11](https://docs.google.com/document/d/16D4_Cmwkiv3OKmljf5v1H5QC_osk0PZE_hEjJNocn2E/edit?usp=drive_web&ouid=114036767353111235305)
