### ISSUE TITLE
Ajustar asignación de clase a los ítem de depreciación, valorización y tipo de bien 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#300]
En el sistema actual la asignación de los parámetros depreciación, valorización y tipo de bien se realiza en el nivel de grupo, se debe realizar el ajuste para mover esta asignación al nivel de clase, la issue debe cumplir con los siguientes requerimientos:

- [x] Se debe ajustar en el cliente que cuando se este creando un nivel de clase se habilite el formulario las opciones de definición de los   parámetros

- [x] Realizar una transacción o modificar una existente  para el registro de esta información

**Comment by AlexFBP** [comment]
Se dio inicio al Issue ayer, hay un avance en el #299 en relacion al primer item
