### ISSUE TITLE
Revisar y ajustar  la asignación de cuentas contables a nivel de clase  

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#303]
Actualmente el sistema asigna a nivel de grupos las cuentas contables (subsistema de Kronos), se debe analizar y realizar los ajustes necesarios para que las asignaciones de las cuentas contables se realice a nivel de clase, la issue debe cumplir con los siguientes requerimientos:

- [x] Revisar la función que activa la asignación de las cuentas contables a nivel de grupo para pasarlo a nivel de clase 

- [x] Revisar y analizar como se esta cargando las cuentan contables en el input ya desarrollado 

- [x] Revisar el [servicio](http://pruebasapi.intranetoas.udistrital.edu.co:8209/v1/nodo_cuenta_contable?fullTree=true) o con [autenticación](https://autenticacion.portaloas.udistrital.edu.co/apioas/cuentas_contables_crud/v1/nodo_cuenta_contable?fullTree=true)  desarrollado con el nuevo sistemas de kronos 

- [x] Ajustar la función para la asignación desde el cliente a niveles de clase

- [x] ajustar la carga de las cuentas contables con el nuevo sistema

**Comment by CristianDavidSanchez** [comment]
Se da inicio a la tarea

**Comment by CristianDavidSanchez** [comment]
La funcionalidad del filtro depende de la herramienta que se usa en la base de datos y el orden de los mismos, dado que el api del nuevo servicio esta desarrollado sobre mongo, no es relacional, sin embargo; se lleva el tema a colación con el líder técnico y se define un nuevo issue para poder realizar el filtrado.

**Comment by CristianDavidSanchez** [comment]
Se conecta con la función generada en kronos udistrital/arka_mid#50 , se consume en arka_cliente y el filtro ya obtiene de manera funcional las cuentas
![Opera Captura de pantalla_2020-12-02_153921_localhost](https://user-images.githubusercontent.com/45292213/100928723-93997f00-34b4-11eb-8d72-ffaf36c22442.png)

**Comment by CristianDavidSanchez** [comment]
Se limita la asignación de cuentas a nivel de clase por medio de tiponivelId
![image](https://user-images.githubusercontent.com/45292213/100932427-db6ed500-34b9-11eb-8c55-c852bd12ebe3.png)

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
