### ISSUE TITLE
Analizar como se esta realizando el registros de elementos en un acta de recibido

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#304]
Se debe revisar como se esta realizando el registro de los elementos de forma masiva desde el componente de registro_acta_recibido, la issue debe cumplir con los siguientes requerimientos:

- [x] Se debe analizar como  se realiza y en donde se registran los elementos al usar la función de carga masiva.

- [x] Revisar si se registra de forma individual casa elemento

**Comment by ludwinggsanchez** [comment]
Una vez se envía el acta, se envían los tres formularios del componente RegistroActaRecibido. Todo se recopila en transacción Transaccion_Acta así:

TransaccionActaRecibido
{
ActaRecibido, 
UltimoEstado, 
SoportesActa,
}

El ActaRecido tiene la siguiente información:
{
Activo: true
FechaCreacion: Fri Dec 04 2020 14:30:54 GMT-0500 (Colombia Standard Time) {}
FechaModificacion: Fri Dec 04 2020 14:30:54 GMT-0500 (Colombia Standard Time) {}
Id: null
Observaciones: "12345"
RevisorId: NaN
UbicacionId: 3
},

Los soportes contienen la lista de elementos y el id asociado al documento soporte subido:

Elementos: 
Elemento {
Id: null, 
Nombre: "PC DELL 9010", 
Cantidad: 1, 
Marca: "DELL", 
Serie: "ASDFDFR123123", …
}...

SoporteActa: {
ActaRecibidoId:"",
Activo: true,
Consecutivo: "567",
DocumentoId: undefined,
FechaCreacion: ,
FechaModificacion: ,
FechaSoporte: ,
Id: null,
ProveedorId: 14860,
}

UltimoEstado: {
ActaRecibidoId:"",
Activo: true,
EstadoActaId:,
FechaCreacion:,
FechaModificacion:,
Id:,
}

**Comment by ludwinggsanchez** [comment]
El acta se sube al endpoint de ARKA_SERVICE: https://autenticacion.portaloas.udistrital.edu.co/apioas/arka_mid/v1/transaccion_acta_recibido, mediante el método postTransaccionActa de ActaRecibidoHelper.

**Comment by fabianbarreto02** [comment]
Se da por finaliza la issue
