### ISSUE TITLE
Ajuste Modelo de Datos Acta de Recibido

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#31]
Se requiere un ajuste en el modelo de datos del acta teniendo en cuenta las observaciones y cambios propuestos en los mockups en el issue #30

**Comment by ManuelMurillo** [comment]
![image](https://user-images.githubusercontent.com/29108085/60688831-3b082180-9e7d-11e9-9df9-43f3e5108f13.png)

en la imagen se muestra el modelo modificado del acta de recibido


aqui se encuentra el link para usar el modelo

https://drive.google.com/open?id=1elpvQn4_SJfksZG1HXGGFZEVxqYt2Pdw

**Comment by mafeave** [comment]
eliminar campo porcentaje_iva de la tabla factura

**Comment by ManuelMurillo** [comment]
Realizar un reajuste del modelo de datos del acta de recibido debido a un ajuste general en los mockups del issue #30

**Comment by ManuelMurillo** [comment]
en el siguiente link se encuentra la modificacion del modelo de datos del Acta de recibido
https://drive.google.com/open?id=1dC8XB8p6XUaj5rA_zDlvJHKdZ5Z1XRrc


![Modelo de Datos Acta de Recibido v 3](https://user-images.githubusercontent.com/29108085/61178009-a00ff580-a5a8-11e9-841a-127e6bdf9009.png)

**Comment by mafeave** [comment]
Se revisa el modelo de datos, se deben hacer los siguientes ajustes:
- Los campos fecha_registro y fecha_modificacion deben ser de tipo timestamp
- Cambiar el nombre del campo fecha_registro por fecha_creacion en todas las tablas
- Cambiar nombre de la tabla tipo_de_bien a tipo_bien
- Cambiar campo estado por activo en las tablas: acta_recibido, estado_acta, estado_elemento y tipo_bien
- Agregar campo activo(boolean) en las tablas: soporte, elemento

**Comment by mafeave** [comment]
De acuerdo a la reunión realizada con @jairolh y @fnrojash el día 15 de Julio, se deben realizar los siguientes ajustes:

Se debe evaluar si es necesario crear la tabla soporte para el nuevo core o se agregarían los campos definidos en las tablas del microservicio de documentos, la tabla tendría los campos de:
- sistema
- id_registro
- tabla_relacionada
- descripcion

Tipo de documento para la tabla de documento_ingreso: factura, acto administrativo

Agregar '_id' a los campos con relación foránea: Campo porcentaje_iva en la tabla elemento

Se sugiere guardar los valores calculados de IVA y totales de la factura, para facilitar a futuro la generación de reportes.

Cambiar nombre de la tabla historico por historico_acta

**Comment by ManuelMurillo** [comment]
En la siguiente imagen se encuentra la version del modelo de datos con los cambios solicitados por @jairolh y @fnrojash con respecto al acta de recibido

![Modelo de Datos Acta de Recibido v4](https://user-images.githubusercontent.com/29108085/61486372-e9759180-a968-11e9-9f65-35ffd76bda0a.png)

en el siguiente enlace se encuentra el modelo relacionado

https://drive.google.com/open?id=1W7Duv9ektN9TSiUt19olml2jj7HOlzi7

**Comment by mafeave** [comment]
Se envian los ajustes para aprobación del modelo de datos mediante el [kanban Nº 31308](https://tuleap.udistrital.edu.co/plugins/tracker/?aid=31308)
