### ISSUE TITLE
Revisión del Excel como realiza la carga de subgrupo (sistema actual) a nivel (clase), analizar y revisar si el tipo de bien se carga de forma automática del subgrupo 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#311]
Se debe realizar el Análisis del archivo excel que se tiene base para realizar el cargue masivo de los elementos, en este documento se ingresa los datos de los elementos y tambien el subgrupo a donde se registrara cada elemento, revisar como se realiza la relación cuando se sube el archivo, la issue debe cumplir con los siguientes requerimientos:

- [x] Revisar la carga masiva y analizar como se realiza la relación del tipo de bien y el subgrupo, existe una función que relaciona el elemento con el subgrupo o clase?

- [x] Analizar como realizar el cargue masivo de los elementos, las relaciones con el catalogo

**Comment by ludwinggsanchez** [comment]
En el componente de Registro de Acta, una vez se carga el archivo excel y se da click en cargar elementos, el método readThis() mediante el servicio postArchivo(), mapea cada fila del archivo excel al siguiente JSON:
{
   "Cantidad":"1"
   "Descuento":"246242.424"
   "Marca":"DELL"
   "NivelInventariosId":"1"
   "Nombre":"PC DELL 9010"
   "PorcentajeIvaId":"3"
   "Serie":"ASDFDFR123123"
   "SubgrupoCatalogoId":"Prueba Subgrupo 22"
   "Subtotal":"1231212.12"
   "TipoBienId":""
   "UnidadMedida":"1"
   "ValorIva":"187144.2422"
   "ValorTotal":"1172113.938"
   "ValorUnitario":"1231212.12"
}

**Comment by ludwinggsanchez** [comment]
En este punto, la única manera de relacionar los elementos con un catálogo, es con la clase que se le va a asignar, por lo tanto, en caso de que haya más de un catálogo, hay que establecer a qué catálogo pertenece la clase seleccionada y asignarla al elemento.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
