### ISSUE TITLE
Revisar al crear un acta donde se almacena la información del proveedor y revisar por que al realizar el registro del acta_recibido el campo revisor_id queda registrado 0 con el usuario pruebasoas, ajustar el select para que se muestre bien pues queda incompleto

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#315]
Se debe revisar como se registra el campo revisor_id y analizar por que no se registra bien con el usuario pruebasoas, no se debe permitir que se registre un revisor_id=0, también se debe corregir el input de dependencia y ubicación, pues se corta la data por que no cabe en el card, la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar y revisar el registro de revisor_id, no se debe registrar un revisor_id=0

- [x] Ajustar el componente de datos iniciales para que no se corte la lista en dependencia y ubicación por que no cabe en la card

**Comment by AlexFBP** [comment]
Se empieza a abordar el Issue

**Comment by AlexFBP** [comment]
Se empieza a abordar desde el último ítem. El que los datos se corten, más concretamente es porque el desplegable con opciones aparece renderizado dentro de otro componente, lo que origina una barra de desplazamiento a la derecha:

![image](https://user-images.githubusercontent.com/6588872/101267077-19bafd00-3723-11eb-82f0-022ac3023323.png)

El componente que se usa para el *autocompleter* es [ng2-complete](https://www.npmjs.com/package/ng2-completer), que, de acuerdo a su autor, parece estar algo abandonado:

> ## help needed
> I don't use this library much anymore and don't have time to properly maintain it. If you are currently using ng2-completer and interested to maintain it please let me know!

Por lo anterior, y aprovechando que también está disponible, se consulta cómo usar el [autocomplete de Angular Material](https://material.angular.io/components/autocomplete/overview) y se carga inicialmente con los mismos datos, para obtener lo siguiente:

![image](https://user-images.githubusercontent.com/6588872/101269178-d4ee9080-3739-11eb-955e-216bd004c144.png)

Como contrapartida, dado que ambos componentes (ng2-complete y mat-autocomplete) tratan los datos de manera diferente, se hace necesario rehacer la integración con los demás componentes, es decir, que el componente externo, el formulario:

- Pueda definir el valor inicial del campo al detectarse valores previamente almacenados
- Pueda leer el valor seleccionado por el usuario

Por lo anterior, al implicar bastantes cambios, se suspende este enfoque y se deja en la rama `fix/opcionesOcultas-CambioMaterial`

**Comment by AlexFBP** [comment]
El desborde (ultimo item) parece ser un [problema recurrente](https://stackoverflow.com/a/40905549/3180052). Se corrige agregando unos estilos adicionales

**Comment by AlexFBP** [comment]
Si bien la rama anterior arregla el problema con el componente actual, se recomienda a futuro retomar el trabajo con el componente mat-autocomplete, similar a lo dejado en la rama `fix/opcionesOcultas-CambioMaterial` (commit 90f2ece)

**Comment by AlexFBP** [comment]
Respecto al primer item (cuando se va RevisorId=0), se identificó el JSON que se envía al registrar un acta de prueba e identificar cómo se envía la transacción:

![image](https://user-images.githubusercontent.com/6588872/101417867-8288ad80-38ba-11eb-8996-79377b30b2dc.png)

La transacción se envía al endpoint `transaccion_acta_recibido` del servicio `ACTA_RECIBIDO_SERVICE`.

Esta línea es la última responsable del objeto `ActaRecibido` del JSON enviado:

![image](https://user-images.githubusercontent.com/6588872/101417790-5f5dfe00-38ba-11eb-8e70-eea4c584f7b5.png)

Se empieza a revisar desde este punto hacia atrás para identificar el momento en que se asigna `ActaRecibido.RevisorId`

**Comment by AlexFBP** [comment]
La función `Registrar_acta()` asigna el `RevisorId` a partir de la variable `persona_id` del localStorage. En relación al #329, se creó un diálogo que se abre al momento de guardar/enviar el acta, en caso que no esté definida:

![image](https://user-images.githubusercontent.com/6588872/101420698-b9fa5880-38c0-11eb-9aae-95a50eefeaba.png)

**Comment by AlexFBP** [comment]
Comprobado: Con utest01 se muestra el dialogo normal:

![image](https://user-images.githubusercontent.com/6588872/101423042-1f9d1380-38c6-11eb-8d1f-ad81abba3eb9.png)
