### ISSUE TITLE
Crear un botón de eliminar los elementos completo o varios para la carga masiva 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#316]
Se debe crear un botón al momento de realizar una carga masiva y se seleccionar en su totalidad o varios registros para eliminar, actualmente existe la función para eliminar uno a uno, la issue debe cumplir con los siguientes requerimientos:

- [x] Crear un botón para poder eliminar todos o varios elementos cargados 

- [x] Realizar la funcionalidad para el boto de eliminar

**Comment by AlexFBP** [comment]
Se empieza a abordar el *Issue*

**Comment by AlexFBP** [comment]
Se da inicio al *Issue*

**Comment by AlexFBP** [comment]
Se agregan controles para eliminar uno o varios elementos (sin funcionalidad aún, de acuerdo al primer item). Se usaron componentes de nebular:

![image](https://user-images.githubusercontent.com/6588872/101275275-6679f480-3772-11eb-9f3f-cf9806938fe8.png)

**Comment by AlexFBP** [comment]
Se reubica la casilla de (de)seleccion total como el titular de la columna de casillas, y se agrega una nube bajo "hover" para la descripción de la funcionalidad de la casilla

![image](https://user-images.githubusercontent.com/6588872/101412134-11dc9380-38b0-11eb-81d8-c9290f596e6f.png)

Para el borrado de los elementos seleccionados, se agregó un modal de confirmación:

![image](https://user-images.githubusercontent.com/6588872/101412255-451f2280-38b0-11eb-80e7-384be5b6d6a9.png)
