### ISSUE TITLE
Ajustes Modelo de datos baja de bienes

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#32]
Realizar los ajustes al modelo de datos del poceso de baja de bienes con base a las observaciones realizadas en el [acta 8](https://drive.google.com/drive/u/0/folders/13q1QzHK2ITGMEhZ7vvCTbrJBWHZGTKqn)

**Comment by Miavega** [comment]
En el siguiente [enlace](https://drive.google.com/drive/folders/160r8aHnzSnJBAQJTKpnMRJIZ7Bxb8fNz) se encuentra el archivo en PgModeler y la imagen PNG asociados al proceso de bajas.

**Comment by mafeave** [comment]
Se deben hacer los siguientes ajustes al modelo:
- Los campos fecha_registro y fecha_modificacion deben ser de tipo timestamp
- Cambiar el nombre del campo fecha_registro por fecha_creacion en todas las tablas
- En la tabla movimiento sobraría el campo fecha_registro_movimiento

**Comment by mafeave** [comment]
Modelo ajustado mediante issue #41
