### ISSUE TITLE
Ajustar la funcionalidad de buscar y organizar arbol de catalogo 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#326]
Se debe realizar el ajuste de la funcionalidad de buscar y la organización del arbol por codigo, nombre, descripcion en los componentes de consultar catalogo, construir catalago y asignación de cuentas, ya que se bloquea y se presenta un error cuando se realiza la funcionalidad, la issue debe cumplir con los siguientes requerimientos:
  

- [x] Ajustar funcionalidad de buscar y la organización del arbol por codigo, nombre, descripcion en el componente consultar catalogo

- [x] Ajustar funcionalidad de buscar y la organización del arbol por codigo, nombre, descripcion en el componente construir catalago

- [x] Ajustar funcionalidad de buscar y la organización del arbol por codigo, nombre, descripcion en el componente asignación de cuentas

**Comment by CristianDavidSanchez** [comment]
Se ajusta la funcionalidad de organizar, sin embargo aún no se ha ajustado la función de búsqueda.
Antes:
![image](https://user-images.githubusercontent.com/45292213/101829510-1fd52300-3b01-11eb-9b49-9f7ded08061f.png)
Después:
![image](https://user-images.githubusercontent.com/45292213/101829615-44c99600-3b01-11eb-8424-dab1280b404e.png)

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
