### ISSUE TITLE
Ajustes Mockup's baja de bienes

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#33]
Realizar los ajustes a los mockups asociados al proceso de bajas de vienes, dado los criterios dados por el cliente.

**Comment by Miavega** [comment]
En el siguiente [enlace](https://drive.google.com/drive/folders/1YF4NdIeGiJEmaZY8pNqwaXFz0ApLfKxw) se encuentran los ajustes respectivos a los mockups de bajas de bien. En el mockup de consulta, el botón de detalles redirecciona a la misma vista de registro con los campos no editables, por eso no se realizan mockups para esto, se reutilizará la vista.

**Comment by mafeave** [comment]
Se verifican los ajustes solicitados en [revisión](https://github.com/udistrital/administrativa_cliente/issues/306) del 12 de julio de 2019 y de las observaciones dadas por el usuario final en el [acta Nº 11](https://docs.google.com/document/d/16D4_Cmwkiv3OKmljf5v1H5QC_osk0PZE_hEjJNocn2E/edit)
