### ISSUE TITLE
Crear componente para el registro de elementos de un proveedor 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#331]
Se debe desarrollar un componente adicional con un submenu independiente para el registro de elementos de un acta de recibido, este componente debe consultar un acta de recibido en estado registrada, cargar datos iniciales y datos de soporte y permitir al proveedor subir los la información de los elementos únicamente ya sea de forma de carga masiva o una a una, al realizar la carga de los elementos el acta se debe cambiar de estado de registrada a En elaboración, la issue debe cumplir con los siguientes requerimientos:

- [x]  Desarrollar el componente en un nuevo submenu de acta de recibido

- [x] Cargar información de un acta de recibido en estado registrada, cargar datos iniciales y datos de soporte

- [x] El provedor puede subir la información de los elementos de forma individual o de forma masiva

- [x] Al cargar la información el acta debe cambiar de estado de registrada a En elaboración

**Comment by AlexFBP** [comment]
Se empieza a abordar el Issue

**Comment by AlexFBP** [comment]
¿Hay algún documento que especifique qué debería poder hacer qué tipo (rol) de usuario? Si se conociera el rol, se podría limitar lo que puede hacer el usuario actual en función de su(s) rol(es) asignado(s)

Actualmente el cargue de los elementos a un acta, de forma individual o masiva, lo realiza [`CapturarElementosComponent`](https://github.com/udistrital/arka_cliente/tree/dev/src/app/pages/acta-recibido/capturar-elementos), que a partir del #337 `CapturarElementosComponent` ya no es parte de [`RegistroActaRecibidoComponent`](https://github.com/udistrital/arka_cliente/tree/dev/src/app/pages/acta-recibido/registro-acta-recibido)

Si se conocieran los roles, se podrían habilitar características específicas, no solamente de `CapturarElementosComponent` en función de los roles asignados, sino de otros componentes de Arka, facilitando la reutilización de código.

En el momento la gestión de roles del cliente parece ser básica: lo que encontré es que del [UserService](https://github.com/udistrital/arka_cliente/blob/dev/src/app/%40core/data/users.service.ts) se puede obtener el id del revisor (comportamiento que se quiere cambiar en #329 ).

Con lo anterior, el tercer ítem en teoría estaría listo, si se acepta que `CapturarElementosComponent` dependa del rol actual del usuario, y se configura de tal manera que un rol con los permisos adecuados, pueda modificar los campos que sean necesarios...

**Comment by AlexFBP** [comment]
En relación con todos los ítem, se agregó una funcionalidad básica de roles a [UserService](https://github.com/udistrital/arka_cliente/blob/dev/src/app/%40core/data/users.service.ts), y de permisos en función del rol, al componente [edicion-acta-recibido](https://github.com/udistrital/arka_cliente/tree/dev/src/app/pages/acta-recibido/edicion-acta-recibido).

Se propone que si en una sección de un componente se requieren unos privilegios determinados (ver, modificar, ocultar) en función del rol y otras variables, por ejemplo, de estados; que sea en el mismo componente que se implementen las reglas adecuadas

Para los ítem:

1. Hubo una desviación a la solicitud original: En "Consulta de Actas", cuando se dá click al lápiz (editar) en vez de mostrarse un aviso, se reutilizó/habilitó el componente edicion-acta-recibido, también para Estado Recibido. Adicionalmente, se modificó para recibir como parámetro el estado actual del Acta.
2. Derivada de la 1, si el estado es Registrada, no se muestra la parte de Carga Masiva. Una vez se presiona en Guardar se habilita el botón de "Envío a Proveedor"
3. Derivada de la 1 y 2, la carga de elementos se muestra en Elaboración o en Modificación.
4. Derivado de la 1, los mensajes (y el estado siguiente al momento tanto de guardar como de enviar a siguiente etapa) se cargan en función del estado actual del acta
