### ISSUE TITLE
Diagrama de Estados Acta de Recibido

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#34]
Se requiere la creacion de un diagrama de estados que sea capaz de definir los movimientos del acta de recibido en el sistema, para la implementacion del proceso en el frontend.

**Comment by ManuelMurillo** [comment]
![Diagrama de Estados](https://user-images.githubusercontent.com/29108085/61177352-e9584900-a598-11e9-8775-6ba4876e155a.png)


En esta imagen se encuentra el modelo inicial de los estados del acta de recibido, donde se relaciona la creacion, elaboracion, anulacion, verificacion y aceptacion del acta de recibido. En el siguiente enlace se encuentra el archivo modificable del modelo:

https://drive.google.com/open?id=1_L4Czeihf-ryr-XuZPDYuE0Cpvp4S0IY

**Comment by ManuelMurillo** [comment]
![Diagrama de Estados v 2](https://user-images.githubusercontent.com/29108085/61177388-d5f9ad80-a599-11e9-9360-ecce7189e603.png)

**Comment by mafeave** [comment]
Verificado el diagrama de estados con el usuario final en reunión del 12 de Julio, ver acta 10

**Comment by ManuelMurillo** [comment]
En la siguiente imagen se muestra la version del acta de recibido teniendo en cuenta los aspectos de la reunion del 18 de Julio

https://drive.google.com/open?id=16zJ4E2Zz-KVYZwwloNgQBA-EbQ1i8_rR

![Diagrama de Estados v 3](https://user-images.githubusercontent.com/29108085/61491302-90abf600-a974-11e9-9e71-556d558d7afc.png)
