### ISSUE TITLE
Realizar función para realizar una anulación de un acta de recibido 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#344]
Se debe realizar la funcionalidad y la función para realizar el proceso de anulación de un acta, se debe agregar un nuevo boton que solo este habilitado para  los usuarios que tengan el rol de "ADMIN_ALMACEN", "REVISOR" y bloquear para el resto de los roles, el boton debe cambiar el estado del acta  anulada y bloquear la funcionalidad de editar mostrando un modal para informar que el acta se encuentra anulada, la issue debe cumplir con los siguientes requerimientos:

- [x]   Crear el boton en la tabla de consulta de actas 

- [x] El boton debe habilitar solo para los usuarios que tengan el rol de "ADMIN_ALMACEN", "REVISOR" y bloquear para el resto de los roles

- [x] Crear una alerta si el roll no cuenta con permisos para acción notificar que el usuario no cuenta con los permisos requeridos

- [x] Al realizar la anulación del acta se debe cambiar el estado del acta y desactivar el boton de editar

**Comment by AlexFBP** [comment]
Se empieza a abordar el *Issue*

**Comment by AlexFBP** [comment]
Por limitaciones de [ng2-smart-table](https://akveo.github.io/ng2-smart-table/) al no permitir más de las acciones "agregar/ver/borrar", se cambiaron los íconos y funcionalidad, así:

- La acción de "ver" un acta ahora se ejecuta al hacer click en la fila a consultar.
- Entonces, donde estaba la acción de "ver" ahora se usa para Anular un acta
- La acción de "editar" sigue siendo la misma

![image](https://user-images.githubusercontent.com/6588872/102170541-9dcb5e00-3e62-11eb-8d69-914353d6e94e.png)

También se agregaron descripciones alternativas a los botones:

![image](https://user-images.githubusercontent.com/6588872/102170617-c6535800-3e62-11eb-90b4-5edf667dace6.png)

Para el tercer ítem, se piensa construir la tabla mostrando el botón de anular a los roles especificados, de tal manera que a los demás roles no les aparecerá este botón. Y el diálogo se usará como advertencia/confirmación de la anulación de la acta, por ejemplo, al dar click sobre la Acta 17:

![image](https://user-images.githubusercontent.com/6588872/102170770-17fbe280-3e63-11eb-913a-da8581723809.png)

**Comment by AlexFBP** [comment]
Respecto al segundo ítem, a los comentarios anteriores y como comprobación del #354 ; probando con alguien que tenga únicamente rol de secretaria:

![image](https://user-images.githubusercontent.com/6588872/102235187-114f8880-3ec0-11eb-84bf-f3e6c211f580.png)

Y con alguien que tenga únicamente rol de revisor:

![image](https://user-images.githubusercontent.com/6588872/102235090-f7ae4100-3ebf-11eb-9429-885f74ee90e6.png)
