### ISSUE TITLE
Crear excel con la información ingresada por el proveedor 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#345]
Se debe crear funcionalidad que permita descargar en formato excel la informacion de los elementos subidos por el proveedor, la issue debe cumplir con los siguientes requerimientos:

- [x] Se debe generar un archivo excel que se pueda descargar para poder  ingresar la información de la clase localmente

- [x] El archivo excel debe tener una columna para incluir el codigo de la clase de forma manual de forma local

**Comment by CristianDavidSanchez** [comment]
se aborda el issue

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
