### ISSUE TITLE
Ajuste para que el roll de SECRETARIA_ALMACEN solo pueda registrar el acta  o modificar un acta en estado de registrada 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#347]
se debe ajustar que en el componente de consultar acta cuando se ingrese con el roll de SECRETARIA_ALMACEN solo se permita observar las actas en estado registrada y pueda modificar alguna acta ya creada que no este anulada, la issue debe cumplir con los siguientes requerimientos:

- [x] Se debe bloquear el componente de consulta acta de recibido para que solo se puedan observar las actas en estado de registrada 

- [x] Se debe permitir editar a este roll cualquier acta que se encuentre estado registrada

**Comment by AlexFBP** [comment]
Se empieza a abordar el *Issue*. Posiblemente ya se avanzó con lo realizado en el #331

**Comment by AlexFBP** [comment]
Fijando el rol a secretaria...

![image](https://user-images.githubusercontent.com/6588872/102133126-9f753180-3e22-11eb-9b0c-748aec286360.png)

... ahora salen únicamente las actas en estado registrado:

![image](https://user-images.githubusercontent.com/6588872/102134136-22e35280-3e24-11eb-9dbf-4b65b017fd04.png)

**Comment by AlexFBP** [comment]
El segundo ítem se desarrolló con #331
