### ISSUE TITLE
Ajustar API del micro servicio entradas

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#35]
Realizar los ajustes al API de micro servicio de entradas con los ajustes realizados al modelo de datos.

**Comment by Miavega** [comment]
En el siguiente [enlace](https://github.com/udistrital/entradas_crud/tree/dev) se encuentra el repositorio que contiene el API de entradas con sus respectivos ajustes.

**Comment by mafeave** [comment]
De la revisión realizada al API, se debe ajustar lo siguiente:
- Definir las variables de configuración en el archivo config.js, tomar de ejemplo: [config](https://github.com/udistrital/produccion_academica_crud/blob/produccion_academica/conf/app.conf), ajustar la ruta de conexión en el main.
- Ajustar las rutas de los modelos en los controladores, la ruta debe apuntar al nombre del repositorio: "github.com/udistrital/entradas_crud/models"
- Ajustar la ruta del directorio de los controladores en router.go, la ruta debe apuntar al nombre del repositorio: "github.com/udistrital/entradas_crud/controllers"
- Ajustar la ruta de los routers en main.go, la ruta debe apuntar al nombre del repositorio: "github.com/udistrital/entradas_crud/routers"
- Ajustar nombre del bin generado en el .gitignore
- Generar de nuevo la documentación del API para actualizar las rutas generadas en swagger

**Comment by mafeave** [comment]
Ajustes realizados en el repositorio, se hace merge de los ajustes https://github.com/udistrital/entradas_crud/commit/e60803b2bb130e3ebeb7b2be0ccc477a4f6c151b
