### ISSUE TITLE
Inclusión de los nuevos tipos de entradas al momento de asignar una cuenta contable 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#360]
Teniendo en cuenta la historia de usuario de [HU - 5 A 15 Entradas - Diferentes Conceptos_V3](https://docs.google.com/spreadsheets/d/18728OtHRvwplGfeSqaoNa57NbyksAWfG/edit#gid=1265250870), se debe ajustar el componente de asignación de cuentas contables con los nuevos tipos de entrada definidos, se deben agregar en el componente para el ingreso de la cuenta contable debito y crédito, este ingreso  puede ser opcional ya que las no todas las clases tiene todos los tipos de entrada, se debe también ajustar la funcionalidad de registro de las nuevas cuentas contables (tr y funciones a nivel de backend), la issue debe cumplir con los siguientes requerimientos:

- [x] Se debe incluir los nuevos tipos de entrada en el componente definidos en la historia de usuario 

- [x]  El ingreso de las cuentas contables no es obligatoria para todos los tipos de entrada

- [x] Agregar migracion en api de tipos de entrada 

- [x] Realizar el ajuste de las funcionalidad de la tr o a nivel de backend para el registro de las nuevos tipos de entrada

**Comment by CristianDavidSanchez** [comment]
Ya se generan los nuevos campos tanto en back como en front, pero  logicamente los puts no van a funcionar porque nunca se han creado cuentas con esa denominación
