### ISSUE TITLE
Comprobar y ajustar los permisos de roles para el proceso de acta de recibido 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#363]
Se debe comprobar los permisos que ya están establecidos y realizar los ajustes correspondientes a los distintos roles, tener en cuenta la información contemplada en el [acta](https://docs.google.com/document/d/1uqvpgyIKVJt2BsCTKT-hqFY4POeDZyZb6eCgf0j1gdo/edit?ts=5fd5407e)  realizada con el usuario, los permisos según el rol son los siguiente:

- [x] SECRETARIA_ALMACEN: **Crear**, observar y editar un acta de recibido en estado de registrada y enviar acta en estado registrada al proveedor 
- [x] PROVEEDOR: Observar y carga de elementos al acta de recibido previamente asignada por el rol de SECRETARIA_ALMACEN y en estado En Elaboración, y el registro de los elementos en el sistema, no puede modificar el resto de data del acta 
- [x] CONTRATISTA: Observar, editar un acta que se encuentre en estado de En Elaboración y En modificación, enviar un acta a estado En Verificación, esas actas deben estar asignados al contratista, este proceso se realiza por primera vez por el rol  SECRETARIA_ALMACEN
- [x] REVISOR: Observar, editar, **anular**, **crear** un acta en cualquier estado excluyendo el estado Asociada a una entrada, este roll junto al ADMIN_ARKA  podrán verificar una acta para pasar el acta a estado de Aceptada, también podrá modificar la asignación del contratista en cualquier estado  excluyendo el estado Asociada a una entrada, podrá ingresar un acta para las entradas de donación o sobrantes 
- [x] ADMIN_ARKA:   Este usuario podrá  realizar cualquier funcionalidad dentro del modulo de acta de recibido 

Además de ajustar estos permisos debe realizar el ajuste para que el proveedor solo pueda observar las actas que tiene en estado en elaboración y asignado, también ajustar que el rol de contratista solo pueda editar y observar las actas que esten asignadas para el, la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustes los permisos a cada uno de los roles definidos 

- [x]   Ajuste de las actas que pueden editar/observar los roles de contratista y proveedor

**Comment by AlexFBP** [comment]
Se empieza a abordar el *Issue*

**Comment by AlexFBP** [comment]
En `EdicionActaRecibidoComponent`, hay dos secciones principales (acta y elementos). Los permisos de estas secciones están en función del rol y de la etapa en que se encuentre la acta, según:

| Etapa, Accion(1) | Acta (2) | Elementos (3) |
|   ---     |                     ----                           |       ----       |
| Registrada, Editar | Admin, Secretaria | Admin |
| Registrada, Ver | Contratista | --/-- |
| Elab/Modif, Editar | Admin | Admin, Contratista |
| Elab/Modif, Ver | Secretaria, Contratista | Secretaria |
| En Verificacion, Editar | ?? | ?? |
| En Verificacion, Ver | ?? | ?? |
| Aceptada, Editar | Admin,Revisor | Admin,Revisor |
| Aceptada, Ver | --/-- | --/-- |
| Asociada a Entrada, Editar | ?? | ?? |
| Asociada a Entrada, Ver | ?? | ?? |
| Anulada, Editar | ?? | ?? |
| Anulada, Ver | ?? | ?? |

(1) Si se tiene permiso de Editar, también se cuenta con el de Ver
(2) Datos básicos y soportes
(3) Asociados a cada soporte del Acta

*Nota: Esta tabla se irá actualizando conforme se avance en el desarrollo*

**Comment by AlexFBP** [comment]
Al guardarse un acta en estado En Elaboración, se pasa automáticamente a En Modificación (actualmente). Teniendo en cuenta los permisos indicados para el proveedor y el contratista, esto estaría bien?

De acuerdo a lo inicialmente requerido y al comportamiento actual, si un contratista edita (los elementos de) un acta, el proveedor no podrá volver a hacerlo...

**Comment by AlexFBP** [comment]
Los cambios de estado obedecen al siguiente diagrama:

![image](https://user-images.githubusercontent.com/6588872/102822010-250a5b80-43a6-11eb-963b-a31f08676c2e.png)

## Estados

- S1: Registrada
- S2: En Elaboracion
- S3: En Modificacion
- S4: En Validacion
- S5: Aceptada
- S6: Asociada a Elemento
- S7: Anulada

## Eventos

| Evento | Descripcion| Rol |
|    ---      | ---               |  --- |
| E0 | Registro Ordinario de Acta  | Secretaria |
| E1 | Envío a Proveedor | Secretaria |
| E2 | Guardar | Proveedor, Contratista |
| E3 | Enviar a Validacion | Contratista |
| E4 | Rechazar Acta | Revisor, Admin |
| E5 | Aprobar Acta | Revisor, Admin |
| E6 | Asociar a Elemento | ??? |
| E7 | Registro Extraordinario de Acta | Revisor, Admin |
| E8 | Anular Acta | Revisor, Admin |

**Comment by AlexFBP** [comment]
La "Consulta de Actas" ([`ConsultaActaRecibidoComponent`](https://github.com/udistrital/arka_cliente/tree/dev/src/app/pages/acta-recibido/consulta-acta-recibido)) carga la lista de actas del [`ARKA_SERVICE` (mid)](https://github.com/udistrital/arka_mid).

Para filtrar las actas que se van a mostrar a proveedores y contratistas, se requiere modificar `ARKA_SERVICE/acta_recibido/get_all_actas/` de tal manera que retorne:
```diff
 [
   {
     "Activo": true,
     "Estado": "Asociada a Entrada",
     "FechaCreacion": "2019-09-27T03:11:33.893Z",
     "FechaModificacion": "2019-09-27T03:17:46.797Z",
     "FechaVistoBueno": "2019-09-27T00:00:00Z",
     "Id": 2,
     "Observaciones": "Registro",
-    "RevisorId": "Axa Colpatria Seguros SA",
+    "Revisor": "Axa Colpatria Seguros SA",
+    "ProveedorId": 3843534,
+    "ContratistaId": 345739,
     "UbicacionId": "Ubicacion No Especificada"
   },
   ...
 ]
```

La idea sería comparar las propiedades `ProveedorId` y `ContratistaId` contra `getPersonaId()` de [`UserService`](https://github.com/udistrital/arka_cliente/blob/dev/src/app/%40core/data/users.service.ts)

Es posible que esto tenga algo que ver con los Issues udistrital/acta_recibido_crud#23 y #340
