### ISSUE TITLE
Ajustar plantillas en excel para el provedor y para la asignación de clases 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#367]
Se debe ajustar las plantillas que podrán descargar el proveedor con los campo que son necesario: 

Nombre | Marca | Serie | Cantidad | Unidad de Medida | Valor Unitario | Subtotal | Descuento | Tipo IVA | Valor IVA | Valor Total
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

configurar que cuando se este con el roll de proveedor se descargue la plantilla para el proveedor antes ajustada, tambien se debe ajustar la plantilla para los contratistas con la siguiente información:

Búsqueda de Clase | Código clase | Nombre Clase| Tipo de Bien| Nombre | Marca | Serie | Cantidad | Unidad de Medida | Valor Unitario | Subtotal | Descuento | Tipo IVA | Valor IVA | Valor Total
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --|--

A partir de funciones de Excel y macros los campos código clase, nombre clase y tipo de bien se deben llenar automáticamente con un filter por nombre o código en el campo Búsqueda de Clase, configurar que cuando se este con el roll de contratista, revisor y admin_arka se descargue la plantilla para el antes ajustada o cuando se descargue la información del proveedor, la issue debe cumplir con los siguientes requerimientos:

- [x]  Ajustar la plantilla para el proveedor 

- [x] Ajustar la descarga del la plantilla correcta para cuando se sea el roll del proveedor 

- [x]  Ajustar la plantilla para el contratista, revisor y admin_arka

- [x] Ajustar la descarga del la plantilla correcta para cuando se sea el roll del contratista, revisor y admin_arka

**Comment by CristianDavidSanchez** [comment]
La plantilla ahora es única y no posee nada relacionado con la clase.
Nombre | Marca | Serie | Cantidad | Unidad de Medida | Valor Unitario | Subtotal | Descuento | Tipo IVA | Valor IVA | Valor Total
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by fabianbarreto02** [comment]
se debe corregir la plantilla con los ajustes requeridos

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
