### ISSUE TITLE
Ajustar API de entradas con configuración para despliegue en entorno local OAS

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#37]
Realizar la configuración del entorno dockerizado para el despliegue del API de entradas en entorno local

**Comment by Miavega** [comment]
En el repositorio [entradas_crud](https://github.com/udistrital/entradas_crud/tree/dev) se encuentran los ajustes realizados al API para el despliegue en entorno local.

**Comment by mafeave** [comment]
API revisada y desplegada en el entorno local OAS - 254
