### ISSUE TITLE
Incluir la función en la tabla de elementos para detectar shift + click para seleccionar varios elementos, desactivar la función de incluir un soporte nuevo en un acta de recibido

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#380]
Se debe desarrollar la función (similar a un excel ) para poder realizar un select multiple con la combinación de shift + click para seleccionar varios elementos en el componente de la tabla de los elementos, también como se hablo en la mesa de trabajo se debe desactivar la funcionalidad que permite crear varios soporte en una acta de recibido, se debe desactivar en todos los componentes, creación, edición y visualizar, la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar la función select multiple con la combinación de shift + click para seleccionar varios elementos en el componente de la tabla de los elementos
- [x] Desactivar la funcionalidad que permite crear varios soporte en una acta de recibido, se debe desactivar en todos los componentes, creación, edición y visualizar

**Comment by AlexFBP** [comment]
Se empieza a abordar el *Issue*

**Comment by AlexFBP** [comment]
El checkbox selecciona entre la última casilla antes de presionar shift, y la última casilla antes de soltar shift

**Comment by AlexFBP** [comment]
Para el segundo ítem, habían avances relacionados en los siguientes commit:

- 9d774c4d (#379) - Registro de Acta Especial no tiene soportes ni permite cargarlos
- f206b8e8 (#363) - Se limitan los campos que pueden editar los roles (y agregar/quitar soportes)
