### ISSUE TITLE
Realizar funcionalidad para notificar al usuario cuando se vaya a vencer la sesión de autenticación

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#381]
Se debe desarrollar una funcionalidad que capture el tiempo de sesión destinado por el servicio de autenticación, llevar un timmer para que al faltar un minuto para cerrar sesión notifique con una alerta al usuario y pueda almacenar la información del acta, la issue debe cumplir con los siguientes requerimiento:

- [x] Se debe capturar el tiempo destinado por el servicio de autenticación para la sesión del usuario 
- [x] Iniciar un timer con el tiempo destinado
- [x] Cuando falte un minuto para cerrar sesión se debe notificar con una alerta al usuario que pronto se va cerrar sesión

**Comment by AlexFBP** [comment]
Se empieza a abordar el *Issue*

**Comment by AlexFBP** [comment]
Sin modificar nada, se identifica que en el local storage está disponible el "timestamp", la fecha de vencimiento del token:

![image](https://user-images.githubusercontent.com/6588872/103319347-8c0bbe00-49ff-11eb-90d9-785cf837e57c.png)

**Comment by AlexFBP** [comment]
Se configuraron las siguientes notificaciones:

- Un toaster al iniciar sesión, indicando el tiempo restante en minutos:

  ![image](https://user-images.githubusercontent.com/6588872/103331237-ea9e5f80-4a32-11eb-83ed-992879f1e42d.png)

- Una alerta faltando 1 minuto. El tiempo es ajustable por código en una constante, lo cual se realizó a efectos de sacar este pantallazo (se ajustó a 7 minutos):

  ![image](https://user-images.githubusercontent.com/6588872/103331341-7fa15880-4a33-11eb-80ff-50b109940781.png)

**Comment by AlexFBP** [comment]
El estilo de colores de Arka, actualmente no permite apreciar claramente que se trata de una notificación de carácter informativo, al ser rojo se entiende que es un error la notificación al comienzo del tiempo restante.

Se cambia a un toaster básico:

![image](https://user-images.githubusercontent.com/6588872/103377699-1ca0d780-4aae-11eb-9682-6b1414a6f151.png)
