### ISSUE TITLE
Simular y ajustar los permisos para el contratista y el proveedor con el api de tercero 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#389]
Se debe simular y ajustar que solo se puedan observar las actas que tienen registradas tanto proveedor como el contratista, para esto se debe simular en el api de tercero los id para que al hacer get de la persona concuerden con el id del api de proveedores, de la misma forma con el contratista, se debe tener en cuenta los usuarios de pruebas para el sistema, después de esto se debe ajustar que con el servicio de get persona se puede habilitar las actas registradas a nombre de cada roll, la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar los ids tanto en proveedores como en persona para que concuerden y poder simular el proceso (quemar Id en el api de terceros)
- [x] Ajustar el cliente y los permiso para observar las actas con los usuarios de contratistas y proveedores

**Comment by AlexFBP** [comment]
Se empieza a abordar el *Issue*

Se observa que esta labor se facilitaría si la lógica de filtrado de actas por rol (#363) , se mueve del cliente al [MID](https://github.com/udistrital/arka_mid), y desde el MID (de Arka) se consume el [MID de Autenticación](https://github.com/udistrital/autenticacion_mid/tree/dev)

[Probando el endpoint token/userRol del MID de Autenticación](https://autenticacion.portaloas.udistrital.edu.co/store/apis/info?name=autenticacion_mid&version=v1&provider=admin&tenant=carbon.super#!/token/TokenController_GetRol), se observó que se devuelven los roles y el correo, si se pasa el usuario de WSO2:

![image](https://user-images.githubusercontent.com/6588872/103841295-38355080-5061-11eb-811b-3e0c6392288c.png)

**Comment by AlexFBP** [comment]
Se agrega al MID de actas la opción de aceptar un usuario WSO2 para obtener (internamente) los roles del usuario y así, migrar la lógica de filtrado de actas al MID. El swagger también se actualizó para reflejar los nuevos parámetros...:

![image](https://user-images.githubusercontent.com/6588872/104236170-14d52180-5424-11eb-8bb3-5942ff1f2277.png)

**Comment by AlexFBP** [comment]
Para el primer ítem, los IDs como proveedor y contratista se resuelven desde el MID: Únicamente hay que indicarle al MID el usuario WSO2 y el MID se encarga de averiguar, inicialmente con el MID API de Autenticación, y luego con la API de Proveedores

Para el segundo ítem, se hicieron pruebas "quemando" un usuario con actas asignadas:
![image](https://user-images.githubusercontent.com/6588872/104509978-79c18080-55b8-11eb-9bcf-a010aa1fad25.png)

Se agregaron helpers adicionales para consultar por estado o por usuario:
![image](https://user-images.githubusercontent.com/6588872/104510046-965db880-55b8-11eb-8082-02a4a9ceafbd.png)

Y al dar click en "Consulta de Actas" aparece:
![image](https://user-images.githubusercontent.com/6588872/104510106-a70e2e80-55b8-11eb-9912-69adf91286c8.png)

Con el inspector, en Network:
![image](https://user-images.githubusercontent.com/6588872/104510170-c311d000-55b8-11eb-9730-bbc767128d42.png)

**Comment by AlexFBP** [comment]
Con un usuario con rol "SECRETARIA" y ya sin quemar el usuario:
![image](https://user-images.githubusercontent.com/6588872/104510909-e721e100-55b9-11eb-93c5-0537d088eaf8.png)
