### ISSUE TITLE
Realizar la documentación de la entradas desarrolladas en el sistema actual contra la historia de usuario 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#396]
Se debe realizar la documentación del modulo de entradas desarrollado y corroborar que lo que se encuentra documentado en la [historia de usuario ](https://docs.google.com/spreadsheets/d/18728OtHRvwplGfeSqaoNa57NbyksAWfG/edit#gid=1265250870), se debe realizar una documentación donde se relacione los que se cumple con las historias y los items que hacen falta, también en los casos de los select documentar que servicios se consumen, la issue debe cumplir con los siguientes requerimientos:

- [ ] Realizar la documentación del modulo de entradas desarrollado y corroborar con la  [historia de usuario ](https://docs.google.com/spreadsheets/d/18728OtHRvwplGfeSqaoNa57NbyksAWfG/edit#gid=1265250870)
- [ ] Documentar que items se cumplen en su totalidad o parcial segun la historia de usuario 
- [ ] Documentar que servicios se consumen para la carga de los select en el modulo

**Comment by juandavidvelezaalvarez** [comment]
Ya hice el documento, quedó en el drive en donde me dijeron que lo pusiera.
https://docs.google.com/document/d/1zc-R3CTzp9tOYGOosB8rLbyvNuSd3bshrnU1P6oWbTs/edit

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
