### ISSUE TITLE
Revisar y controlar los errores que se pueden presentar por la plantilla 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#397]
Se debe corregir y controlar los errores que se puedan presentar cuando se suba algún error de sintaxis o formato en la plantilla de excel, la issue debe cumplir con los siguientes requerimientos:

- [x] Revisar y controlar los errores de  sintaxis o formato en la plantilla de excel al ser cargada por el usuario

**Comment by CristianDavidSanchez** [comment]
Issue abordado a las 12m del presente día

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
