### ISSUE TITLE
Revisión del bug en el modulo de entrada que no carga los elementos cuando se va a realizar una entrada 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#399]
Se debe revisar y corregir el bug en el modulo de entrada al realizar el proceso de una entrada algunas actas no tiene  elementos para relacionar, se debe revisar si es que el acta no tenia elementos asociados y si es así se debe controlar el error para que ninguna acta pase a estado aceptada sin elementos, la issue debe cumplir con los siguientes requerimientos:

- [x] Revisar cual es el bug al momento de generar una entrada que no carga los elementos asociados a esa acta en estado de aceptada 
- [x] ajustar que las actas que se encuentre en esatdo de aceptadas si tengan elementos asociados

**Comment by fabianbarreto02** [comment]
no se encuentra necesario la issue

**Comment by ludwinggsanchez** [comment]
Los elementos no se cargan cuando el acta no tiene un proveedor asociado (actas especiales). La carga de elementos se hace a través del mid en la función GetElementos del helper de acta de recibido.

**Comment by ludwinggsanchez** [comment]
El mid se actualiza en el PD udistrital/arka_mid#59.
