### ISSUE TITLE
Generar la arquitectura de la información de ARKA

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#4]
Diseñar el modelo de la arquitectura de la información para ARKA en Archimate.

**Comment by Miavega** [comment]
En el siguiente [enlace](url) se encuentra la imagen PNG y el fuente de archimate con la arquitectura de la información para el modelo actual de ARKA.

**Comment by mafeave** [comment]
Se revisa modelo de arquitectura creado, junto al archivo en archi.
