### ISSUE TITLE
Ajuste de modelo de datos de movimientos

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#41]
Ajustar el modelo de datos del módulo de movimientos incluyendo bajas y traslados.

**Comment by Miavega** [comment]
En el siguente [enlace](https://drive.google.com/drive/folders/160r8aHnzSnJBAQJTKpnMRJIZ7Bxb8fNz) se encuentra la imagen png y el archivo en PgModeler correspondiente al modelo de datos de movimientos. El archivo tiene el nombre de **_movimientos.png_**

**Comment by ManuelMurillo** [comment]
se remite a issue #42

**Comment by mafeave** [comment]
Modelo verificado e integrado al proceso de salidas mediante #42
