### ISSUE TITLE
Ajustar el modulo de bodega de consumo del sistema arka || de lo que se encuentre desarrollado 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#410]
Se debe realizar el ajuste del modulo de bodega de consumo que se encuentra desarrollado en la actualidad del sistema arka ||, se debe ajustar el sub modulo de consulta de kardex, teniendo en cuenta la Reunión con Manuel, revisar el sub modulo de solicitar elementos, consultar solicitudes, responder solicitudes y asignación de kardex, la issue debe cumplir con los siguientes requerimientos:

- [x] Ajuste y revisión del sub modulo  consulta de kardex
- [x] Ajuste y revisión del sub modulo solicitar elementos
- [x] Ajuste y revisión del sub modulo consultar solicitudes
- [x] Ajuste y revisión del sub modulo responder solicitudes 
- [x] Ajuste y revisión del sub modulo  asignación de kardex

**Comment by AlexFBP** [comment]
De Bodega consumo, solo queda pendiente "Responder Solicitudes"
Especificamente, el controlador
`/bodega_consumo/solicitud/{id}`
del MID está funcionando mal:
![image](https://user-images.githubusercontent.com/6588872/104671631-23ce0500-56ac-11eb-81d5-53ae708f770f.png)

**Comment by AlexFBP** [comment]
El endpoint/controlador `/bodega_consumo/solicitud/{id}` del [MID](https://github.com/udistrital/arka_mid), actualmente está fallando cuando el `{id}` especificado NO existe al consultar el endpoint `/movimiento?query=Id:...` del [CRUD de Movimientos Arka](https://github.com/udistrital/movimientos_arka_crud).

Se corrigió que cuando esto sea así, se retorne junto al error, un código de estado HTTP 404

Adicionalmente, este controlador del MID consume los siguientes endpoints:
- [Terceros](https://github.com/udistrital/terceros_crud) / `datos_identificacion/?query=TerceroId__Id:xxx`
- [Oikos](https://github.com/udistrital/oikos_api) / `asignacion_espacio_fisico_dependencia?query=Id:xxx`
  - [Oikos](https://github.com/udistrital/oikos_api) / `espacio_fisico?query=CodigoAbreviacion:xxx`
  - [Catalogo de Elementos](https://github.com/udistrital/catalogo_elementos_crud) / `elemento?query=Id:xxx`
    - [Movimientos Arka](https://github.com/udistrital/movimientos_arka_crud) / `elementos_movimiento?query=ElementoCatalogoId:xxx,Activo:true&limit=1&sortby=FechaCreacion&order=desc&fields=ElementoCatalogoId,Id,SaldoCantidad,SaldoValor`
