### ISSUE TITLE
Realizar el ajuste del modulo de entradas para los 6 tipos de entradas ya definidos en el sistema desarrollado 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#411]
Se debe ajustar el modulo de entradas para los 6 tipos de entradas ya definidos en el desarrollo del sistema arka 2, se debe revisar que el flujo del proceso para cada uno de los tipos d entrada, revisar el registro y la consulta de las entradas registras, tambien revisar la generación de los reportes de las entradas, la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustas el registro de una entrada para los 6 tipos de entradas definidas
- [x] Ajustar los reportes de cada entrada 
- [x] Revisar que el flujo de registro de cada entrada ente funcional
- [x] Ajustar y revisar la consulta del registro de las entradas

**Comment by ludwinggsanchez** [comment]
La carga de elementos de actas especiales se arregla ajustando la consulta en el mid. udistrital/arka_mid#64

**Comment by fabianbarreto02** [comment]
se da por finaliza la issue
