### ISSUE TITLE
Ajuste Modelo de Datos Salidas

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#42]
Se debe crear y ajustar el modelo de datos de salidas teniendo en cuenta los siguientes aspectos:

- [x] tener en cuenta traslados 

- [x] Tener en cuenta bajas 

- [x] historico de movimientos

**Comment by ManuelMurillo** [comment]
en el siguiente enlace se encuentra el modelo de datos de movimientos en el cual se relacionan salidas, traslados y bajas
![movimientos_v2](https://user-images.githubusercontent.com/29108085/62839922-b4065000-bc57-11e9-8ff5-1e4ecaa6934d.png)

https://drive.google.com/open?id=12X93u73W0BibEUzXVmX7VoTuiy0dMzIP

**Comment by mafeave** [comment]
Revisado el modelo, hacer los siguientes ajustes:
- Agregar campos de fecha_creacion, fecha_modificacion y activo en las tablas de inventario y relacion_movimiento_inventario
- Los campos de la restricción unique de la tabla inventario deben ser: elemento_id, funcionario_id y ubicacion_id

**Comment by ManuelMurillo** [comment]
![image](https://user-images.githubusercontent.com/29108085/63035431-c31c1680-be80-11e9-8132-09a5d4260009.png)

Modificacion del modelo

https://drive.google.com/open?id=12X93u73W0BibEUzXVmX7VoTuiy0dMzIP

**Comment by mafeave** [comment]
Se debe ajustar el modelo de datos propuesto para la gestión de movimientos, contemplando el modelo de movimientos que se propuso en Kronos, #49
