### ISSUE TITLE
Ajustar tabla de visualización de los elemento cuando el revisor aprueba o no aprueba el acta de recibido 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#426]
Se debe ajustar la carga de la tabla que visualiza los elementos en el acta de recibido pues esta desactualizada con los ajuste realizados a la jerarquía del árbol de elementos, esta tabla se ve  observa al momento que una acta se envía a revisión y el revisor realiza el proceso de revisión del acta, la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar la tabla y la muestra de datos en el componente necesario

**Comment by CristianDavidSanchez** [comment]
Se aborda el issue

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
