### ISSUE TITLE
En la creación del acta especial se debe incluir que se agregue un soporte documento 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#427]
Se debe agregar un soporte al momento de agregar un acta de recibido especial para soportar la creación del acta, se debe configurar el componente para cargar el soporte y poder consultar el soporte después de cargar el documento, la issue debe cumplir con el siguiente requerimiento:

- [x] Ajustar el componente  de creación de acta especial para que se pueda agregar un soporte al momento de crear el acta
- [x] Ajusar el componente para que se pueda visualizar el soporte en el acta especial ya creada

**Comment by ludwinggsanchez** [comment]
#439

**Comment by fabianbarreto02** [comment]
se da por finalizada la issue
