### ISSUE TITLE
Desarrollo Componente Consulta Acta de Recibido

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#43]
desarrollo del componente de consulta para la vista de las actas de recibido teniendo en cuenta:

- [x] poder ver los datos del acta con el icono ver

- [ ] trabajar con el componente de registro/edicion 

- [ ] asociar al componente de verificacion 

- [x] establecer datos de prueba con API CRUD desplegada 

- [x] no usar url + parametros

**Comment by ManuelMurillo** [comment]
se crea la primera tabla con datos locales en el siguiente commit 
8dfc1bdfba5332ba93475214c06fc9931f32556e

**Comment by ManuelMurillo** [comment]
![image](https://user-images.githubusercontent.com/29108085/62842153-93e58980-bc75-11e9-92d5-dbe2187a76f2.png)

**Comment by mafeave** [comment]
Revisar consumo de servicio de consulta de acta de recibido

**Comment by mafeave** [comment]
Se verifica agregación del consumo del API, teniendo en cuenta el estado activo del acta.
