### ISSUE TITLE
Creación del formulario para el tipo de entrada nuevo aprovechamiento en el modulo de entrada 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#432]
Se debe desarrollar el formulario para el nuevo tipo de entrada de aprovechamiento siguiendo la [historia de usuario](https://docs.google.com/spreadsheets/d/18728OtHRvwplGfeSqaoNa57NbyksAWfG/edit?dls=true#gid=1265250870), tener en cuenta que la mayoría de las Variable / fórmula ya se encuentran definida en los formularios de los tipos de entradas ya desarrollados, seguir el mismo flujo que tiene los tipos de entradas ya implementados, la issue debe cumplir con los siguientes requerimientos:

- [x]   Desarrollar el formulario para el nuevo tipo de entrada siguiendo la historia de usuario entregada
- [x] Ajustar la carga de los select o los inputs que se definan en la historia de usuario

**Comment by AlexFBP** [comment]
Despues de seleccionar el acta 47

Cabecera:
![image](https://user-images.githubusercontent.com/6588872/105884545-13842700-5fd6-11eb-8685-cb9cf6e833a2.png)

Pasos:
![image](https://user-images.githubusercontent.com/6588872/105884926-783f8180-5fd6-11eb-8ebe-249d9588e13c.png)
![image](https://user-images.githubusercontent.com/6588872/105884952-81c8e980-5fd6-11eb-8ab7-9d92493bd20e.png)
![image](https://user-images.githubusercontent.com/6588872/105884978-88576100-5fd6-11eb-81bc-81fd8cab294b.png)
![image](https://user-images.githubusercontent.com/6588872/105885030-97d6aa00-5fd6-11eb-917a-79960c3591f2.png)
![image](https://user-images.githubusercontent.com/6588872/105885050-9f964e80-5fd6-11eb-950c-f0ff9cbde55d.png)

Despues de presionar "Registrar Entrada" se enviaría lo siguiente en un POST al [MID](https://github.com/udistrital/arka_mid) `/entrada/`
![image](https://user-images.githubusercontent.com/6588872/105885296-f7cd5080-5fd6-11eb-9f2b-bb2dd7610573.png)

**Comment by AlexFBP** [comment]
Se requiere una aclaración/revisión adicional de la HU (9?) asociada a este Issue

**Comment by AlexFBP** [comment]
Se cambian los nombres de los pasos
![image](https://user-images.githubusercontent.com/6588872/106226655-af1fbe00-61b5-11eb-834b-d441f5ee8275.png)

**Comment by AlexFBP** [comment]
Se traen los datos de proveedores
![image](https://user-images.githubusercontent.com/6588872/106240447-4b57be00-61d2-11eb-8dc4-d97b8644ddb0.png)

**Comment by AlexFBP** [comment]
De acuerdo a una aclaración de @mcrubianot , los supervisores pueden ser funcionarios de planta.
De la mano con lo mencionado en el sprint, es necesario considerar el siguiente procedimiento:
1. De la [API de Parámetros](https://github.com/udistrital/parametros_crud), buscar el ID asociado a funcionario de planta (o proveedor, o contratista, según se requiera en otros *Issues*...)
2. Para obtener los supervisores, se usa el ID anterior para filtrar en la API de terceros, tabla "vinculacion", en el campo "tipo_vinculacion_id"
3. De la tabla anterior, también se puede obtener la dependencia

Con todo lo anterior, solo queda por confirmar si la "sede" (último campo pendiente para completar la HU) se podría averiguar de Oikos a partir de la dependencia, o si es independiente a la dependencia y habría que buscarla de otra manera...

**Comment by AlexFBP** [comment]
Para poder hacer pruebas, se hicieron los siguientes POST con los campos mínimos posibles

A [Terceros](https://github.com/udistrital/terceros_crud/) /vinculacion:
- ```json
  {
      "Activo": true,
      "DependenciaId": 500,
      "TerceroPrincipalId": {
        "Id": 94
      },
      "TipoVinculacionId": 292
  }
  ```
- ```json
  {
      "Activo": true,
      "DependenciaId": 565,
      "TerceroPrincipalId": {
        "Id": 9759
      },
      "TipoVinculacionId": 300
  }
  ```

A [Oikos](https://github.com/udistrital/oikos_api/) /asignacion_espacio_fisico_dependencia:
- ```json
  {
    "EspacioFisicoId": {
      "Id": 1092
    },
    "DependenciaId": {
      "Id": 500
    },
    "Activo": true,
    "FechaInicio": "2019-11-05T22:20:38Z",
    "FechaCreacion": "2019-11-26T23:42:12.735766Z",
    "FechaModificacion": "2019-11-26T23:42:12.735766Z"
  }
  ```
- ```json
  {
    "EspacioFisicoId": {
      "Id": 1084
    },
    "DependenciaId": {
      "Id": 565
    },
    "Activo": true,
    "FechaInicio": "2019-11-05T22:20:38Z",
    "FechaCreacion": "2019-11-26T23:42:12.735766Z",
    "FechaModificacion": "2019-11-26T23:42:12.735766Z"
  }
  ```
