### ISSUE TITLE
Desarrollo Componente Registro Acta de Recibido

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#44]
Desarrollo del componente de registro/edicion del acta de recibido teniendo en cuenta:

- [ ] comunicacion con API CRUD desplegada 

- [x] no usar url + parametros 

- [ ] creacion de tablas y formularios

**Comment by mafeave** [comment]
Se verifican los ajustes en el cliente para el registro del acta y el registro de elementos asociados a varias facturas.

El registro del acta de recibido con los soportes y los elementos se debe hacer mediante una transacción, la cual se está realizando desde el issue: https://github.com/udistrital/acta_recibido_crud/issues/5, por lo cual se da por finalizada esta tarea.

**Comment by mafeave** [comment]
Quedan las siguientes observaciones del registro de acta de recibido:
- Falta ajustar el desarrollo para contemplar el descuento general a la factura, esta actividad se realizará en el issue #65 
- La unidad de medida se debe cargar de un servicio de Agora, revisar con el Equipo del Core si ellos lo incluirán en el nuevo Core.
- El IVA se debe consultar del API de parametros_gobierno del Core
- Queda pendiente referenciar el subgrupo asociado a los elementos, el cual se obtendría del API de catálogo de elementos.
- Por ahora no se están cargando los documentos asociados a las actas de recibido (facturas), ya que el Equipo del Core está ajustando la forma de acceder a Nuxeo y no se tiene definido el API para la gestión de documentos.
- El registro masivo de elementos se realizará a través de los issues #67 y #68 
- Pendiente la asignación de responsable del Acta, la cual depende del API de terceros (personas) que debe realizar el Core
- Revisar si registrar el proveedor de la factura
- Agregar modal indicando el registro del acta de recibido #66
