### ISSUE TITLE
Revisar servicios de administrativa

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#45]
Revisar los servicios de administrativa que pueden ser utilizados para ARKA II.

**Comment by Miavega** [comment]
En el siguiente [enlace](https://docs.google.com/document/d/1xqG5WisDV3J87TpjPWYqosD7mp-v6ilw4PRKXlTkEYw/edit) se encuentra un documento con los servicios que sirven para ARKA II. Del mismo modo se dejan unas observaciones para su revisión.

**Comment by mafeave** [comment]
Del análisis realizado y de acuerdo a la consulta con @blacburn, se hace la solicitud al equipo de Administrativa para que se generen los siguientes servicios WEB:
- Creación de servicio que liste las ordenes de compra y ordenes de servicio de ARGO
- Creación de servicio que consulte los datos de los contratos de las ordenes de compra y ordenes de servicio de ARGO, teniendo en cuenta que se debe traer el supervisor que se registra al momento de realizar la orden de compra u orden de servicio, no el supervisor actual.
- La consulta de las Sedes, Dependencias y espacios fìsicos se consultarán desde OIKOS
