### ISSUE TITLE
Ajustar el componente de salida con la funcionalidad de selección múltiple y poder asignar un elemento de consumo controlado y creación de la placa de forma aleatoria al registrar una salida a un funcionario

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#457]
Se debe desarrollar los ajustes que para cuando se realice la asignación de elementos de consumo controlados se pueda realizar de forma por demanda igual que al momento de asignar elementos (cntrl + click), adicionamente se debe simular la generación de la placa siguiendo el formato año, mes, dia y un numero aleatorio de maximo 5 digitos y asignar la placa al elemento, la issue debe cumplir con los siguientes requerimientos:

- [x] Desarrollar la función para asignar por demanda varios elementos de consumo controlados 
- [ ] Simular la creación de la placa con el formado dado, y asignar a cada elemento que se genera una salida

**Comment by fabianbarreto02** [comment]
https://docs.google.com/document/d/1UHF8sNe7l0YO0xDlF_P4V5c6A1FOeYraUxUTy7L_tnM/edit

**Comment by AlexFBP** [comment]
Referencias para el primer item de este _Issue_:

### Detectar shift + click para seleccionar un rango

Comportamiento esperado de los checkbox al hacer click y <kbd>shift/mayus</kbd>+click: #316 y #380 (de manera similar a como funciona en MS Excel o en Gmail con los correos). Esto con el objetivo de seleccionar un rango de filas

(Entrar al modulo de Actas, y crear un acta con al menos 5 elementos para poder ver que se cambia el punto inicial y final)

### Poder hacer algo con el rango seleccionado

Con lo anterior funcional, hay una base para poder realizar una o más acciones con los elementos seleccionados, por ejemplo, a la tabla de elementos en las Actas, cuando se consultan desde el modulo de Actas (especificamente, al editar un acta):
- #316 / #380 Borrar elementos seleccionados
- #379 Asignar una clase a elementos seleccionados

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
