### ISSUE TITLE
Desarrollo del registro de entradas

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#46]
Realizar el componente de registro de entradas.

**Comment by mafeave** [comment]
En revisión con @Miavega surgen las siguientes dudas:

Entrada por Adquisición:
- El campo que indica que es una importación aplicaría por factura o es una especifica para la entrada?
- La persona que realiza la entrada contaría con el Número de Registro Importación?

Entrada por reposición:
- En el campo de encargado: va la persona que estaba asignada al elemento o se asigna el funcionario de un listado?

Elaboración propia:
- No se trae un contrato pero se debe seleccionar Ordenador del gasto. Rta: se deben listar los posibles ordenadores de gasto: Rector, Vicerrectores..

En donación y sobrante 
- Quien es el solicitante?

Las dudas fueron resueltas por MariaC, las que no se lograron resolver, fueron agregadas en el [acta Nº 14](https://docs.google.com/document/d/1qZp99ahXmZ7enARMiyUHoG7ei79qKRtbGjLLODhxcQU/edit) de la próxima reunión con el usuario final.
