### ISSUE TITLE
Revisar y ajustar las entradas existentes teniendo en cuenta la HU 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#477]
Se debe ajustar y desarrollar las 6 entradas que ya están desarrolladas teniendo en cuenta la historia de [usuario ](https://docs.google.com/spreadsheets/d/18728OtHRvwplGfeSqaoNa57NbyksAWfG/edit#gid=154584319), se debe realizar los ajustes necesario para que el formulario quede acorde a la HU, la issue debe cumplir los siguientes requerimientos:

- [x] Revisar las seis entradas que ya estaba  en el desarrollo del aplicativo
- [x] Ajustar cada uno de las entradas con las HU

**Comment by CristianDavidSanchez** [comment]
Las nuevas entradas ya se encuentran acordes con la HU, sin embargo hay vacios que deben consultarse con el cliente para soportar la HU:

- Sobrantes: solo exige una vigencia en HU pero en cliente esta con un ordenador, ¿cuál es mejor?
- Que entradas exigen un soporte
- Los ordenadores y supervisores se traen por listas o por contratos?
- Estructura de los reportes
- Importación en adquisición ¿es necesario o no ? por existencia de entrada Compras en el extranjero

Se debe validar con cliente los formularios para realizar más modificaciones a los mismos. En conclusión es necesario una reunión con el analista y los clientes para validar requerimientos con HU.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
