### ISSUE TITLE
Generación MID Arka II

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#48]
Generar el MID API para gestionar los servicios de ARKA II.

**Comment by Miavega** [comment]
Se genera el API mid para ARKA II, incluyendo su configuración para un despliegue en entorno local OAS. En el siguiente [enlace](https://github.com/udistrital/arka_mid) se encuentra el API.

**Comment by mafeave** [comment]
Se verifica generación de la estructura base para el API mid.
