### ISSUE TITLE
Asignación de cuentas contables para las transacción de bajas y traslados 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#482]
Se debe desarrollar el registro, la consulta y la edición de las cuentas contables para las clases para las transacciones de bajas y traslados, teniendo en cuenta que para el modulo de gestión contable se requiere el registro de esa movimientos para las transacciones, la issue debe cumplir con la siguientes requerimientos:
 

- [x] Realizar el desarrollo para el registro de las cuentas de naturaleza crédito y debito para las dos transacciones  
- [x] Realizar el desarrollo para la consulta de las cuentas de naturaleza crédito y debito para las dos transacciones 
- [x] Realizar el desarrollo para la edición  de las cuentas de naturaleza crédito y debito para las dos transacciones

**Comment by AlexFBP** [comment]
Se empezó a abordar el Issue a las 8:44

**Comment by AlexFBP** [comment]
En el [CRUD de Movimientos (Kronos?)](https://github.com/udistrital/movimientos_crud) no hay registros (activos) para traslados ni bajas de Arka ([registros cuyo acrónimo tenga "arka" en algún lado](https://github.com/udistrital/arka_mid/blob/develop/helpers/catalogoElementosHelper/catalogoElementos.helper.go#L90)) - [validar en la API store](https://autenticacion.portaloas.udistrital.edu.co/store/apis/info?name=Movimientos&version=v1&provider=admin&tenant=carbon.super#!/tipo_movimiento/TipoMovimientoController_Get_All), por lo que se creó el PR udistrital/movimientos_crud#87

Por otro lado, en el [CRUD de movimientos de Arka](https://github.com/udistrital/movimientos_arka_crud) ya existe el movimiento... : ([validar en la API store](https://autenticacion.portaloas.udistrital.edu.co/store/apis/info?name=MovimientosArka&version=v1&provider=admin&tenant=carbon.super#!/formato_tipo_movimiento/FormatoTipoMovimientoController_Get_All))
```json
{
  "Id": 13,
  "Nombre": "Solicitud de Bajas",
  "Formato": "{ \"Funcionario\": \"number\", \"Ubicacion\": \"number\", \"Revisor\": \"number\", \"FechaVistoBueno\": \"string\", \"Elementos\": [ { \"Id\": \"number\", \"Soporte\": \"number\", \"TipoBaja\": \"number\", \"Observaciones\": \"string\" } ] }",
  "Descripcion": "Formato para realizar la solicitud de bajas de varios elementos",
  "CodigoAbreviacion": "SOL_BAJA",
  "NumeroOrden": 13,
  "FechaCreacion": "2020-09-30T10:38:04.328315Z",
  "FechaModificacion": "2020-09-30T10:38:04.328315Z",
  "Activo": true
}
```
... que [se está usando en el módulo de bajas](https://github.com/udistrital/arka_cliente/blob/dev/src/app/pages/bajas/solicitud-bajas/solicitud-bajas.component.ts#L159), por lo que solo hay que crear el registro para traslados

**Comment by AlexFBP** [comment]
![image](https://user-images.githubusercontent.com/6588872/107842875-84785c80-6d94-11eb-8a1d-f6d4ea504eb3.png)

Mientras lo desarrollado en udistrital/movimientos_crud#87 se pasa a test, se simulan los datos:
```diff
diff --git a/src/app/pages/catalogo-bienes/registro-cuentas-catalogo/registro-cuentas-catalogo.component.ts b/src/app/pages/catalogo-bienes/registro-cuentas-catalogo/registro-cuentas-catalogo.component.ts
index 3018191..c01adb8 100644
--- a/src/app/pages/catalogo-bienes/registro-cuentas-catalogo/registro-cuentas-catalogo.component.ts
+++ b/src/app/pages/catalogo-bienes/registro-cuentas-catalogo/registro-cuentas-catalogo.component.ts
@@ -89,6 +89,28 @@ export class RegistroCuentasCatalogoComponent implements OnInit {
 
     this.catalogoElementosService.getTiposMovimientoKronos().subscribe((res: TipoMovimientoKronos[]) => {
       // console.log({res});
+      res.push(
+        {
+          Id: 32,
+          Nombre: 'Traslado',
+          Descripcion: 'Traslado de bienes y servicios de Arka II',
+          Acronimo: 'tr_arka',
+          Activo: true,
+          FechaCreacion: new Date('0001-01-01T00:00:00Z'),
+          FechaModificacion: new Date('0001-01-01T00:00:00Z'),
+          Parametros: '',
+        },
+        {
+          Id: 31,
+          Nombre: 'Baja',
+          Descripcion: 'Baja de bienes y servicios de Arka II',
+          Acronimo: 'b_arka',
+          Activo: true,
+          FechaCreacion: new Date('0001-01-01T00:00:00Z'),
+          FechaModificacion: new Date('0001-01-01T00:00:00Z'),
+          Parametros: '',
+        },
+      );
       const desglose = res.reduce((acc: TiposMovimiento[], val): TiposMovimiento[] => {
         const tipo = movimientos.find(mov => val.Descripcion.indexOf(mov.buscar) !== -1);
         const criterio = (t: TiposMovimiento) => tipo && (t.tipo === tipo.buscar);
```

**Comment by AlexFBP** [comment]
De manera complementaria al movimiento para bajas que ya estaba disponible ([arriba](https://github.com/udistrital/arka_cliente/issues/482#issuecomment-778388464)), se agregó en udistrital/movimientos_arka_crud#36 el movimiento para traslados, así:
```json
{
  "Id": 19,
  "Nombre": "Provisional",
  "Formato": "{ \"acta_recibido_id\": \"number\", \"consecutivo\": \"string\",  \"documento_contable_id\": \"number\", \"contrato_id\": \"number\", \"vigencia_contrato\": \"number\" }",
  "Descripcion": "Formato para guardar una Entrada de Bienes Entregados de Manera Provisional",
  "CodigoAbreviacion": "EBEMP",
  "NumeroOrden": 20,
  "FechaCreacion": "2021-01-29T06:25:55.292672Z",
  "FechaModificacion": "2021-01-29T06:25:55.292672Z",
  "Activo": true
}
```

Queda pendiente confirmar si el formato de cada movimiento tiene todo lo que se necesita
