### ISSUE TITLE
Desarrollar componente paramétrico para los tipos de entrada 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#483]
Se debe desarrollar el componente paramétrico para  realizar el registro de nuevas entradas teniendo en cuenta el modulo de gestión de administración de parametrización, se debe crear un nuevo menu llamado administración y un nuevo submeno de Registro de tipos de entrada, similar a la imagen:

![image](https://user-images.githubusercontent.com/43799065/106316825-5b57b800-623b-11eb-9a3b-36f2bd2a4eef.png)

el componente debe mostrar las entradas existente en el api de [movimiento_crud](https://github.com/udistrital/movimientos_crud), el servicio de pruebas es http://pruebasapi.intranetoas.udistrital.edu.co:8202/v1/tipo_movimiento , tener presente que todos los registros de arka debe tener en el campo acrónimo se debe informar que es de arka, imagen de referencia 

![image](https://user-images.githubusercontent.com/43799065/106317938-0452e280-623d-11eb-8a8d-55b3d04ca7a0.png)

![image](https://user-images.githubusercontent.com/43799065/106317893-f56c3000-623c-11eb-9db4-b34b4165bba2.png)

Se debe permitir el registro y la edición de cualquier registro, imagen de referencia 

![image](https://user-images.githubusercontent.com/43799065/106318025-2b111900-623d-11eb-9c5e-239a9ce46a9b.png)

la issue debe cumplir con los siguientes requerimiento:

- [ ] Realizar los componentes con los mockups informados para la consulta, el registro y la edición 
- [ ] Realizar la funcionalidad para cada una de ellos 
- [ ] Tener presente que por debajo se debe realizar el registro del acrónimo

**Comment by CristianDavidSanchez** [comment]
Se define con usuario y equipo de desarrollo que no es posible realizar un modulo de parametrización para tipos de entradas
