### ISSUE TITLE
Ajustar modelo de movimientos ARKA de acuerdo al modelo propuesto en KRONOS

### ISSUE THREAD

**Issue by mafeave** [udistrital/arka_cliente#49]
De acuerdo a la observación de @corio27 de la reunión  se debe revisar el modelo propuesto junto al modelo de movimientos de Kronos, por lo cual, se debe ajustar el modelo de datos propuesto para la gestión de movimientos, contemplando el modelo de movimientos que se propuso en Kronos.

**Comment by mafeave** [comment]
El siguiente es el modelo de movimientos de Kronos para revisión:
![image](https://user-images.githubusercontent.com/14035745/63092420-560f8c00-bf27-11e9-8965-eef80ef5c639.png)
Archivo pgmodeler: 
[movimientos_kronos.zip](https://github.com/udistrital/arka_cliente/files/3505377/movimientos_kronos.zip)

**Comment by mafeave** [comment]
¿Cómo se sabría el proceso externo que se está referenciando?

**Comment by Miavega** [comment]
El proceso externo referenciado se sabe gracias al campo _**acronimo**_ en la tabla _**tipo_movimiento**_. Cada movimiento tendría un acrónimo asociado para saber a qué sistema pertenece y así evitar conflictos en caso de que el id del proceso externo sea igual en ARKA o KRONOS.
