### ISSUE TITLE
Realizar el componente para la la edición de los diferentes tipos de entrada 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#493]
Se debe iniciar el desarrollo para el modulo de edición de una entrada ya registradas teniendo en cuenta cada tipo de entradas, se debe poder modificar los diferentes partes de la entrada y revisar y ajustar el put con las nuevos ajustes a la entrada, la issue debe cumplir con los siguientes requerimientos:

- [ ] Realizar el componente para poder editar una entrada ya registrada
- [ ] Realizar la funcionalidad del put con los ajustes  a la entrada en edición 
- [ ] Se debe realizar el componente dinámico para los diferentes tipos de entrada

**Comment by fabianbarreto02** [comment]
Se debe realizar el modulo de ajustes par poder realizar la modificación, se da por finalizada la issue

**Comment by ludwinggsanchez** [comment]
Debido a que el módulo de gestión de ajustes consiste en la generación de un comprobante de ajustes y la anulación de todos los movimientos, se revierten estos cambios ya que no se puede hacer la edición de una entrada tal como se había considerado.
