### ISSUE TITLE
Diseño de mockups de bodega de consumo: gestión de elementos

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#50]
Diseñar los Mockups correspondientes al módulo de bodega de consumo, en específico la gestión de elementos. El mockup debe ser realizado en draw.io.

**Comment by Miavega** [comment]
En el siguiente [enlace](https://drive.google.com/drive/u/0/folders/1r2Nr9QGLQetbFdmV-hf2jTLLj5x09g1c) se pueden encontrar los mockups conrrespondientes a la gestion de elementos del módulo de bodega de consumo. Se realizan las siguientes observaciones:  

- El mockup se encuentra en la página **_consulta_elementos_kardex_**. 

- Se aclara que las otras dos páginas _**solicitud_elemento_kardex**_ y **_salida_kardex_** hacen referencia a la gestión de solicitudes. 

- Así mismo, no se realiza mockup para la primer salida de los elementos puesto que se utiliza la misma salida propuesta anteriormente.

**Comment by mafeave** [comment]
En espera de validación con el usuario final, hoy 20 de Agosto

**Comment by mcrubianot** [comment]
Observaciones en 

Revisión Mockups de Bodega de Consumo #315

**Comment by Miavega** [comment]
Dada las correcciones realizadas por @mcrubianot, se ajustan los Mockups de gestión elementos.
 En el siguiente [enlace](https://drive.google.com/drive/u/0/folders/1r2Nr9QGLQetbFdmV-hf2jTLLj5x09g1c) se encuentran los nuevos Mockups. El archivo que contiene la gestión de elementos se llama _**consulta.drawio.**_

**Comment by mafeave** [comment]
Queda pendiente la aprobación por parte de almacen.
