### ISSUE TITLE
Realizar la organización de la consulta de ordenadores y supervisores de acuerdo a la reunión con usuarios 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#503]
Realizar la organización de la consulta de ordenadores y supervisores de acuerdo a la reunión con usuarios, tener en cuenta el flujo se definió en la reunión con los usuarios,  tener en cuenta los cargos como ordenadores de gastos( vicerrector, decanos, rector, director Ideux, Director CIDC, y los otros cargos que se definieron) se debe crear en el api de parametros los cargos y realizar datos de pruebas en terceros para la función de consulta, la issue debe cumplir  con los siguientes requerimientos:

- [x] Ajustar todos los datos necesarios para la función (cargos, vinculaciones)
- [x] Ajustar la función de consulta para ordenadores y supervisores

**Comment by CristianDavidSanchez** [comment]
Generación de los nuevos cargos. 
`{
  "Data": [
    {
      "Id": 323,
      "Nombre": "VICERECTOR ADMINISTRATIVO Y FINANCIERO",
      "Descripcion": "VICERECTOR ADMINISTRATIVO Y FINANCIERO",
      "CodigoAbreviacion": "VAF",
      "Activo": true,
      "NumeroOrden": 1,
      "FechaCreacion": "2021-02-16 17:43:12.755216 +0000 +0000",
      "FechaModificacion": "2021-02-16 17:43:12.755323 +0000 +0000",
      "TipoParametroId": {
        "Id": 15,
        "Nombre": "Cargos",
        "Descripcion": "Cargos",
        "CodigoAbreviacion": "C",
        "Activo": true,
        "NumeroOrden": 15,
        "FechaCreacion": "2021-01-28 15:23:00 +0000 +0000",
        "FechaModificacion": "2021-01-28 15:23:00 +0000 +0000",
        "AreaTipoId": {
          "Id": 5,
          "Nombre": "Contratación",
          "Descripcion": "Contratación",
          "CodigoAbreviacion": "C",
          "Activo": true,
          "NumeroOrden": 0,
          "FechaCreacion": "2021-01-08 19:42:00 +0000 +0000",
          "FechaModificacion": "2021-01-08 19:42:00 +0000 +0000"
        }
      },
      "ParametroPadreId": null
    },
    {
      "Id": 322,
      "Nombre": "DIRECTOR DE INSTITUTO",
      "Descripcion": "DIRECTOR DE INSTITUTO",
      "CodigoAbreviacion": "DI",
      "Activo": true,
      "NumeroOrden": 1,
      "FechaCreacion": "2021-02-16 17:35:38.240354 +0000 +0000",
      "FechaModificacion": "2021-02-16 17:35:38.240459 +0000 +0000",
      "TipoParametroId": {
        "Id": 15,
        "Nombre": "Cargos",
        "Descripcion": "Cargos",
        "CodigoAbreviacion": "C",
        "Activo": true,
        "NumeroOrden": 15,
        "FechaCreacion": "2021-01-28 15:23:00 +0000 +0000",
        "FechaModificacion": "2021-01-28 15:23:00 +0000 +0000",
        "AreaTipoId": {
          "Id": 5,
          "Nombre": "Contratación",
          "Descripcion": "Contratación",
          "CodigoAbreviacion": "C",
          "Activo": true,
          "NumeroOrden": 0,
          "FechaCreacion": "2021-01-08 19:42:00 +0000 +0000",
          "FechaModificacion": "2021-01-08 19:42:00 +0000 +0000"
        }
      },
      "ParametroPadreId": null
    },
    {
      "Id": 321,
      "Nombre": "DECANO",
      "Descripcion": "DECANO",
      "CodigoAbreviacion": "D",
      "Activo": true,
      "NumeroOrden": 1,
      "FechaCreacion": "2021-02-16 17:33:25.882634 +0000 +0000",
      "FechaModificacion": "2021-02-16 17:33:25.882745 +0000 +0000",
      "TipoParametroId": {
        "Id": 15,
        "Nombre": "Cargos",
        "Descripcion": "Cargos",
        "CodigoAbreviacion": "C",
        "Activo": true,
        "NumeroOrden": 15,
        "FechaCreacion": "2021-01-28 15:23:00 +0000 +0000",
        "FechaModificacion": "2021-01-28 15:23:00 +0000 +0000",
        "AreaTipoId": {
          "Id": 5,
          "Nombre": "Contratación",
          "Descripcion": "Contratación",
          "CodigoAbreviacion": "C",
          "Activo": true,
          "NumeroOrden": 0,
          "FechaCreacion": "2021-01-08 19:42:00 +0000 +0000",
          "FechaModificacion": "2021-01-08 19:42:00 +0000 +0000"
        }
      },
      "ParametroPadreId": null
    },
    {
      "Id": 319,
      "Nombre": "VICERECTOR ACADÉMICO",
      "Descripcion": "VICERECTOR ACADÉMICO",
      "CodigoAbreviacion": "VA",
      "Activo": true,
      "NumeroOrden": 1,
      "FechaCreacion": "2021-02-16 17:27:14.082122 +0000 +0000",
      "FechaModificacion": "2021-02-16 17:27:14.082232 +0000 +0000",
      "TipoParametroId": {
        "Id": 15,
        "Nombre": "Cargos",
        "Descripcion": "Cargos",
        "CodigoAbreviacion": "C",
        "Activo": true,
        "NumeroOrden": 15,
        "FechaCreacion": "2021-01-28 15:23:00 +0000 +0000",
        "FechaModificacion": "2021-01-28 15:23:00 +0000 +0000",
        "AreaTipoId": {
          "Id": 5,
          "Nombre": "Contratación",
          "Descripcion": "Contratación",
          "CodigoAbreviacion": "C",
          "Activo": true,
          "NumeroOrden": 0,
          "FechaCreacion": "2021-01-08 19:42:00 +0000 +0000",
          "FechaModificacion": "2021-01-08 19:42:00 +0000 +0000"
        }
      },
      "ParametroPadreId": null
    },
    {
      "Id": 318,
      "Nombre": "RECTOR",
      "Descripcion": "RECTOR",
      "CodigoAbreviacion": "R",
      "Activo": true,
      "NumeroOrden": 1,
      "FechaCreacion": "2021-02-16 17:20:36.548016 +0000 +0000",
      "FechaModificacion": "2021-02-16 17:20:36.548133 +0000 +0000",
      "TipoParametroId": {
        "Id": 15,
        "Nombre": "Cargos",
        "Descripcion": "Cargos",
        "CodigoAbreviacion": "C",
        "Activo": true,
        "NumeroOrden": 15,
        "FechaCreacion": "2021-01-28 15:23:00 +0000 +0000",
        "FechaModificacion": "2021-01-28 15:23:00 +0000 +0000",
        "AreaTipoId": {
          "Id": 5,
          "Nombre": "Contratación",
          "Descripcion": "Contratación",
          "CodigoAbreviacion": "C",
          "Activo": true,
          "NumeroOrden": 0,
          "FechaCreacion": "2021-01-08 19:42:00 +0000 +0000",
          "FechaModificacion": "2021-01-08 19:42:00 +0000 +0000"
        }
      },
      "ParametroPadreId": null
    },
    {
      "Id": 312,
      "Nombre": "JEFE OFICINA",
      "Descripcion": "JEFE OFICINA",
      "CodigoAbreviacion": "JO",
      "Activo": true,
      "NumeroOrden": 1,
      "FechaCreacion": "2021-01-28 15:23:00 +0000 +0000",
      "FechaModificacion": "2021-01-28 15:23:00 +0000 +0000",
      "TipoParametroId": {
        "Id": 15,
        "Nombre": "Cargos",
        "Descripcion": "Cargos",
        "CodigoAbreviacion": "C",
        "Activo": true,
        "NumeroOrden": 15,
        "FechaCreacion": "2021-01-28 15:23:00 +0000 +0000",
        "FechaModificacion": "2021-01-28 15:23:00 +0000 +0000",
        "AreaTipoId": {
          "Id": 5,
          "Nombre": "Contratación",
          "Descripcion": "Contratación",
          "CodigoAbreviacion": "C",
          "Activo": true,
          "NumeroOrden": 0,
          "FechaCreacion": "2021-01-08 19:42:00 +0000 +0000",
          "FechaModificacion": "2021-01-08 19:42:00 +0000 +0000"
        }
      },
      "ParametroPadreId": null
    }
  ],
  "Message": "Request successful",
  "Status": "200",
  "Success": true
}`

**Comment by CristianDavidSanchez** [comment]
para ingresar una nueva vinculación se requiere info en varias apis, aquí se dejara el procedimiento cuando se tenga que hacer la migración de datos, se debe hacer ene este orden:

1. Crear los cargos api de parametros, se debe realizar un query con esta estructura  para encontrar los id de tipo de vinculación cargo: TipoParametroId__CodigoAbreviacion:C,TipoParametroId__AreaTipoId__CodigoAbreviacion:C, a este api con esos id se debe realizar el post de los rectores decanos vicerectores etc.
2. En el api de terceros, se deben generar los terceros relacionados a los cargos anteriormente mencionados, dejo pantallazo de los que cargue:
![image](https://user-images.githubusercontent.com/45292213/108255308-18964b00-712a-11eb-9edf-4ae56d2493d6.png)
3. En el api de oikos 2 con el siguiente URL de pruebas http://pruebasapi.intranetoas.udistrital.edu.co:8087/v1/dependencia?limit=-1 se deben buscar los id correspondientes a las dependencias.
4. en el api de parametros con el código de abreviación TV se debe buscar el ID de Docentes de planta para signarselos a los ordenadores generados.
5. La estructura del json para vinculación al realizar estos pasos sería entonces:
```
{
  "Activo": true,
  "CargoId": Cargo insertado en parametros,
  "DependenciaId":Id dependencia de oikos2,
  "TerceroPrincipalId": {
    "Id": Tercero generado en el paso 2
  },
  "TipoVinculacionId": Vinculacion en este caso docente de planta
} 
```

**Comment by CristianDavidSanchez** [comment]
```
    {
        "Id": 5,
        "TerceroPrincipalId": {
            "Id": 9801,
            "NombreCompleto": "Ricardo García Duarte",
            "PrimerNombre": "Ricardo",
            "SegundoNombre": "",
            "PrimerApellido": "García",
            "SegundoApellido": "Duarte",
            "LugarOrigen": 0,
            "FechaNacimiento": null,
            "Activo": true,
            "TipoContribuyenteId": {
                "Id": 1,
                "Nombre": "PERSONA NATURAL",
                "Descripcion": "",
                "CodigoAbreviacion": "P_NATURAL",
                "Activo": true,
                "FechaCreacion": "2019-11-25 20:39:54.419232 +0000 +0000",
                "FechaModificacion": "2019-11-25 20:39:54.419232 +0000 +0000"
            },
            "FechaCreacion": "2021-02-17 11:38:46.131822 +0000 +0000",
            "FechaModificacion": "2021-02-17 11:38:46.131921 +0000 +0000",
            "UsuarioWSO2": "string"
        },
        "TerceroRelacionadoId": null,
        "TipoVinculacionId": 292,
        "CargoId": 318,
        "DependenciaId": 7,
        "Soporte": 0,
        "PeriodoId": 0,
        "FechaInicioVinculacion": "0001-01-01T00:00:00Z",
        "FechaFinVinculacion": "0001-01-01T00:00:00Z",
        "Activo": true,
        "FechaCreacion": "2021-02-17 14:21:11.527711 +0000 +0000",
        "FechaModificacion": "2021-02-17 14:21:11.527831 +0000 +0000"
    },
    {
        "Id": 6,
        "TerceroPrincipalId": {
            "Id": 9802,
            "NombreCompleto": "William Fernando Castrillón Cardona",
            "PrimerNombre": "William",
            "SegundoNombre": "Fernando",
            "PrimerApellido": "Castrillón",
            "SegundoApellido": "Cardona",
            "LugarOrigen": 0,
            "FechaNacimiento": null,
            "Activo": true,
            "TipoContribuyenteId": {
                "Id": 1,
                "Nombre": "PERSONA NATURAL",
                "Descripcion": "",
                "CodigoAbreviacion": "P_NATURAL",
                "Activo": true,
                "FechaCreacion": "2019-11-25 20:39:54.419232 +0000 +0000",
                "FechaModificacion": "2019-11-25 20:39:54.419232 +0000 +0000"
            },
            "FechaCreacion": "2021-02-17 11:42:56.624497 +0000 +0000",
            "FechaModificacion": "2021-02-17 11:42:56.624571 +0000 +0000",
            "UsuarioWSO2": ""
        },
        "TerceroRelacionadoId": null,
        "TipoVinculacionId": 292,
        "CargoId": 319,
        "DependenciaId": 8,
        "Soporte": 0,
        "PeriodoId": 0,
        "FechaInicioVinculacion": "0001-01-01T00:00:00Z",
        "FechaFinVinculacion": "0001-01-01T00:00:00Z",
        "Activo": true,
        "FechaCreacion": "2021-02-17 14:26:25.15617 +0000 +0000",
        "FechaModificacion": "2021-02-17 14:26:25.15626 +0000 +0000"
    },
    {
        "Id": 7,
        "TerceroPrincipalId": {
            "Id": 9803,
            "NombreCompleto": " Álvaro Espinel Ortega",
            "PrimerNombre": "Álvaro",
            "SegundoNombre": "",
            "PrimerApellido": "Espinel ",
            "SegundoApellido": "Espinel ",
            "LugarOrigen": 0,
            "FechaNacimiento": null,
            "Activo": true,
            "TipoContribuyenteId": {
                "Id": 1,
                "Nombre": "PERSONA NATURAL",
                "Descripcion": "",
                "CodigoAbreviacion": "P_NATURAL",
                "Activo": true,
                "FechaCreacion": "2019-11-25 20:39:54.419232 +0000 +0000",
                "FechaModificacion": "2019-11-25 20:39:54.419232 +0000 +0000"
            },
            "FechaCreacion": "2021-02-17 11:45:48.94136 +0000 +0000",
            "FechaModificacion": "2021-02-17 11:45:48.94148 +0000 +0000",
            "UsuarioWSO2": ""
        },
        "TerceroRelacionadoId": null,
        "TipoVinculacionId": 292,
        "CargoId": 323,
        "DependenciaId": 15,
        "Soporte": 0,
        "PeriodoId": 0,
        "FechaInicioVinculacion": "0001-01-01T00:00:00Z",
        "FechaFinVinculacion": "0001-01-01T00:00:00Z",
        "Activo": true,
        "FechaCreacion": "2021-02-17 14:30:22.33598 +0000 +0000",
        "FechaModificacion": "2021-02-17 14:30:22.33608 +0000 +0000"
    },
    {
        "Id": 8,
        "TerceroPrincipalId": {
            "Id": 9804,
            "NombreCompleto": "Julio Varon Velandia",
            "PrimerNombre": "Julio",
            "SegundoNombre": "",
            "PrimerApellido": "Varon",
            "SegundoApellido": "Velandia",
            "LugarOrigen": 0,
            "FechaNacimiento": null,
            "Activo": true,
            "TipoContribuyenteId": {
                "Id": 1,
                "Nombre": "PERSONA NATURAL",
                "Descripcion": "",
                "CodigoAbreviacion": "P_NATURAL",
                "Activo": true,
                "FechaCreacion": "2019-11-25 20:39:54.419232 +0000 +0000",
                "FechaModificacion": "2019-11-25 20:39:54.419232 +0000 +0000"
            },
            "FechaCreacion": "2021-02-17 11:54:25.385018 +0000 +0000",
            "FechaModificacion": "2021-02-17 11:54:25.385119 +0000 +0000",
            "UsuarioWSO2": ""
        },
        "TerceroRelacionadoId": null,
        "TipoVinculacionId": 292,
        "CargoId": 321,
        "DependenciaId": 14,
        "Soporte": 0,
        "PeriodoId": 0,
        "FechaInicioVinculacion": "0001-01-01T00:00:00Z",
        "FechaFinVinculacion": "0001-01-01T00:00:00Z",
        "Activo": true,
        "FechaCreacion": "2021-02-17 14:35:05.109644 +0000 +0000",
        "FechaModificacion": "2021-02-17 14:35:05.109744 +0000 +0000"
    },
    {
        "Id": 9,
        "TerceroPrincipalId": {
            "Id": 9805,
            "NombreCompleto": "Jaime Eddie Ussa",
            "PrimerNombre": "Jaime",
            "SegundoNombre": "",
            "PrimerApellido": "Eddie",
            "SegundoApellido": "Ussa",
            "LugarOrigen": 0,
            "FechaNacimiento": null,
            "Activo": true,
            "TipoContribuyenteId": {
                "Id": 1,
                "Nombre": "PERSONA NATURAL",
                "Descripcion": "",
                "CodigoAbreviacion": "P_NATURAL",
                "Activo": true,
                "FechaCreacion": "2019-11-25 20:39:54.419232 +0000 +0000",
                "FechaModificacion": "2019-11-25 20:39:54.419232 +0000 +0000"
            },
            "FechaCreacion": "2021-02-17 12:04:58.160949 +0000 +0000",
            "FechaModificacion": "2021-02-17 12:04:58.161074 +0000 +0000",
            "UsuarioWSO2": ""
        },
        "TerceroRelacionadoId": null,
        "TipoVinculacionId": 292,
        "CargoId": 321,
        "DependenciaId": 65,
        "Soporte": 0,
        "PeriodoId": 0,
        "FechaInicioVinculacion": "0001-01-01T00:00:00Z",
        "FechaFinVinculacion": "0001-01-01T00:00:00Z",
        "Activo": true,
        "FechaCreacion": "2021-02-17 14:39:16.726298 +0000 +0000",
        "FechaModificacion": "2021-02-17 14:39:16.726421 +0000 +0000"
    },
    {
        "Id": 10,
        "TerceroPrincipalId": {
            "Id": 9806,
            "NombreCompleto": "Cecilia Rincón Verdugo",
            "PrimerNombre": "Cecilia",
            "SegundoNombre": "",
            "PrimerApellido": "Rincón",
            "SegundoApellido": "Verdugo",
            "LugarOrigen": 0,
            "FechaNacimiento": null,
            "Activo": true,
            "TipoContribuyenteId": {
                "Id": 1,
                "Nombre": "PERSONA NATURAL",
                "Descripcion": "",
                "CodigoAbreviacion": "P_NATURAL",
                "Activo": true,
                "FechaCreacion": "2019-11-25 20:39:54.419232 +0000 +0000",
                "FechaModificacion": "2019-11-25 20:39:54.419232 +0000 +0000"
            },
            "FechaCreacion": "2021-02-17 12:05:41.464027 +0000 +0000",
            "FechaModificacion": "2021-02-17 12:05:41.4641 +0000 +0000",
            "UsuarioWSO2": ""
        },
        "TerceroRelacionadoId": null,
        "TipoVinculacionId": 292,
        "CargoId": 321,
        "DependenciaId": 17,
        "Soporte": 0,
        "PeriodoId": 0,
        "FechaInicioVinculacion": "0001-01-01T00:00:00Z",
        "FechaFinVinculacion": "0001-01-01T00:00:00Z",
        "Activo": true,
        "FechaCreacion": "2021-02-17 14:43:54.849022 +0000 +0000",
        "FechaModificacion": "2021-02-17 14:43:54.849128 +0000 +0000"
    },
    {
        "Id": 11,
        "TerceroPrincipalId": {
            "Id": 9807,
            "NombreCompleto": "Jorge Enrique Rodríguez Rodríguez",
            "PrimerNombre": "Jorge",
            "SegundoNombre": "Enrique",
            "PrimerApellido": "Rodríguez",
            "SegundoApellido": "Rodríguez",
            "LugarOrigen": 0,
            "FechaNacimiento": null,
            "Activo": true,
            "TipoContribuyenteId": {
                "Id": 1,
                "Nombre": "PERSONA NATURAL",
                "Descripcion": "",
                "CodigoAbreviacion": "P_NATURAL",
                "Activo": true,
                "FechaCreacion": "2019-11-25 20:39:54.419232 +0000 +0000",
                "FechaModificacion": "2019-11-25 20:39:54.419232 +0000 +0000"
            },
            "FechaCreacion": "2021-02-17 12:07:57.157057 +0000 +0000",
            "FechaModificacion": "2021-02-17 12:07:57.157166 +0000 +0000",
            "UsuarioWSO2": ""
        },
        "TerceroRelacionadoId": null,
        "TipoVinculacionId": 292,
        "CargoId": 321,
        "DependenciaId": 66,
        "Soporte": 0,
        "PeriodoId": 0,
        "FechaInicioVinculacion": "0001-01-01T00:00:00Z",
        "FechaFinVinculacion": "0001-01-01T00:00:00Z",
        "Activo": true,
        "FechaCreacion": "2021-02-17 14:45:24.329998 +0000 +0000",
        "FechaModificacion": "2021-02-17 14:45:24.330089 +0000 +0000"
    },
    {
        "Id": 12,
        "TerceroPrincipalId": {
            "Id": 9808,
            "NombreCompleto": "Jose Felix Assad Cuellar",
            "PrimerNombre": "Jose",
            "SegundoNombre": "Felix",
            "PrimerApellido": "Assad",
            "SegundoApellido": "Cuellar",
            "LugarOrigen": 0,
            "FechaNacimiento": null,
            "Activo": true,
            "TipoContribuyenteId": {
                "Id": 1,
                "Nombre": "PERSONA NATURAL",
                "Descripcion": "",
                "CodigoAbreviacion": "P_NATURAL",
                "Activo": true,
                "FechaCreacion": "2019-11-25 20:39:54.419232 +0000 +0000",
                "FechaModificacion": "2019-11-25 20:39:54.419232 +0000 +0000"
            },
            "FechaCreacion": "2021-02-17 12:08:51.701269 +0000 +0000",
            "FechaModificacion": "2021-02-17 12:08:51.70137 +0000 +0000",
            "UsuarioWSO2": ""
        },
        "TerceroRelacionadoId": null,
        "TipoVinculacionId": 292,
        "CargoId": 321,
        "DependenciaId": 35,
        "Soporte": 0,
        "PeriodoId": 0,
        "FechaInicioVinculacion": "0001-01-01T00:00:00Z",
        "FechaFinVinculacion": "0001-01-01T00:00:00Z",
        "Activo": true,
        "FechaCreacion": "2021-02-17 14:47:54.813017 +0000 +0000",
        "FechaModificacion": "2021-02-17 14:47:54.813097 +0000 +0000"
    },
```

**Comment by CristianDavidSanchez** [comment]
![image](https://user-images.githubusercontent.com/45292213/108263933-de7e7680-7134-11eb-9cd3-b972e9d5c9ee.png)


Funcional falta ajuste en el cliente.

**Comment by CristianDavidSanchez** [comment]
http://pruebasapi.intranetoas.udistrital.edu.co:8087/v2/asignacion_espacio_fisico_dependencia/

Se debe hacer la asignación de sede dependencia a los docentes de planta siempre o da problemas en el cliente, puesto que ellos también son supervisores por el tipo de vinculación.

**Comment by fabianbarreto02** [comment]
Se da por finalizada la issue
