### ISSUE TITLE
Diseño de mockups de bodega de consumo: gestión de solicitudes

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#51]
Diseñar los Mockups correspondientes al módulo de bodega de consumo, en específico la gestión de solicitudes. El mockup debe ser realizado en draw.io.

**Comment by Miavega** [comment]
En el siguiente [enlace](https://drive.google.com/drive/u/0/folders/1r2Nr9QGLQetbFdmV-hf2jTLLj5x09g1c) se pueden encontrar los mockups conrrespondientes a la gestion de solicitudes del módulo de bodega de consumo. Se realizan las siguientes observaciones:  

- Los mockups se encuentra en las páginas _**solicitud_elemento_kardex**_ y **_salida_kardex_**.. 

- Se aclara que la otra página **_consulta_elementos_kardex_** hace referencia a la gestión de elementos. 

- Así mismo, no se realiza mockup para la primer salida de los elementos puesto que se utiliza la misma salida propuesta anteriormente.

**Comment by mafeave** [comment]
En espera de validación con el analista y el usuario final, hoy 20 de Agosto

**Comment by mcrubianot** [comment]
Observaciones en Revisión Mockups de Bodega de Consumo #315

**Comment by Miavega** [comment]
Dada las correcciones realizadas por @mcrubianot, se ajustan los Mockups de gestión de solicitudes.
En el siguiente [enlace](https://drive.google.com/drive/u/0/folders/1r2Nr9QGLQetbFdmV-hf2jTLLj5x09g1c) se encuentran los nuevos Mockups. 
Los archivo que contienen la gestión de solicitudes se llaman **solicitud.drawio._** y **aprobacion.drawio._**

**Comment by mafeave** [comment]
Queda pendiente aprobación de los mockups por parte de almacen.
