### ISSUE TITLE
Ajustar en el sub modulo de registro de salida los detalles por cada tipo de de entrada 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#517]
En el modulo de salidas en el tag de Detalle Entrada se debe ajustar la información que se debe mostrar dependiendo en cuenta cada tipo de entrada, como el modulo de entrada ya esta ajustado con los requerimientos definidos por cada tipo de entrada, la issue debe cumplir con los siguientes requerimientos:

- [x] ajustar el tag de detalle entrada con la información para cada tipo de entrada

**Comment by CristianDavidSanchez** [comment]
No se estaban cargando todas las entradas aceptadas, se soluciono ya, en la descripcion de cada entrada ya no hay datos quemados, todos los datos de los registros se actualizaron con base en el modulo de consultar entradas.
