### ISSUE TITLE
Ajustar los reportes de entradas con los ajustes definidos por analista de requerimientos y por cada tipo de entrada 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#519]
Se debe ajustar los reportes de las entradas incluyendo los datos faltantes definidos por la analista de requerimientos y tambien ajustar que información no aplica dependiendo del tipo de entrada, los ajustes a realizar son:

- [x] Incluir dentro de los reportes los códigos y nombre de la clase definidos por el catalogo compra eficiente para cada elemento relacionado en la entrada
- [x] Incluir los valores faltantes, valor total, valor total de subtotal, valor iva
- [x]  Ajustar los datos para los distintos tipos de entradas, si algun dato no aplica informar en el reporte

**Comment by ludwinggsanchez** [comment]
El query se cambia para asignar un valor default para el campo de tipo y número de contrato. Se incluye el código y nombre de clase:

SELECT s.consecutivo as consecutivo_factura, 
m.detalle ->>'consecutivo' consecutivoM,
m.fecha_creacion,
a.id as acta_recibido_id,
t.nombre as tipo_entrada_nombre,
tb.nombre as tipo_bien_nombre, 
b.nombre as elemento_nombre,
b.marca,
b.serie, 
b.cantidad, 
b.unidad_medida, 
b.valor_unitario,
b.porcentaje_iva_id,
b.descuento,
m.observacion,
sg.codigo,
sg.nombre,
CASE
	WHEN coalesce(m.detalle ->>'tipo_contrato', '') = '' THEN 'N/A'
	ELSE m.detalle ->>'tipo_contrato'
END tipo_contrato,
CASE
	WHEN coalesce(m.detalle ->>'contrato_id', '') = '' THEN 'N/A'
	ELSE m.detalle ->>'contrato_id'
END contrato_id
FROM movimientos_arka.movimiento m,
movimientos_arka.formato_tipo_movimiento t,
acta_recibido.acta_recibido a,
acta_recibido.soporte_acta s,
acta_recibido.elemento b,
acta_recibido.tipo_bien tb,
catalogo.subgrupo sg
WHERE m.detalle ->>'consecutivo' = ?
AND t.id = m.formato_tipo_movimiento_id
AND a.id = CAST(m.detalle ->>'acta_recibido_id' as INTEGER)
AND s.acta_recibido_id = a.id
AND b.soporte_acta_id = s.id
AND tb.id = b.tipo_bien_id
AND b.activo = TRUE
AND sg.id = b.subgrupo_catalogo_id;

**Comment by ludwinggsanchez** [comment]
El reporte queda como sigue:

![image](https://user-images.githubusercontent.com/35748918/109350206-1ed0a980-7845-11eb-9e35-1a50505de9d6.png)
