### ISSUE TITLE
En el modulo de registrar una entrada ocultar la columna de estado del acta

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#520]
Se debe quitar la columna de estado del acta en la tabla cuando se esta registrando una entrada pues todas las actas que aparecen en este modulo ya estan en estado aceptada, la issue debe cumplir con el siguiente requerimiento:

- [x] Quitar la columna estado en la tabla del submódulo de registrar entrada

**Comment by AlexFBP** [comment]
Se empieza a abordar el Issue a las 20:38
