### ISSUE TITLE
Ajustar la carga y la consulta en el modulo de acta de recibido el campo de persona_asignada del api de administrativo al api de terceros

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#521]
Se debe realizar el ajuste de la consulta de la información de la persona asignada actualmente se consulta la información del api de administrativa y pasar la consulta a terceros, dentro del api de terceros  hay un vinculación de contratistas para este campo, la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar una función a nivel de mid que consulte  todos los terceros con vinculación de contratista, la función debe retornar el nombre completo de los terceros con su documento de identificación para la vinculación definida.
- [x] Ajustar la carga en en el componente de registro de acta normal.
- [x] Ajustar la carga en el componente de consulta del acta.
- [x] Ajustar la carga en el componente de edición del acta.
- [x] Verificar que la consulta del acta se pueda ver por la persona asignada  (al iniciar sesion)

**Comment by AlexFBP** [comment]
Se empieza a abordar el *Issue*

**Comment by AlexFBP** [comment]
De manera similar a udistrital/arka_mid#95 y a udistrital/arka_mid#97, se traerán inicialmente los terceros que tengan asociado un registro en la tabla de vinculación ([modelo](https://github.com/udistrital/terceros_crud/blob/master/sql/Terceros_Schema.png)) en _tipo_vinculacion_id_ alguno de los siguientes tipos de vinculación (de la tabla de parámetros - [modelo](https://github.com/udistrital/parametros_crud/blob/master/sql/modelo_parametros_crud.png)) disponibles de la API de Parámetros:

```json
[
  {
    "CodigoAbreviacion": "CPS",
    "Descripcion": "CONTRATO DE PRESTACIÓN DE SERVICIOS",
    "Id": 290,
    "Nombre": "CONTRATO DE PRESTACIÓN SERVICIOS"
  },
  {
    "CodigoAbreviacion": "OPS",
    "Descripcion": "ORDEN DE PRESTACIÓN DE SERVICIOS",
    "Id": 291,
    "Nombre": "ORDEN DE PRESTACIÓN DE SERVICIOS"
  },
  {
    "CodigoAbreviacion": "PS",
    "Descripcion": "PRESTACIÓN DE SERVICIOS",
    "Id": 289,
    "Nombre": "PRESTACIÓN DE SERVICIOS"
  }
]
```

Todos los parámetros anteriores tienen como TipoParametroId.CodigoAbreviacion "TV" (Tipo de Vinculación)

**Comment by AlexFBP** [comment]
Para poder probar, se hizo un post a Terceros/Vinculación, así:
```json
{
  "Activo": true,
  "TerceroPrincipalId": {
    "Id": 94
  },
  "TipoVinculacionId": 290
}
```

El 94 en `TerceroPrincipalId` corresponde a utest01
Y el 290 en `TipoVinculacionId` corresponde a lo mencionado [arriba](#issuecomment-783853378) y a lo indicado por analista

**Comment by AlexFBP** [comment]
Con la vinculación agregada arriba, el controlador de Arka MID /terceros/tipo/contratista actualmente, a partir de los datos de identificación disponibles tanto por Terceros como por el MID de Autenticacion, retorna:

```json
[
  {
    "DataAutenticacion": {
      "Codigo": "",
      "Estado": "",
      "FamilyName": "password",
      "documento": "123456789",
      "documento_compuesto": "",
      "email": "utest01@test.com",
      "role": [
        "DOCENTE",
        "ADMIN_CAMPUS",
        "CONTRATISTA",
        "Internal/everyone",
        "Internal/selfsignup",
        "Application/utest01_DefaultApplication_SANDBOX",
        "ESTUDIANTE"
      ]
    },
    "DataTercerosDocumento": {
      "Numero": "1232443",
      "TipoDocumentoId": {
        "Activo": true,
        "CodigoAbreviacion": "RC",
        "Descripcion": "REGISTRO CIVIL DE NACIMIENTO",
        "FechaCreacion": "2019-11-07 20:38:40.911141 +0000 +0000",
        "FechaModificacion": "2019-11-07 20:38:40.911141 +0000 +0000",
        "Id": 1,
        "Nombre": "REGISTRO CIVIL DE NACIMIENTO",
        "NumeroOrden": 0
      }
    },
    "Tercero": {
      "Id": 94,
      "NombreCompleto": "prueba 3 Cliente Cliente Cliente",
      "PrimerNombre": "prueba 3",
      "SegundoNombre": "Cliente",
      "PrimerApellido": "Cliente",
      "SegundoApellido": "Cliente",
      "LugarOrigen": 824,
      "FechaNacimiento": "2019-12-01T05:00:00Z",
      "Activo": true,
      "TipoContribuyenteId": {
        "Id": 1,
        "Nombre": "PERSONA NATURAL",
        "Descripcion": "",
        "CodigoAbreviacion": "P_NATURAL",
        "Activo": true,
        "FechaCreacion": "2019-11-25 20:39:54.419232 +0000 +0000",
        "FechaModificacion": "2019-11-25 20:39:54.419232 +0000 +0000"
      },
      "FechaCreacion": "2019-12-02 01:23:24.972053 +0000 +0000",
      "FechaModificacion": "2021-01-28 10:41:44.928326 +0000 +0000",
      "UsuarioWSO2": "utest01"
    }
  }
]
```

**Comment by AlexFBP** [comment]
Finalmente, la información que se retornará será la siguiente:
```json
[
  {
    "Identificacion": {
      "Numero": "1232443",
      "TipoDocumentoId": {
        "Id": 1,
        "Nombre": "REGISTRO CIVIL DE NACIMIENTO"
      }
    },
    "Tercero": {
      "Id": 94,
      "NombreCompleto": "prueba 3 Cliente Cliente Cliente"
    }
  }
]
```

**Comment by AlexFBP** [comment]
Se logra traer de Terceros, y mostrar en el Cliente el contratista registrado [arriba](#issuecomment-785405405):
![image](https://user-images.githubusercontent.com/6588872/109453110-3a8fa780-7a1f-11eb-908b-9b376647efa6.png)

**Comment by AlexFBP** [comment]
De manera similar, se muestra la información de la persona asignada también desde la consulta de actas:
![image](https://user-images.githubusercontent.com/6588872/109460209-40d95000-7a2e-11eb-95b8-a4e8d4a22f87.png)
