### ISSUE TITLE
Ajustar en todas apis del proyecto arka II la librería de auditoria 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#536]
Se debe realizar el ajuste de la librería de auditoria en todos las apis (no cliente ) del proyecto, tener en cuenta los [repositorios](https://github.com/orgs/udistrital/teams/administrativa/repositories), la inclusión de la librería  se puede guiar del [repositorio ](https://github.com/udistrital/configuracion_api/blob/release/0.0.1/main.go#L42)de configuración api, la issue debe cumplir con los siguientes requerimientos:

- [x] Realizar el ajuste a todas las apis del team

**Comment by CristianDavidSanchez** [comment]
Se actualiza la libreria auditoría en las apis del proyecto.
