### ISSUE TITLE
Realizar un análisis técnico y análisis de las necesidades que se requieren para implementar el modulo de ajustes 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#540]
Se debe realizar un análisis técnico y análisis de las necesidades que se requieren para implementar el modulo de ajustes, revisar modelos de datos,  revisar posibles ajustes de apis para poder realizar el modulo de ajustes para cuando se debe ajustar una salida, un entrada con y sin una salida asociada y posiblemente ajustes a acta de recibido con cambio que cambien movimientos contables y los ajustes que no realicen cambios contables, la issue debe cumplir con los siguiente requerimientos:

- [x] Realizar un análisis técnico  y necesidades para poder implementar el modulo de ajustes
- [x] Realizar la documentación de los análisis y plantear una posible solución para la implementación 
- [x] Mantener informado al equipo de desarrollo, arquitectos con los posibles ajustes que se tengan que realizar y tener en cuenta las sugerencias

**Comment by AlexFBP** [comment]
## Tareas "De mantenimiento" (implicitas)

Antes de proceder con el desarrollo del Módulo de Ajustes, se trae a colación unas tareas de mantenimiento/ajuste previo al desarrollo del módulo de ajustes. Se tomó como punto de partida el informe presentado por el Ing. @ManuelMurillo ; sobre el cual se han realizando [comentarios](https://drive.google.com/file/d/1JIgl-ks29bR4zRPVoGm201qOU4_80PL_/view?usp=sharing) y se han identificado las siguientes:

- Por trazabilidad, agregar un campo "editado_por" en la tabla "historico_acta" de (1), con el objetivo de identificar al responsable de cada cambio de estado de cada acta

### Elementos Duplicados

Dado que hay información duplicada de elementos, tanto en (1) como en (3) (e incluso en (2) pero _parece_ estar en desuso actualmente) se plantea crear una API unificada para los Elementos, que podría extenderse para ser una API de Bienes y así ser el inventario en sí (que incluya todo tipo de bien muebles e inmuebles, materiales e inmateriales, etc...).
  
  Inicialmente sería pasar las tablas "elemento", "tipo_bien" y "estado_elemento", actualmente en (1) a una API dedicada a Elementos/Bienes, y cambiar los endpoint en MID y Cliente, donde sea necesario (si se pasan sin modificaciones).

  Para la tabla "elementos_movimiento" de (3) inicialmente se propuso moverla también como otra tabla, quizas simplemente como "movimientos" a la API de Bienes, quitando algunos campos con información duplicada

## Tareas identificadas por este Issue (explícitas)

De acuerdo a la [reunión con Contabilidad](https://drive.google.com/file/d/1hbGU1Jp_XkowF6K4NOUIdyg-YX0jOS-H/view) para aclaración de dudas, todo ajuste que implique un movimiento contable debe ser inamovible, inalterable; con el fin de mantener la trazabilidad de los movimientos contables

Lo anterior implica que es posible hacer las correcciones que sean necesarias, siempre y cuando se cree un nuevo movimiento por cada movimiento original que deba ser reversado. Y para cada movimiento, siempre deberá de usarse el plan actual de cuentas. Por ejemplo: Suponiendo que se realizó una entrada (con su respectivo movimiento contable), luego se cambió el plan de cuentas de tal manera que las cuentas para el movimiento (en este caso, el tipo de entrada realizado) ahora son otras, y Almacen decide (con justa causa) que hay que reversar/anular la entrada; se hará siguiendo el plan de cuentas vigente, usando las nuevas cuentas.

- Empezar a usar la [MID API de Movimientos Contables](https://github.com/udistrital/movimientos_contables_mid), de acuerdo a [la explicación](https://drive.google.com/file/d/1Ts-fQO38urNLym_lN351IdVb0Uga7T8H/view). Esta tarea se realizaría mayormente en el MID. Se propone que la primer semana se haga uno de los movimientos, y en la(s) siguiente(s) los demás
- Del lado del Cliente, hay que hacer los mock-up, que posteriormente usarían el desarrollo anterior

## Referencias

Nota: los modelos se irán actualizando conforme a #537

1. [Modelo CRUD Actas a la fecha](https://raw.githubusercontent.com/udistrital/acta_recibido_crud/4219b6ab247f549d305135aebd1da21da01cc7ec/models/model.svg)
2. [Modelo CRUD Catalogo a la fecha](https://user-images.githubusercontent.com/23342808/68551355-22cf8280-03da-11ea-8c25-4cb053a1513b.png)
3. [Modelo CRUD Movimientos Arka a la fecha](https://github.com/udistrital/movimientos_arka_crud/blob/develop/Modelo_datos_movimientos_arka.PNG)
