### ISSUE TITLE
Generación de comprobante de entrada

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#55]
Generar un archivo (PDF o XMLS) que contenga la información de la entrada registrada.

**Comment by Miavega** [comment]
Se realiza un ejemplo básico con los campos que mostraría un reporte. Aún no se aplican estilos ni formatos del SIGUD puesto que solo se desea mostrar los datos que traería el reporte. Queda pendiente aplicar formato del SIGUD.
![imagen](https://user-images.githubusercontent.com/23342808/64139514-c42ccd80-cdc6-11e9-82e7-5294ac83db8b.png)
Se dejan las siguientes observaciones:
- _**Entrada**_:  Consecutivo de la entrada
- _**Tipo Entrada**_: Tipo de entrada (Adquisición, reposición, etc...)
- **_Contrato_**: Número de contrato suscrito.
- **_Fecha Creación_**: Fecha en que se registra la entrada.
- **_Fecha Reporte_**: Hace referencia al momento en que se genera el documento.
- **_Proveedor_**: Nombre del proveedor de los elementos de la entrada.
- **_Observaciones_**: Observaciones realizadas al momento de realizar la entrada.
El archivo generado por Knowage Report Designer:

[pruebaEntradas.zip](https://github.com/udistrital/arka_cliente/files/3567478/pruebaEntradas.zip)

**Comment by mafeave** [comment]
Se debe revisar cómo consumir los datos que vienen de otros sistemas, por ej: los datos asociados al contrato para las entradas por adquisición, esta tarea se realizará mediante el issue #70
