### ISSUE TITLE
Revisión documentación módulo de gestión de inmuebles.

### ISSUE THREAD

**Issue by ludwinggsanchez** [udistrital/arka_cliente#550]
A partir de la información proveída por la analista @mcrubianot, [Documentación bienes inmuebles](https://app.diagrams.net/#G1mgS4NLTH8D6zfiXsWBLE4Pxu-cvPkMSr), proponer la implementación del mismo en el sistema ARKA II.

**Comment by AlexFBP** [comment]
Pendiente colocar fotos y/o documento de la revisión

**Comment by ludwinggsanchez** [comment]
-El análisis se realiza considerando que un bien inmueble se puede gestionar de manera similar que los bienes muebles, mediante el api de acta de recibido.
-El objetivo de este módulo, es que se puedan gestionar los bienes inmuebles poseídos por la universidad. Más adelante, éste debe permitir registrar los avalúos a cada uno de los mismos.
-Al igual que los elementos muebles, los mismos están asociados a una clase del catálogo escogido por la universidad CCE y mediante este, asociado a la respectiva cuenta contable.

**Comment by ludwinggsanchez** [comment]
-En particular, los bienes inmuebles tienen las siguientes características particulares:
* Soportes (Escrituras, Matrícula inmobiliaria, Registro en catastro)
* Tipo de terreno (Residencial, Urbano, Comercial, ...)
* Tipo de edificación (Casa, edificio, lote, ...)
* Servicios públicos (Alcantarillado, Gas natural, Internet, ...)
* Descripción de la edificación (Alcobas, Oficinas, Muros, Acabados, ...)
* Planos

**Comment by ludwinggsanchez** [comment]
Los requerimientos del módulo son los siguientes:
-Realizar un primer registro que dé lugar a la posterior gestión del bien.
-Regustrar las características del bien inmueble.
-Registrar la información asociada a los distintos avalúos del bien.

**Comment by ludwinggsanchez** [comment]
### acta_recibido_crud
*En el api acta_recibido_crud es donde se hace el registro del inmueble mediante un acta para posteriormente realizar la gestión respectiva.
*Estas actas se caracterizan porque todos sus elementos son de tipo bien inmueble.
*Se debe agregar la columna **espacio_fisico_id** a la tabla de elemento, para asociar el inmueble al api oikos_crud.
*En la tabla paramétrica tipo_bien, agregar una fila con el tipo de bien inmueble.

**Comment by ludwinggsanchez** [comment]
### oikos_crud
-Cuando se registra un acta con un nuevo inmueble, se debe rcrear un registro del elemento en el api oikos_crud.
-En este api, se propone que se agregue lo siguiente:
*En la tabla **campo** se agregar filas para almacenar características como el área, área construida, descripción de la edificación, dirección, matrícula inmobiliaria, ....
*Se propone crear dos tablas paramétricas:
tipo_terreno: Almacena los tipos de terrenos (Residencial, Urbano, Comercial, ...)
tipo_edificación: Almacena los tipos de edificación (Casa, edificio, lote, ...)
*Agregar las columnas tipo_terreno_id y tipo_edificacion_id a la tabla de espacio_fisico

**Comment by ludwinggsanchez** [comment]
![oikos](https://user-images.githubusercontent.com/35748918/111108768-7fd7cd00-8527-11eb-86bb-28b10833c2f3.png)
