### ISSUE TITLE
desarrollo funcionalidades tabla consulta de entradas

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#553]
Desarrollo de funcionalidades para la tabla de consulta en el modulo de entradas, se debe presentar los filter y sort funcionales en esta tabla.

**Comment by CristianDavidSanchez** [comment]
Issue finalizada, se genero todo el flujo para la entrada de reposición con la función generada en el mid que relaciona las placas con los encargados, se elimina el campo de importación.
