### ISSUE TITLE
Ajustes al modelo de datos de movimientos y entradas, de acuerdo a revisión de arquitectos y DBAs.

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#56]
Ajustar el modelo de datos de movimientos y entradas, conforme las observaciones de los DBA's si es necesario.

**Comment by Miavega** [comment]
Se realizan cambios en el modelo de datos y se ajusta el API [entradas_crud](https://github.com/udistrital/entradas_crud/tree/update/controllers). El proceso se refleja en los commits: 
- [4b3708b](https://github.com/udistrital/entradas_crud/commit/a273995a95563cb04ad9f67cbe36a7de52210af0)
- [dc429de](https://github.com/udistrital/entradas_crud/commit/dc429de8c38ec928c669f228806e3b93e3077c72)
- [a273995](https://github.com/udistrital/entradas_crud/commit/a273995a95563cb04ad9f67cbe36a7de52210af0)

**Comment by Miavega** [comment]
El modelo de datos final es el siguiente: 

![entradas_final](https://user-images.githubusercontent.com/23342808/63897028-7b85a680-c9b9-11e9-932a-19c68bfbff42.png)
El archivo PgModeler:

[entradas_final.sql.zip](https://github.com/udistrital/arka_cliente/files/3553125/entradas_final.sql.zip)

**Comment by Miavega** [comment]
Se realizan ajustes al modelo: [b10bc14](https://github.com/udistrital/entradas_crud/commit/b10bc14f60c3687a04879efb04151d8d2dfe07b2)

**Comment by mafeave** [comment]
Se verifican los ajustes realizados.
