### ISSUE TITLE
Revisión historias de usuario Salidas

### ISSUE THREAD

**Issue by juandavidvelezaalvarez** [udistrital/arka_cliente#565]
- [x] Revisar la historia de usuario de salidas y compararla con lo desarrollado actualmente
- [x] Asistir a las reuniones de aclaración de dudas sobre esa historia
- [x] Crear documento de tareas globales especificas pendientes sobre salidas

**Comment by juandavidvelezaalvarez** [comment]
Se revisaron las historias actuales contra lo actualmente desarrollado.  Lo desarrollado está acorde con la historia pero esa historia no está aprobada y se hizo una [reunion](https://drive.google.com/file/d/1OXW5i8ed3sviFAI_dsNXyZxkLsh9UbQi/view)   con la mesa de trabajo para mostrar lo que hay y escuchar sugerencias.  Maria Claudia me dijo que iba a actualizar las historias para pasarlas a aprobación con base en lo que nos dijeron en la reunión.

Se asistió a la reunión. [reunion](https://drive.google.com/file/d/1OXW5i8ed3sviFAI_dsNXyZxkLsh9UbQi/view) de esa reunión salieron unos pendientes que ya enumero.

Tareas especificas de salidas que salieron en la reunión.

Tareas especificas de las salidas que salieron de las reuniones

Estas cuatro tareas.
Estado: las salidas deben tener estado como las entradas, los estados son: En Tramite, Aprobado. Anulado.  Solo se hacen movimientos de inventario y contabilidad al aprobar la salida.

Se debe agregar una parametrización de cuentas contables para salidas por elemento con los mismo conceptos existentes para entradas, porque en este momento solo hay un concepto para salidas.  Debe haber una parametrización de cuentas contables por cada tipo de entrada para salidas.

En la parametrización de cuentas contables de entradas hay pendiente un cambio surgido en la reunión, en la parametrización de cuentas contables de elementos se debe validas que para cada elemento todos los tipos de entrada tengan la misma cuenta debito.  Y esa cuenta debito debe ser la misma en todos los creditos al parametrizar las salidas.

Actualmente la placa se genera al momento de asignar el funcionario en la salida, esto está mal, debe generarse la placa es al momento de hacer la salida.

En [la mesa de trabajo general de ese día] (https://drive.google.com/file/d/160a-evShXui2-YnKhm7q3LSY6jL23ACW/view)  se definió hacer una mesa de trabajo solo con contabilidad para definir las dudas que yo tengo sobre contabilidad tanto de entradas como de salidas.

**Comment by CristianDavidSanchez** [comment]
Tareas especificas.

Tareas especificas de las salidas que salieron de las reuniones

- [ ] Estado: las salidas deben tener estado como las entradas, los estados son: En Tramite, Aprobado. Anulado. Solo se hacen movimientos de inventario y contabilidad al aprobar la salida.

- [ ] Se debe agregar una parametrización de cuentas contables para salidas por elemento con los mismo conceptos existentes para entradas, porque en este momento solo hay un concepto para salidas. Debe haber una parametrización de cuentas contables por cada tipo de entrada para salidas.

- [ ] En la parametrización de cuentas contables de entradas hay pendiente un cambio surgido en la reunión, en la parametrización de cuentas contables de elementos se debe validas que para cada elemento todos los tipos de entrada tengan la misma cuenta debito. Y esa cuenta debito debe ser la misma en todos los creditos al parametrizar las salidas.

- [ ] Actualmente la placa se genera al momento de asignar el funcionario en la salida, esto está mal, debe generarse la placa es al momento de hacer la salida.

- [ ] Otra tarea que resultó de esta reunión es explicarles en la próxima mesa de trabajo cual es el manejo que le damos a los dos tipos diferentes de elementos: los que se van gastando y los que salen de almacen para siempre en la salida.

- [ ] En [la mesa de trabajo general de ese día] (https://drive.google.com/file/d/160a-evShXui2-YnKhm7q3LSY6jL23ACW/view) se definió hacer una mesa de trabajo solo con contabilidad para definir las dudas que yo tengo sobre contabilidad tanto de entradas como de salidas.
