### ISSUE TITLE
Ajustes al flujo de entradas, tipo: reposición

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#567]
Continúa #552

De acuerdo a la HU se pide factura, ¿esto es correcto?
Corregir HU para poder ajustar el desarrollo

**Comment by mcrubianot** [comment]
Para este caso debemos confirmar con el usuario, por que creería que no, ya que la aseguradora debe enviar el documento remisorio o para entrega del bien.

**Comment by CristianDavidSanchez** [comment]
Con base en reunión con @mcrubianot  se define que la factura no debe ser ingresada en el formulario de entrada, debe ser agregada en formato pdf en el soporte del acta por lo tanto se procede a eliminar el campo de factura del formulario de reposición
