### ISSUE TITLE
Ajustes al desarrollo del módulo Registro de entradas, de acuerdo a reunión con el usuario programada para el 27 de agosto. 

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#57]
Ajustar el desarrollo del módulo de entradas conforme las observaciones que haga el usuario final en la reunión.

**Comment by Miavega** [comment]
Se ajusta el registro de entradas en el MID API: [f282e9c](https://github.com/udistrital/arka_mid/commit/f282e9c8a1cec23b98fbb994d463705ca8c9acad)

**Comment by mafeave** [comment]
Se verifica ajuste de la transacción para el registro de las entradas.
