### ISSUE TITLE
Agregar manejo de estado a las salidas En tramite y Aprobado a las salidas 

### ISSUE THREAD

**Issue by juandavidvelezaalvarez** [udistrital/arka_cliente#577]
Tarea para dos semanas: agregar a las salidas el manejo del estado en tramite, aprobación

- [x] Preguntar a Maria Claudia cuales deben ser las opciones de menus y forma de presentación, presentandole una propuesta
- [x] Agregar estado al movimiento de salidas
- [x] Editar salidas 
- [x] Implementar el manejo de estados, en que estado se puede modificar y en cual no. 

Relacionado con #565

**Comment by AlexFBP** [comment]
Revisar si el funcionamiento actual del tema de solicitudes de Bodega de Consumo, se pueda usar como ejemplo

**Comment by AlexFBP** [comment]
Por favor hacer un push del desarrollo hasta donde se alcanzó

**Comment by AlexFBP** [comment]
Mencionado en la [mesa del 7 de Julio](https://drive.google.com/file/d/1BoOsk3JFm0DeMITc84iOvHzLCufecAct/view)

**Comment by AlexFBP** [comment]
Se devuelve a Doing al no haber PRs que mencionen este Issue...

**Comment by AlexFBP** [comment]
Para el flujo de aprobación, tener en cuenta lo relacionado/mencionado en las [HUs de las Salidas](https://docs.google.com/spreadsheets/d/1iHOVhOvuJ4qNMRmNOakZ1hf2_vG8vNwLL57SNE7-moE/)

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
