### ISSUE TITLE
Propuesta de modulo: Gestión de avalúos

### ISSUE THREAD

**Issue by CristianDavidSanchez** [udistrital/arka_cliente#579]
Se debe analizar y generar un documento con la descripción de la información que se  utilizará de oikos y bienes, para empezar con los mock-up

**Comment by CristianDavidSanchez** [comment]
### Aspectos importantes: 

- Aún no se define la finalidad del modulo de avalúos y por ende su funcionalidad, por entre tanto el usuario debe definir de manera completa el requerimiento.
- Se realiza una revisión de los avalúos realizados a los bienes inmuebles de la universidad en el año 2018 por parte de la analista @mcrubianot donde se revisa un posible flujo, a su vez la parte descriptiva está contemplada en el modulo de bienes inmuebles.
### Procedimiento propuesto:
Una vez realizado el análisis del documento de avalúos en el ejemplo de la callle 40, se define que la información que aparentemente es de vital importancia es la definida en esta tabla:
![image](https://user-images.githubusercontent.com/45292213/112506507-d5984a80-8d5b-11eb-94e2-4040763abe8d.png)

Aparentemente los avalúos en general poseen esta estructura, la cual resume una lista de procedimientos.
Dado que el avaluó se realiza sobre un bien registrado, a un acta, y la propuesta establecida en: #550  es la de registrar los bienes inmuebles en la tabla de elementos de acta de recibido, y la asignación de bienes muebles ya se encuentra en esta api. a criterio personal considero que la mejor opción es añadir un campo llamado avaluo_id a la tabla elemento en el api acta_recibido_crud cuyo modelo se postea a continuación:
![image](https://user-images.githubusercontent.com/45292213/112507438-a1715980-8d5c-11eb-8e53-b409d15b364a.png)
Adicionalmente, esta key debe ser foránea a una nueva tabla llamada avaluo_elemento, que a su vez registrara por cada sede el avaluó de sus edificios y el subtotal avaluado. Se sugiere por el momento que se realice el registro del avaluó en formato json pues aun no es clara la información que requiere el usuario.

### API's

- Las api's de las cuales se propone hacer uso corresponden a acta_recibido_crud  con la finalidad de registrar el avaluó asociado a cada elemento.

- oikos_crud con la finalidad de extraer el número de edificios y la respectiva información que posee el bien inmueble registrado.

**Comment by CristianDavidSanchez** [comment]
A continuación se adjunta un breve análisis del avalúo de la sede calle 40 :
![image](https://user-images.githubusercontent.com/45292213/112509136-2f9a0f80-8d5e-11eb-998e-f805eff612fa.png)
En amarillo se observa la información que se encuentra en oikos relacionada a cada tipo de bien inmueble, por ende nos era registrada nuevamente en avaluos.
En verde y azul celeste información relacionada a como se realiza el proceso del avalúo del bien inmueble y en purpura el contenido más relevante para el modulo a desarrollar.

**Comment by CristianDavidSanchez** [comment]
Propuesta de mockup actualizada, a espera de aprobación por mesa de trabajo, Se genera propuesta interoperativa con bienes inmuebles #603.
https://drive.google.com/drive/folders/11obo9ocZOoadm27bgTAiPAkKDx5wbwbU?usp=sharing

**Comment by mcrubianot** [comment]
Se realizó la revisión de caso, haciendo algunas observaciones las cuales fueron tenidas en cuenta por los desarrolladores
