### ISSUE TITLE
Ajustar la parametrización contable para que todos los tipos de entradas tengan la misma cuenta debito

### ISSUE THREAD

**Issue by juandavidvelezaalvarez** [udistrital/arka_cliente#581]
- [x] Bloquear todos los debitos de las cuentas de tipos de entrada esceptuando la del primer tipo de entrada no se pueden editar
- [x] Al seleccionar la cuenta debito del primer tipo de entrada se deben actualizar las cuentas debitos de los otros tipos de entrada con esa misma cuenta

Esta tarea se basa en los requerimientos realizados por contabilidad durante el analisis de la opción de salidas
https://github.com/udistrital/arka_cliente/issues/565

**Comment by juandavidvelezaalvarez** [comment]
Los días seis y siete de julio estuve trabajando en la fusión de la parametrización contable. Durante estos dos días estuve buscando por qué no permitía grabar la parametrización.  Ya sé por qué.

Al hacer la fusión se encontró un problema en la implementación que viene desde antes de la fusión, ya verifiqué y el problema viene desde antes, el problema se da cuando se crean nuevos movimientos contables, al no existir para el subgrupo el programa no permite grabar la parametrización del subgrupo.

Para ver el problema: 
Movimientos Kronos:
curl -X GET --header 'Accept: application/json' --header 'Authorization: Bearer 5c4aa890-cb00-303c-98ce-ee0f848e17df' 'https://autenticacion.portaloas.udistrital.edu.co/apioas/arka_mid/v1/catalogo_elementos/movimientos_kronos'

Cuentas del subgrupo pruebacristian en el catalogo prueba_data:
curl -X GET --header 'Accept: application/json' --header 'Authorization: Bearer eacd6c7e-cfdd-30bd-9b72-b90ff91f232c' 'https://autenticacion.portaloas.udistrital.edu.co/apioas/catalogo_elementos_crud/v1/cuentas_subgrupo?query=SubgrupoId.Id%3A4334%2CActivo%3Atrue%2CSubtipoMovimientoId%3A34&limit=100'

En el subgrupo pruebascristian no existe el movimiento "Entrada anulada por medio del módulo de ajustes", que tiene el id 34

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
