### ISSUE TITLE
Analizar como se podría implementar el modulo de Parametrizacion

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#588]
Antes de proceder con #483, hay que mirar la posibilidad de que se pueda aprovechar el [cliente de configuracion](http://pruebasconfiguracion.portaloas.udistrital.edu.co/). Por ejemplo, revisar si hay la posibilidad de, por ejemplo, mostrar en Arka un link que lleve al cliente de Configuracion (a los roles adecuados), de tal manera que el cliente de configuracion muestre únicamente los parámetros/acciones/menus asociados a Arka.

De no ser posible, levantar requerimientos sobre la posibilidad de mostrar unicamente los parametros y permisos de acciones/menus segun rol, asociados a la aplicacion `arka_ii_main` de la [API de Configuracion](https://github.com/udistrital/configuracion_api/blob/dev/sql/configuracion_schema_v2.png), y su relación con los roles

**Comment by ludwinggsanchez** [comment]
### Módulo gestión de administración
Se establece que este módulo se encarga de restringir/asignar funciones a los usuarios dependiendo del rol de los mismos.
Este trabajajo ya se ha venido realizando en #594 #566.
Para este módulo, se debe continuar reflejando de manera ordenada y clara las diferentes funciones de modo que cuando se quiera hacer alguna modificación a los roles, baste con cambiar la asignación mediante el cliente de configuración.

**Comment by ludwinggsanchez** [comment]
### Módulo gestión de parametrización
Se establece que este módulo se refiere a la administración de los registros en las tablas paramétricas. Se proponen dos tipos de cambios:

1. Cambios que no afectan el flujo actual

- Activar/Desactivar tipos de bien
- Cambiar nombre tipos de bien
- Cambiar nombre estado de actas
- Activar/Desactivar tipos de entradas
- Cambiar nombre tipos de entradas

2. Cambios que requieren ajustes al flujo actual:

-Agregar tipo de bien: Se requiere agregar una columna en esta tabla que indique si al tipo de bien se le debe asignar placa o no y así determinar si el tipo de bien es suceptible de ir al kárdex.
-Agregar/Eliminar estado de acta: Cuando se desactive alguno de los estados de acta, se requiere que se cree uno con el mismo numero_orden. Crear un estado adicional sin más, no permitiría la integración del mismo en el flujo del registro de acta.
