### ISSUE TITLE
Mockups del procedimiento ingreso por compra og

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#6]
Realizar el diseño del mockup para el procedimiento de ingreso por compra og (Ordenador de gasto)

**Comment by Miavega** [comment]
Se determinó que el procedimiento no hace parte del sistema ARKA sino que se consume por medio de argo por lo que se da por cerrado el issue.

**Comment by mafeave** [comment]
De acuerdo con información dada por @blacburn, se determina que este procedimiento hace parte del Sistema Argo, por lo tanto se suspende la realización de la tarea. La información del contrato o la orden de servicio correspondiente para el registro de la entrada por OG se debe consumir desde un servicio WEB de Argo.
