### ISSUE TITLE
Cargar reporte Knowage en cliente Angular 7

### ISSUE THREAD

**Issue by mafeave** [udistrital/arka_cliente#60]
Se debe realizar la inclusión del reporte generado #55 en el cliente de Arka (Angular 7), se debe usar el SDK de Knowage, tener en cuenta el siguiente componente: https://github.com/rajeevmc77/KnowageReportComponent

**Comment by mafeave** [comment]
Se verifica carga del reporte de entradas en Spagobi desde el cliente:
![image](https://user-images.githubusercontent.com/14035745/64496144-7e10b780-d267-11e9-9e97-f683503894f1.png)

@Miavega modificar el título del reporte en el formulario y agregar la opción en el menú del sistema.

**Comment by Miavega** [comment]
Se corrige el título del reporte en el formulario.
![imagen](https://user-images.githubusercontent.com/23342808/64561454-6b05f200-d310-11e9-8888-343f9fc9aef8.png)

**Comment by Miavega** [comment]
Se agrega en el menú del sistema la opción para entrar al componente de reportes.
![imagen](https://user-images.githubusercontent.com/23342808/64562093-cedcea80-d311-11e9-85e8-3b9dad47ef91.png)

**Comment by mafeave** [comment]
Realizados los ajustes solicitados, se da por finalizada la tarea.
