### ISSUE TITLE
Componente de parametrización para tipos de entradas

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#601]
- [x] Desarrollar componente paramétrico activar/desactivar tipos de entradas.

- [x] Ajustar la consulta de tipos de entradas disponibles para ser registradas, de modo que se permita registrar únicamente un tipo de entrada activo

**Comment by ludwinggsanchez** [comment]
Se propone agrupar los tipos de movimiento aprovechando la columna numero_orden de la siguiente manera:

- numero_orden = 1: Para entradas con factura
- numero_orden = 2: Para entradas sin factura
- numero_orden = 3: Salidas 
- numero_orden = 4: Bajas

Se debe revisar en caso que haya un nuevo tipo de salida.
