### ISSUE TITLE
Componente de parametrización de tipos de bien

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#602]
- [x] Desarrollar componente paramétrico para activar o desactivar tipos de bien
- [x] Ajustar select en componente de construcción de catálogo de modo que se pueda seleccionar únicamente entre los tipos de bien activos

**Comment by ludwinggsanchez** [comment]
Se asocia la columna _orden_ para agrupar los tipos de bien según si son asignables al kárdex o no, de modo que cuando se genere una salida, los elementos estén clasificados de esta manera de acuerdo al tipo de bien.
