### ISSUE TITLE
mock-ups bienes inmuebles

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#603]
Generar propuesta para el módulo de inmuebles.

**Comment by CristianDavidSanchez** [comment]
Se desarrolla una porpuesta interoperativa con el mockup de avalúos #579  que postula la posibilidad de generar todo en el modulo de bienes inmuebles
Propuesta:
https://drive.google.com/drive/folders/11obo9ocZOoadm27bgTAiPAkKDx5wbwbU?usp=sharing
