### ISSUE TITLE
mock-ups traslados

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#604]
Tomar como referencia el sistema de solicitudes que está en Bodega de Consumo (solicitud/consulta/respuesta)
- [x] mock-ups
- [x] revisar posibles ajustes a modelos de datos

**Comment by AlexFBP** [comment]
Queda pendiente colocar (enlaces a) la documentación derivada de este Issue

**Comment by juandavidvelezaalvarez** [comment]
https://app.diagrams.net/#G1mwRoyOnt_49JAnvNHg8mHN_-2goQv1Fy
