### ISSUE TITLE
ajustar flujo de ajuste de entradas en el modulo de ajustes

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#605]
- [x] Filtrar entradas y salidas según el acta seleccionada
- [x] Implementar anulación de la entrada con lo desarrollado en #592

**Comment by ludwinggsanchez** [comment]
-Se filtran las entradas y salidas correctamente, el filtro de las bajas queda pendiente. 
-En el cliente, el funcionamiento queda limitado hasta que el movimiento contable de la entrada sea registrado.
-Queda pendiente hacer la anulación de la salida y generar el documento.
