### ISSUE TITLE
Datos de Prueba

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#621]
Para que Almacen pueda hacer pruebas

**Comment by AlexFBP** [comment]
Se envió un correo con estos datos de prueba o quedaron consignados en algún documento? @ludwinggsanchez

**Comment by ludwinggsanchez** [comment]
Los datos de prueba quedaron consignados en el siguiente documento:

[Datos de prueba ARKA II](https://docs.google.com/document/d/1nSEYIwsobU551rGvCVkuomUUV4Fk-4U2_vmBoplCQOI/edit)

**Comment by AlexFBP** [comment]
Gracias @ludwinggsanchez . Se procede nuevamente a cerrar este Issue
