### ISSUE TITLE
Revisión Parámetros, Catalogo

### ISSUE THREAD

**Issue by CristianDavidSanchez** [udistrital/arka_cliente#632]
Revisión de que modulos son parametrizables y en que medida

**Comment by AlexFBP** [comment]
Algunos de los siguientes mencionan parámetros de Actas y Catálogo:
(editaré este mensaje para agregar más, si veo)
- udistrital/administrativa_cliente#498

**Comment by AlexFBP** [comment]
Clasificar los parámetros según el dominio
- **Parámetros bajo nuestro dominio**: Que controlamos directamente desde Arka - Ej: todo el catálogo, la asignación de cuentas, quizás los tipos de bien, etc.
- **Parámetros de dominio externo**: Que NO se cuadran desde Arka. Ej: tipos de IVA, cuentas contables en sí, etc.

**Comment by CristianDavidSanchez** [comment]
https://drive.google.com/file/d/1vzLm8BeysYi_1h5k9iHr2Yf1sQBXOnTz/view?usp=sharing
Reunión con maria c para concluir el analisis preliminar de parametros en arkaII hasta modulo de entradas

**Comment by CristianDavidSanchez** [comment]
Cambios Referentes a catalogo de elementos: 

1. Según la norma deben ir amortización y deterioro adicionales a Depreciación y valorización(a espera de reunión con contabilidad)
2. En el menú de elementos se tiene que cambiar la fecha de finalización, no es necesaria según HU
3. Tipos de movimiento: según reuniones con el líder técnico @AlexFBP , es necesario tener un registro local de tipos de movimiento en arka, lo que hace necesario un análisis del modelo de datos de movimientos_arka, además es necesario tener en cuenta que no es referente solo a entradas, si no a salidas y bajas también.

**Comment by CristianDavidSanchez** [comment]
https://autenticacion.portaloas.udistrital.edu.co/apioas/movimientos_arka_crud/v1/formato_tipo_movimiento?limit=-1
![image](https://user-images.githubusercontent.com/45292213/130679945-99c27c7a-c808-4ff6-90ac-6a2507b2b574.png)
A partir del analisis de movimientos_arkacrud  https://github.com/udistrital/movimientos_arka_crud/blob/develop/models/modelo.svg
en la tabla formato tipo movimiento para ser mas especifico, se encuentra que en esta tabla estan contenidos los tipos de movimiento, razón por la cual no es necesario incluir una tabla de tipo de movimiento, sin embargo es apropiado adicionar una tabla paramétrica que incluya si el movimiento es entrada salida baja o asociado a kardex. puede ser una adición de un campo o una tabla paramétrica.

**Comment by AlexFBP** [comment]
Posibles parámetros sobre los que Arka no tendría dominio:
- Vigencias - https://github.com/udistrital/presupuesto_cliente/issues/449

**Comment by AlexFBP** [comment]
Para los mockups de la parte parametrica, contemplar principalmente los siguientes casos:
- Parametros implicitos (transversales a Arka)
- Parametros fuera del dominio de Arka (puede ser simplemente una lista)
