### ISSUE TITLE
Revisar cargue de actas

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#639]
Al ir al módulo Acta Recibido > Consulta de Actas, no están cargando actas para el usuario "pruebadocente"

DevTools:
![image](https://user-images.githubusercontent.com/6588872/123500775-0e1f1d00-d606-11eb-9c3f-88fdac1756b3.png)

Logs en AWS:
```text
2021/06/26 03:34:21.427 [1;31m[E][0m [panic.go:969]  map[err:el usuario 'pruebadocente' no está registrado en WSO2 y/o no tiene roles asignados funcion:GetAllActasRecibidoActivas - autenticacion.DataUsuario(usrWSO2) status:404]
```

**Comment by AlexFBP** [comment]
![image](https://user-images.githubusercontent.com/6588872/124032338-12f51f80-d9be-11eb-86c3-b742befaf490.png)

**Comment by AlexFBP** [comment]
Al probar el token https://jwt.io/ de los usuarios de prueba, no viene un correo.
En cambio, si que viene lleno el campo "email" cuando se inicia sesión con una cuenta asociada a un correo personal
Ej, iniciar sesion con la cuenta para cargar papeles de contratacion

**Comment by CristianDavidSanchez** [comment]
Solución: Del token data ahora se extrae el email en lugar de el sub, ya se genera la petición de manera correcta
![image](https://user-images.githubusercontent.com/45292213/124162424-075c3400-da64-11eb-8537-442f6ef2f354.png)
