### ISSUE TITLE
Excel Carga Masiva con "datos reales"

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#643]
Para efectos de una validación general del estado actual del sistema, se requiere actualizar la plantilla de Carga Masiva con elementos que abarquen una gran cantidad de escenarios
- Elementos con/sin retención de IVA
- etc

**Comment by AlexFBP** [comment]
[Plantilla (Drive)](https://docs.google.com/spreadsheets/d/1D1I2Cnb2c4yqrgSR5mjeOwHKrg2kdH9t/edit#gid=528416806)

**Comment by mcrubianot** [comment]
Se elimina la nota anterior que yo había incluido por que no corresponde a este proyecto y de acuerdo a las observaciones planteadas en la nota del ingeniero AlexFBP, se valida la información en la plantilla de cargue y se actualiza.

https://docs.google.com/spreadsheets/d/1D1I2Cnb2c4yqrgSR5mjeOwHKrg2kdH9t/edit#gid=528416806

Se hacen pruebas en el entono de pruebas con un ejercicio el día de hoy. Se diligencia el respectivo formato de aplicación de pruebas

https://docs.google.com/spreadsheets/d/1xVns6w29ZpP39TcBuzzIWt5J63iCd_7YxoubznMcpIw/edit#gid=0

Es pertinente indicar que no se logró concluir la tarea teniendo en cuenta los errores presentados al momento de elaborar un acta de recibido
