### ISSUE TITLE
Ajustar permisos rol secretaria/auxiliar

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#645]
En el formulario de registro de actas, practicamente todo lo tiene que diligenciar el contratista, hay pocas cosas que puede cambiar el rol "secretaria"

Tener en cuenta:
- Rol 1: Actualmente SECRETARIA. Actualmente puede trabajar actas solo con estado Registrada
- Rol 2: Actualmente CONTRATISTA. Actualmente puede trabajar actas en estado En Elaboracion y En Modificacion (y únicamente si le fueron asignadas)
(En lo posible, confirmar/homologar los roles según #685)

Los campos en el recuadro son obligatorios para el rol SECRETARIA
![image](https://user-images.githubusercontent.com/6588872/125487020-3785d645-5dfc-4800-b025-06683b090c2d.png)
![image](https://user-images.githubusercontent.com/6588872/125487103-69ac8eaa-d63b-43a7-8271-cb59995821c7.png)
Los otros campos actualmente los puede/debe diligenciar SECRETARIA pero ahora debe diligenciarlos el contratista

Confirmar con [las HUs](https://drive.google.com/drive/u/2/folders/1mAmRv9O2d8W8dRJ0JaVWoTgp_ex5snbE)

Cambiar el comportamiento/los permisos, de tal manera que cuando a los Roles anteriores les corresponda editar un acta:

- [x] Los campos "de la izquierda" serán opcionales para ambos roles, pero para rol 2 serán obligatorios para poder enviar el acta a verificación
- [x] Los campos "de la derecha", enmarcados en las imagenes de arriba en rojo; serán obligatorios para el Rol 1

**Antes de poder realizar lo anterior**, hay que desligar "el campo de arriba" (combinacion roles/estados/permisos) en "dos campos":
- [x] Identificar el(los) parámetro(s) (de configuracion_crud) asociado a los permisos que se requieren para editar los campos de ambas imágenes en función de los roles y estados-de-acta
- [x] Hacer que "el" parámetro que actualmente se usa, aplique solamente para los campos "de la derecha"
- [x] Para los campos "de la izquierda" crear "un" parámetro adicional

**Comment by ludwinggsanchez** [comment]
Adicionalmente, se presentan los siguientes inconvenientes a nivel de modelo de datos en el api acta_recibido_crud:

1. Tabla acta_recibido: 

- Columna ubicacion_id: Se deben permitir valores nulos.
- Columna acta_especial: Se requiere agregar esta nueva columna dado que por este guardado temporal ya no hay manera de identificar las actas especiales, por lo que el modelo quedaría como sigue:

![acta_recibido_v5](https://user-images.githubusercontent.com/35748918/126114526-05b2064c-3d5f-4b19-a634-85ba8e2ac9f4.png)

**Comment by AlexFBP** [comment]
Lo anterior debe revisarse con John y/o DBAs

Adicional/Complementariamente; en vez de agregarse una columna de Acta Especial, podría considerarse en vez de un booleano, una clave foranea de una nueva tabla "tipoActa". A los IDs de esta nueva tabla adicionalmente podrían vincularse los tipos de entrada que se pueden asociar y así se podría, por un lado, dejar de trabajar con estos valores "quemados", y por otro lado, facilitaría considerar la parte paramétrica relacionada con esta gestión

**Comment by CristianDavidSanchez** [comment]
![image](https://user-images.githubusercontent.com/45292213/126241668-aa6639b8-119f-4e66-ae9e-64b2afaee51d.png)
Solucionado error de usuario de prueba para  utest, debido a registros repetidos en terceros relacionados a los documentos asociados a este usuario. conflictuaba con el mid.

**Comment by ludwinggsanchez** [comment]
Fueron ajustados los permisos para actas en estado En Modificación_
