### ISSUE TITLE
Descuento general de acta de recibido

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#65]
Revisión y ajustes del desarrollo para descuento general de acta de recibido (registro y edición)

- [x] Registro

- [x] Edicion

**Comment by ManuelMurillo** [comment]
Se referencia el commit en el cual se hizo la agregacion del descuento a travez del componente de capturar-elementos

https://github.com/udistrital/arka_cliente/commit/e6639eb98648eccb8b004cefa87e35586231729e

**Comment by mafeave** [comment]
Se da por finalizada la tarea.
