### ISSUE TITLE
Corregir duplicidad intangibles

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#651]
Hay dos "Intangibles"

![image](https://user-images.githubusercontent.com/6588872/124021171-da9b1480-d9b0-11eb-8798-1732f4eab5bc.png)

Eliminar duplicidad o completar
(Primero mirar qué pasó, posiblemente haya sido alguna migracion)

**Comment by AlexFBP** [comment]
Aparentemente esto va de la mano con los inconvenientes encontrados en el desarrollo de #581

**Comment by juandavidvelezaalvarez** [comment]
Este problema se debe a que el tipo de entrada está duplicado en los movimientos

Api ArkaMid - v1

Endpoint
catalogo_elementos/movimientos_kronos

 curl -X GET --header 'Accept: application/json' --header 'Authorization: Bearer 89b294c6-f2ea-3d69-a59e-3bd567f913db' 'https://autenticacion.portaloas.udistrital.edu.co/apioas/arka_mid/v1/catalogo_elementos/movimientos_kronos'


![image](https://user-images.githubusercontent.com/52647570/125819136-d7b1d34a-e2da-4e3d-8fd6-f008e011e6e2.png)

Solución propuesta
Inactivar uno de los dos.

**Comment by AlexFBP** [comment]
Realizar la solución propuesta, aunque sería de manera temporal. Se abrirá un nuevo Issue para abordar este problema en detalle

**Comment by juandavidvelezaalvarez** [comment]
Se ejecuta la solución propuesta:
curl -X PUT --header 'Content-Type: application/json' --header 'Accept: text/plain' --header 'Authorization: Bearer 40985c7e-5fa8-3c88-a0db-8df5ab7d6c82' -d '{   "Id": 31, \ 
       "Nombre": "Desarrollo interior", \ 
      "Descripcion": "Entrada Intangibles Desarrollados al interior de los entes", \ 
       "Acronimo": "e_arka", \ 
       "Activo": false, \ 
       "FechaCreacion": "0001-01-01T00:00:00Z", \ 
       "FechaModificacion": "0001-01-01T00:00:00Z", \ 
       "Parametros": ""}' 'https://autenticacion.portaloas.udistrital.edu.co/apioas/movimientos_crud/v1/tipo_movimiento/31'

Se verifica exitosamente que el problema se haya solucionado temporalmente como era la meta del issue.

**Comment by AlexFBP** [comment]
Se cierra de acuerdo a [lo indicado](#issuecomment-880875752)
