### ISSUE TITLE
Registro Actas, no carga proveedores

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#652]
El autocompletar no funciona y/o funciona a veces
![image](https://user-images.githubusercontent.com/6588872/124023255-5c8c3d00-d9b3-11eb-9c5d-a44563332732.png)

**Comment by CristianDavidSanchez** [comment]
![image](https://user-images.githubusercontent.com/45292213/125137747-ee422b80-e0d2-11eb-835f-8c489e35fce7.png)
Solucionado sin embargo surgió otro error al guardar ese registro 
![image](https://user-images.githubusercontent.com/45292213/125137833-16318f00-e0d3-11eb-9765-8550cf0bdbc8.png)
Parece estar relacionado con autenticación, por lo pronto el error de carga ya no está
