### ISSUE TITLE
Quitar entradas Crear si ya hay accion en Consultar

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#656]
- [x] ~~Crear Catalogo~~ --> Listar Catalogo
![image](https://user-images.githubusercontent.com/6588872/124028023-2356cb80-d9b9-11eb-99c0-73ac4432379c.png)
- [x] ~~Registrar Entrada~~ --> Consultar Entradas
![image](https://user-images.githubusercontent.com/6588872/124027939-0d490b00-d9b9-11eb-9822-2a4bf31d9c5d.png)
- [x] De la mesa del 27/07/21, se observa que cuando la pantalla es ligeramente estrecha, el menu tapa por defecto el contenido. Mejorar el comportamiento, podría ser inicialmente que al dar click en cualquier parte del contenido, cuando la interfaz sea "angosta" el menú se oculte automáticamente

Entrega estimada: 10/sep/21

**Comment by CristianDavidSanchez** [comment]
Para los items 1 y 2 no es posible editar el menú en el cliente de configuración ni realizando la petición delete directamente al api @corio27 .
![image](https://user-images.githubusercontent.com/45292213/129962532-be2d9480-a247-497f-a960-0c8819beb769.png)
Se sugiere un campo de activo e inactivo en la tabla menu_opcion para evitar la eliminación del registro en caso de no ser usado, sin embargo es necesario ajustar el metodo delete en dicha api para poder culminar la issue.

**Comment by AlexFBP** [comment]
Tomar como referencia https://github.com/udistrital/central_cuentas_cliente/issues/135#issuecomment-904988164

**Comment by CristianDavidSanchez** [comment]
https://drive.google.com/file/d/1KvFbUfskxBuT7T_ZGVTMsTOvFBzeHBP1/view?usp=sharing

mockup aprobado

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial y al comportamiento a la fecha
