### ISSUE TITLE
Notificacion de alerta Acta Recibido

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#66]
Notificación de alerta que indique que se registró exitosamente el acta de recibido (edición, registro, etc.)

- [x] Registro

- [x] Edicion

- [x] Verificacion

**Comment by mafeave** [comment]
Se verifica ajuste en el registro:
![image](https://user-images.githubusercontent.com/14035745/64530490-e5b01c80-d2d2-11e9-9386-0e7f8a02f901.png)

**Comment by mafeave** [comment]
Se verifica mensaje de alerta cuando se hace envía el Acta para verificación por parte del encargado de Almacén
![image](https://user-images.githubusercontent.com/14035745/64531148-602d6c00-d2d4-11e9-8d08-a0ac67698970.png)

**Comment by mafeave** [comment]
Revisar edición y aprobación del Acta de recibido
