### ISSUE TITLE
Que los reportes no carguen solo en Firefox

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#660]
- [x] De acuerdo a lo informado por Jhon, cambió el host/ url-base para spagobi. Actualizar las peticiones para que funcione con la nueva URL
- [x] Una vez actualizadas las peticiones, validar si se pueden abrir en Firefox
- [x] Validar si se pueden abrir en navegadores distintos a Firefox
- [x] Ajustar según sea necesario

Tiempo estimado faltante: 3d

**Comment by ludwinggsanchez** [comment]
Se crea el registro del reporte para la nueva versión de SpagoBI. Se adjunta reporte visualizado en la nueva versión de la plataforma.

![image](https://user-images.githubusercontent.com/35748918/125179333-5cf6b600-e1b3-11eb-96a1-3398b4acaada.png)

**Comment by ludwinggsanchez** [comment]
Se realizan los cambios necesarios para embeber el reporte y que no dependa del navegador. Queda pendiente completar el flujo de autenticación para que el reporte sea visualizado.
![image](https://user-images.githubusercontent.com/35748918/125179530-6fbdba80-e1b4-11eb-9223-55ea4adebe0a.png)

**Comment by AlexFBP** [comment]
Si entiendo bien, que en spagobi se hacen consultas SQL, sería posible almacenar estas consultas ([ejemplo](https://github.com/udistrital/arka_cliente/issues/617#issuecomment-826528554)) como [VIEW](https://www.postgresql.org/docs/9.2/sql-createview.html)s?

De tal manera que se puedan consultar, tanto por APIs como por spagobi...

**Comment by AlexFBP** [comment]
Revisar si algo de lo mencionado en #60 aún sirve... Dentro de lo que se menciona, se encuentra esto: https://github.com/rajeevmc77/KnowageReportComponent/tree/master/src/knowageAPI/knowagesdk

**Comment by ludwinggsanchez** [comment]
Con el cambio desplegado en #792, se resuelve la autenticación.

![image](https://user-images.githubusercontent.com/35748918/134972498-7e90f94d-ac18-47ab-a845-8aa5664cad9c.png)

Aún se debe resolver:

- La carga del documento está muy lento (alrededor de 30 segundos).

![image](https://user-images.githubusercontent.com/35748918/134972563-9fd1c6c7-b796-4d43-b414-f17a0c760359.png)

- El reporte no carga correctamente la primera vez.

**Comment by ludwinggsanchez** [comment]
Se actualiza el query según los cambios a los modelos de acta y catálogo:

`SELECT s.consecutivo as consecutivo_factura, 
m.detalle ->>'consecutivo' consecutivoM,
m.fecha_creacion,
a.id as acta_recibido_id,
t.nombre as tipo_entrada_nombre,
tb.nombre as tipo_bien_nombre, 
b.nombre as elemento_nombre,
b.marca,
b.serie, 
b.cantidad, 
b.unidad_medida, 
b.valor_unitario, 
b.subtotal, 
b.porcentaje_iva_id, 
b.valor_iva, 
b.valor_final,
b.descuento,
m.observacion,
sg.codigo,
sg.nombre,
CASE
	WHEN coalesce(m.detalle ->>'tipo_contrato', '') = '' THEN 'N/A'
	ELSE m.detalle ->>'tipo_contrato'
END tipo_contrato,
CASE
	WHEN coalesce(m.detalle ->>'contrato_id', '') = '' THEN 'N/A'
	ELSE m.detalle ->>'contrato_id'
END contrato_id
FROM movimientos_arka.movimiento m,
movimientos_arka.formato_tipo_movimiento t,
acta_recibido.acta_recibido a,
acta_recibido.soporte_acta s,
acta_recibido.elemento b,
catalogo.tipo_bien tb,
catalogo.subgrupo sg,
catalogo.detalle_subgrupo dsg
WHERE m.detalle ->>'consecutivo' = ?
AND t.id = m.formato_tipo_movimiento_id
AND a.id = CAST(m.detalle ->>'acta_recibido_id' as INTEGER)
AND s.acta_recibido_id = a.id
AND b.acta_recibido_id = a.id
AND sg.id = b.subgrupo_catalogo_id
AND dsg.subgrupo_id = sg.id
AND tb.id = dsg.tipo_bien_id
AND dsg.activo = TRUE
AND b.activo = TRUE;`

**Comment by ludwinggsanchez** [comment]
> Si entiendo bien, que en spagobi se hacen consultas SQL, sería posible almacenar estas consultas ([ejemplo](https://github.com/udistrital/arka_cliente/issues/617#issuecomment-826528554)) como [VIEW](https://www.postgresql.org/docs/9.2/sql-createview.html)s?
> 
> De tal manera que se puedan consultar, tanto por APIs como por spagobi... Y adicionalmente se podrían manejar/documentar con/como migraciones Beego...

Se puede considerar hacer una migración creando ese view, habría que confirmar si los views están permitidos por la arquitectura actual.

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
