### ISSUE TITLE
Duplicidad Bajas

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#661]
Las siguientes entradas son confusas:
![image](https://user-images.githubusercontent.com/6588872/124033674-dd513600-d9bf-11eb-9b94-5b1f8203a232.png)

- [x] Identificar cuales realmente se necesitan
- [x] Con lo anterior, proponer el reordenamiento
- [x] Reordenar y/o eliminar entradas según se indique

Entrega estimada: 10/sep/21

Referencias
- udistrital/administrativa_cliente#554

**Comment by CristianDavidSanchez** [comment]
Propuesta de refactor de movimientos: https://drive.google.com/file/d/1KvFbUfskxBuT7T_ZGVTMsTOvFBzeHBP1/view?usp=sharing

**Comment by AlexFBP** [comment]
Dado el VoBo de Almacén, por favor proceder con el reordenamiento (Ajustar, bien sea por API o por el cliente de pruebasconfiguracion)

Menú a la fecha:
![9aFkoygYou](https://user-images.githubusercontent.com/6588872/132962641-eb3aa191-0235-443b-8327-7948bd530138.png)

**Comment by CristianDavidSanchez** [comment]
https://drive.google.com/file/d/1KvFbUfskxBuT7T_ZGVTMsTOvFBzeHBP1/view?usp=sharing

Mockup aprobado

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
