### ISSUE TITLE
Revisión MockUps Traslados

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#667]
Confirmar lo realizado en https://github.com/udistrital/arka_cliente/issues/604 por @juandavidvelezaalvarez 

Tiempo estimado faltante: 2 dias

**Comment by ludwinggsanchez** [comment]
[Mock-up traslados](https://app.diagrams.net/#G1mwRoyOnt_49JAnvNHg8mHN_-2goQv1Fy)

**Comment by ludwinggsanchez** [comment]
- La evaluación del mock-up se hace teniendo en cuenta que el mismo se realizó en Mayo cuando la HU se hizo a finales de Julio

**Comment by ludwinggsanchez** [comment]
### Cambios requeridos

El mock-up actual contempla que no se hagan solicitudes sino que el traslado es registrado por el personal del almacén e inmediatamente queda aprobado. Según la historia de usuario, la solicitud es realizada por un `funcionario de dependencia`

1. Funcionario de dependencia

Registro de solicitud:

- Los elementos se filtran por ubicación
- Agregar campo de cargo del tercero
- Agregar campo de correo electrónico del tercero

Consulta de solicitudes

La tabla debe incluir lo siguiente:
- Consecutivo
- Fecha de solicitud
- Solicitante
- Revisor
- Estado
- Acciones (ver detalle)

2. Funcionario de almacén

Aprobar solicitud, la lista de solicitudes debe incluir lo siguiente:

- Consecutivo
- Fecha de solicitud
- Solicitante
- Revisor
- Estado
- Acciones (aprobar)

Listar solicitudes:

Aprobar solicitud, la lista de solicitudes debe incluir lo siguiente:

- Consecutivo
- Funcionario
- Fecha de solicitud
- Fecha de visto bueno
- Revisor
- Estado
- Detalle
- Acciones (nueva solicitud)

**Comment by AlexFBP** [comment]
Realizar los ajustes al mock-up acorde a lo indicado por Analista

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
