### ISSUE TITLE
Desarrollo cliente cargue archivo plano

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#67]
Desarrollo cliente cargue archivo plano para el registro de elementos de forma masiva, de acta de recibido

- [ ] Registro

- [ ] Edicion

**Comment by ManuelMurillo** [comment]
a travez del MID se genera un issue para la carga y conversion del archivo de excel (*.xlsx) 
https://github.com/udistrital/arka_mid/issues/1

**Comment by mafeave** [comment]
Se hace la prueba cargando archivo de excel con elementos y se verifica funcionalidad:
![image](https://user-images.githubusercontent.com/14035745/64529152-d9769000-d2cf-11e9-9d55-2529e8e8514f.png)

**NOTA:** Ajustar nombres de los botones
**NOTA:** Restringir el tipo de archivo admitido en el cargue masivo, se hizo la prueba cargando un archivo de tipo PDF, lo admite y sale mensaje de alerta indicando registro exitoso, pero por consola se genera error en el sistema:

![image](https://user-images.githubusercontent.com/14035745/64525361-4dac3600-d2c6-11e9-8ab1-6d869e1e993a.png)

**Comment by ManuelMurillo** [comment]
https://github.com/udistrital/arka_cliente/commit/e6639eb98648eccb8b004cefa87e35586231729e

Validacion agregada en el commit relacionado

**Comment by mafeave** [comment]
Se verifica ajuste solicitado.
