### ISSUE TITLE
Mostrar consecutivo asignado a Salida

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#672]
Al registrar una salida, solo se muestra un modal/*pop-up* "Salida Registrada", pero no se muestra en este el consecutivo asignado a esta nueva salida

- [x] ~~Preguntar a @mcrubianot sobre los consecutivos que deberían tener las salidas.~~ Tener en cuenta que hay dos tipos de salidas: Directa (al funcionario final) o a Bodega de Consumo (Almacén). Tener en cuenta lo mencionado al respecto en udistrital/administrativa_cliente#507
- [x] Identificar y Actualizar la llave i18n asociada al _pop-up_ para que incluya el consecutivo como variable

**Comment by mcrubianot** [comment]
Con respecto a los consecutivos se hace la consulta a la Sección de Contabilidad, estoy pendiente de la respuesta

**Comment by mcrubianot** [comment]
La respuesta de la Sección de Contabilidad es :

Ernesto Suastegui: el consecutivo de salidas lo establece la Sección de Almacén. Si ellos establecen un único consecutivo de salidas seria el H21. Si van a establecer mas de un consecutivo, en la contabilidad se le asignara un nuevo tipo de documentos

**Comment by mcrubianot** [comment]
Debemos entonces consultar en mesa de trabajo con la Sección de Almacén la decisión al respecto.

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
