### ISSUE TITLE
 Asociar Datos de Carga Masiva al Formulario

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#68]
Asociar los datos de elementos al formulario para el módulo registro de elementos de forma masiva, de acta de recibido

- [x] Registro

- [x] Edicion

**Comment by mafeave** [comment]
Restringir el tipo de archivo admitido en el cargue masivo, se hizo la prueba cargando un archivo de tipo PDF, lo admite y sale mensaje de alerta indicando registro exitoso, pero por consola se genera error en el sistema:

![image](https://user-images.githubusercontent.com/14035745/64525361-4dac3600-d2c6-11e9-8ab1-6d869e1e993a.png)

**Comment by mafeave** [comment]
Se verifica la carga del componente para el registro de los elementos. Se da por finalizada la tarea.
