### ISSUE TITLE
Revisar que Proveedor y Contratista carguen bien a la primera en Edicion de Actas

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#688]
Solucionar bug relacionado a la carga de contratistas en edición de acta de recibido

**Comment by CristianDavidSanchez** [comment]
![image](https://user-images.githubusercontent.com/45292213/125684992-b8ec1949-7d73-4e62-a506-9c2d0446f9af.png)

El bug se ve por la afectación de uno de los registros de prueba que aparentemente no tiene identificación, se implementa un control de error para este caso que el tercero no tenga este registro.

**Comment by AlexFBP** [comment]
Resolverlo con una consulta del correo a la tabla de información complementaria.
Tener en cuenta al pasar a producción que en producción solo están cargados los documentos

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial y al comportamiento actual del ambiente de pruebas
