### ISSUE TITLE
Ajustar los mockups de bodega de consumo

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#69]
Ajustar los mockups de bodega de consumo, de acuerdo a la revisión hecha por Yesenia de Almacén e Inventarios y solicitados en el [Acta No. 14](https://docs.google.com/document/d/1qZp99ahXmZ7enARMiyUHoG7ei79qKRtbGjLLODhxcQU/edit).

**Comment by Miavega** [comment]
Se realiza el ajuste del Mockup de [solicitud](https://www.draw.io/?state=%7B%22ids%22:%5B%22175Oivi4Xu_0gIkCPbfsjBcLvcOjtbHKo%22%5D,%22action%22:%22open%22,%22userId%22:%22104246491753395693148%22%7D#G175Oivi4Xu_0gIkCPbfsjBcLvcOjtbHKo) dadas las observaciones realizadas:
- Se añade un campo para añadir dependencia.
- Se añade un campo para añadir ubicación.

**Comment by Miavega** [comment]
Se realiza el ajuste del Mockup de [aprobación](https://www.draw.io/?state=%7B%22ids%22:%5B%221Y5qRpIpGuU49jquN3osTAlkzdwNO-bIl%22%5D,%22action%22:%22open%22,%22userId%22:%22104246491753395693148%22%7D#G1Y5qRpIpGuU49jquN3osTAlkzdwNO-bIl) dadas las observaciones realizadas:

- Se cambia el campo **_total_** por **_cantidad_**.
- Como observación se deja que aunque no se contempló en la reunión, se decidió añadir un campo **_elemento_** y **_detalle_** para que el campo _**cantidad**_ tuviera sentido ya que sin esto no se sabía a qué hacía referencia esta cantidad.

**Comment by Miavega** [comment]
Se realiza el ajuste del Mockup de [consulta](https://www.draw.io/?state=%7B%22ids%22:%5B%221-v5L-5EbJmE3kXbWaj2ADg7w2rnTDcmA%22%5D,%22action%22:%22open%22,%22userId%22:%22104246491753395693148%22%7D#G1-v5L-5EbJmE3kXbWaj2ADg7w2rnTDcmA) dadas las observaciones realizadas:

- Se agerega campo fecha y detalle

**Comment by mafeave** [comment]
Se revisan ajustes en conjunto con @mcrubianot, se da por finalizada la tarea.
