### ISSUE TITLE
Mejoras UI Actas

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#691]
- [x] 1. Al ver/editar/validar un acta, mostrar el estado actual
      ![image](https://user-images.githubusercontent.com/6588872/125795724-535ea333-159c-4fbe-9f2f-0ad801e69be5.png)
      (Puede estar relacionado con #696)
- [x] 2. Al registrar/editar un acta, indicar el peso máximo de cada soporte (Primero averiguar/probar si realmente hay algún limitante, y así no haya limite, indicarlo)
- [x] 3. ~~(Adicional a 2.) Actualmente solo se permite un soporte (esto podría cambiar a futuro), por lo que las instrucciones actuales no son claras en esto. Cambiar la redacción de las instrucciones asociadas al soporte, de tal manera que indique que (el usuario) deberá cargar un único PDF con todos los soportes en uno solo. Para no alterar lo que ya está respecto a i18n, crear una nueva clave i18n a ser usada por estas instrucciones provisionales~~

- [x] 4. ~~No hay botón "Volver" al ver un acta~~ :arrow_left: Probar que esto sea cierto, a la fecha al consultar acta (no editar) aparentemente si está, pero en pruebas que se hicieron ayer por alguna razón no apareció... Hacer varias pruebas (con actas en varios estados) y verificar que el botón de volver salga
- [x] 5. En el componente de cargue de elementos, ajustar para que cuando se asignen masivamente las clases (a los elementos chequeados), no se desmarquen los elementos (el checkbox total, de arriba, ya permite marcarlos/desmarcarlos todos)
- [x] 6. En el paso 3, mostrar el consolidado solo si hay 1 o más elementos cargados
- [ ] 7. Al validar un Acta, Cambiar el botón "validar" por "Aprobar", y de modo similar actualizar los diálogos que se muestran al dar click a este botón, dado que después de esto el acta quedaría en estado Aceptada. Comentar a Analista antes de proceder. - ESPERAR CONFIRMACIÓN ANTES DE PROCEDER
- [ ] 8. Al registrar un acta (ordinaria o especial), después del Estado (primer item de este Issue), indicar los tipos de entradas que se pueden asociar a esta acta (De confirmarse con Analista, depende de udistrital/acta_recibido_crud#61) - ESPERAR CONFIRMACIÓN ANTES DE PROCEDER
- [x] 9. (R1, Hallazgo 012) En los soportes, cambiar la descripción de la fecha del soporte, así: "Fecha ~~de Factura o~~ **del** Soporte"

Referencias:
- R1. [Formato permanente de pruebas funcionales](https://docs.google.com/spreadsheets/d/1iUcdL6snRZ8fZIJxX0eWfnPFe0meHOygYh-S6E_yFxQ/)

**Comment by juandavidvelezaalvarez** [comment]
Probé que el botón volver funcionara correctamente al ver actas en los siguientes estados: Aceptada, En Modificación, En Elaboración, Registrada

**Comment by AlexFBP** [comment]
Parece que el 7 y el 8 de pronto no es pertinente hacerlos, y mas bien de pronto hace falta un paso adicional al [flujo de aprobación de las actas](https://github.com/udistrital/arka_cliente/issues/363#issuecomment-749195130) que contemple la aprobación/rechazo por parte del jefe de almacén

Podríamos revisarlo @mcrubianot ?

**Comment by mcrubianot** [comment]
Voy a realizar las pruebas del caso y les comento

**Comment by mcrubianot** [comment]
7. Al validar un Acta, Cambiar el botón "validar" por "Aprobar", y de modo similar actualizar los diálogos que se muestran al dar click a este botón, dado que después de esto el acta quedaría en estado Aceptada. Comentar a Analista antes de proceder. - ESPERAR CONFIRMACIÓN ANTES DE PROCEDER

Lo que logro entender en este ítem es que ítem es que cada rol realiza una acción así
Secretaria - Asignar
Auxiliar I - Registrar
Auxiliar II - Verificar
Jefe Almacén - Aprobar

Entonces en el Botón 

![image](https://user-images.githubusercontent.com/50463422/133672768-d566c5b6-6737-4f67-906d-9c1472e0b7d9.png)

Se debería reflejar cada acción que realiza el rol.

![image](https://user-images.githubusercontent.com/50463422/133672759-a7c65b2f-9185-47f6-a6a6-8a2155ee2d9e.png)

**Comment by mcrubianot** [comment]
8. Al registrar un acta (ordinaria o especial), después del Estado (primer item de este Issue), indicar los tipos de entradas que se pueden asociar a esta acta (De confirmarse con Analista, depende de Parametrizar tipo de Acta acta_recibido_crud#61) - ESPERAR CONFIRMACIÓN ANTES DE PROCEDER

No entiendo la observación

**Comment by AlexFBP** [comment]
> 1. Al registrar un acta (ordinaria o especial), después del Estado (primer item de este Issue), indicar los tipos de entradas que se pueden asociar a esta acta (De confirmarse con Analista, depende de Parametrizar tipo de Acta acta_recibido_crud#61) - ESPERAR CONFIRMACIÓN ANTES DE PROCEDER
> 
> No entiendo la observación

@mcrubianot como actualmente tenemos dos tipos de actas (ordinaria y especial), se pensaba en mostrar al momento de registrar el acta, los tipos de entrada que se pueden asociar después, a esa acta

**Comment by mcrubianot** [comment]
En mi concepto me parece que no. Considero pertinente que lo defina el usuario

**Comment by AlexFBP** [comment]
> En mi concepto me parece que no. Considero pertinente que lo defina el usuario

Vale @mcrubianot , entonces tratemolo en mesa de trabajo :v:

Por otro lado, respecto a esto

> 1. Al validar un Acta, Cambiar el botón "validar" por "Aprobar", y de modo similar actualizar los diálogos que se muestran al dar click a este botón, dado que después de esto el acta quedaría en estado Aceptada. Comentar a Analista antes de proceder. - ESPERAR CONFIRMACIÓN ANTES DE PROCEDER
> 
> Lo que logro entender en este ítem es que ítem es que cada rol realiza una acción así
> Secretaria - Asignar
> Auxiliar I - Registrar
> Auxiliar II - Verificar
> Jefe Almacén - Aprobar
> 
> Entonces en el Botón
> 
> ![image](https://user-images.githubusercontent.com/50463422/133672768-d566c5b6-6737-4f67-906d-9c1472e0b7d9.png)
> 
> Se debería reflejar cada acción que realiza el rol.

- De momento entonces no ajustarlo, y tratémoslo en udistrital/administrativa_cliente#564 con calma

**Comment by juandavidvelezaalvarez** [comment]
Ya terminé todas las actividades aprobadas para hacer del issue.  El pantallazo de que no le quite el check a los elementos al asignar clase masivamente
![image](https://user-images.githubusercontent.com/52647570/133686942-53821c05-9086-44cb-8365-e378a28f2872.png)

**Comment by AlexFBP** [comment]
Se deja en HOLD este Issue mientras se decide cómo proceder con 7 y 8

**Comment by AlexFBP** [comment]
Las tareas no completas se confirma que no se requieren
