### ISSUE TITLE
Desligar los nombres de los estados (L10n) de las transacciones

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#696]
De la mano con lo desarrollado/documentado en #363
En las transacciones que se realizan en "Consultar Actas" al MID, los nombres de los estados están quemados en lo que retorna la transacción

- [x] ~~Confirmar con Analista (quien de ser necesario escalará a Almacén) si realmente es pertinente cambiar_(Confirmado en mesa del 27/07/21)_ el nombre del primer estado en que queda un acta, a "Borrador"? "Iniciada"?~~ De acuerdo a lo explicado, desde las mesas de trabajo del 10/08/21, ya no es necesario
- [x] Listar los ajustes necesarios en las APIs y en el Cliente, para que el MID no envíe quemado el nombre del estado, sino ~~solamente~~ al menos el id
- [x] Ajustar el MID

En el MID, y por retrocompatibilidad (temporal) implementar de tal manera que el parametro actual, el estado como string; se mantenga, y se agregue un parametro adicional, con el estado como objeto

Llegar solamente hasta el ajuste del MID, el cliente se podrá ajustar en #762. Una vez se ajuste el MID, se podrá considerar cerrado/finalizado este Issue

Fecha de entrega estimada: 07/sep/21

**Comment by ludwinggsanchez** [comment]
Los cambios en el cliente son:

- En el componente consulta-actas: cargar el label del filtro según el EstadoId
- Modificar las validaciones del estado, pasarlas de validar según el nombre al Id
- Modificar componente de edición, de modo que no se dependa del estado del acta que se envía desde el componente de consulta
