### ISSUE TITLE
Errores Transacciones Acta Recibido

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#698]
Teniendo en cuenta las referencias:
1. [Mesa Julio 13](https://drive.google.com/file/d/1jw3QyQdrI2y89a79kz39vWeqWde5RD7U/view)
2. [Exposicion a Viviana, Julio 15](https://drive.google.com/file/d/1Ok8H-aOmtHuSXmnZ0wzosOC9apcdjUDj/view)

- [x] En algunas actas que en el pasado tuvieron soporte pero por razones desconocidas permanece en Nuxeo; el "ojo" de ver el soporte se muestra en los componentes de ver/editar/validar un acta, por lo que al abrirlo aparece un Error 404. Para resolver esto, se recomienda en la inicialización de estos componentes hacer un "pre-chequeo" en Nuxeo del "soporte referenciado", de tal manera que se indique que el soporte está corrupto o que simplemente se asuma que no se cargó
- [x] Confirmar que después de corregido el anterior, en los componentes asociados (registrar-acta-especial/ver/editar/validar), que el botón de envío (a la siguiente etapa) se desactive si no se ha especificado el soporte. El único momento en que se debería "poder cambiar el soporte" (realmente, dejarlo en blanco) es solamente cuando está en estado Registrada, al dar en Guardar, pero deben de ser obligatorios para poder enviar a la siguiente etapa (contratista/proveedor). **En otras palabras:** Verificar que en efecto se esté desactivando el botón cuando el soporte esté vacío o corrupto
- [x] (R1, 24:40 y 39:29) Después de enviar a Proveedor/Contratista y Verificación (y posiblemente en otros estados), se observa que el acta fue enviada pero luego sale un Error 400... Asegurarse que no siga saliendo, al menos desde la rama develop, y comparar con lo que está en pruebasarka - Posiblemente tiene que ver con #705

**Comment by CristianDavidSanchez** [comment]
![image](https://user-images.githubusercontent.com/45292213/127199622-cf41a119-0d31-46db-a2c3-d150b8a855bd.png)
Al entrar a un acta registrada desde el componente de edición, sale un error al intentar descargar el soporte.

**Comment by CristianDavidSanchez** [comment]
![image](https://user-images.githubusercontent.com/45292213/127199984-41df24f6-f46e-4faa-969b-c9be7111f26c.png)
Con el PR  7d39330  se soluciona todas las cargas de soporte cuyo ID no se encuentre sin embargo el error mencionado anteriormente no parece estar relacionado. Dado que el eliminar un soporte es una opción y depende de una decisión del usuario y una autorización no se realiza automáticamente al detectar el error, en su lugar se realiza una advertencia como la mostrada en la anterior imagen que indica al usuario la situación actual para que el tome la decisión de eliminar este soporte en el componente de edición.

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
