### ISSUE TITLE
Revisar carga de soporte Knowage con información de otros sistemas.

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#70]
Revisar la manera en que se debe consultar y consumir la información proveniente de otros sistemas fuera de ARKA II para que sea visualizada en los reportes generados por SpagoBI.

**Comment by Miavega** [comment]
Se realiza el soporte teniendo en los sistemas que lo componen. Para esto se agregó en la BD los schemas de **_entradas_** y _**acta_recibido**_. Así mismo se hizo el análisis con sistemas externos sin embargo no se tuvo acceso a la BD por lo que aún no fue posible cargar el contrato asociado en el reporte, en caso de que exista. Se deja la observación de que se muestra el número de contrato pero no el tipo de contrato, si no es necesario, el reporte podría quedar así, de otra manera toca consultar el tipo de contrato ya que no es almacenado en la entrada.

**Comment by Miavega** [comment]
Un ejemplo de salida del reporte es el siguiente:
![imagen](https://user-images.githubusercontent.com/23342808/64494929-9d541880-d258-11e9-947c-7d066cbe61ff.png)

**Comment by Miavega** [comment]
El código de la consulta realizada para armar el reporte es el siguiente:
`SELECT 
e.consecutivo,
e.fecha_creacion, 
t.nombre, 
h.acta_recibido_id, 
e.contrato_id,
e.observacion, 
s.consecutivo, 
tb.nombre,
b.nombre, 
b.marca, 
b.serie, 
b.cantidad, 
b.unidad_medida, 
b.valor_unitario, 
b.subtotal, 
b.porcentaje_iva_id, 
b.valor_iva, 
b.valor_final`
`FROM 
entradas.entrada_elemento e, 
entradas.tipo_entrada t, 
acta_recibido.acta_recibido a, 
acta_recibido.historico_acta h, 
acta_recibido.soporte_acta s, 
acta_recibido.elemento b,
acta_recibido.tipo_bien tb`
`WHERE 
e.consecutivo = ?
AND e.tipo_entrada_id = t.id 
AND h.acta_recibido_id = a.id 
AND s.acta_recibido_id = a.id 
AND b.soporte_acta_id = s.id
AND b.tipo_bien_id = tb.id;`

**Comment by Miavega** [comment]
Queda pendiente definir el formato final que tendrá el reporte.

**Comment by mafeave** [comment]
Pendiente subida de la última versión del reporte a SpagoBI

**Comment by Miavega** [comment]
Se sube la última versión del reporte a SpagoBI y se consume desde el cliente:
![imagen](https://user-images.githubusercontent.com/23342808/64636752-fd1d0180-d3c7-11e9-8f55-34f2dc35074c.png)

**Comment by Miavega** [comment]
Se sube el archivo final de Knowage Studio:
[ReporteEntradas.zip](https://github.com/udistrital/arka_cliente/files/3597022/ReporteEntradas.zip)

**Comment by mafeave** [comment]
Se verifica subida de reporte en SpagoBI, se da por finalizada la tarea.
