### ISSUE TITLE
Catalogo: Fecha de Inicio y Fin no necesaria

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#700]
- [x] Revisar modelo actual
- [x] ~~Preguntar a Analista sobre udistrital/administrativa_cliente#497, especialmente en el propósito de la fecha de Inicio. Aclarar que por lineamientos de la OAS relacionados con Auditoría, todo registro debería tener una fecha de Creación, de tal manera que si lo que se pretende con el campo de "Fecha de Inicio" es guardar la fecha de creación, no sería necesario mostrarlo en el formulario, y por tanto, junto a "Fecha de Finalización" se podrían quitar del modelo~~ Confirmado en mesa de trabajo del 27/07/21
- [x] (*) Ajustar modelo del catálogo (Require VoBo de Jhon y/o DBAs)
- [x] (*) Ajustar API CRUD del catálogo
- [x] (*) Ajustar Arka MID
- [x] Identificar todo lugar que pueda haber sido afectado por CRUD o MID en el Cliente (Angular, este repo)
- [x] (*) Ajustar Cliente

Los ajustes (*) se harán una vez se estime el tiempo necesario para abordarlos

Adicionalmente, completar la parte de análisis técnico y estimación de tiempos de/en
- [x] #701 
- [x] #722

**Comment by ludwinggsanchez** [comment]
Según la historia de usuario, el campo de inicio cumple la misma labor de la columna existente fecha_creacion, por lo que se confirma que las columnas fecha_inicio y fecha_fin se deben eliminar:

![image](https://user-images.githubusercontent.com/35748918/127608285-a3b58013-1af6-4f26-a409-20f23fce0d54.png)

**Comment by ludwinggsanchez** [comment]
Se propone que los cambios en los APIs y el cliente relacionados a este issue se unifiquen con los realizados en [Inactivar Elementos](https://github.com/udistrital/arka_cliente/issues/701)

**Comment by ludwinggsanchez** [comment]
### Las actividades en los repositorios son las siguientes:

### catalogo_elementos_crud

- Generar el script de la migración
- Actualizar el modelo elemento

### arka_mid

- Actualizar modelo ElementoCatalogo

### arka_cliente

- En el componente registro-elementos actualizar el template y la construcción de la transacción del post

Tiempo estimado: 1-2 días

**Comment by AlexFBP** [comment]
Visto bueno. Proceder con la implementación. Respecto a #701, hacer inicialmente los ajustes necesarios que permitan ajustar la columna "Activo", para priorizar los ajustes a modelos de datos sin implementar nueva funcionalidad. (Que todo siga funcionando casi igual)
Trabajar en otras ramas la nueva funcionalidad
