### ISSUE TITLE
Inactivar Elementos

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#701]
Actualmente no hay forma de desactivar elementos, se pueden crear pero no hay forma de desactivarlos
- [x] Identificar si es que la funcionalidad está pero llegó a ocultarse
- [x] Validar si en el modelo de Catálogo los elementos tienen el campo "Activo", agregarlo si no lo tiene
- [x] Ajustar el CRUD (si aplica)
- [ ] Ajustar el MID (si aplica)
- [ ] Crear vista en el cliente (si aplica)

Se sugiere trabajar esta funcionalidad en la vista de Registrar Elementos, hacer que la petición al MID se le pueda especificar un parámetro adicional (por ejemplo, un booleano) que cuando se especifique, en el árbol, la jerarquía que retorna de un catálogo también traiga los elementos asociados

**Comment by AlexFBP** [comment]
Por analogía al Clasificador de Bienes y Servicios de Colombia Compra Eficiente, la tabla de Elementos realmente correspondería a nivel "Producto"

**Comment by ludwinggsanchez** [comment]
La tabla elemento ya tiene la columna activo, no hace falta agregarla.

![image](https://user-images.githubusercontent.com/35748918/127601631-525a2ba9-52af-4018-8f7a-8dc85301fca7.png)

**Comment by ludwinggsanchez** [comment]
En el cliente NO existe componente para:
- Ver detalle de los elementos (Nombre, descripción y activo).
- Modificar elementos.

La funcionalidad actual del módulo de registrar elementos, consiste en que si se le da click a la fila de la clase, abre un formulario para registrar un nuevo elemento. Adicionalmente, en cada fila hay un botón para ver la lista de elementos.

![image](https://user-images.githubusercontent.com/35748918/127601880-2133d308-1710-415e-9aab-bffaa1170770.png)

**Comment by ludwinggsanchez** [comment]
Se propone que se cambie el nombre al menu _Registrar Elementos_ por _Gestionar Elementos_, y ajustar la funcionalidad del componente _registro-elementos_ de modo que permita:
- Agregar un nuevo elemento a una clase determinada
- Listar los elementos (y el detalle de los mismos) asociados a una clase
- Modificar los atributos de los elementos

Se sugiere que cuando se dé click a una fila, en lugar de mostrar el formulario para registrar un nuevo elemento, se listen los elementos asociados, dando la opción para editar cada uno de ellos y adicionalmente, un botón para agregar elemento.

**Comment by ludwinggsanchez** [comment]
Se sugiere que los cambios requeridos en #700 y #722 se unifiquen con los cambios de este issue y la tabla _elemento_ quede como sigue:

![image](https://user-images.githubusercontent.com/35748918/127609449-3c982e9d-d52b-4e1a-8e53-41137531181b.png)

Los cambios en el cliente y APIs deben considerar este modelo.
