### ISSUE TITLE
Quitar par de cuentas asociadas a Traslados de la interfaz

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#702]
En la transacción contable asociada a traslados, la cuenta crédito se puede especificar como la misma cuenta debito, lo único que cambiaría sería el tercero/propietario asociado.

- [ ] Confirmar con Analista (@mcrubianot ) lo anterior: si el movimiento de traslados se puede reflejar (contablemente) como un credito/debito de la misma cuenta, actualizando "unicamente" el responsable del elemento, y si esta "misma cuenta" anterior es la que corresponde a la salida
- [ ] Si se confirma lo anterior, el par de cuentas credito/debito que actualmente se pueden especificar en Catalogo > Asignación de cuentas para Traslados sería innecesario. Quitar el ingreso manual de estas cuentas.

Cuando se desarrolle la parte de traslados habrá de considerarse todo lo anterior

**Comment by mcrubianot** [comment]
Se envia correo a la Sección de Contabilidad con el fin de que sean ellos quienes nos den las indicaciones al respecto.

**Comment by mcrubianot** [comment]
Se recibe la siguiente respuesta

contab@udistrital.edu.co
--
para: | Maria Claudia Rubiano Torres <mcrubianot@udistrital.edu.co>
fecha: | 29 jul 2021 14:26
asunto: | RE: Inquietud para Arka II

Hola Maria Claudia, no el traslado no tiene impacto en los Estados financieros, por este motivo no creo que deba generarse un movimiento contable para esto, que es un control interno de la Sección de Almacen.

Cordial Saludo,

Ernesto Suastegui Molina

CPS

Sección de Contabilidad

**Comment by AlexFBP** [comment]
Vale @mcrubianot 
Creo que en su momento se había comentado que si en el movimiento de traslado implicaba cambiar el tercero, posiblemente sea necesario reflejar el movimiento, de acuerdo a
https://github.com/udistrital/financiera_documentacion/issues/313#issuecomment-542203550

**Comment by AlexFBP** [comment]
Posiblemente haya que mirar primero la lógica actual y mirar si es necesaria alguna migración en movimientos kronos.
Puede llegar a tener relación con #693

**Comment by AlexFBP** [comment]
Ya implementado
