### ISSUE TITLE
Elementos con serial solo deberían tener cantidad:1 y unidad: UNIDAD

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#707]
## Considerando

Actualmente se permite registrar elementos que tengan serial y a la vez una cantidad mayor a 1.

Lo ideal sería que cuando se especifique un serial, automáticamente se establezca/bloquee:
- la cantidad a 1 
- la unidad a UNIDAD

## Tareas

- [x] Confirmar lo anterior con Analista (@mcrubianot )
- [x] Ajustar componente de captura de elementos, para carga masiva
- [x] Ajustar componente de captura de elementos, para ingreso manual (Este componente debería realizar una validación adicional sobre lo que venga después de Carga Masiva)

**Comment by mcrubianot** [comment]
Se envía consulta a la Sección de Almacén en el siguiente sentido:


de: | Maria Claudia Rubiano Torres <mcrubianot@udistrital.edu.co>
para: | Almacén - Universidad Distrital <almacen@udistrital.edu.co>
Cc: | AYDA LUZ DONADO PEREZ <aldonadop@udistrital.edu.co>
fecha: | 29 jul 2021 15:15

Buenas tardes Ayda Luz, comedidamente nos permitimos solicitar tu colaboración en el sentido de confirmar estos dos datos:
1. Las placas que se asignan a los bienes solamente se generan en el momento de la salida, o existe algún otro evento en el que se deba asignar?
2. Solicitamos por favor la confirmación de la sintaxis que deberá tener la placa.

Muchas gracias, quedamos atentos
--
MARIA CLAUDIA RUBIANO TORRES
Oficina Asesora de Sistemas

**Comment by mcrubianot** [comment]
Se recibe la siguiente respuesta por parte de la Jefe de Almacén e Inventarios


de: | AYDA LUZ DONADO PEREZ <aldonadop@udistrital.edu.co>
-- | --
para: | mcrubianot@udistrital.edu.co
fecha: | 31 jul 2021 11:54
asunto: | Fwd: Consulta Arka II
enviado por: | udistrital.edu.co

Buenos días,
Maria Claudia 

Cordial saludo, en atención a su preguntas me permito responder lo siguiente:

1. Las placas que se asignan a los bienes solamente se generan en el momento de la salida, o existe algún otro evento en el que se deba asignar? 
RESPUESTA: las placas se generan en el momento de la salida de acuerdo a la información que arroja para la asignación en el inventario  al funcionario.
2. Solicitamos por favor la confirmación de la sintaxis que deberá tener la placa. 
Respuesta.(se adjunta un documento en word con la imagen de cómo se está generando actualmente las placas y la propuesta de cómo generar las placas sobre todo en los elementos que se relacione marca y serie)


Atentamente, 
Ayda Luz Donado P
Jefe Almacén General e Inventarios


![image](https://user-images.githubusercontent.com/50463422/127871595-e982ed71-d635-41e8-ab67-a91692bfdebe.png)

**Comment by AlexFBP** [comment]
Gracias @mcrubianot 

La pregunta iba encaminada en sí a la sintaxis de la placa, o sea, saber qué significa cada dígito en la placa
Digamos
![image](https://user-images.githubusercontent.com/6588872/130307324-ec3d8ac0-1d68-4212-afeb-7d8c25a01e16.png)

Si la sintaxis es clara, la solicitud de que "...LOS ELEMENTOS QUE TENGAN RELACIONADOS MARCA Y SERIE LES APAREZCA EN LA PLACA..." podría hacerse pero sería innecesaria...

**Comment by mcrubianot** [comment]
Considero que mañana en la mesa de trabajo se puede tocar este tema

**Comment by AlexFBP** [comment]
Se observa en el ambiente de pruebas que, de acuerdo al propósito original de este Issue, cuando el tipo de bien es Devolutivo (Requiere Placa) la cantidad ya queda bloqueada/ajustada en 1.
Previo a cerrar este Issue, faltaría bloquear/fijar la unidad de medida en "UNIDAD" (Actualmente es ajustable)
![image](https://user-images.githubusercontent.com/6588872/168977272-a394ff54-bd1b-412d-ab3a-ff67e18232cf.png)
