### ISSUE TITLE
Levantamiento Issues

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#721]
De las mesas de trabajo:
- [x] [27/07/21](https://drive.google.com/file/d/1KhvhgYTdslMxUFCr8M73uSQaVvG035Fb/view)
- [x] [21/07/21](https://drive.google.com/file/d/1nZ_J9mEgy8OU5aQeo2r8qQvgQnMpGRFc/view)

Anterior: #695

**Comment by AlexFBP** [comment]
De la mesa del 27/07/21:

Catálogo de Elementos:

- [ ] 3:31 - Quitar opcion de Añadir del menú
- [ ] 13:20 - Colocar código a los elementos - #722 
- [ ] 18:10 - Mostrar columna de Estado Activo/Inactivo en el Árbol de Catálogo, en Inactivar Niveles
- [ ] 22:06 (No mencionado) - (Mejora) Programar un timer o algo, o mejorar la interfaz para indicar que el cambio de estado (cuentas bloqueadas/en modificación) fue exitoso
- [ ] Asignación Masiva de Cuentas
- [ ] Reportes Dinámicos: Analizar y Estimar viabilidad técnica
- [ ] Histórico de Elementos: Analizar y Estimar viabilidad técnica
- [ ] Mostrar el nombre de la cuenta que se va a asignar
- [ ] Aclaración: En las salidas, la cuenta crédito es la misma cuenta débito de las entradas
- [ ] Aclaración: Tener en cuenta que todo movimiento debería bloquearse si implica cuentas vacías

**Comment by CristianDavidSanchez** [comment]
17-21

**Comment by AlexFBP** [comment]
De la mesa del 21/07/21

Bodega de Consumo

- [ ] (37) 12:57 (No mencionado) - Entradas raras en menú, se confunden las de bajas con movimientos
- [ ] (38) 16:18 (No mencionado) - El selector de dependencias (y otros) están cargando dentro de otra ventana. Migrar a componente Angular Material y tener en cuenta que la selección sea válida
- [ ] (39) - Preguntar a Analista si la sede/dependencia/ubicacion de una solicitud debe de poder llenarla el solicitante o traerse automaticamente (Confirmar con Almacen si los solicitantes deberían poder cambiar/establecer esta información)
- [ ] (40) 18:46 (No mencionado) - Al aprobar una solicitud, es confuso que se muestre "Salida Registrada". Debería mejorarse la redacción para que (adicionalmente) diga Solicitud Aprobada. También hace falta un diálogo de confirmación antes de hacer la solicitud. El diálogo aparece oculto por el spinner, posiblemente se podría arreglar cambiando al "dialogService" en vez de usar directamente swal
- [ ] (41) 19:18 - Se aprobó una solicitud (442) pero no se muestra en "Consultar Solicitudes", por qué?
- [ ] (42) 21:27 - Cambiar "Registro de Elementos" por "Registro de Productos" en analogía con el último nivel del [Clasificador CCE](https://colombiacompra.gov.co/clasificador-de-bienes-y-Servicios) para, en concordancia, actualizar las instrucciones del primer paso de Asignación a Kardex, mejorar la redacción
- [ ] (43) 22:08 - (No directamente mencionado) Hay fichas Kardex que no se pueden ver, por qué? Identificar qué pasó y realizar los ajustes necesarios en API(s) y Cliente. Lo ideal sería, así sea mostrar la información completa pero si realmente no hay nada (la ficha Kardex está vacía), pues borrarla...
- [ ] 27:28 (Duplicado de 37)
