### ISSUE TITLE
Código en Elementos

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#722]
(REVISAR PRIMERO LAS HUs)

Al momento de registrar elementos no se está especificando el código de producto

- [x] Revisar si el modelo actual lo permite
- [x] (Si aplica) Proponer cambios al modelo de Catalogo
- [x] (Si aplica) Visto Bueno de Jhon y/o DBAs
- [x] (Si aplica) Actualizar CRUD
- [x] (Si aplica) Actualizar MID
- [x] Actualizar Cliente

**Comment by AlexFBP** [comment]
Este Issue puede/debería desarrollarse en conjunto a #701

**Comment by ludwinggsanchez** [comment]
El modelo actual no contempla que un elemento tenga código:

![image](https://user-images.githubusercontent.com/35748918/127571805-f134d55c-eece-451e-a6fe-8758ec3e95ac.png)

**Comment by ludwinggsanchez** [comment]
El único cambio necesario es que se se adicione la columna codigo a la tabla elemento.

![image](https://user-images.githubusercontent.com/35748918/127572841-294ac6f0-6df5-425e-98bd-93ce638f678b.png)

**Comment by AlexFBP** [comment]
Adicionalmente retirar las columnas fecha_inicio y fecha_fin permitiría avanzar algo de #700 ...

**Comment by ludwinggsanchez** [comment]
Actualmente, dado el único componente en el cliente en el que se requieren cambios es el de registro-elementos, se propone que los cambios en los APIs y el cliente se unifiquen con los del issue [Inactivar Elementos](https://github.com/udistrital/arka_cliente/issues/701)

**Comment by ludwinggsanchez** [comment]
### Las actividades en los repositorios son las siguientes:

###  catalogo_elementos_crud
- Generar el script de la migración
- Actualizar el modelo elemento

### arka_mid
- Actualizar modelo ElementoCatalogo

### arka_cliente
- En el componente registro-elementos actualizar el template y la construcción de la transacción del post

Tiempo estimado: 1-2 días

**Comment by AlexFBP** [comment]
Porfa @corio27 ajustar migración:
![image](https://user-images.githubusercontent.com/6588872/130314110-b6788863-7b5f-46cf-bc16-b3bcc0279aba.png)

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial. Hay unos registros por purgar que se tratarán en #924
