### ISSUE TITLE
Contratista (Auxiliar I) no registra Actas

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#728]
Teniendo en cuenta
- #645 
- el [Documento de Roles](https://docs.google.com/spreadsheets/d/1PHKLrjMOSWAdB6eDNjxNvW4lMrQTTgecC7hlnZOLUV8/edit)
- El correo enviado a Almacén para pruebas
- Lo comentado en udistrital/arka_mid#165
- #363
- #696

- [ ] Ajustar configuracion_api para que al contratista no le aparezcan actas en estado "Registrada"

**Comment by CristianDavidSanchez** [comment]
![image](https://user-images.githubusercontent.com/45292213/128732312-bdee2049-0f53-4bfe-8c39-e688a4075c95.png)
 Solucionado desde api de configuración, el rol contratista o auxiliar 1 ya no puede registrar actas

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
