### ISSUE TITLE
Botones de consulta

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#73]
Ajustar los botones de consulta de la tabla de consulta para que no se superpongan en ningun navegador

- [x] Cambiar Estilos

- [x] Pruebas

**Comment by ManuelMurillo** [comment]
e6639eb98648eccb8b004cefa87e35586231729e en el siguiente commit se relaciona el cambio del estilo para la correcta vista de los botones

**Comment by mafeave** [comment]
Se verifica corrección del estilo de los botones.
