### ISSUE TITLE
Glitches Acta Recibido

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#730]
De la [mesa del 27/07/21](https://drive.google.com/file/d/1KhvhgYTdslMxUFCr8M73uSQaVvG035Fb/view)
- [x] 1:08:46 (no mencionado) - Acta 180 solo se pudo editar después de darle F5 (y posiblemente también la 181)

Del [Documento Macro de Hallazgos](https://docs.google.com/spreadsheets/d/1iUcdL6snRZ8fZIJxX0eWfnPFe0meHOygYh-S6E_yFxQ/):
- [x] Hallazgo 006 - Error 500 al listar actas con rol SECRETARIA (no aparecen actas, se queda cargando...)
- [x] Hallazgo 007, Item 3 - En cargue de elementos, al asignar clases, no está apareciendo el tipo de bien ni el código para clases 951015, 101212 ni 951115. De pronto tenga que ver con la validación del componente --> Mostrar (adicionalmente) # elementos seleccionados a la izquierda del checkbox total para ver si tiene que ver con la paginación
- [x] Hallazgo 008, Item 1 - En cargue de elementos, no se están dejando eliminar/borrar elementos

**Comment by CristianDavidSanchez** [comment]
![image](https://user-images.githubusercontent.com/45292213/132402584-96dbe774-0a46-4fc8-911e-4acda87118ea.png)
Errores 1 y 2 no fueron posibles de replicar, se sugiere si se presenta nuevamente alguno de los dos errores mostrar el flujo con el que se realizo para poder observar la causa del problema. por lo pronto las actas con rol secretaria cargan aparentemente bien, quedó pendiente a una replica del error.
  @mcrubianot

**Comment by CristianDavidSanchez** [comment]
![image](https://user-images.githubusercontent.com/45292213/132583432-fa07ca4b-af10-473f-8c09-6833d5768c3a.png)
Ya se encontraba solucionado el item 3 y 4 la issue al parecer fue más de verificación.

**Comment by ludwinggsanchez** [comment]
> debido a los recientes cambios en el modelo de datos referidos a [udistrital/acta_recibido_crud@ca7ed8a](https://github.com/udistrital/acta_recibido_crud/commit/ca7ed8a8c3629df31ae3a2a4630103f604b80bac)
> se observan ultiples cambios necesarios a nivel de arka_mid más puntualmente en el registro de elementos
> ![image](https://user-images.githubusercontent.com/45292213/132418107-ff813807-be40-4db8-80ca-1b8f8c587fae.png)
> se observa que para algunas actas se conserva el modelo de datos anterior pero para las más recientes y que no tengan elementos asignados o que se encuentren inactivos va a generar conflictos, posterior a arreglar el problema en el mid se sugiere una limpieza de base de datos pues la petición va generar errores en las actas antiguas pero soluciona las nuevas y más recientes @AlexFBP En la imagen se ve que la función del mid que consulta si un acta tiene elementos activos registrados está consultando una columna no relacionada con los elementos en el modelo actual: SoporteActaId
> 
> Nuevo estado solucionado en : [udistrital/arka_mid#172](https://github.com/udistrital/arka_mid/pull/172) sin embargo aún queda la duda de la redirección a la tabla inexistente SoporteActaId @ludwinggsanchez

Esa sección de código debe corresponder a una versión desactualizada de arka_mid

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial

**Comment by AlexFBP** [comment]
Se dejará abierto (y en Done) mientras se valida en el documento de hallazgos

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
