### ISSUE TITLE
Textos "rotos" (i18n/L10n)

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#734]
De la mesa del 27/07/21

- [x] (24) 1:05:20 - Texto "ver" i18n asociado al soporte, roto
- [x] (29) - texto validación ubicación roto...
- [x] (34) 1:15:40 - Texto de validación roto en Fecha de soporte y en Observaciones

Entrega estimada: 7/sep/21

**Comment by CristianDavidSanchez** [comment]
![image](https://user-images.githubusercontent.com/45292213/132250836-a3db06e0-767c-4e13-b426-d8847ba35ce0.png)
primer item ya estaba solucionado en pruebas .

**Comment by CristianDavidSanchez** [comment]
los global rotos parecen estar bien sin importar el rol, seguramente las correcciones ya fueron implementadas. se verifica tanto los códigos de globals como su implementación en el html y la sintaxis es correcta. se replica el ejercicio de la mesa de trabajo para observar si vuelve a suceder con el acta 182 pero no se observan globals rotos.

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
