### ISSUE TITLE
Mensajes de Alerta

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#75]
generar Mensajes de alerta de confirmacion en caso de generar algun movimiento en el acta de recibido y para la revision de valores de elementos para los componentes del acta

- [x] Eliminacion de elementos

- [x] Registro

- [x] Edicion

- [x] Verificacion

**Comment by ManuelMurillo** [comment]
Se relaciona tambien el redireccionamiento a la pagina de consulta de actas de recibido

**Comment by mafeave** [comment]
Se verifican los mensajes de alerta en el cliente. Se da por finalizada la tarea.
