### ISSUE TITLE
Optimizar Consulta de Arbol

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#752]
Continúa udistrital/catalogo_elementos_crud#78

El arbol de catalogo se trae mediante `tr_catalogo` en su totalidad, lo que hace que la consulta sea demorada sobretodo cuando se consulta el Catalogo de Colombia Compra Eficiente. Hacer que vaya trayendo según se vaya desplegando cada rama del arbol (que el arbol se cargue por demanda)

- [ ] Mirar si el componente de arbol permite hacer consultas parciales
- [ ] Ajustar/desarrollar para permitir consultas parciales

**Comment by AlexFBP** [comment]
@CristianDavidSanchez como es? como sería?

**Comment by CristianDavidSanchez** [comment]
Actualmente el sistema en los menús de asignación cuentas contables y de asignación de elementos hacen un get para traer todo el árbol de un catalogo especifico. La propuesta es limitar la búsqueda a las clases de cada catalogo para evitar la sobrecarga de datos. a continuación las razones de porque es viable 

1. La funcionalidad tanto de carga de elementos como de asignación de cuentas no se realizan nunca sobre una familia, segmento o grupo, está actualmente limitado a las clases que son el ultimo hijo del árbol
2. Actualmente existe una función que extrae las clases activas y con tipo de bien asignado, dicha funcionalidad se puede utilizar para asignar elementos únicamente a clases activas, mucho más simple en desarrollo que trabajar sobre el árbol pues no sería necesario usar arka_mid 
3.  La selección puede ser con el criterio de clase de un catalogo, por ejemplo Selecccione catalogo => CCE => muestra las clases activas asociadas al catalogo y permite que al dar click se puedan agregar los elementos.
4. En términos de usabilidad  es más cómodo para el usuario cuando se hable de multitasking si desea buscar varias clases para asignarles elementos la búsqueda por ramas resultaría más incomoda desde el punto de vista de usuario.
5. La afinidad con el propósito de asignación es mucho más clara pues la función solo se aplicaría sobre lo necesario (Las Clases)
