### ISSUE TITLE
Modelo de datos del módulo de gestión de catálogo de elementos 

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#76]
Se debe generar el modelo de datos en PgModeler para el módulo de gestión de catálogo de elementos. La tarea tiene una estimación de 6 horas

**Comment by mafeave** [comment]
Tener en cuenta modelo definido inicialmente para la gestión de catálogo
![image](https://user-images.githubusercontent.com/14035745/64648433-7f192480-d3e0-11e9-8bee-d5816e169780.png)

**Comment by mafeave** [comment]
Se consultan dudas sobre la definición del catálogo con el equipo de trabajo, https://github.com/udistrital/arka_cliente/issues/87

**Comment by Miavega** [comment]
Se revisa el modelo definido inicialmente y se propone un nuevo modelo con algunos ajustes:
![catalogo_elementos](https://user-images.githubusercontent.com/23342808/64749930-06e45900-d4dd-11e9-8940-36f761a8a0c7.png)
Se dejan dos observaciones en el modelo para su revisión.
El archivo pgModeler es el siguiente:
[catalogo_elementos.zip](https://github.com/udistrital/arka_cliente/files/3603466/catalogo_elementos.zip)

**Comment by mafeave** [comment]
Pendiente aprobación por parte de los arquitectos. Se da por finalizada la tarea.
