### ISSUE TITLE
Cuentas no están cargando

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#769]
[Hallazgo 003](https://docs.google.com/spreadsheets/d/1iUcdL6snRZ8fZIJxX0eWfnPFe0meHOygYh-S6E_yFxQ/)

Las cuentas no se pueden editar, aún estando en modo de edición de cuentas

- [x] Corregir, teniendo en cuenta el comportamiento esperado en los Issues relacionados

Issues anteriores y/o posiblemente relacionados:
- #727
- #581
- udistrital/contabilidad_cliente#113

Entrega estimada: 10/09/21

**Comment by juandavidvelezaalvarez** [comment]
Ya sé exactamente cómo ocurre el problema:
Es cuando se están visibilizando las cuentas con la configuración de cuentas bloqueada, si se habilita la configuración de cuentas con las cuentas ya en la pantalla no se pueden editar hasta que no se recarguen seleccionando otra clase, o otro catalogo.
El siguiente paso es que voy a hacer que el "habilitar" del campo de la cuenta esté ligado a la variable de edición de escritura en forma reactiva.

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial y al funcionamiento a la fecha del sistema
