### ISSUE TITLE
Generación del API CRUD del módulo de gestión catálogo de elementos

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#77]
Se debe generar el API CRUD del módulo de gestión de catálogo de elementos, incluyendo su configuración para despliegue en entorno local. La tarea tiene una estimación de 4 horas para su desarrollo.

**Comment by Miavega** [comment]
Se adjunta el modelo con el que se genera el API.

![catalogo_elementos](https://user-images.githubusercontent.com/23342808/64881213-cb9e7300-d61f-11e9-8f34-4de63234adcf.png)

**Comment by Miavega** [comment]
Se crea el API CRUD  para la gestión de catálogos de elementos. Se encuentra en el [repositorio](https://github.com/udistrital/catalogo_elementos_crud). Bajo los siguientes commits:
- [6ec683e](https://github.com/udistrital/catalogo_elementos_crud/commit/6ec683e5785e20b2e028542e1b9363d926326a48)
- [94d3a46](https://github.com/udistrital/catalogo_elementos_crud/commit/94d3a46347b2a711fbc8b57ef0c3429d36b5cf9d)
- [8a578c4](https://github.com/udistrital/catalogo_elementos_crud/commit/8a578c4e3af2f41f91c0095d60e94e86579c2239)

**Comment by mafeave** [comment]
De la revisión realizada se tienen las siguientes observaciones:
- Cambiar el nombre de las variables del archivo de configuración app.conf
- Eliminar binario catalogo_elementos_crud y agregarlo en el .gitignore

**Comment by Miavega** [comment]
Se realiza la corrección de las variables en el app.conf, en el docker-compose.yml y en el .env

**Comment by Miavega** [comment]
Se agrega el binario catalogo_elementos_crud al .gitignore

**Comment by mafeave** [comment]
Realizados los ajustes, se da por finalizada la tarea.
