### ISSUE TITLE
Consumir servicio unidades para el servicio de entradas

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#78]
Se debe consumir el servicio **_unidades_** en el módulo de entradas. La tarea tiene una estimación de 2 horas para ser completada.

**Comment by Miavega** [comment]
Se realiza el ajuste para consumir el servicio de unidades en entradas. Para esto fue necesario ajustar el APID MID y el cliente.

**Comment by Miavega** [comment]
Salida del MID API en Postman: 
![imagen](https://user-images.githubusercontent.com/23342808/64933296-38756100-d80a-11e9-8064-d0a85f07c570.png)

**Comment by Miavega** [comment]
Salida en el cliente: 
![imagen](https://user-images.githubusercontent.com/23342808/64933767-2b597180-d80c-11e9-9bcd-30fbcaa9af1f.png)

**Comment by mafeave** [comment]
Se verifica la consulta de la Unidad con el API de Administrativa, tanto desde el servicio del MID como desde el Cliente.
