### ISSUE TITLE
Registrar acta no avanza

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#782]
Tener en cuenta
- R1: [Documento general de Hallazgos de Arka II](https://docs.google.com/spreadsheets/d/1iUcdL6snRZ8fZIJxX0eWfnPFe0meHOygYh-S6E_yFxQ/edit#gid=481118634)

Para ajustar:
- [x] #786

**Comment by ludwinggsanchez** [comment]
Se verifica funcionamiento normal del api por vpn, se revisa swagger y una vez actualizado se resuelve el problema.

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
