### ISSUE TITLE
Ajustar icono de detalle en entradas

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#79]
Se debe ajustar el ícono de detalle en la consulta de entradas ya que no se visualiza bien en todos los navegadores. La tarea tiene una estimación de 1 hora para su desarrollo.

**Comment by Miavega** [comment]
Se realiza el ajuste del ícono de selección de acta y de detalle de entrada ya que presentaban el siguiente bug visual en algunos navegadores: 
![imagen](https://user-images.githubusercontent.com/23342808/64644486-5a20b380-d3d8-11e9-991b-6ebcf683d569.png)
A continuación se muestra su corrección en diferentes navegadores:
- Firefox
![imagen](https://user-images.githubusercontent.com/23342808/64644580-8b997f00-d3d8-11e9-9e65-9189b6804312.png)
- Chrome
![imagen](https://user-images.githubusercontent.com/23342808/64644589-9227f680-d3d8-11e9-884f-fc9a05f6eefc.png)

**Comment by mafeave** [comment]
Se verifica ajuste realizado. Se da por finalizada la tarea.
