### ISSUE TITLE
Mockups del procedimiento baja de bienes

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#8]
Realizar el diseño de los mockups del procedimiento baja de bienes:

- [x] Revisión del proceso

- [x] Diseño en angular de los campos necesarios para el formulario baja de bienes

- [x] Dar estilo al formulario

**Comment by Miavega** [comment]
En el siguiente [enlace](https://drive.google.com/drive/folders/1B6iow6vdffRmaHGl_tvsE2V0-cNySote) se suben las imagenes PNG correspondientes al proceso de baja de bien.

**Comment by mafeave** [comment]
Para la solicitud de baja:
Revisar cuáles son los posibles tipos de bajas, y cual sería la información a solicitar por cada uno.

Para la respuesta a las solicitudes de baja:
Agregar campo que indique si se aprobó o no la baja

**Comment by mafeave** [comment]
Debido a dudas frente al proceso, se da por finalizada la tarea. 
Se hará consulta con la persona encargada de Almacén para evaluar los mockups realizados hasta el momento, en caso de tener que hacer ajustes se creará un nuevo issue.
