### ISSUE TITLE
Eliminar mensaje de alerta al registrar la entrada

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#80]
Eliminar los mensajes de alerta que genera el módulo de entradas al momento de seleccionar un acta, ver los detalles y al registrar. La tarea tiene una estimación de 1 hora para su desarrollo.

**Comment by Miavega** [comment]
Se eliminan los mensajes de alerta que generan las acciones de consultar y registrar: 

![imagen](https://user-images.githubusercontent.com/23342808/64934047-d9b1e680-d80d-11e9-9c09-594d6b3fcb82.png)

Ahora el proceso continua normalmente sin ninguna alerta.

En el registro, se mantiene la alerta exitosa para que el usuario sepa que fue registrada, sin embargo se le añadirá la información correspondiente al registro para que sea mas clara la alerta. Se referencia esto en el [issue 83](https://github.com/udistrital/arka_cliente/issues/83)

**Comment by mafeave** [comment]
Se verifica realización del ajuste para eliminar el alert.
