### ISSUE TITLE
Revisión/Limpieza del Sistema a la fecha

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#800]
- [x] Validar/Ajustar/responder los [hallazgos](https://docs.google.com/spreadsheets/d/1iUcdL6snRZ8fZIJxX0eWfnPFe0meHOygYh-S6E_yFxQ/edit#gid=481118634) encontrados a la fecha (hasta el 28/09/21 - 020) - Entrega máxima: 29/09/21

**Edit 29/09/21 por @AlexFBP** :
De acuerdo a lo conversado/acordado, incluir los siguientes bugs de Asignación Contable:
- [x] Revisar la propagación/encadenamiento de cuentas. Debe ser únicamente entre las cuentas débito (izquierda) de las entradas, con la cuenta crédito de la salida
- [x] Revisar la condición disabled del botón de envío, Debería estar desactivado bajo cualquiera de las dos condiciones: cuentas en solo lectura o cuentas pendientes por llenar

**Comment by ludwinggsanchez** [comment]
- Se evidencia que todos los items fueron revisados excepto el 06 relacionado con el rol proveedor.
- Se debe revisar el flujo de asignación a proveedor. En el flujo actual, no hay validación de los campos de proveedor, ubicación, datos de los soportes ni subgrupo en los elementos. 
- No se puede permitir al rol SECRETARIA el envío a proveedor. 
- Se propone: que el rol SECRETARIA envíe únicamente al AUXILIAR I y luego este haga el respectivo envío al proveedor, una vez se halla llenado el formulario completo.

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
