### ISSUE TITLE
Marcar entradas por importación

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#81]
Se debe verificar el check para marcar las entradas cuando son por importación. La tarea tiene una estimación de 2 horas para su culminación.

**Comment by Miavega** [comment]
Se elimina el campo para añadir un número de importación ya que no es necesario:

![imagen](https://user-images.githubusercontent.com/23342808/64934423-50e87a00-d810-11e9-8d5a-23ab21e09f6f.png)

Ahora solo es necesario marcar la opción:

![imagen](https://user-images.githubusercontent.com/23342808/64934455-9016cb00-d810-11e9-9b60-4ca2765cbeae.png)

**Comment by Miavega** [comment]
Se corrige la tarea añadiendo la información necesaria en la consulta de la entrada:

![imagen](https://user-images.githubusercontent.com/23342808/65193012-039e1f80-da3f-11e9-9eab-80f5599efb36.png)

**Comment by Miavega** [comment]
Se deja como observaciones:

- La entrada por reposición no se desarrolla ya que depende de un elemento que ya haya tenido salida y aún no se puede realizar esto.

- La entrada por elaboración propia no se realiza aún, falta un campo en la BD que permita guardar el supervisor, sin embargo no se realiza aún a espera de si es necesario en verdad almacenar esta información.

- En la entrada por terceros, aunque ya funciona, no se guarda el tercero en administración (IDEXUD, CICD, I+3) puesto que aún no es claro si es posible que esta información la traiga el contrato, de ser así no es necesario guardarla, en otro caso, haría falta un campo más en la BD para guardar esta información.

- La vigencia se toma actualmente del año en curso, sin embargo se considera revisar esto ya que como observación, creería que se debe tomar la vigencia del contrato seleccionado. Ya que de esta vigencia depende la consulta de la información de dicho contrato.

**Comment by mafeave** [comment]
La vigencia no depende del contrato
