### ISSUE TITLE
Resolver Hallazgos Acta Recibido

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#810]
## Consideraciones y Referencias
- [Documento de Pruebas Funcionales](https://docs.google.com/spreadsheets/d/1iUcdL6snRZ8fZIJxX0eWfnPFe0meHOygYh-S6E_yFxQ/edit#gid=481118634)

## Ajustar Hallazgos
Del Documento de Hallazgos, Hoja "Hallazgos", revisar la columna M como consideraciones adicionales para resolver los siguientes hallazgos:

Nota: Entre paréntesis se indica si primero hay que validar, y/o la prioridad

- [x] 034 (P.Alta) - La acción de Anular un acta no es efectiva...
- [x] 019 (Validar - P.Alta) - No se están trayendo las cuentas, posible mala experiencia de usuario consecuencia de udistrital/arka_cliente#694
- [x] 027 (Validar - P.Alta) - Si únicamente se tiene rol de proveedor, el botón de Enviar a Verificación (o en general, a siguiente etapa) no debería ni mostrarse
- [x] 025 (P.Media) - En la plantilla, mostrar las columnas de Clasificación, indicando que son de "USO EXCLUSIVO DE ALMACÉN" (actualmente están ocultas)
- [x] 029 (P.Media) - En la plantilla, el descuento por defecto es cero, quitar la fórmula que hay. Si lo hay, lo debe especificar el usuario y/o auxiliar
- [x] 026 (Validar - P.Media) - A pesar que con el proveedor se están llenando todos los elementos, no se está habilitando el botón de pasar al siguiente paso
- [x] 020 (P.Baja) - En carga de elementos, la acción de borrar clases puede llegar a borrar otras clases...
- [x] 031 (P.Baja) - Indicar cuales son exactamente los errores (Revisar, en código se había dejado un bloque `<div>` preparado para mostrar los errores)
- [x] 017 (P.Baja) - Mejorar rendimiento de actas, posiblemente tiene que ver con los soportes, en caso que sea esto, mirar si se puede colocar un indicador de progreso (HOLD: Únicamente confirmar si es esto, los soportes. De ser así, deberá trabajarse en un Issue aparte lo del indicador de carga y acá realizar un ajuste mínimo/rápido)
- [x] 021 (Validar - P.Baja) - Que las actas se traigan ordenadas

**Comment by ludwinggsanchez** [comment]
- 034 Fue abordado en #811
- 019 Fue abordado en #804
- 027 Fue abordado en #811
- 029 Fue abordado en udistrital/arka_mid#177
- 026 Fue abordado en #811
- 020 Fue abordado en #804

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial y documento de pruebas funcionales
