### ISSUE TITLE
Mostrar comprobante contable una vez aprobada una entrada

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#817]
## Consideraciones
- [HU Comprobante Contable](https://github.com/udistrital/administrativa_cliente/projects/1#card-69264130)

## Dependencias
1. https://github.com/udistrital/arka_cliente/issues/657
2. https://github.com/udistrital/movimientos_arka_crud/issues/46
3. https://github.com/udistrital/arka_mid/issues/115

## Tareas
- [x] Crear un componente para la visualización del detalle de la transacción contable retornado por el MID (Depende de 1.)
- [x] Consumir el componente en la Entrada

**Comment by juandavidvelezaalvarez** [comment]
https://github.com/udistrital/arka_mid/pull/174

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
