### ISSUE TITLE
Agregar nota de descripción para el usuario para que entienda que pasa de registro a consulta o viceversa, en entradas

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#82]
Se debe agregar una ayuda visual en el cliente para que el usuario entienda que está consultando o registrando una entrada ya que no es claro en donde se encuentra actualmente. La tarea tiene una estimación de 1 hora para su desarrollo.

**Comment by Miavega** [comment]
Se añade texto de ayuda al momento de registrar y consultar entradas:
- Registro
![imagen](https://user-images.githubusercontent.com/23342808/64650480-e933c880-d3e4-11e9-8e39-98c08f3a4122.png)
- Consulta
![imagen](https://user-images.githubusercontent.com/23342808/64650487-f05ad680-d3e4-11e9-9661-73e2f1fb045d.png)

**Comment by mafeave** [comment]
Se verifica mensaje con la analista del proyecto, se da por finalizada la tarea.
