### ISSUE TITLE
Comprobante Contable Salidas

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#828]
## Referencias / Consideraciones
- De manera similar a las entradas
- https://github.com/udistrital/administrativa_cliente/projects/1#card-69263581

## Ajustar
- [x] mid, agregar movimiento contable (según petición del cliente). Para bienes de consumo el movimiento es trasladó (a jefe almacen - buscar dónde está quemado)
- [x] cliente, ajustar para mostrar el movimiento contable

**Comment by juandavidvelezaalvarez** [comment]
https://github.com/udistrital/arka_cliente/issues/828

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
