### ISSUE TITLE
En la alerta se debe mostrar el Nombre del comprobante que se generó y el consecutivo asignado

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#83]
Se debe generar una alerta con el nombre del comprobante y el consecutivo asignado al momento de registrar una entrada. La tarea tiene una estimación de 1 hora para su desarrollo.

**Comment by Miavega** [comment]
Se añade el consecutivo de la entrada en la alerta generada al registrar una entrada:

![imagen](https://user-images.githubusercontent.com/23342808/64934922-775be480-d813-11e9-8717-b7065fb90591.png)

**Comment by mafeave** [comment]
Agregar parámetro para que no se muestre el 'GLOBA.operacion_exitosa'

**Comment by Miavega** [comment]
Se corrige el bug visual añadiendo los parámetros necesarios a la internacionalización.

![imagen](https://user-images.githubusercontent.com/23342808/64999845-e2a6c480-d8ae-11e9-8957-0bfa16c74eb2.png)

**Comment by mafeave** [comment]
Se verifica ajuste del mensaje para internacionalización. Se da por finalizada la tarea.
