### ISSUE TITLE
Comprobante Contable Bodega de Consumo

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#830]
- [x] MID, (a partir del POST/PUT que aprueba solicitudes a bodega) agregar movimiento contable (salida, a efecto práctico, teniendo en cuenta que acá se le asigna al funcionario final)
 - [x] Cliente, Detectar donde se aprueba la solicitud, para detectar la petición que se hace al MID

**Comment by juandavidvelezaalvarez** [comment]
https://github.com/udistrital/arka_mid/pull/174

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
