### ISSUE TITLE
Hallazgos Salidas

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#834]
## Consideraciones / Referencias
- [Mesa de trabajo](https://drive.google.com/file/d/18Qj91r3xIEQnOIsWtKsWWCMwa7gH3SsZ/view?ts=617829cf)

## Hallazgos
- [x] (1) 9:30 - Revisar las validaciones que se están realizando a la salida, están asignados los funcionarios y descargados los elementos pero sigue diciendo que hay elementos sin asignar, posiblemente tenga que ver con la asignación del funcionario
- [x] (2) 16:24: _"La placa debe generarse desde que se hace la entrada"_ - Mover el proceso de generación de la placa a la entrada. Se recomienda que (en caso que no sea así) se haga desde el MID en la aprobación de la entrada
- [x] (3) 18:03: Falta mostrar el consecutivo asignado a la salida
- [x] (4) 20:07: Asegurarse que lo que no sea tipo bien "activo tangible" NO se le asigne placa
- [x] (5) 21:12: Asegurarse que a los servicios, específicamente para los mantenimientos: si es preventivo no implica entrada a almacén, el correctivo aumentaría la vida útil del bien (afectación/integración con módulo de vida útil / valor residual)... Que en general los servicios o lo que no sea tipo bien devolutivo tangible, que más adelante se pueda vincular a un bien (análisis por confirmar, posiblemente toque crear un nuevo Issue y/o restringir el alcance)
- [x] (6) 30:56: Al consultar la salida no se está viendo la información de la entrada (consecutivo ni fecha)
- [x] (7) (No mencionado): Validar que para las salidas solamente se puedan tomar solo entradas aceptadas

**Comment by ludwinggsanchez** [comment]
Estoy trabajando en (1), (3), (6) y (7)
