### ISSUE TITLE
Hallazgos Bodega de Consumo

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#835]
## Consideraciones / Referencias
- [Mesa de trabajo](https://drive.google.com/file/d/18Qj91r3xIEQnOIsWtKsWWCMwa7gH3SsZ/view?ts=617829cf)

## Hallazgos
- [x] (2) 33:17-34:31: A pesar que se está haciendo la asignación de elementos a Kardex, no están apareciendo para hacer solicitudes de elementos
- [x] (1) 35:56 para facilitar el entendimiento del proceso, Reordenar el menú, así:
      1. Asignación a Kardex
      2. Consulta de Kardex
      3. Solicitar Elementos
      4. Responder Solicitudes
      5. Consultar Solicitudes
- [x] (3) 37:37: Revisar que para nuevas entradas/salidas de bodega de consumo se estén realizando los cálculos (cantidades y valores) adecuadamente, acorde al método de inventario de la ficha kardex actual
- [x] (4) 38:50: (De la mano con lo anterior) Validar/ajustar el método de inventario PEPS

**Comment by ludwinggsanchez** [comment]
Ítem (2): Aparentemente los movimientos de kárdex se están guardando con el estado movimiento equivocado

![image](https://user-images.githubusercontent.com/35748918/140241456-fa28976b-c8e6-42b7-9a4d-180c53aa713b.png)
