### ISSUE TITLE
Despues de generar la entrada, el sistema debe redirigir a listado de actas de recibido

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#84]
Se debe permitir que al momento de registrar una entrada, el sistema envíe al usuario al listado de las actas de recibido para que pueda registrar una nueva entrada. La tarea tiene una estimación de 1 hora para su desarrollo.

**Comment by Miavega** [comment]
Se agrega un botón en el módulo de reportes que redirige al registro de entradas, ya que al momento de registrar la entrada, se muestra este módulo para generar su respectivo reporte.

**Comment by mafeave** [comment]
Se verifica agregación de botón para ir al módulo de registro de entradas:
![image](https://user-images.githubusercontent.com/14035745/65007110-b8fb9680-d8ca-11e9-9697-217f22b27a4e.png)

Se da por finalizada la tarea.
