### ISSUE TITLE
Funcionalidad de Traslados

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#843]
## Consideraciones / Referencias
- MockUps de Traslados
  - https://github.com/udistrital/arka_cliente/issues/667
  - https://github.com/udistrital/administrativa_cliente/issues/535
- HUs de Traslados (El filtro resume los codigos de las HUs)
  - https://github.com/udistrital/administrativa_cliente/projects/1?card_filter_query=traslado
  - https://drive.google.com/drive/u/2/folders/1mAmRv9O2d8W8dRJ0JaVWoTgp_ex5snbE
- El traslado debe implicar un flujo de aprobación con estados: Solicitado, Aceptado, Rechazado
- El traslado, de aceptarse, debe generar una transacción contable
- El objetivo general, la funcionalidad "a grosso modo" es que se pueda actualizar el tercero responsable de un bien

## Tareas
- [x] Identificar de dónde tomar los datos, de qué APIs
- [x] (Si aplica) Para los datos que no se puedan guardar, proponer y socializar cambios a APIs
- [x] (Si aplica) Aplicar cambios propuestos a APIs CRUD
- [x] (Si aplica) Ajustar MID
- [x] Crear interfaz de traslados, "cascaron"
- [x] Conectar la interfaz con la(s) API(s)
- [x] Flujo de Aprobación
- [x] Transacción contable al aprobarse el traslado

**Comment by ludwinggsanchez** [comment]
Los primeros 4 ítems serán abordados por @MateoAlfons

Hacer la migracion para manejar los estados de los traslados
Controlador para filtrar las placas por funcionario
Proponer transaccion_traslado para registrar la información relacionada al traslado

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
