### ISSUE TITLE
Funcionalidad Bajas

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#844]
## Consideraciones / Referencias
- HUs Bajas (y otros análisis)
  - https://github.com/udistrital/administrativa_cliente/projects/1?card_filter_query=baja
  - https://drive.google.com/drive/u/2/folders/1mAmRv9O2d8W8dRJ0JaVWoTgp_ex5snbE
  - https://github.com/udistrital/administrativa_cliente/issues/484
  - https://github.com/udistrital/administrativa_cliente/issues/518
  - https://github.com/udistrital/administrativa_cliente/issues/594
- Mock-Ups Bajas (si es que hay...)
- Funcionalidad actual en Bajas, "cascarones"
- El objetivo general de la funcionalidad, del proceso, es que para un elemento arbitrario se hagan los ajustes necesarios de inventario (cantidades) y contabilidad (valores económicos) con el fin de decrementar, el inventario en 1(asumiendo que se le da de baja a un bien), y la cuenta contable en el valor actual. Deberá detenerse/finalizarse la depreciación del bien
- Las bajas deben manejar un flujo de aprobación de al menos 3 estados: Solicitada, Aprobada, Rechazada (Nota: Cantidad de estados por confirmarse)
- Una vez aprobada la solicitud de baja, deberá hacerse efectiva la baja, generando la transacción contable y el ajuste a inventario

## Tareas
- [x] Identificar de dónde tomar los datos, de qué APIs
- [x] (Si aplica) Para los datos que no se puedan guardar, proponer y socializar cambios a APIs
- [x] (Si aplica) Aplicar cambios propuestos a APIs CRUD
- [x] (Si aplica) Ajustar MID
- [x] Ajustar interfaz de bajas
- [x] Conectar la interfaz anterior con la(s) API(s)
- [x] Flujo de aprobación - https://github.com/udistrital/arka_cliente/issues/598
- [x] Transacción contable

**Comment by ludwinggsanchez** [comment]
Los primeros 4 ítems serán abordados por @MateoAlfons

- Hacer la migracion para manejar los estados de los traslados
- Controlador para filtrar las placas por funcionario
- Proponer transaccion_traslado para registrar la información relacionada al traslado

**Comment by MateoAlfons** [comment]
¿Cómo proceder con el tercero anterior?

**Comment by AlexFBP** [comment]
> ¿Cómo proceder con el tercero anterior?

Desde la parametrización contable tuvo que haberse escogido para la baja una cuenta que no requiera un tercero. En caso de detectarse desde el MID que la cuenta que está actualmente configurada para la baja requiere un tercero, deberá retornarse al cliente un error, indicando eso, que "la cuenta actualmente asignada para XXX requiere un tercero. Notificar a Contabilidad"

**Comment by AlexFBP** [comment]
Considerar los siguientes apuntes tomados de la mesa de trabajo del 2 de Noviembre ...

> Proceso de Bajas
>
> 1. Solicitud (realiza dependencia)
>   - Placa/Dependencia
>   - Observaciones/Descripción/Detalle?
>
>   Botón "Enviar a Almacén"
> 2. "En proceso de baja" - Almacén *propone* el destino final. Entre otros:
>   - Destrucción
>   - Terceros
>   - Hurto
>   - Otro? (Ingreso manual)
>   Como primer entregable, un campo abierto que permita especificar el destino final (por elemento)
>
>   Botón: "Enviar a Revisión / Generar pre-informe"
>   Botón: "Devolver a Funcionario"
> 3. En Revisión (por el comité)
> 4.a Aceptada --> Tener en cuenta
>
>   - la depreciación, debe calcularse y detenerse
>   - la transacción contable (decrementar según valor)
>   - El ajuste a inventario (decrementar según cantidad)
>
> 4.b Rechazada/Devolver
>
>   - Rechazada? Ej, no era baja sino traslado
>   - Devolver? Ej, dato mal digitado
>
> Control: - Si aceptada, adjuntar acto administrativo
>          - Si rechazada?
>            - Botón "Devolver a Proceso de Baja"
>
> 5. Si fue aceptada, confirmar/ajustar el destino final de cada elemento, con base al acto administrativo

Se puede pensar que el flujo de bajas tiene que considerar los siguientes estados:
1. En Elaboración (El estado en que quedaría la baja mientras la redactan hasta que no se le de enviar - Se podría omitir este estado...)
2. En Revisión por Almacén (En que quedaría con el botón "Enviar a Almacén")
3. En Revisión por Consejo de Inventarios
4. Aceptada

**Comment by ludwinggsanchez** [comment]
Se proponen las siguientes actividades:

CRUD:
- Inserts formato_tipo_movimiento para los diferentes tipos de baja
- Inserts estado_movimiento para los diferentes estados de la solicitud

MID
- Controlador carga masiva en el proceso de crear la solicitud
- Controlador consulta de todos los traslados
- Controlador consulta del detalle de un traslado
- Controlador registro de un traslado

CLIENTE

- Integrar la funcionalidad con lo realizado en el mid y el crud

**Comment by ludwinggsanchez** [comment]
El reporte se ve así 

![image](https://user-images.githubusercontent.com/35748918/144871784-f5ad2189-75b3-4ed4-920b-5435b45d9981.png)
