### ISSUE TITLE
Servicio de Proveedor

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#85]
Relacionar proveedor del servicio de administrativa, al acta de recibido

- [x] Configuracion

- [x] Registro

- [x] Edicion

- [x] Verificacion

**Comment by mafeave** [comment]
Se revisan servicios de administrativa y en consulta con @blacburn, se encontró que existe un servicio en amazon api pero este solo lista las personas naturales, por lo anterior, se debe hacer una solicitud para la generación de un servicio que liste los proveedores (personas naturales y jurídicas) al equipo de Funcionamiento (Administrativa)

**Comment by mafeave** [comment]
Se verifica carga de la información de los proveedores, se debe agregar filtro adicional por numero de documento.

**Comment by ManuelMurillo** [comment]
Se agrega filtro para la busqueda y seleccion de los proveedores en el formulario de registro
