### ISSUE TITLE
Permitir retomar entradas y salidas rechazadas

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#850]
## Consideraciones
- [Documento de Hallazgos](https://docs.google.com/spreadsheets/d/1iUcdL6snRZ8fZIJxX0eWfnPFe0meHOygYh-S6E_yFxQ/edit#gid=481118634) - Hallazgo 045
- Si se rechaza una entrada o salida, no hay forma de corregirla. Considerar, por ejemplo, una de las siguientes alternativas/enfoques:
  - Permitir que entradas/salidas en estado rechazado (siempre y cuando no esté aprobada) puedan editarse (de manera similar al proceso de Actas, que solo se pueden editar si están en Elaboración/Modificación) ~~- O BIEN:~~
  - ~~Permitir que se pueda registrar una nueva entrada/salida~~

## Tareas
- [x] Ajustar flujo para las entradas
- [x] Ajustar flujo para las salidas

A ser desarrolladas por @juandavidvelezaalvarez , consultando a @ludwinggsanchez donde sea necesario

**Comment by juandavidvelezaalvarez** [comment]
https://github.com/udistrital/arka_cliente/pull/856
