### ISSUE TITLE
Revisión gestión de catálogo

### ISSUE THREAD

**Issue by mafeave** [udistrital/arka_cliente#87]
Se hace reunión con el equipo de trabajo para aclarar dudas frente a la gestión del catálogo de elementos

**Comment by mafeave** [comment]
Se aclara con @mcrubianot la definición de las cuentas contables por tipo de movimiento y por subgrupos de elementos

**Comment by ManuelMurillo** [comment]
![20190911_150925](https://user-images.githubusercontent.com/29108085/64734421-3a5abf80-d4ac-11e9-9eff-48318695e254.jpg)

**Comment by mcrubianot** [comment]
Se hace una explicación de los parámetros qye deben estar establecidos al momento de crear el catálogo. Se hace una breve explicación de los movimientos contables a generar.

Se revisan algunos tipos de transacciones que deberán generar movimientos contables. Es un supuesto toda vez que almacén no nos ha definido los movimientos

**Comment by mafeave** [comment]
Tener en cuenta que para los traslados entre dependencias no aplican movimientos contables.
Para el tipo de movimiento de entrada por donación se aplican varias cuentas contables aparte de las de débito y crédito
