### ISSUE TITLE
Desarrollar mockups de Ajustes, desde la parte de inventario (cantidades y valores registrados en APIs propias de Arka)

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#886]
## Consideraciones
- El "cascarón", la funcionalidad desarrollada al final de la contratación
- El https://github.com/udistrital/arka_cliente/issues/584
- Apuntes de la mesa de trabajo del 4 de Noviembre:
  > # Cambios que basta con Ajuste
  >
  > Que no implican anular y/o devolver un proceso:
  >
  > ¿Qué es un ajuste "sencillo"?
  > Aquellos que son de forma y no afecten...
  >
  > - Desde Almacén:
  >   - existencias
  > - Desde Contabilidad:
  >   - valores monetarios
  >
  > Entre otros:
  > 
  > - Descripciones
  > - Marca
  > - Serie
  >
  > Grupos:
  >
  > 1. (Lo de arriba, ajustes de forma)
  > 2. Bodega de Consumo... (ej, se le colocó un valor incorrecto a un toner)
  > 3. Aquello que tenga historico/"cola"
- De la anterior contratación: https://pruebasarka.portaloas.udistrital.edu.co/#/pages/ajustes/lista-movimientos (Pendiente por confirmar y/o actualizar este link)
- Si hay algo que afecte valores y/o terceros, deberá generarse un comprobante contable adicionalmente
- [Presentación Tipos de ajustes](https://docs.google.com/presentation/d/1M0x-h8XvRwel4OYf1YoqzZvP-8uFIpLX/edit#slide=id.p1)
- https://github.com/udistrital/administrativa_cliente/issues/651
- https://github.com/udistrital/administrativa_cliente/issues/599
- https://github.com/udistrital/administrativa_cliente/issues/593

## Tareas
- [ ] Confirmar con Analista las funcionalidades (HUs) mínimas que finalmente se requieren del lado de Inventario - Revisar actas y/o reuniones, dado que el usuario ha mencionado en varias mesas de trabajo, que este tema se ha tratado en mesas/reuniones anteriores
- [ ] Revisar, tanto la funcionalidad desarrollada en la anterior contratación, como el ajuste contable; para proponer y finalizar mockups de la interfaz que permitiría hacer ajustes de valores (la parte de cantidades queda por confirmar con Analista)- Entregable: Links a dos archivos: el editable y a un PDF generado

Entrega estimada: En la primer semana

**Comment by ludwinggsanchez** [comment]
- Se hace la revisión de la documentación y se hacen las respectivas anotaciones en el documento [Documentación ajustes](https://docs.google.com/presentation/d/1M0x-h8XvRwel4OYf1YoqzZvP-8uFIpLX/edit?usp=sharing&ouid=112793248709816638532&rtpof=true&sd=true)
- Se propone el siguiente mock-up [Mock-up Ajustes](https://drive.google.com/file/d/1hoBLadMM2M0EcZAPl1LLjkID0B5pvUfq/view?usp=sharing)

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial y al funcionamiento actual del sistema
