### ISSUE TITLE
Paso a Producción a la fecha

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#889]
## Consideraciones

- [Lineamiento Despliegues](https://github.com/udistrital/lineamientos_oas/blob/master/despliegues/lineamientos.md)
- [Lineamiento Ramas](https://github.com/udistrital/lineamientos_oas/blob/master/repositorios_institucionales/nombre_branch.md)
- [Inventario de APIs](https://docs.google.com/spreadsheets/d/15vnSFpfyOaf8dWfvG9h4EHmlf2bKOUSYSxydrafyqLU/edit?pli=1#gid=921962158)
- https://github.com/udistrital/arka_cliente/issues/770

## Tareas
- [x] Identificar CRUD APIs necesarias y sus migraciones faltantes, mirar qué tanto cambiaron las bases de datos entre master y develop. Arrancar por las APIs propias:
      - catalogo
      - acta
      - movimientos_arka
- [x] Abrir solicitudes de migraciones en Tuleap (en donde aplique - ayudarse con la grafica de git y/o con el lider)
- [x] Despliegue (en donde aplique - ayudarse con la grafica de git y/o con el lider): Abrir PRs a master de CRUD APIs
- [x] Despliegue (en donde aplique - ayudarse con la grafica de git y/o con el lider): Abrir PRs a master de MID APIs
- [x] Despliegue (en donde aplique - ayudarse con la grafica de git y/o con el lider): Abrir PRs a master del cliente
- [x] #640
- [x] #927

**Comment by MateoAlfons** [comment]
Respecto a gestor documental mid y autenticación mid no hay que hacer paso a producción, ya que la rama más reciente es master (consultado con lider tecnico)
https://github.com/udistrital/gestor_documental_mid/network
https://github.com/udistrital/autenticacion_mid/network

**Comment by AlexFBP** [comment]
Limpieza go.mod realizada en
- [autenticacion_mid](https://github.com/udistrital/autenticacion_mid)
- [google_mid](https://github.com/udistrital/google_mid)

**Comment by AlexFBP** [comment]
Respecto a [consecutivos_crud](https://github.com/udistrital/consecutivos_crud):
- [x] [Tuleap pruebas de carga y seguridad](https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=45565)
- [ ] Tuleap despliegue en producción

Respecto a [movimientos_contables_crud](https://github.com/udistrital/movimientos_contables_crud):
- [x] [Tuleap pruebas carga y seguridad](https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=45566)
- [ ] Tuleap despliegue a producción

**Comment by AlexFBP** [comment]
Resumiendo la información agregada al inventario de APIs:

| [Repositorio UDFJC](https://github.com/udistrital) | Estado Despliegue | Observaciones |
|                                       ---                                      |              ---              |             ---           |
| **CRUD** | --- | --- |
| acta_recibido_crud | | |
| administrativa_amazon_api | | |
| catalogo_elementos_crud | | |
| configuracion_api | | |
| cuentas_contables_crud | | |
| documentos_crud | | |
| movimientos_arka_crud | | |
| movimientos_crud |  | Se está intentando prescindir de esta API |
| oikos_api | |  |
| parametros_crud | |  |
| terceros_crud | |  |
| **MID u OTRO** | --- | --- |
| administrativa_jbpm-v1 | | No hay repo asociado |
| arka_mid | |  |
| autenticacion_mid | | |  |
| gestor_documental_mid | | |  |
| google_mid | | |  |
| terceros_mid | | |  |
| **CLIENTES** | --- | --- | --- |
| arka_cliente | | |  |

**Comment by AlexFBP** [comment]
Respecto a tesoreria_mid
- [ ] Tuleap pruebas de Carga y Seguridad
- [ ] Tuleap Despliegue a Producción
