### ISSUE TITLE
Modelo de datos del procedimiento baja de bienes

### ISSUE THREAD

**Issue by Miavega** [udistrital/arka_cliente#9]
Realizar el diseño del modelo de datos para el procedimiento de baja de bienes

- [x] Revisar el modelo actual

- [x] Revisar el proceso para el procedimiento de baja de bienes

- [x] Generar un modelo en pg modeler con el nuevo modelo de datos

- [x] Generar imagen png con el nuevo modelo de datos

**Comment by Miavega** [comment]
En el siguiente [enlace](https://drive.google.com/drive/u/0/folders/160r8aHnzSnJBAQJTKpnMRJIZ7Bxb8fNz) se anexa el modelo de datos en PgModeler y la imagen PNG correspondiente al procedimiento de baja de bienes.

**Comment by mafeave** [comment]
Se verifica modelo realizado, con la imagen y el archivo en pgmodeler correspondiente.
