### ISSUE TITLE
Conversion datos IVA 

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#90]
Relacionar porcentaje del IVA con el ID del registro del API, en registro masivo de acta de recibido

**Comment by mafeave** [comment]
Revisar si desde el archivo en excel se puede agregar campo de tipo select para que se registre el id del valor seleccionado

**Comment by ManuelMurillo** [comment]
a travez del API MID, se realiza la conversion de la tarifa del IVA al id correspondiente al registro

**Comment by mafeave** [comment]
Se verifica registro masivo de los elementos cargando el valor del IVA en el archivo de excel.
