### ISSUE TITLE
Validación consulta de supervisores y ordenadores del gasto

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#928]
## Consideraciones
- Imagen de referencia de la consulta adecuada que debe de hacerse
![image](https://user-images.githubusercontent.com/6588872/170415053-53d57be3-e183-45a4-ae73-390fb1529147.png)
- Consultar a líder técnico de Core de ser necesario
- Posiblemente relacionado con [terceros_mid](https://github.com/udistrital/terceros_mid)

## Ajustar / Validar

Donde aplique:
- [ ] Supervisor
- [ ] Ordenador del Gasto

**Comment by AlexFBP** [comment]
Para los ordenadores del gasto, [se traen de terceros_mid actualmente](https://github.com/udistrital/terceros_mid/blob/6c82a6b6476557ccdf2e00c6a0179ebfb48586cf/helpers/tipos/jefes.helper.go#L77-L82
).
De acuerdo a lo informado, deberían traerse con
`https://autenticacion.portaloas.udistrital.edu.co/apioas/administrativa_jbpm/v1/ordendor`

**Comment by ludwinggsanchez** [comment]
La consulta a `https://autenticacion.portaloas.udistrital.edu.co/apioas/administrativa_jbpm/v1/ordendor` no existe, validar la siguiente:
`https://autenticacion.portaloas.udistrital.edu.co/apioas/administrativa_amazon_api/v1/ordenadores`

**Comment by milo19980525** [comment]
Los endpoints actualizados son:

**ordenadores**
http://api.intranetoas.udistrital.edu.co:8104/v1/ordenadores?limit=-1

**Supervisor**
http://api.intranetoas.udistrital.edu.co:8104/v1/supervisor_contrato?limit=-1
