### ISSUE TITLE
Validar Archivo de migración 20-09-2022

### ISSUE THREAD

**Issue by milo19980525** [udistrital/arka_cliente#972]
- [x] Validar si el archivo de migración corresponde a la estructura de la plantilla elaborada y si es factible su cargue en Arka II.

- [x] Revisar si las cuentas contables encontradas en el archivo se encuentran inscritas en el plan de cuentas (Kronos).

[Archivo migración 20-09-2022](https://github.com/udistrital/arka_cliente/files/9708597/Plantilla.migracion.computo.20-09-2022.SOFTWARE.xlsx)

**Comment by ludwinggsanchez** [comment]
Observaciones: 

- La revisión rápida de los proveedores permite confirmar que ya se encuentran registrados en terceros.
- La revisión rápida de los funcionarios permite confirmar que ya se encuentran registrados en terceros.
- Se evidencian múltiples sedes y ubicaciones no registradas en el sistema oikos. 
- Para los siguientes elementos, se solicita que las cuentas contables estén en formato dividido por guiones, es decir: 2-4-01-01-90 en lugar de 2401019000.
