### ISSUE TITLE
Internacionalizacion acta de recibido

### ISSUE THREAD

**Issue by ManuelMurillo** [udistrital/arka_cliente#98]
se debe configurar la traduccion en los componentes del acta de recibido

- [x] Registro

- [x] Consulta

- [x] Edicion

- [x] Verificacion

- [x] Detalle

**Comment by mafeave** [comment]
De la revisión realizada, se observa que los valores para el translate del idioma inglés quedaron igual al idioma español, por favor hacer los ajustes correspondientes.

**Comment by mafeave** [comment]
Se verifica ajuste mediante el commit https://github.com/udistrital/arka_cliente/commit/91ef0635e3646ed0890aec60198f1810140c265c 
Se da por finalizada la tarea.
