### ISSUE TITLE
Verificación de data actualizada en pruebas OIKOS

### ISSUE THREAD

**Issue by milo19980525** [udistrital/arka_cliente#987]
- [x] Validar si se actualizó la información que asocia un espacio físico con la dependencia en Oikos pruebas.

**Comment by ludwinggsanchez** [comment]
Los registros faltantes se asocian en el siguiente documento [Revisión](https://docs.google.com/spreadsheets/d/1ihL1vgwkg8veRPr7ydKG5Va2wvptuD4u/edit?usp=sharing&ouid=112793248709816638532&rtpof=true&sd=true)
